metatron-app/metatron-discovery

README.md

Change tags for some elements.
Add styles to images in README.

Change element tags and styles

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-ds-select.component.html

#8 Remove unnecessary message

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshot.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java

Snapshot에 status라는 필드를 추가했습니다.
서버는 snapshot 생성 과정에서 이 필드를 업데이트 합니다.
INITIALIZING -> RUNNING -> WRITING -> TABLE_CREATING (only in Hive case) -> SUCCEEDED 가 보통의 흐름입니다.
UI는 이 필드를 보고 snapshot 생성 작업의 상태를 알 수 있습니다.

#15 add snapshot generation status field

---

discovery-frontend/src/app/common/component/chart/option/ui-option/ui-pie-chart.ts
discovery-frontend/src/app/common/component/chart/type/pie-chart/pie-chart.component.ts
discovery-frontend/src/app/page/chart-style/common-option.component.html
discovery-frontend/src/app/page/chart-style/common-option.component.ts
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/chart/PieChart.java
discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/chart/PieChartTest.java

파이차트의 생성룰을 1 dimension and 1 measure으로 변경하였습니다.
Related Issue : #22 
- 선반에서 1개 이상의 dimension을 추가시 validation 체크
- 선반에서 1개 이상의 measure를 추가시 validation 체크
- 선반가이드에서 변경된 문구 확인
**Test Configuration**:
- OS: iOS
- Browser: chrome
- Version: 68

F#22 add max category property

---

discovery-frontend/src/app/common/component/chart/type/network-chart/network-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/sankey-chart/sankey-chart.component.ts
discovery-frontend/src/app/page/chart-style/datalabel-option.component.ts
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

- 특정 데이터소스 (두개의 필드내 동일한 항목이 존재하는) Sankey 및 Network Chart 내에서 차트 표시오류를 수정합니다.
- Sankey 차트 행 선반내 제약 조건을 변경합니다.(3 dimension -> 2 dimension)
**Related Issue** : #67 
- 특정 데이터소스 (두개의 컬럼내 동일한 항목이 존재하는) 데이터 소스를 준비합니다. 
- Sankey 및 Network Chart 선반을 그립니다.

F#67 sankey chart not displayed

---

discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepHdfsService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

스냅샷 생성을 위한 API {dsId}/transform/configuration 에서
기존 FILE -> 현재 FILE, HDFS, HIVE 로 
설정 상태를 모두 반환하도록 변경하였습니다.

#40 to confirm where snapshot will be made in

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

skip commented query.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/103
1. create workbench
2. input query 2 lines.
-- show tables;
show tables;
3. execute whole query

#103 skip commented query

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java

fix encoding issue when download file
**Related Issue** : #119 
Set datasource with Korean characters,
then create some dashboard and chart with that datasource.
Click 'Save data table' on the chart widget.
Check Korean texts are printed properly in the exported file.
I reused a method of HttpUtils.

Fix the character encoding of downloaded file

---

discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
discovery-frontend/src/app/page/chart-style/datalabel-option.component.ts
discovery-server/src/main/java/app/metatron/discovery/common/MatrixResponse.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

- Data Label/ToolTip 설정시 Preview와 일치하게 수정하였습니다.
- 열/행 차원값 1개씩, 측정값 1개 인경우 Y 축 최상단에 추가적인 열이 생성되는 부분 서버 수정 후 잘 동작되는지 확인하였습니다.
- 열 차원값 1개, 측정값 1개 인경우 X/Y 축에 불필요한 열/행이 생성되는부분 서버 수정 후 잘 동작되는지 확인하였습니다.
**Related Issue** : #102
- 열/행 차원값 1개씩, 측정값 1개인경우 Y축에 열이 생성되지 않는지 확인하였습니다.
- 열 차원값 1개, 측정값 1개인경우 X/Y축에 불필요한 열/행이 생성되지 않는지 확인하였습니다.
- Data Label/Tooltip에서 Category Name을 설정시 Preview와 일치하는지 확인하였습니다.

F#102 heatmap not rendered

---

README.md

F57 Change Readme File

---

discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-information.component.html
discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-information.component.ts

메타데이터 상세 페이지에서 설명이 두 줄 이상일 때 한 줄로 보이는 문제 해결
#171 
메타데이터 설명을 두 줄 이상으로 줄바꿈 해서 입력해서 줄 바꿈이 적용되는지 확인

F#171 metadata detail description linebreak

---

discovery-frontend/src/app/meta-data-management/metadata/create-metadata/complete-create-metadata.component.ts

연결형 데이터소스로 메타데이터 생성시 발생하는 에러 수정
(ui에서 연결형 데이터소스로 메타데이터 생성시 파라메터 수정)
#233 
1. 데이터소스 > 연결형 데이터소스 생성
2. 메타데이터 > 데이터소스로 메타데이터 생성 > 1에서 생성한 연결형 데이터소스 선택 > 생성 확인

#233 change property in metadata create from linked type source

---

discovery-frontend/src/app/common/component/grid/grid.component.ts
discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

when execute multiple query on workbench, changing result tab does not work properly. .
**Related Issue** : #112 
1. Go to Workbench 
2. Execute query as
use polaris;
SELECT * FROM polaris.book;
use polaris;
3. Click the different number of result tab several times.
4. The result will be shown as "No Data" if there is no data to show.

F#112 workbench result tab bug

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

중간 룰 편집을 하기 위해서 current index를 바꾸면 한번씩 타임스탬프 포멧이 null로 돌아오는 경우가 있습니다.
#232 
룰 리스트에서 점프한 후 null로 돌아오는 칼럼이 있는지 확인합니다.

#225 timestamp format list does not become null

---

discovery-frontend/src/app/meta-data-management/column-dictionary/create-column-dictionary/create-column-dictionary.component.html
discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.html
discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.html

메타데이터 생성 및 컬럼 사전에서 logcialType의 etc와 more types에 해당하는 타입을 제거함
- 메타데이터 상세화면 
- 컬럼 사전 생성화면
- 컬럼 사전 상세화면
#211 
1. 데이터소스 생성
2. HIVE로 데이터 커넥션 생성
3. 메타데이터 생성 > 1에서 생성한 데이터소스로 메타데이터 생성 > 메타데이터 상세화면 > logicalType에 etc 항목이 나오지 않는것 확인
4. 메타데이터 생성 > 2에서 생성한 HIVE로 메타데이터 생성 > 메타데이터 상세화면 > logicalType에 more types가 나오지 않는것 확인
5. 컬럼 사전 생성 > logicalType 목록에 more types가 없는것 확인 > 생성완료
6. 5에서 생성한 컬럼 사전 상세화면 > logicalType 변경 목록에 more types가 없는것 확인

#211 delete etc in logical type

---

discovery-frontend/src/app/common/component/abstract.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.ts
discovery-frontend/src/app/dashboard/dashboard.component.ts
discovery-frontend/src/app/dashboard/filters/component/timeUnit-select.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/configure-filters-time.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/configure-filters-time.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.ts
discovery-frontend/src/app/dashboard/service/dashboard.service.ts
discovery-frontend/src/app/notebook/notebook.component.ts
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/app/workspace/workspace.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStream.java
discovery-server/src/main/java/app/metatron/discovery/domain/activities/spec/ActivityType.java

* 다양한 사용자 통계를 위하여 activity stream 내 추가 액션이 필요합니다.
**Related Issue** : #202 
1. 워크스페이스 내 워크북, 워크벤치, 노트북, 대시보드 화면에 접속합니다.
2. 데이터베이스 내 워크북, 워크벤치, 노트북에 대한 접속 이력이 등록되었는지 확인합니다.
3. 대시보드를 생성한 후, 데이터베이스 내 대시보드와 데이터소스 연결에 대한 이력이 등록되었는지 확인합니다.

F#202 add action in stream

---

discovery-frontend/src/app/common/directive/input-mask.directive.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-ingestion-permission/db-ingestion-permission.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-ingestion-permission/db-ingestion-permission.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-server/src/main/java/app/metatron/discovery/config/SchedulingConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/ingestion/IncrementalIngestionJob.java

- 데이터소스 생성시 주기적으로 증분 데이터를 가져올 떄 TIMESTAMP가 current_time인 경우 문제가 발생하는 점 수정
- current_time으로 TIMESTAMP를 지정했을 경우 Batch의 INCREMENTAL을 지정할 수 없도록 수정
- 추가적으로 Batch의 Max row를 기존 10,000건에서 5,000,000 건으로 늘림
- 5백만건을 넘어갔을 경우 error message를 표시하도록 추가
#182 
공통. 데이터소스 생성 > Ingested 형으로 생성 >
1. 스키마 설정화면에서 current_time으로 TIMESTAMP지정 > ingestion 화면에서 Batch 타입을 선택할 경우 INCREMENTAL을 설정할 수 없는것을 확인
2. ingestion 화면에서 Batch 타입의 Max row가 최대 5,000,000 건으로 설정되었는지 확인
3. Max row가 5,000,000을 넘어갈 경우 error message가 올바르게 출력되고 있는지 확인

F#182 batch datasource query error

---

discovery-frontend/src/app/workbench/component/editor-workbench/codemirror.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

When sql has comment, case when then statement
sql beautifier new line rule has error.
**Related Issue** :  #114  
1. 워크벤치 화면으로 이동합니다.
2. 아래의 쿼리문 입력합니다.
SELECT
CASE
WHEN true is NOT NULL -- case1
THEN 1
ELSE 0
end;
3. 전체선택 후 beautifier 실행 후 정상적으로 표시되는지 확인합니다.

#114 sql beautifier update (case when then statement)

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

첫줄이 코멘트로 시작하는 쿼리일 경우 정상 실행안되는 이슈
#254 
1. Go to Workbench
2. input query
-- test
select 1;
3. execute query
4. see result 1.

#254 all line starts with '--' is isComment=true.

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-settype.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java

룰 수정 버튼을 클릭하면 커맨드를 선택하는 셀렉트 박스는 비활성화 되면서 변경할 수 없었습니다.
#198 
룰 수정 버튼을 클릭하고 다른 커맨드로 변경 후 룰을 적용합니다. 룰 수정이 변경된 커맨드로 적용됐는지 확인합니다.

F#198 change command when editing

---

discovery-frontend/src/app/meta-data-management/metadata/service/metadata.service.ts
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table-info-desc/detail-workbench-table-info-desc.ts
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataController.java

workbench metadata service change 
**Related Issue** : #261  
1. 메타데이터 생성합니다. 
2. 워크 벤치 화면으로 이동하여 메타데이터 관련 내용이 정상적으로 나오는지 확인합니다.

F#261 metadata source api method change

---

discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts

- 파이차트의 색상설정에서 dimension에서 measure로 변경시 스크립트 에러발생
**Related Issue** : #296 
- 차트 타입을 파이차트로 선택하고 dimension / measure를 선택 후 color타입을 dimension에서 measure로 변경시 스크립트 에러가 발생하지 않는지 확인합니다.

#296 fix color type script bug in pie chart

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

생성된 Connection이 정상적으로 Close 되도록 코드 수정
JdbcTemplate을 사용하는 경우는 따로 Close 코드 사용하지 않음(spring framework에서 close 처리함) 
#302 
Workbench 접속, DataConnection 생성, DataSource 생성

#302 close connection

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts

워크벤치내 데이터베이스, 메타데이터를 변경할 시 스키마 브라우저에서 오류가 발생합니다.
**Related Issue** : #305  
1.워크벤치 화면으로 이동합니다.
2.좌측에 스키마 브라우저를 띄웁니다.
3.테이블을 선택하고 다른 데이터베이스로 변경합니다.
4.변경한 데이터베이스의 메타데이터 탭을 선택하면 오류가 발생합니다.

#305 schema browser selected table error update

---

discovery-frontend/src/app/dashboard/widgets/text-widget/text-widget.component.css
discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.html
discovery-frontend/src/app/page/page-data/page-data-context.component.ts
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-frontend/src/assets/i18n/en.json

1 . 두 개 이상의 데이터 소스로 생성한 대시보드에서 차트 편집 시 데이터 소스를 선택하는 팝업 창의 검색어 문구가 이상합니다.
2. 메타데이터 위도/경도 논리 타입이 잘 표시는 되는데 다른 논리 타입은 모두 대문자인데 위도/경도는 첫 글자만 대문자이고 소문자라서 통일성이 없습니다.
3. ![image](https://user-images.githubusercontent.com/42233517/45863280-661efa00-bdb0-11e8-948f-029a6cb0abbe.png)
4. 
5.
#221 
1. Search Formula 가 아니라 Search로 수정 
2 . Longitude -> LONGITUDE, Latitude -> LATITUDE 로 수정
3 . 텍스트 위젯을 만든 후 대시보드 화면에서 편집 버튼 호버 후 글씨가 보이는지 확인
4. 바 차트 생성 시 measure 3개 와 dimension 3개를 올린 후 차트 생성 후 대시보드 화면에서 위젯 정보 아이콘 호버 후 설명이 길어졌을 때 박스 밖으로 나가지 않는지 확인
5. IE 에서 값이 나오는지 확인

F#221 Fix css errors and wording 

---

discovery-distribution/pom.xml
discovery-frontend/pom.xml
discovery-prep-parser/pom.xml
discovery-server/pom.xml
pom.xml

Update version in the pom files to 3.0.4

Update version in the pom files to 3.0.4

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/dashboard.component.ts
discovery-frontend/src/app/workbook/workbook.component.html
discovery-frontend/src/app/workbook/workbook.component.ts

* 대시보드를 모두 삭제한 경우, 마지막 대시보드가 지워지지 않고 그대로 남아있어 화면이 깨지는 상황이 발생합니다.
**Related Issue** : #222 
1. 워크스페이스에서 워크북을 생성합니다.
2. 대시보드를 생성 한 후, 차트 하나를 생성하고 저장합니다.
3. 왼편 대시보드 목록에서 대시보드를 하나도 남김 없이 삭제합니다.
4. 대시보드가 하나도 남아 있지 않을 경우, 대시보드 없음 화면이 정상적으로 표시되는지 확인합니다.

#222 Fixed initialization error when deleting dashboard

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Revision.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java

- union 과 join을 했을 때 rule이 너무 길게 보이는 문제 해결
- union 과 join을 하고 전 단계로 jump 했을 때 rule list에서 join with undefined라고 보였던 문제 해결
#333 
- 1개 이상의 wrangled dataset 을 만든 후 만든 wrangled dataset 을 union 적용한다. rule list에서 Union with `{dataset name}`으로 나오는지 확인한다.
- 1개 이상의 wrangled dataset 을 만든 후 만든 wrangled dataset 을 join 적용한다. rule list에서 Join with `{dataset name}`으로 나오는지 확인한다.
- Union이나 join 을 한 후 편집 버튼을 눌러서 팝업이 뜨면 아래 rule list에 undefined라는 단어가 없고 rule list 가 join/union with `{dataset name}` 이 나오는지 확인한다

F#333 enhance slave ds map

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
discovery-frontend/src/app/data-preparation/dataset/detail-dataset/dataset-detail.component.ts
discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDataset.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetJdbcService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetSparkHiveService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/ColumnType.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfDerive.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSet.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSetType.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Util.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java

Timestamp가 있는 Hive 테이블을 import하면 해당 column의 모든 값이 mismatched로 표시됩니다.
Dataset preview 에서는 timestamp 타입 컬럼에 timestamp format이 적용되지 않았습니다.
#330 
Hive 테이블을 import하면 해당 column의 모든 값이 mismatched로 표시 되지 않는지 확인합니다.
데이터플로우 preview에서 타임스탬프 포멧이 적용되는지 확인합니다.

F#330 hive timestamp mismatch

---

.github/CONTRIBUTING.md
discovery-server/src/main/resources/checkstyle.xml

Add checkstyle for Java convention.
(based on [google style](https://google.github.io/styleguide/javaguide.html))
#401

Add checkstyle ruleset

---

discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.html
discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.ts
discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.html
discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-frontend/src/assets/i18n/en.json

advanced setting은 접혀있는 상태가 기본이도록 변경
Job property와 Ingestion tunning config 순서 변경
#396 
데이터소스 > 데이터소스 생성 > stagingDB로 생성 > ingestion step 에서 아래 사항 확인

#396 fix advanced setting show flag

---

discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/common/component/chart/type/network-chart/network-chart.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts

- 차트 선반 변경, 차트 옵션변경시 차트에 제대로 반영되지 않는 에러를 수정합니다.
**Related Issue** : #418 #353 #414 #417 
1. 차트상세화면에서 바차트를 선택합니다.
2. 열선반 : dimension 1개와 교차선반 : measure2개를 설정하여 차트를 draw합니다.
3. 교차선반에서 measure 1개를 삭제하고 차트에 제대로 반영되는지 확인합니다.

#418 Changing chart options doesn’t apply to chart

---

discovery-frontend/src/app/app.component.html
discovery-frontend/src/app/common/util/common.util.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.ts
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

공통 log component 안에서 에러 메세지가 길어질 경우 화면을 벗어나는것 수정
#421 
데이터소스 상세화면 > 컬럼 상세화면
에러가 나는 컬럼 클릭
에러 발생시 나타나는 에러 alert에서 detail 클릭
에러 메세지 확인

#421 fix common log ui

---

discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/page/page.component.ts

대시보드에서 차트가 그려질 때, 한번에 채워져서 그려지지 않고 좌측 상단에서 펼쳐지듯이 그려지는 현상이 발생합니다.
**Related Issue** : #430 
1. 대시보드를 생성합니다.
2. 대시보드 편집화면에서 차트( 바차트, 라인차트 등 )를 3~4개정도 생성한 후, 차트를 대시보드에 배치시킵니다.. 
3. 대시보드를 저장 후, 화면을 새로고치거나 다른 대시보드로 이동하면서 대시보드가 그려지는 것을 확인합니다.
4. 좌측 상단에서 펼쳐지듯이 그려지지 않고, 영역에서 바로 그려지는지 확인합니다.

#430 The chart is drawn as it expands from the top left corner.

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilter.java

필터 위젯 활용하여 셀렉션 필터링을 수행시 서버내 파라미터 처리시 오류발생내용을 수정합니다.
**Related Issue** : #255 
1. 대시보드 생성
2. 대시보드내 네트워크 차트 생성
3. 대시보드내 다른 종류의 차트 생성(ex.bar)
4. 필터 위젯 생성
5. 필터위젯내 항목 선택 및 네트워크 차트내 노드 선택
6. 정상적으로 필터링이 되는지 확인

#255 add Serializable interface

---

discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.html
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.page.css

차트 상세 화면에서 알리아스를 세팅하면 표출되지 않는 문제를 해결합니다.
**Related Issue** : #415 
1. Go to '차트 상세 화면'
2. 좌측 데이터 패널 이동
3. 더보기 버튼 클릭
4. 'Alias' 변경
5. 변경된 Alias가 데이터 패널에 표시되는지 확인

#415 Chart data panel alias name

---

discovery-server/src/main/java/app/metatron/discovery/common/Mailer.java
discovery-server/src/main/java/app/metatron/discovery/common/MetatronProperties.java
discovery-server/src/main/resources/application.yaml
discovery-server/src/main/resources/templates/api/email/user_reset_password.html
discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
discovery-server/src/main/resources/templates/api/email/user_signup_request.html

- 패스워드 리셋 메일을 전송하는 API 가 인증이 걸려있어 이를 해제하는 설정을 추가했습니다.
- 사용자 등록 요청시 관리자에게 Noti. 메일 전송중 오류가 발생하였습니다. 추후 보완이 필요하지만, 
현 수준에서 설정으로 관리자를 지정하도록 구성하였습니다.
- 메일 템플릿 링크를 수정하였습니다.
**Related Issue** : #400 
- 로그인 화면에서 사용자 등록 요청을 수행한후, 설정에 지정한 관리자 메일로 정상적으로 전달되는지 확인합니다.
- 사용자 등록후, 로그인 화면에서 특정 사용자의 패스워드 초기화 버튼클릭후 메일 입력, 메일이 해당 사용자 메일로 전송되는지 확인 합니다.

#400 fix error sending mail for sign up and resetting password

---

discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.ts

frontend product 빌드시 오류가 발생하여 빌드가 완료되지 않습니다.
**Related Issue** : #444  
1. discovery-frontend 폴더에서 npm prod 를 실행하거나 프로젝트 전체 빌드를 돌려 확인합니다.
2. 오류 없이 정상적으로 빌드가 되는지 확인합니다.

#444 Fix frontend build error

---

discovery-frontend/src/app/workbench/workbench.component.ts

Hive query result showed 'No data' update
**Related Issue** : #459  
2. excute query
select * from sample
3. See "No data" message
4. drawing grid as a result

#459 Hive query result showed 'No data' update

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
discovery-frontend/src/app/data-preparation/dataset/detail-dataset/dataset-detail.component.ts
discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts

CSV file로 데이터 셋 생성 시 사용자 칼럼 구분자 변경 시에 데이터 그리드 미적용 되는 부분 수정
#457 
파일 데이터셋 생성 >  csv 파일 선택 > delimiter 수정 > 그리드가 바뀌는지 확인
업로드하는 파일 이름에 . 이 있을 경우 지원하지 않는 확장자라고 나온 부분도 같이 수정

F#457 change grid with delimiter

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java

Dataset importing does not work for MultiSheet Excel file.
so, Excel reading uses StreamingReader instead of WorkbookFactory.
and was checked something about null value check, index counting, and so on.
[#480](https://github.com/metatron-app/metatron-discovery/issues/480)
1. import multi sheet excel file
2. select any sheet
3. make a dataset
4. see the details of dataset

#480 change excel library to another version using streaminng reader

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
discovery-frontend/src/app/data-preparation/dataset/detail-dataset/dataset-detail.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

Show name of sheet if imported dataset is excel type
#482 
Dataflow > click on excel type imported dataset > check if you can see the sheet name instead of N/A

#482 show sheet name

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts

`Rename` 후 context menu에서 `sort` 할 때 에러나는 부분 수정
#467 
Rename  후 context menu 에서 sort 했을 때 잘 되는지 확인
히스토그램을 클릭한 후 context menu 에서 delete 도 잘 되는지 확인 부탁드립니다.

F#467 sorting error after rename

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfPivot.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfReplace.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

기존의 Replace Rule이 이전 Dataframe의 값을 바꾸는 문제가 있었습니다.
로직이 기존 Dataframe에서 row objecte들을 얻어와서 변형한 뒤 새 dataframe에 추가하도록 설계되어 있었습니다.
새로운 row object를 생성하도록 로직을 변경합니다.
Old "Replace Rule" logic changes previous Dataframe's data.
Because the logic designed to get row objects of old Dataframe and modify & add it to new Dataframe.
So, change the logic to create new row object and do not change old Dataframe.
#477
Test these rules and check if the rule changes previous dataframe.
window value:[avg(column27), rolling_sum(column28,1,1), row_number(), lead(column28, 1)] group: column2, column3 order: column1
window value:[avg(column27), rolling_sum(column28,1,1), row_number(), lead(column28, 1)] group: column2, column3 order:
window value:[avg(column27), rolling_sum(column28,1,1), row_number(), …

F#477 rule editing is not applied in data preparation

---

discovery-frontend/src/app/common/util/common.util.ts

BR tag shown in Folder delete confirmation window
**Related Issue** : #506  
1. Go to workspace
2. Click on trashbean icon in folder
3. See error

#506 remove HTML tag in confirm window

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts

fix overlapping in case many data at dataflow chart
#489 
1. menu>MANAGEMET>Data Preparation>Dataflow > Dataflow detail
2. add New dataset
3. check chart scroll

F#489 overlapping in case many data

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadService.java
discovery-server/src/main/java/app/metatron/discovery/util/ExcelProcessor.java
discovery-server/src/main/java/app/metatron/discovery/util/PolarisUtils.java

ExcelProcessor was using POI Excel library.
It is changed to streaming-reader library.
Preparation excel loading code is the same.
[#480](https://github.com/metatron-app/metatron-discovery/issues/480)
1. upload an excel file on datasource.
1-1. create new datasource
1-2. datasource type is 'file' and file type should be excel file
1-3. sheet names of /api/datasources/file/upload and
1-4. sheet data of /api/datasources/file/{fileKey}/data should be correct
2. upload an excel file on preparation dataset
2-1. create new dataset
2-2. upload an excel file
2-3. the preview of the file is shown. it should be correct.

F#480 Enhance Excel file loading process

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts

Sorting fails after renaming a column
#467 
Navigate to main grid > click on context menu and change the column name > try sorting with context menu > check if sorting works well

#467 fix sort fail error

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts

Delete size information in dataset information (db type)
#228 
Make db type dataset > Add it in dataflow > click on imported dataset > check 
Imported db type dataset must not have size information

F#228 row count error

---

discovery-server/src/main/java/app/metatron/discovery/common/datasource/LogicalType.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
discovery-server/src/main/resources/samples/ingesion/sales_ingestion_spec.json
discovery-server/src/main/resources/samples/ingesion/sales_ingestion_spec_with_geo.json
discovery-server/src/main/resources/scripts/default.sql
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/resources/sql/test_gis_datasource.sql

기존 merge 본에 추가하여 데이터 소스 조회 오류를 수정하였습니다.
**Related Issue** : #38 
GEO Type 필드가 포함된 데이터 소스 조회
: 데이터소스 관리 > 데이터 목록 조회 > 데이터 소스 상세 조회 > "DATA" 탭
: 대시보드내 데이터 소스 조회 > "DATA" 탭

fix error for data source view in "introduce mapview issues"

---

discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option2.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option2.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option3.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option3.component.ts
discovery-server/src/main/java/app/metatron/discovery/common/datasource/LogicalType.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
discovery-server/src/main/resources/samples/ingesion/sales_ingestion_spec.json
discovery-server/src/main/resources/samples/ingesion/sales_ingestion_spec_with_geo.json
discovery-server/src/main/resources/scripts/default.sql
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/resources/sql/test_gis_datasource.sql

- 포인트 타입의 Map 에서 색상 분배가 제대로 동작하지 않는 이슈를 추가 수정합니다.
**Related Issue** : #38 
- salse_geo 포인트타입의 맵 차트 생성시 geo type 의 location 과 profit 항목을 레이어 선반에 올려둡니다.
- 해당 값의 min/max 값이 제대로 분배가 되는지 확인합니다.

fix error diplaying color using point type of field in map view

---

discovery-frontend/src/app/workbench/service/workbench.service.ts
discovery-frontend/src/app/workbench/workbench.component.ts

워크벤치의 스키마 브라우져에서 presto connection의 경우 샘플 데이터 조회 시 에러가 발생합니다. 
**Related Issue** : #562  
1. presto connection 타입으로 워크벤치 화면으로 이동합니다. 
2. 스키마 브라우져를 열어 테이블을 선택 후 데이터 탭을 클릭합니다. 
3. 데이터가 있는경우 정상적으로 데이터가 표시되는지 확인합니다.

F#562 schema browser error sample data from presto

---

discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

If the result of the workbench is 0, the numRows value is -1 and the Next button is enabled
**Related Issue** : #572
go to workbench
execute result 0 query.
see numRows = 0 and next button disappeard.

F#572 workbench error 0 result

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts

스키마 브라우저에서 데이터 베이스 변경 후 샘플 데이터 조회 시 에러가 발생합니다. 
**Related Issue** : #580  
1. workbench 화면에서 스키마 브라우저를 오픈합니다. 
2. 샘플 데이터 조회 후, 데이터베이스를 변경하여 다시 샘플데이터를 조회합니다. 
3. 데이터가 정상 조회 되는지 확인합니다.

#580 Change database name when database changes in schema browser

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java

Column labels and column names do not match in mysql
**Related Issue** : #588 
1. go to mysql workbench.
2. execute query.
- show tables;
- select id, id as id1 from polaris.book;
3. see result.

#588 change columnName to columnLabel

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts

Set default name when creating dataset
#550 
Check default name when creating dataset (last step in creation)
1. create dataset with csv file ->  filename (CSV)
2. create dataset with excel file ->  filename - sheetname (EXCEL)
3. create dataset with staging -> tablename (STAGING)
4. create dataset with db -> tablename (TYPE OF DATABASE eg. MYSQL)

#550 set default name when creating dataset

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts

histogram bar is too short to click
#564 
1) click dataflow
2) click wrangled dataset
3) click rule edit
4) histogram bar is too short to click

F#564 short histogram bar

---

discovery-frontend/src/app/data-storage/component/schema-detail/schema-detail.component.html
discovery-frontend/src/app/data-storage/component/schema-detail/schema-detail.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.ts

데이터 소스 생성시 unix time 설정 메뉴 전체에 대해 클릭 이벤트가 적용되어 있는것 제거
#583 
데이터소스 > 데이터소스 생성 > DB, FILE, StagingDB 생성 > schema 설정 단계에서 unix time 옆에 timestamp format 부분 클릭

#583 fix tag in schema detail

---

discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineIngestionService.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpec.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpecBuilder.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/CsvStreamParser.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/Parser.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/StringParser.java

#547 
Create datasource with csv file including new line.
Successfully created 
need to deploy new druid version

F#547 ingest with new line

---

discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbench/workbench.component.ts

워크벤치 결과 영역에 있는 검색버튼이 동작하지 않습니다.
**Related Issue** : #577 
1. 워크벤치를 띄웁니다.
2. 쿼리를 실행하여 결과창을 표시합니다.
3. 결과창 우측 하단에 있는 검색버튼을 클릭하여 검색바가 표시되는지 확인합니다.

#577 Small area of the search button of the workbench does not work

---

discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts

modify uri last path when typing snapshot name
modify uri last path when FileSystem location changing
#648 
1. dataflow chart > select wrangled data > Edit rules > Click Snapshot
2. change Snapshot name ( Snapshot type : FileSystem , Location : WAS or HDFS ) 
3. check File URL in Advanced settings
- [x ] New feature (non-breaking change which adds functionality)

#648 modify uri last path as snapshot name

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

데이터소스 상세화면에서 데이터 타입 정보를 확인할 수 있도록 수정
Ingestion type : Ingested type / Linked type
Meta data > type : File / Database(DB종류) / Staging DB
#549 #631 
1. 데이터소스 생성
2. 데이터소스 상세화면 클릭
3. ingestion type과 meta data의 type이 올바르게 표시되는지 확인

F#549 fix datasource info

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/druid-create-component/druid-select/druid-select.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts

데이터소스 생성 후 생성한 사용자가 바로 데이터소스를 사용할 수 있도록 권한 부여
#643 
1. 데이터소스 생성
2. 데이터소스 상세화면 클릭
3. 데이터소스 permission에 생성한 사용자가 추가되어있는지 확인

#643 add link workspace logic in create datasource

---

discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts

fixed lower / upper quartile values in data preview & column detail.
in detail, changed position of lower and upper quartile values.
#363 
follow the "reproduce" section in issue #363 
1. 데이터 소스 관리 > 데이터 소스 목록 > 상세 보기
or 대시보드 내 데이터 소스 상세 보기
1. "Column Detail" Tab 클릭
1. 측정값 선택 > "Statistic" 항목 확인
1. See error

#363 fix quartile values in data preview and column detail

---

discovery-frontend/src/app/data-preparation/component/snapshot-loading.component.html
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.page.css

#689 
Check if snapshot success/popup isn't broken when dataset name is long

F#689 snapshot popup css error

---

discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/filter/Envelope.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/filter/FilterOperators.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

API 형태로 제공하고 있는 GEO 속성에 대한 BBox filter 의 동작이 되지 않아 이를 수정합니다.
**Related Issue** : #639 
1. sales_geo 데이터 소스 준비 
2. API Search Query 수행 - 값이 정상적으로 전달되는지 확인
```
{
"name": "sales_geo"
},
"filters": [
{
"type": "spatial_bbox",
"field": "location",
"lowerCorner": "-123.0998 25.4766",
"upperCorner": "-68.7918 48.7974"
}
],
"shelf": {
"type": "geo",
"layers": [
[
{
"type": "dimension",
"name": "location",
"alias": "location",
"format": {
"type": "geo"
}
},
{
"type": "measure",
"name": "Sales",
"alias": "SUM(Sales)",
"aggregationType": "SUM"
}
]
]
},
"limits": {
"limit": 10
},
"resultFormat": {
"type": "chart",
"mode": "map"
}
}
```

#639 fix error fitering bbox operator

---

discovery-frontend/src/assets/css/polaris.v2.page.css

워크벤치 하단 에러 박스 부분 위치 수정 
**Related Issue** : #707  
2. 쿼리를 실행 후 취소를 실행합니다. 
3. 실패하여 에러 케이스 인경우, 하단 영역을 확인하여 에러 박스 영역 높이가 동일한지 확인합니다.

#707 Modify error box location

---

discovery-frontend/src/lib/split/split.js

Syncronize hotfix 3.0.6.1 into 3.0.7 release branch.
#775

Sync hotfix commit

---

discovery-frontend/src/app/data-preparation/data-preparation.module.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.service.ts
discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.html
discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.ts
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preparation_dataset.css
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

Dataset can be added to exisiting dataflow (In dataset detail page)
#688 
Go to dataset detail -> click `Add to exisiting dataflow` -> click one dataflow -> check if dataset is added to selected dataflow

F#688 Add dataset to existing dataflow

---

discovery-frontend/src/app/data-storage/component/schema-detail/schema-detail.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.ts
discovery-frontend/src/app/domain/datasource/datasource.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSource.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java

데이터소스 생성시 컬럼 삭제시 사용되는 removed 프로퍼티를 unloaded로 변경
#777 
1. 데이터소스 > 데이터소스 생성
2. configuration 단계에서 특정 컬럼들 제거
3. 데이터소스 생성 
4. 생성시 사용되는 api에 제거된 컬럼의 내부 프로퍼티가 unloaded: true로 변경되어있는지 확인

#777 deleting column not working

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts

fix auto complete of command in case of typing in Hangul
#774 
1. menu MANAGEMENT>Data Preparation>Dataflow 
2. click Wrangled Data
3. click Wrangled dataset > click Edit Rules
4. typing in Hangul at command input and check command list

#774 fix auto complete in command

---

discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.html
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
discovery-frontend/src/app/workbench/service/workbench.service.ts
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-server/src/main/java/app/metatron/discovery/common/datasource/DataType.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java

스키마 브라우저에서 postgresql 연결 후 샘플데이터 및 테이블 조회 시 에러가 발생합니다. 
**Related Issue** : #726  
1. postgresql 연결하여 워크벤치 화면으로 이동합니다. 
2. 테이블 조회, 스키마 브라우저 에서 테이블 리스트 및 샘플데이터가 정상적으로 나오는지 확인합니다. 
3. 다른 데이터 커넥션에서도 문제가 없는지 확인합니다.

F#726 error sample data postgresql in schema browser

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-countpattern.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-drop.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-extract.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-flatten.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-merge.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-move.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-nest.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-replace.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-setformat.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-settype.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-sort.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-split.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-unnest.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-unpivot.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.ts

Editing `split`, `extract`, `countpattern` rule fails
#798 
1. Add split, extract, countpattern rule -> click edit for each rule -> see if there's no error when editing

F#798 Rule edit fail

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.model.ts

1) fix histogram row fetch error
2) If you click on a histogram(or bar chart) with a value greater than 0%, one or more grid rows are selected
(assume that the entire data is 1000, the current screen configuration data is 100, 
and the minimum value of the data selected by the histograms is 240 rows.
In this case, an additional 200 (count) of data is requested to configure the screen.
The requested count may be larger, taking into account the position of the grid vertical scroll bar.)
3) If a grid more event occurs after clicking histograms, select row without any action
#746 
1) fix histogram row fetch error
① click dataflow
② click Wrangled dataset
③ click rdit rule
④ click gridHeader histogram
⑤ click gridHeader bar chart
⑥ loop ④⑤
2) If you click on a histogram(or …

F#746 histogram row fetch error

---

discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/service/data-snapshot.service.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-snapshot-list.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-snapshot-list.component.ts
discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preparation_dataflow_rule.css
discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotRepository.java

1. Show snapshot type in snapshot list, snapshot detail and dataflow main snapshot tab
2. Filtering by snapshot type in snapshot list
#750 
1 . Snapshot Tab > Check if snapshot list shows snapshot type (eg. hdfs, local, staging db)
2 . Snapshot Tab > Check filtering by snapshot type 
3. Snapshot detail > Check if snapshot type is shown
4. Dataflow main grid > snapshot list tab > Check if you can see the type of snapshot

F#750 snapshot type in list

---

discovery-frontend/src/assets/i18n/en.json

Removed mis-committed comments.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/816

#816 remove mis-committed comments

---

discovery-frontend/src/app/common/component/period/period.component.ts
discovery-frontend/src/app/data-storage/data-connection/data-connection.component.ts
discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.ts
discovery-frontend/src/app/meta-data-management/code-table/code-table.component.ts
discovery-frontend/src/app/meta-data-management/column-dictionary/column-dictionary.component.ts

데이터소스 및 메타데이터 화면에서 시간으로 필터링을 할때 정상적으로 조회되지 않는 현상 수정
#501 
1. 데이터소스 > 데이터소스 목록, 데이터 커넥션 목록에서 시간으로 필터링
2. 메타데이터 > 컬럼 사전 목록, 코드 테이블 목록에서 시간으로 필터링

#501 fix search time filter in datasource, metadata

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java

change query generator for ingestion to JPQLParser.
#395 
1. create datasource
2. source type : Database
3. input connection info or select preset connection (HIVE)
4. select query tab
5. input query
```
SELECT * FROM default.sales a join default.sales b on a.orderdate = b.orderdate
```
6. complete datasource create
7. datasource created without error.

F#395 error occured when execute query with duplicated column name.

---

discovery-server/src/main/java/app/metatron/discovery/domain/mdm/CodeTable.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/ColumnDictionary.java

#825
1. 메타데이터 관리 > Column Dictionary 생성
2. Column Dictionary 상세 > CodeTable 생성
3. 메타데이터 관리 > 메타데이터 상세보기탭 > 컬럼 스키마 내 1에서 생성한 Column Dictionary 연결
4. Code Table 내 2번에서 생생한 Code Table 삭제 : **오류없이 삭제됨**
5. Column Dictionary 내 1번에서 생생한 Code Table 삭제 : **오류없이 삭제됨**

#825 Bidirectional remove for code table and colmnn dictionary

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

hibernate session clear before query history save
#848 
3. click cancel button
4. See "Cancel Complete" message not error.

Error notification when query cancelled

---

discovery-frontend/src/app/workbench/workbench.component.ts

워크벤치에서 일정 시간이 지난 후, 쿼리를 실행 시 "The current query is running." 문구와 함께 실행이 되지 않습니다. 
**Related Issue** : #665  
2. 일정시간동안 동작을 하지 않고 대기합니다. 
3. 쿼리 실행 시 정상 동작하는지 확인합니다.

#665 fix init part when query error

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts

Fix misaligned grid
problem while scrolling the grid to the touchpad.
check the grid scroll horizontal value, and run the timer once.
#818 
1. click dataflow
2. click Wrangled dataset
3. click rdit rule
4. scroll grid left and right using touchpad
5. stop touchpad operation 
6. loop 5,6

F#818 fix misaligned grid

---

discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
discovery-frontend/src/app/data-preparation/component/radio-select-dataset.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.ts
discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.service.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDataflowController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepParamDatasetIdList.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSwapRequest.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

The effect of the "change input dataset" should be to change the upstream only for the corresponding wrangled dataset.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/664
Run locally.

F#664 enhance dataset swapping

---

discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java

Remove first row option is not working properly.
1. Datasource > Import CSV file type 
2. Select "Remove first row" option
3. Ingest successfully
HOT BUG FIX

Fix checking first header row in csv

---

discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/DataConnectionController.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java

워크벤치 화면에서 테이블 검색 시 조회가 되지 않습니다. 
**Related Issue** : #726 
2. 테이블 내역 검색 시, 정상 동작 하는지 확인합니다.

F#726 error sample data postgresql in schema browser fix

---

discovery-frontend/src/app/domain/audit/audit.ts
discovery-frontend/src/app/domain/query/queryHistory.ts
discovery-frontend/src/app/monitoring/audit/job-log/component/job-detail/job-detail.component.html
discovery-frontend/src/app/monitoring/audit/job-log/job-log.component.html
discovery-frontend/src/app/monitoring/audit/job-log/job-log.component.ts
discovery-frontend/src/app/monitoring/audit/log-statistics/log-statistics.component.html
discovery-frontend/src/assets/css/metatron/component/component.tag.css
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java

Show cancelled and running in different font (job log, log statistics)
#875 
Log statistics -> check cancelled, running status
Log statistics -> log statistics detail   check cancelled, running status
Job log ->  check cancelled, running status
Job log detail ->  check cancelled, running status

F#875 monitoring cancelled & running status

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-navigation/detail-workbench-navigation.html
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-navigation/detail-workbench-navigation.ts

워크벤치 네비게이션 더 보기 처리 추가 
**Related Issue** : #891  
2. 네비게이션 버튼을 클릭합니다.
3. 목록이 20건 이상일때, 더 보기 버튼이 활성화 되며 정상 동작하는지 확인합니다.

#891 display more button update

---

discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/extension/AggregationExtension.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/extension/DruidExtension.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/extension/ViewExtension.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/GeoHashFormat.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

- metatron Query Spec. 에서 제공하는 user-defined 필드, time_list/expr 타입의 필터 를 WFS 를 통해 동작하도록  구성합니다. 
- geo aggreation type 에 geohex 타입을 추가합니다.
**Related Issue** : #616 #920 
- 3.1.0 용 신규 Druid 및 GeoServer 가 필요합니다. 
- estate 라는 geo column 이 포함된 데이터 소스를 생성합니다.  (location 이라는 이름으로 geo_point 타입의 필드 생성, y - lat , x - lon )
[geo_estate.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2618842/geo_estate.csv.txt)
- API 를 통한 테스트 수행
- filter (expr/time_list type)
- user_defined 필드
```
{
"name": "estate"
},
"filters": [
{
"type": "time_list",
"field": "event_time",
"timeUnit": "MONTH",
"byTimeUnit": "MONTH",
"discontinuous": false,
"valueList": [
"Jul 2018"
]
},
{
"type": "expr",
"expr": "amt < 50000 && amt > 40000"
},
{
"type": "include",
"field": …
```

Support user-defined field through WFS query

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/dashboard.component.ts
discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/app/workspace/component/permission/shared-member-manage.component.html
discovery-frontend/src/app/workspace/component/permission/shared-member-manage.component.ts

Fixed some defected bugs
**Related Issue** : MT-108, MT-149, MT-155
1. 공유 워크스페이스 > 상단 멤버&그룹 선택 > Setting > 불러올 내용이 있을때만 더보기 버튼이 표시되고 있는지 확인합니다. 
2. 프리젠테이션 대시보드 뷰에서 비어있는 대시보드가 있을 경우 정상적으로 다음 대시보드로 넘어가는지 확인합니다.
3.  워크북 > 댓글 목록 > 댓글 삭제 시 로딩바가 정상적으로 없어지는지 확인합니다.

Bugfix in workbook

---

discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/linked-resources/detail-workspace-linked-resources.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/linked-resources/detail-workspace-linked-resources.component.ts
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/viewer/resources-view.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/viewer/resources-view.component.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-frontend/src/app/workspace/workspace.component.ts

Fixed some defected bugs
**Related Issue** : MT-16, MT-87, MT-88
1. LNB영역 표시 상태에서 메타트론 로고 선택 시 LNB 영역 닫히는지 확인합니다.
2. administration > 워크스페이스 > 임의의 데이터 선택 > 데이터소스 "더보기" 를 클릭한 후 팝업 내에서 페이징 기능이 정상적으로 동작하는지 확인합니다.
3. administration > 워크스페이스 > 임의의 데이터 선택 > 데이터커넥션 "더보기" 를 클릭한 후 팝업 내에서 페이징 기능이 정상적으로 동작하는지 확인합니다.

Bugfix in lnb and administration

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.ts

Fix column context menu(set) in the main transform page.
#976 
1. Open any wrangled dataset.
2. Click: column context menu - Edit - Set
3. Check rule editor

#976 fix set rule via context menu

---

README.md

메타트론 설명 파일에 신규 기능에 대한 설명을 추가합니다.
**Related Issue** : #661 
1. 신규 추가된 맵차트에 대한 이미지와 설명을 확인합니다.

F#661 update readme

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts

1. Oracle is removed from create dataset with database 
2. Security component is added
#1015 
1. Dataset -> create dataset (db) -> check if ORacle is removed from database type
2. Check if security component is added

#1015 Fix UI in create dataset with database

---

discovery-frontend/package.json
discovery-frontend/src/app/common/directive/input-mask.directive.ts
discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts

데이터소스 생성 마지막 단계에서 스크립트 에러가 발생하는 현상 수정
1. 데이터소스 > DB로 데이터소스 생성 > ingestion step에서 row 입력
2. 데이터소스 생성 complete에서 done 버튼 클릭
3. 정상적으로 데이터소스 생성되는것 확인

Fix datasource create step script error

---

discovery-frontend/src/app/common/domain/extension.ts
discovery-frontend/src/app/common/service/common.service.ts
discovery-frontend/src/app/common/util/common.util.ts
discovery-frontend/src/app/external/external-page.component.html
discovery-frontend/src/app/external/external-page.component.ts
discovery-frontend/src/app/external/external-view.module.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-frontend/src/app/layout/layout/layout.module.ts
discovery-frontend/src/app/workspace/service/workspace.service.ts
discovery-frontend/src/environments/environment.prod.ts
discovery-frontend/src/environments/environment.ts
discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionController.java
discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionProperties.java
discovery-server/src/main/resources/application.yaml
discovery-server/src/test/java/app/metatron/discovery/domain/extension/ExtensionRestIntegrationTest.java

We will continue to add a seamless set of features within metatron discovery.
Therefore, we need to add an extensible function to the LNB menu structure.
**Related Issue** : #906 
1. LNB에 integrator 메뉴가 정상적으로 표시되는지 확인합니다.
2. 메뉴 클릭 시 integrator가 정상적으로 표시되는지 확인합니다.
- [] Bug fix (non-breaking change which fixes an issue)

#906 (Experimental) Add extension function in lnb area : integrator

---

discovery-frontend/src/app/page/page.component.ts

- geo 타입일때 맵차트의 스크립트 오류를 수정하였습니다.
**Related Issue** : #659 
- GEO타입인 dimension을 선반에 올릴때 스크립트의 오류가 발생하지 않는지 확인합니다.

F#659 fix map chart validation bug

---

discovery-frontend/src/app/user/profile/profile.component.html
discovery-frontend/src/app/user/profile/profile.component.ts
discovery-frontend/src/app/workspace/component/management/change-owner-workspace.component.ts
discovery-frontend/src/app/workspace/component/permission/shared-member-manage.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceMemberPredicate.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

공통 영역에서의 오류를 수정합니다.
**Related Issue** :  
1. 프로필 수정 화면에서 Save 버튼이 비활성 상태일 때 동작하지 않는지 확인합니다.
2. IE 에서 공유 워크스페이스 내 공유 멤버 및 그룹 설정 팝업이 정상적으로 표시되는지 확인합니다.
3. 공유 워크스페이스 소유자 변경 팝업에서 이전 검색 정보가 없어지는지 확인합니다. ( MT-114 )
4. 프로필 변경 화면 입력 체크 표시가 나타나는지 확인합니다. ( MT-22 )

Bugfix in common

---

discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.html
discovery-frontend/src/assets/css/metatron/component/component.filtering.list.css

데이터소스 필터링 목록 중 delete 버튼이 표시되지 않던 현상 수정
데이터소스 목록의 수가 정상적으로 표시되지 않던 현상 수정
x
1. 데이터소스 목록
2. 필터링 목록에서 MORE를 통해 추가한 필터에 delete 버튼이 제대로 표시되는지 확인
3. 데이터소스 목록의 수가 정상적으로 표시되는 것 확인

Fixed datasource list page

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepMonitorService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java

Bug fix on dataprep meta DB migration.
Handling CLOB and ignoring missing dataflow-dataset relations.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1046
Locally.

F#1046 dataprep migration

---

discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.ts
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/app/page/page.component.ts
discovery-frontend/src/assets/css/metatron/popup/metatron.popup.02Workbook_ChartMap.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

- releasetest에서 발견된 버그사항을 해결합니다.
**Related Issue** : #659 
- tooltip 에러
1. 맵차트를 선택하고 geo 데이터를 올립니다.
2. layer type에서 hexagon을 선택합니다.
3. radius값을 증가시킵니다.
4. 차트에 마우스오버시 툴팁이 잘 보이는지 확인합니다.
- 맵차트를 제외한 다른차트에서의 geo dimension 막기
1. geo dimension을 포함한 데이터소스로 대쉬보드를 생성합니다.
2. 바차트를 선택 후 geo dimension을 선반에 올립니다.
3. alert이 뜨고 선반에 올라가지 않는지 확인합니다.

#659 fix tooltip z-index bug, block geo data

---

discovery-distribution/conf/application-config.templete.yaml
discovery-frontend/src/app/dashboard/filters/component/time-range.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/geo/GeoRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRangeFilter.java
discovery-server/src/main/resources/application.yaml

Within the Map Widget, the search query is passed through geo server.
An error occurs when you add a filter to a column of type timestamp in query.
#1055 
1. Go to dashboard linked datasource including geo related column
2. Create map widget on dashboard
3. Put on geo related column on shelf
4. Add timestamp type of column on filter
5. Click to 'Specific'
6. There is no error
Hotfix thing

Error when quering timestamp filter

---

README.md

Fix druid link and add geo server binary into readme file.
Show Readme file or 
check this page (https://github.com/metatron-app/metatron-discovery/tree/fn-update_readme)
요 부분 영어 쓴것 리뷰를 부탁 드립니다.. 😄

Update installation guide and fix binary link

---

README.md
discovery-distribution/conf/application-config.templete.yaml
discovery-frontend/src/app/dashboard/filters/component/time-range.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepMonitorService.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/GeoRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRangeFilter.java
discovery-server/src/main/resources/application.yaml

Sync hotfix onto 3.1.1 Release candidates branch.

Sync Hotfix

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionServiceTest.java

1. DataSource 생성 > DataBase > Query Type을 통한 데이터 소스 생성 시 Alias를 제대로 처리하지 못하는 오류 발생
2. Ingested Type의 데이터소스일 경우는 Query구문 수정없이 사용자가 입력한 Query문을 그대로 수행하도록 변경함.
3. 중복 컬럼명 발생시에는 난수를 추가하여 오류 회피하도록 수정함
#1079 
#1081 
1. DataSource 생성
2. DataBase 선택
3. Query 탭 선택하여 쿼리 입력 (alias projection)
4. DataSource 생성
5. 정상적으로 생성되는지 확인

H#1079 datasource with query error

---

discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
discovery-frontend/src/app/common/component/chart/option/ui-option/map/ui-layers.ts
discovery-frontend/src/app/common/component/chart/option/util/chart-util.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/page/chart-style/color-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/app/page/page.component.ts
discovery-frontend/src/assets/css/metatron/popup/metatron.popup.02Workbook_ChartMap.css
discovery-frontend/src/assets/css/polaris.v2.page.css

맵차트에서의 color by measure의 사용자 색상설정을 추가합니다.
**Related Issue** : #1069 
1. 차트화면에서 맵차트를 선택합니다.
2. 선반에 geo dimension, measure를 올립니다.
3. 레이어 옵션에서 color by measure의 사용자 색상설정을 on으로 변경합니다.
4. 사용자 색상설정을 변경하고 차트에 잘 반영되는지 확인합니다.

F#1069 Support setting custom color for layer in map view

---

discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonParseResult.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java

Currently, we only support CSV file type snapshot generating.
JSON file type snapshot generating feature is required.
https://github.com/metatron-app/metatron-discovery/issues/1074
1. Create snapshot with JSON format to local and hdfs storage.
2. Check if snapshot preview is displayed well.
3. Download generated snapshot file.(Currently it downloaded as csv file. It will be fixed soon.)

F#1074 create json file type snapshot

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/BuiltinFunctions.java
discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/Expr.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java

Fix error when applying keep/delete with histogram click + context menu when column type is timestamp
#1019

F#1019 timestamp type column error when deleting

---

discovery-frontend/src/app/common/component/chart/type/gauge-chart/gauge-chart.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/page/page.component.html

게이지차트의 오름차순 / 내림차순의 미동작 에러를 해결합니다.
**Related Issue** : #1104 
1. 차트화면에서 게이지차트를 선택합니다.
2. 선반에 diemsnion / measure를 각각 하나씩 올립니다.
3. measure의 오름차순 / 내림차순에 따라 차트가 정렬되는지 확인합니다.

#1104 Sorting error in gauge chart

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/service/data-snapshot.service.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetSparkHiveService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java

You can download the STAGING_DB snapshot as a CSV or JSON file.
#1086 
1. Menu > MANAGEMENT > Data Preparation > Data Snapshot
2. Click Staging DB type data
3. Click download JSON or CSV

F#1086 download file or staging db snapshots as json file

---

discovery-frontend/src/app/common/component/chart/option/util/chart-util.ts
discovery-frontend/src/app/dashboard/util/dashboard.util.ts
discovery-frontend/src/app/page/chart-style/common-option.component.html
discovery-frontend/src/app/page/chart-style/common-option.component.ts

게이지 차트에서 Limit 경고 아이콘이 표시되는 오류를 수정합니다.
**Related Issue** : #1104 
1. 게이지 차트를 추가합니다.
2. 대시보드 편집 화면 및 열람화면에서 게이지 차트에 Limit 경고 아이콘이 나타나지 않는지 확인합니다.
( Limit 경고 아이콘이 표시 되지 않아야 정상 )

#1104 Fixed an error where limit icon appeared on gauge chart.

---

discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.ts
discovery-frontend/src/assets/css/metatron/component/component.table.css

In dataset detail `Add dataset to existing dataflow`  didn't work properly
#1071
Dataset detail -> click `Add dataset to existing dataflow` -> check if dataset is added to selected dataflow

#1071 Fix add dataset to existing dataflow error

---

discovery-frontend/src/app/page/chart-style/color-option.component.html
discovery-frontend/src/app/page/chart-style/color-option.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
discovery-frontend/src/assets/css/metatron/component/component.input.css
discovery-frontend/src/assets/css/polaris.v2.page.css

사용자 색상설정의 말줄임 적용 및 디자인을 변경합니다.
**Related Issue** : #1069 
1. 차트화면으로 이동합니다.
2. 맵차트에 geo dimension과 measure를 올리고 layer 패널을 엽니다.
3. 색상의 사용자 색상설정을 on으로 변경하고 말줄임 설정이 잘되는지 확인합니다.

F#1069 change custom color design

---

discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

Add rule list in dataset detail page when dataset is wrangled
#1173 
Check if you can see rule list in dataset detail page ( wrangled)

#1173 Add rule list in dataset detail - wrangled

---

README.md

- README 파일에서 `Github Issue` 링크를 수정했습니다.
**Related Issue** : #1205 
- README에서 `Github Issue` 링크를 클릭했을때 `https://github.com/metatron-app/metatron-discovery/issues` <- `Github Issue` 페이지로 이동하는지 확인
(N/A)

#1205 Modify the link to the Github issue in the README file

---

discovery-frontend/src/app/monitoring/audit/job-log/component/job-detail/job-detail.component.html
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

Change Phrase `Recent 5 queries` to `Recent history of the same connection`
#640 
Go to job log list -> Click one job log -> Check if 
`Recent 5 queries` is changed to `Recent history of the same connection`

#640 Fix phrase in job log detail

---

discovery-frontend/src/app/common/component/chart/base-chart.ts

* #972 오류를 해결 했습니다. 
* 상세한 오류 내용은 #972 이슈에 첨부해 두었습니다.
#972
엔진에 기본 탑재되어 있는 sales_geo 데이터 소스를 사용하여 Text Table 차트를 아래 조건으로 테스트 하였습니다.

#972 If the data table dimension is 3, and the measure value is 2, the browser does not work

---

discovery-frontend/src/app/meta-data-management/code-table/create-code-table/create-code-table.component.html
discovery-frontend/src/app/meta-data-management/column-dictionary/create-column-dictionary/create-column-dictionary.component.html
discovery-frontend/src/app/meta-data-management/meta-data-management.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/complete-create-metadata.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.ts
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-set-connection.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.html
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/css/polaris.v2.page.css

Scroll scope has been changed in  [metadata, column dictionary, code table, catalog]  lists and [-[ [Metadata, column dictionary, code table] create popup
#1233 
1. 
2 . Create datasource metadata
3 . create hive metadata
4 . last step in creating metadata
5 . Create column dictionary
6. create code table

F#1233 improve scrolling in metadata

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.ts

Snapshot list is requested too many times.
Only request snapshot list only when one request is finished.
#1220 
Go to data flow main grid -> create snapshot -> check network if `/api/preparationsnapshots/${dfId}/work_list` api is requested only when one request is finished

F#1220 polling error in snapshot list

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
discovery-frontend/src/assets/css/polaris.v2.component.css

add function horizontal scroll in histogram area
(This function does not work in the ie browser.)
#795 
1. menu MANAGEMENT > DataPreparation > Dataflow
2. click dataflow item
3. click Wrangled item > click Edit rules button
4. test using the touchpad. [Horizontal scroll in histogram area]

F#795 horizontal scroll in histogram area

---

discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/assets/css/metatron/page/metatron.page.02Workbook_Chart.css

데이터 테이블의 표현된 전체 레코드가 실제 데이터 레코드 갯수와 일치하지 않음
**Related Issue** : #968 
1. 원본보기 형식의 데이터 그리드 차트를 생성합니다.
2. 데이터가 100건 이상 표시되는지 확인합니다.  ( 기본 limit 이 1000 으로 적용되고 있는지 확인합니다. )

#968 The records in the data table do not match the actual data.

---

discovery-frontend/src/app/common/component/chart/option/util/option-generator.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/common/constant/common.constant.ts
discovery-frontend/src/app/dashboard/service/widget.service.ts
discovery-frontend/src/app/page/chart-style/map/map-common-option.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetProperties.java
discovery-server/src/main/resources/application.yaml
discovery-server/src/test/java/app/metatron/discovery/domain/workbook/widget/WidgetRestIntegrationTest.java

기본 맵에 대해서 설정할 수 있으며, 추가된 맵에 대해서 차트 생성 시 설정할 수 있어야 합니다.
**Related Issue** : #1064 
1. 맵 차트 생성 시, 설정에 따라 기본 맵 차트가 변경되는지 확인합니다.
2. 맵 차트 옵션에서 추가된 차트 스타일 목록이 표시되는지 확인합니다.
3. 대시보드 상에서 정상적으로 표시되는지 확인합니다.
개발 시 테스트 설정 
`widget:
mapView:
defaultBaseMap: TOP
override: false
baseMaps:
-
name: TOP
url: https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/{z}/{x}/{y}?access_token=[token]
`

#1064 Support for adding basemap in mapview via configuration

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataflowProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDatasetProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java

In data preparation, createdBy was used instead of user's full name
#1171 
1 . Check if user's full name is shown in  created column (dataset list, dataflow list, snapshot list)
2 . Check in dataset and dataflow detail navi area
3 .Check in dataflow panel

F#1171 dataprep shows user full name

---

discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/page/chart-style/map/map-common-option.component.ts
discovery-frontend/src/assets/i18n/ko.json

이전에 만든 지도 차트를 열거나 새로 지도 차트 생성할 경우 오류가 발생하여 정상적으로 동작하지 않습니다.
**Related Issue** :  #1064 
1. 이전에 만들어진 지도 차트가 포함된 대시보드를 접속했을 때 오류없이 정상적으로 표시되어야 합니다.
2. 새로 지도를 생성할 경우 오류없이 정상적으로 표시되어야 합니다.

#1064 fix error when creating map chart

---

discovery-distribution/pom.xml
discovery-frontend/pom.xml
discovery-frontend/src/app/data-storage/service/granularity.service.ts
discovery-frontend/src/assets/css/metatron/component/component.form.css
discovery-prep-parser/pom.xml
discovery-server/pom.xml
pom.xml

Release 3.1.2

---

discovery-frontend/src/app/page/page.component.ts

바 차트에서 선반(행 또는 교차)에 dimension 값이 추가될때 차원값 색상 및 범례를 변경 합니다. 
**Related Issue** : #463  
1. 차트 화면으로 이동하여 바차트를 선택합니다. 
2. 선반에 차원값을 복수로 추가합니다. (행 또는 교차 선반) 
3. 가장 최신에 등록된 차원값 기준으로 색상과 범례가 변경됩니다. 
Dimension 값으로 변경되며 가장 최근 등록된 값 기준으로 변경

#463 bar chart change the dimension value when row, aggregation

---

discovery-frontend/src/app/common/component/data-download/data.download.component.ts
discovery-frontend/src/app/dashboard/service/widget.service.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/domain/datasource/data/search-query-request.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/BoardConfiguration.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java

대시 보드에서 설정한 필터 조건을 위젯 다운로드 화면에 반영 하였습니다.
#1129 
파이 차트와 데이터 테이블 차트를 만들고 파이 차트에서 드릴 다운으로 데이터를 필터링 후 데이터 테이블 다운로드를 수행 하였습니다.

#1129 The data represented in the chart does not match the download data

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java

Fix to use the delimiter
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1345
I've made a snapshot on local.

#1345 use the delimiter for snapshots

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-list.component.html

Show browser tool tip in snapshot detail file uri
#1296 
Go to snapshot detail(file type) ->  put mouse cursor on file uri (file:///....) -> check if you can see browser tooltip

#1296 Show tooltip when snapshot file uri is shortened

---

discovery-frontend/src/app/dashboard/dashboard.module.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/embedded/embedded-view.module.ts
discovery-frontend/src/app/page/page.module.ts

차트 데이터 조회 시 선반 정보 내, timezone 정보가 누락되어 있습니다.
**Related Issue** : #1193 
1. 차트 데이터 조회 시, 선반 정보에서 timezone 정보가 포함되어 있는지 확인합니다.

#1193 add timezone in pivot

---

discovery-frontend/src/app/data-storage/service/granularity.service.ts

timestamp 실 데이터가 undefined로 내려오는경우 interval을 지정할수 없던 문제 수정
#1355 
1. 아래 테스트파일로 업로드 후 데이터소스 생성
2. interval 설정이 올바르게 표현되는지 확인
[Timezone3s.xlsx](https://github.com/metatron-app/metatron-discovery/files/2819681/Timezone3s.xlsx)

#1355 fix config data undefined error

---

discovery-distribution/pom.xml
discovery-frontend/pom.xml
discovery-prep-parser/pom.xml
discovery-server/pom.xml
pom.xml

Set new pre-release version 3.2.0-rc2
Built all projects

Set new pre-release version 3.2.0-rc2

---

discovery-frontend/src/app/workspace/component/permission/permission-schema.component.html

IE에서 공유 워크스페이스가 생성할 때 오류를 수정하였습니다.
#1308 
IE 11과 Chrome 71 에서 공유 워크스페이스를 생성해서 테스트 하였습니다.
(https://github.com/metatron-app/metatron-discovery/issues/1308#issuecomment-461694558 참조)

#1308 Workspaces are not created under certain conditions in I.E Browser.

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunner.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/JdbcIngestionJob.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunnerIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/fixture/MySqlDatasourceTestFixture.java
discovery-server/src/test/resources/fixture/mysql/payment.sql
discovery-server/src/test/resources/sql/test_datasource_list.sql

DB 타입 데이터 소스 생성 시 적재 설정을 주기적 수집으로 하고 수집 데이터 범위를 증감분 데이터으로 선택한 경우 오류 없이 Ingestion 되도록 수정함.
#1340 
* #1340 재현 경로로 테스트
* JUnit 테스트 케이스로 검증

#1340 'No database selected' error when selecting 'Overwrite only incremental' when creating DB type datasource

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts

#1400 
1. Menu> Data Preparation > Data Snapshot
2. Click Snapshot
3. Scroll grid
4. Check grid data (100 rows of paging size)

#1400 Snapshot grid paging processing

---

discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
discovery-frontend/src/app/data-storage/service/timezone.service.ts
discovery-frontend/src/app/page/component/analysis/slider/range-slider.component.ts

version up 관련 에 빌드 오류 수정
**Related Issue** : #1151 
빌드가 정상적으로 되는지 확인합니다.

fix build error

---

discovery-frontend/src/app/common/component/paging-search-select/paging-search-select.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
discovery-frontend/src/app/data-storage/data-storage.module.ts
discovery-frontend/src/app/data-storage/service/data-connection-create.service.ts
discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
discovery-frontend/src/app/domain/dataconnection/dataconnection.ts
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/css/polaris.v2.page.css

데이터소스 생성 단계 중, 데이터베이스 선택 단계에서 쿼리를 이용하여 데이터를 조회할 경우, 해당 쿼리의 에러 내용이 데이터 미리보기 화면에 나타나도록 수정
- 잘못된 쿼리 사용시 안내문구 
#941 
1. 데이터소스 > DB로 데이터소스 생성 > 데이터베이스 선택 단계
2. Query 탭을 선택 후, 잘못된 쿼리 작성 후 RUN을 눌러 데이터조회 시도
3. 2에서 작성한 쿼리에 대한 에러 내용이 하단의 데이터 미리보기 화면에 나타나는지 확인

#941 add error message query source create

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts

Relplace to html entity in grid (tag symbol, new line)
#1381 
1. Import [finefood.sample.txt](https://github.com/metatron-app/metatron-discovery/files/2821459/finefood.sample.txt) **with colon delimiter.**
2. Click the new generated I.DS.
3. Click Create dataflow with this dataset. 
4. Edit rules.
5. Drop column3 and all after.
6. Click "Snapshot" button
7. Click "Done" (make a CSV snapshot)
8. Click the new generated snapshot.
9. Scroll down and you'll see the empty lines (in the middle)
Also applies to dataset, dataflow

#1381 Relplace to html entity(tag symbol,new line)

---

discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts

대시보드 프리젠테이션 모드에서 3시간 이상 유지 시 브라우저 멈추는 현상이 있습니다.
**Related Issue** : #1275 
1. 맵차트, 바차트, 라인차트 등 여러 종류가 있는 대시보드를 생성합니다.
2. 프리젠테이션 모드로 들어가서 실행 버튼을 누릅니다.
3. 메모리 상황을 확인해서 정상적으로 해제가 되는지 확인합니다.

#1275 Memory leaks when maintaining Presentation Mode for long time

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts

Change colour of histogam bar when it's clicked
#1459 
1 .  Go to dataflow main grid
2 . Click histogram bar
3 . Check if colour of histogram bar changes when it's clicked

#1459 Fix histogram click error

---

discovery-frontend/src/app/common/service/abstract.service.ts
discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-select-schema.component.ts
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.html
discovery-frontend/src/app/meta-data-management/metadata/create-metadata/staging-select-schema.component.ts

Hive/StagingDB로 메타데이터 생성시 서버 응답이 느려서 로딩바가 도는 경우 '취소' 버튼과 'X' 버튼을 클릭할 수 없음
**Related Issue** :  #159 
* Go to Metadata
* Click on 'Create metadata'
* Select 'Hive' or 'StagingDB'
* Choose a DB connection and Go to Next
* Choose a Schema and Table
* Try click cancel button or X(exit) button when progress bar is displayed.

#159 Unable to click cancel button and X button when generating metadata

---

discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

데이터소스 생성 > file로 생성 중 file 선택에 대한 안내문구 수정
기존 문구: Only files with comma-separated values such as xls, xlsx, csv are allowed.
바뀐 문구: .xls, .xlsx, .csv formats are allowed.
release test
1. 데이터소스 생성 > file생성
2. file 선택에 대한 안내문구 수정

change file create source guide label

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/css/polaris.v2.page.css

- Remove tab from snapshot detail
- Fix button margin
Release test,
#1475 
1 . Go to users -> members -> detail -> check if two buttons have margin
2 . Go to dataflow main grid -> check margin
3. Go to dataflow detail -> click add dataset button -> check margin
4. Go to snapshot detail -> there should be no tab

#1475 Fix bug from release test

---

discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts

1. 필터 필드 선택 팝업에서 상단 영역에 공백이 있습니다.
2. 필터 패널에서 검색 결과가 없을 때 페이지 표시에 문제가 있습니다.
1. 필터 생성 시, 필드 선택 팝업에서 상단 공백이 없어졌는지 확인합니다.
2. inclusion filter 에서 검색 결과가 없을 때 페이지 표시가 정상적으로 나오는지 확인합니다.

fix dashboard filter

---

discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetDatabaseService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java

Wrong size and summary information in dataset information
#1477 
1 .  Go to dataflow detail -> click excel or csv type imported dataset 
Check if NaN undefined is fixed

#1477 Fix undefined error in dataset information

---

discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts

Script Error Occurs When You View Column Detail, If You Preview the Chart on the Workbench
**Related Issue** : #1216 
* Execute query in workbench
* Click on Chart Preview
* Click DataSource Info button
* Select Column Detail tab

#1216 fix script error in workbench chart

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfDelete.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfKeep.java

Column not found -> Type mismatch
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1378
Ran locally.

#1378 fixed a wrong exception handling

---

discovery-frontend/src/app/data-preparation/data-preparation.module.ts

prod build 시 에러나는 현상 수정
#1554 
```
clean package -Dmaven.test.skip=true
```

#1554 fix build error in module

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

Added limitation (currently 16) so that the DOP (degree of parallelism) become less than thread pool size.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1562
Run locally.
There's a sample file attached in https://github.com/metatron-app/metatron-discovery/issues/1562.

#1562 added limitation on DOP when calculating the histograms

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java

Resurrected skipHeader flag. I thought it was unnecessary.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1568
Run locally.

#1568 bug-fix on header processing of CSV files

---

discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts

대시보드 수정 화면에서, Date/Time 필터의 granularity 수정 시, 무한루프
**Related Issue** : #1446 
1. Edit Dashboard
2. Filter 선택
3. 우측 Filter 항목에서 Date/Time 필터의 granularity 변경
4. 로딩바가 없어지면서 정상적으로 변경되어야 합니다.

#1446 Date/Time filter granularity change error

---

discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java

Show the loading bar until the creation of the temporary data source is complete, and change it to run the chart popup when the creation is complete.
**Related Issue** : #1496 
1. go to workbench
3. click chart preview button
4. Make sure the loading bar is visible until the temporary data source is complete.
5. Make sure that the chart is drawn normally.

#1496 check segment's status for temporary datasource

---

discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts

1 . Refresh error when snapshot type is changed
2. Fix keep/delete expression in context menu
3 . Fix snapshot paging logic
Release test
1. Go to snapshot create popup -> leave snapshot name empty (FILE TYPE) -> click done -> click hive radio -> check if error is removed
2 . Use file with null value
Check if ruleString is `keep row: !ismismatched(`name`,'STRING') && !isNull(`name`)`
3 . Use dataset with 10 rows. -> Make snapshot -> check if you can see 10 rows in snapshot

Fn dataprep release fix

---

discovery-frontend/src/app/admin/user-management/component/group/create-group/create-user-management-groups.component.html
discovery-frontend/src/app/admin/user-management/component/group/create-group/create-user-management-groups.component.ts
discovery-frontend/src/app/common/util/string.util.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css

대시보드 > 데이터소스 선택 > 데이터 미리보기 화면에서 설명이 제대로 표시되지 않는것 수정
데이터소스 > 파일 생성 > 50미만의 row를 가진 데이터를 업로드시 현재 row수가 제대로 표시되지 않던 현상 수정
어드민 > 그룹 > 그룹 생성시 특정 문자열에 대해서 그룹이 생성되지 않던 현상 수정
release test
1. 대시보드 > 데이터소스 선택 > 데이터 미리보기 화면에서 설명이 제대로 표시되는것 확인
2. 데이터소스 > 파일로 데이터소스 생성 > 50 미만의 row를 가진 데이터 업로드시 현재 row가 제대로 표시되는것 확인
3. 어드민 > 그룹 > 그룹생성 시 특정 문자열에 대해 그룹이 제대로 생성되는것 확인

Fix datasource, group release error

---

discovery-frontend/src/app/common/component/chart/type/waterfall-chart/waterfall-chart.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
discovery-frontend/src/app/dashboard/component/update-dashboard/text-widget-panel.component.html
discovery-frontend/src/app/dashboard/update-dashboard.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css

1. 대시보드 편집 화면에서 필터가 없을 때 우측 패널에 불필요한 선이 하나 더 생깁니다.
2. 대시보드 편집 화면에서 위젯 편집 레이어가 하단 위젯의 헤더에 가려지는 현상이 발생합니다.
3. 필터 위젯 추가 시 로딩바가 없어지는 현상이 발생합니다.
1. 대시보드 편집 화면에서 필터가 없을 때 우측 패널에 불필요한 선이 제거 되었는지 확인합니다.
2. 대시보드 편집 화면에서 위젯 편집 레이어가 하단 위젯의 헤더 위로 표시되는지 확인합니다.
3. 필터 위젯 추가 시 로딩바가 정상적으로 없어지는지 확인합니다.

#0 fix error that dashboard

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts

fix create dataset with multi file, modify delete dataset
release test
1. fix create dataset with multi files 
1.1. menu> MANAGEMENT > Data Preparation > Dataset > Generate new dataset 
1.2. Multi file Upload and Create dataset 
2. modify delete dataset
 2.1. menu> MANAGEMENT > Data Preparation > Dataset 
2.2. Delete dataset

f#0-fn-dataprep-create-dataset-fix  fix create dataset with multi files

---

discovery-frontend/src/app/dashboard/component/update-dashboard/dashboard.layout.config.component.html
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

1. 필터 패널의 좌측 여백이 없습니다.
2. 스키마 브라우저에서 버튼간의 간격이 없어졌습니다.
3. 워크벤치에서 두 개의 쿼리를 실행 후, 결과탭을 삭제하면 남은 결과탭의 내용이 보이지 않습니다.
1. 대시보드 편집 화면에서 필터 패널의 좌측 여백이 있는지 확인합니다.
2. 스키마 브라우저에서 버튼 간격이 있는지 확인합니다.
3. 워크벤치에서 결과탭을 삭제했을 때 정상적으로 동작하는지 확인합니다.

adjust margin button and panel / fix error when remove result tab in workbench

---

discovery-server/src/main/resources/application.yaml

Fixed misusable property templates.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1632
Ran locally.

F#1632 fix conf template

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
discovery-frontend/src/app/workbench/workbench.component.html

Add Double quote when you click on table name of LNB of Druid workbench.
**Related Issue** : #1490 
1. 드루이드 커넥션으로 워크벤치를 생성합니다.
2. 왼쪽의 테이블 목록에서 테이블 명을 클릭합니다.
3. SQL 이 추가될 때 테이블명에 쌍따옴표가 추가되어 있는지 확인합니다.

#1490 Add Double quote when you click on table name of LNB of Druid workbench

---

discovery-server/src/main/java/app/metatron/discovery/common/MetatronProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbench/hive/WorkbenchHiveService.java
discovery-server/src/main/java/app/metatron/discovery/util/CsvProcessor.java
discovery-server/src/main/java/app/metatron/discovery/util/csv/CsvTemplate.java

Error occurred when creating data source with CSV file.
Exceeding max character per column value of csv parser.
**Related Issue** : #1594 
1. create datasource from csv
2. use this file
https://github.com/metatron-app/metatron-discovery/files/2939563/sample_col_size.csv.zip
3. see data preview without error

F#1594 set max chars per column for csv parse

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.model.service.ts
discovery-frontend/src/app/data-preparation/util/prep-select-box-custom.component.ts
discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
discovery-frontend/src/assets/css/polaris.v2.page.css

Change direction of drop down in window/aggregate/pivot expression because it's hard to use the drop down when there are many expressions.
#1379 
Go to dataflow main grid -> click window rule
-> Check if direction of drop down in upward not downward
GOOD
BAD

#1379 fix suggestion layer direction

---

discovery-frontend/src/app/workbench/workbench.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java

An error occurs when using reserved words for field names.
**Related Issue** : #1495 
1. mysql 커넥션으로 워크벤치를 생성합니다.
2. 다음의 쿼리를 실행합니다.  ( select '1' as count, 2 as __time; )
3. 차트 미리보기를 해서 정상적으로 표시되는지 확인합니다.

#1495 An error occurs when using reserved words for field names.

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java

hive description : start row 2 => 0 
**Related Issue** : #1690 
1.데이터 소스 선택
2.Staging 선택
3.ORC 테이블 선택 후 druid 적재 테스트를 진행한다.
4.적재 후 druid에 해당 필드가 있는지 확인 한다.

#1690 hive table description bug fix (start row 2 => 0)

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts

When you create a dataset with a file, Show the upload location for each file.
#1693 
When you create a dataset with a file, check file upload location.

#1693 Show file upload location when creating dataset with file

---

discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java

create data source via excel file properly
통합테스트
create datasource with excel file
[세일즈데이터.xlsx](https://github.com/metatron-app/metatron-discovery/files/3002170/default.xlsx)

fn-add support dimension type : TEXT

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistory.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistoryRepositoryTest.java

#1711 참조
#1711 
* JUnit 테스트 케이스로 검증
* 테스트 대시 보드를 만들고 아래 처럼 긴 URL을 호출시 정상적으로 차트 노출되는지 확인함.
* http://www.test.com/app/v2/dashboard/3f9aaf8e-d541-4187-95b3-e11bccc1460e?work_no=O190314000077&event_time=2019-03-14%2020:00:00%2F2019-03-21%2020:00:00&occr_dt=20190308&occr_dt=20190309&occr_dt=20190310&occr_dt=20190311&occr_dt=20190312&occr_dt=20190313&occr_dt=20190314&occr_dt=20190315&occr_dt=20190316&occr_dt=20190317

#1711 Embedded chart implementation error when parameter is long

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java

Add Filter Criteria for Extended Connections
1. goto connection list
2. drop down DB type in filter criteria
3. see extended connection

Add Filter Criteria for Extended Connections

---

discovery-frontend/src/app/common/component/chart/option/define/map/map-common.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/page/chart-style/map/map-format-option.component.ts
discovery-frontend/src/app/page/component/analysis/map-spatial/map-spatial.component.html
discovery-frontend/src/app/page/component/analysis/map-spatial/map-spatial.component.ts
discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.html
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java

공간연산을 수행하고 대시보드에 넣는순간 아래와 같은 오류가 발생합니다.
1. 공간연산을 적용한 맵 차트를 생성합니다.
2. 대시보드에 배치한 후 정상적으로 표시되는지 확인합니다.

Fixed an error when adding a map operation with a spatial operation to a dashboard

---

discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/connector/AbstractJdbcConnector.java

none auth connection like DRUID connection failed
**Related Issue** : #1295 
1. create druid connection
2. click validate button
3. see success

#1295 none auth connection properties handle

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/HiveDataAccessor.java

Error in retrieving detailed information of partitioned hive table
통합테스트
1. create datasource > StageDB
2. select partitioned table
3. see data preview without error

Fix hive desc statement null point exception

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts

Sorting is refreshed every time filters are applied
Test issue
1. Go to snapshot list
2. Sort by snapshot name ascending
3. Search snapshot
4. Check if list is still sorted by name asc

Fix sorting error in snapshot list

---

discovery-frontend/src/app/notebook/component/create-notebook-api/create-notebook-api.component.html
discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.html
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

1. 비활성화 상태인 라디오버튼 클릭 이벤트 제거
2. 노트북 서버 설정 화면에서 검색부분 placeholder에 메세지 추가
통합테스트
- 비활성화 상태인 라디오버튼 클릭 이벤트 제거
1. 워크스페이스  > 노트북 선택
2. API 버턴 클릭
3. 비활성화된 Radio Btn이 클릭안되는것 확인
- 노트북 서버 설정 화면에서 검색부분 placeholder에 메세지 추가
1. 워크스페이스 > 노트북 서버 설정 화면에서 placeholder 확인

Fix radio btn event modified  in notebook html

---

discovery-frontend/src/app/data-preparation/component/dataset-summary.component.html
discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
discovery-frontend/src/app/data-preparation/component/long-update-popup.component.html
discovery-frontend/src/app/data-preparation/component/long-update-popup.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/union-add-datasets/union-add-datasets.component.ts

Maintain selected items even after sorting or searching.
No issue
1 . Go to data flow detail -> click + add dataset  -> check some items -> sort list by asc or desc -> check if selected items are not refreshed.
2 . Go to dataflow detail -> click one wrangled dataset -> open swap dataset popup -> change selected item -> search dataset -> check if radio button is not refreshed.
3 . Go to dataflow detail -> click +add dataset button
total number of selections are not based on displaying list.
3-1. check three items
3-2. search `sdsddea`  -> there will be no items in the list
3-3. selected number of items should not change (3 selections)

Selected items must not refresh after sorting or searching

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/component/ingestion-log/ingestion-log.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts

실시간 데이터소스 상세화면에서 fail 상태에 대한 detail 클릭시 나타나는 스크립트 에러를 수정
통합테스트
1. fail 상태인 실시간 데이터소스 상세화면 클릭
2. detail 클릭
3. 스크립트 에러가 나타나지 않는것 확인

Fix progress script error in datasource information tab

---

discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
discovery-frontend/src/app/data-storage/service/granularity.service.ts

granularity 세그먼트 단위 수가 이상하게 계산되던 현상 수정
통합테스트
1. 데이터소스 생성
2. config 설정단계에서 TIEMSTAMP를 '컬럼'으로 설정
3. ingestion 설정 단계에서 세그먼트를 변경
4. 3에 따라서 세그먼트 단위 수가 제대로 변경이 되는지 확인

Fix granularity unit setting

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceMemberRepositoryExtends.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceMemberRepositoryImpl.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

Fixed permission checks for users registered in multiple shared workspaces
1. create 2 shared workspace (test1_ws, test2_ws)
2. add test_user to test1_ws as watcher
3. add test_user to test2_ws as editor
4. login test_user
5. goto test1_ws and Confirm that there is no workbook creation button.
6. goto test2_ws and see workbook creation button.

fix workspace permission

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.ts
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/union-add-datasets/union-add-datasets.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/union-add-datasets/union-add-datasets.component.ts

Only master dataset checkbox should be disabled.
No issue
1 . Go to dataflow detail 
2 . make 3 wrangled datasets from one imported dataset 
3 . go to main grid 
4 . apply union rule
5 . Change to edit mode
6 . Check if checkbox is not disabled.
Only master dataset should be disabled

checkbox is always disabled in union edit mode

---

discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
discovery-frontend/src/app/page/chart-style/axis-value-option.component.ts
discovery-frontend/src/app/page/chart-style/datalabel-option.component.html
discovery-frontend/src/app/page/chart-style/labelbase-option.component.ts
discovery-frontend/src/app/page/chart-style/tooltip-option.component.html
discovery-frontend/src/assets/css/metatron/page/metatron.page.09WorkbenchDetail.css
discovery-frontend/src/assets/css/polaris.v2.page.css

1. 워크벤치 글로벌 변수 탭에서 변수 수정 시, 버튼 사이의 마진이 없습니다. 
2. 숫자 포멧 옵션에서 통화 기호를 선택 후, 툴팁 옵션 탭에서 카테고리 비율만 선택 하여도 통화기호가 같이 나옵니다. 
3. 바차트 Y축설정에서 최소값만 지정할 경우, 최대값이 최소값보다 클 수 없다는 오류 문구만 보여집니다. 
4. 히트맵차트 표시레이블옵션에서 시리즈 이름을 선택했으나 화면에 보여지지 않습니다. 
1. 워크벤치 글로별 변수에서 탭에서, 버튼 사이의 마진이 추가되었는지 확인합니다. 
2. 숫자 포멧 옵션에서 통화 기호를 선택 후, 툴팁 옵션에서 카테고리 비율만 선택 후 통화기호가 않나오는지 확인합니다. 
3. 바차트 Y축 설정에서 최소값만 변경시에도 차트가 변경하는지 확인합니다. 
4. 히트맵차트 표시레이블 옵션에서 선반 열(Y축)에 값이 없는경우에 비활성화 처리 되었는지 확인합니다.

Fn fix chart option error, global variable margin 

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts

Show error mesaage at the bottom of the page in select sheet popup.
No issue
Go to dataset list -> create file type dataset -> upload a file -> next -> if fail, show proper error message for each file

Show proper error msg when fail to fetch grid info in create file dataset

---

discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/data-source-create.module.ts

데이터소스에서 사용자정의 GEO 컬럼생성시 error 표시가 나는현상 수정
데이터 스냅샷에서 데이터소스 생성이 제대로 열리지 않는 현상 수정
통합테스트
1. 데이터소스 > 데이터소스 생성 > config단계 > 우측 상단의 add column을 눌러 GEO 컬럼 생성
2. error가 나지않는것 확인
3. 데이터 스냅샷 > 스냅샷 상세화면 선택 > 데이터소스 생성 클릭
4. 제대로 생성창이 뜨는지 확인

Fix geo column error and service injector error in datasource

---

discovery-frontend/src/app/dashboard/service/widget.service.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts

linked data source can not be downloaded.
**Related Issue** : #1787 
1. create linked datasource
2. create databoard with linked datasource.
3. open schema browser
4. click download button

#1787 linked data source can not be downloaded

---

discovery-distribution/bin/common.sh
discovery-distribution/conf/metatron-env.sh.templete

jvm option change. (perm -> meta)
(jdk 8 based)
https://github.com/metatron-app/metatron-discovery/issues/1841
not yet
not yet
not yet
not yet

jvm option change (perm -> meta)

---

discovery-frontend/angular.json
discovery-server/src/main/java/app/metatron/discovery/common/oauth/CustomJdbcClientDetailsServiceBuilder.java
discovery-server/src/main/java/app/metatron/discovery/common/web/OauthFilter.java
discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/resources/messages/messages.properties
discovery-server/src/main/resources/messages/messages_en.properties
discovery-server/src/main/resources/messages/messages_ko.properties
discovery-server/src/main/resources/templates/api/oauth/login.html

Support login page for external apps
Generate clientId for external apps
**Related Issue** : #1817 #1819 
1. generate clientId and clientSecret 
- URL : /api/oauth/generate
- Param : clientName(clientName), redirectUri(Uri you want to redirect)
- Header : Authorization (Bearer {})
- Response(ex) : {
"clientId": "naU8OH",
"clientName": "test",
"basicHeader": "bmFVOE9IOlBuNWFwWERZaTc=",
"clientSecret": "Pn5apXDYi7"
}
2. test login page
1 {domain}/oauth/authorize?response_type=code&client_id=naU8OH&redirect_uri=https://www.google.com/&scope=read
2 
3 input id/pw
4 redirect https://www.google.com/?code={code}
5 curl -F "grant_type=authorization_code" -F "code={code}" -F "scope=read" -F "redirect_uri=https://www.google.com/" -H "Authorization: Basic {basicHeader}" "{domain}/oauth/token" -> you …

#1817 support login page for external apps

---

discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts

Wrangled icon in dataset list i outdated.
Should be changed to updated wrangled icon.
Release test issue

Fix wrong wrangled dataset icon

---

discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

geo 컬럼이 일반 차트 선반에 올릴수 없도록 제약을 추가해야합니다.
geo 컬럼을 일반 차트에 올릴려고 하면 alert 발생

fn bug fixed geo column on different chart layer

---

discovery-extensions/README.md

add README for extension

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilder.java

fix error for NPE in batch ingestion stage
**Related Issue** : #1927 
1. Go to datasource management.
2. Click to "Create Datasource" 
3. Select "database" mode > select or create any database connection.
4. select "Ingest periodically" in Ingestion settings
5. Create datasource and check ingestion histroy in datasource detail view

#1927 fix error for NPE in batch ingestion stage

---

discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/app/page/page.component.ts

User-defined field can't put on the shelf with script error as below
```
ERROR TypeError: Cannot read property 'toString' of undefined
at n.onPivotSelect (18.129255828ce6a0e4a347.js:1)
at Object.handleEvent (18.129255828ce6a0e4a347.js:1)
at Object.handleEvent (main.e25b0dc0a969c5931b18.js:1)
at Object.handleEvent (main.e25b0dc0a969c5931b18.js:1)
at $i (main.e25b0dc0a969c5931b18.js:1)
at main.e25b0dc0a969c5931b18.js:1
at HTMLLIElement.<anonymous> (main.e25b0dc0a969c5931b18.js:1)
at e.invokeTask (main.e25b0dc0a969c5931b18.js:1)
at Object.onInvokeTask (main.e25b0dc0a969c5931b18.js:1)
at e.invokeTask (main.e25b0dc0a969c5931b18.js:1)
```
**Related Issue** :  #1928 
1. Go to 'Edit chart widgetview'
2. Create any user-defined field.
3. Try to put on the shelf.

#1928 User-defined field can't put on the shelf

---

README.md

F#1499 readme file change

---

discovery-frontend/src/app/page/chart-style/color-option.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts

After discovery 3.2.2.1 updating the version, when trying to enter workbook or workbench in IE, "loading chunk 18 failed" error occurred.
**Related Issue** : #1959 
1. Go to 'Workspace' in I.E.
2. Click on 'Any Workbook' or 'Any Workbench'

#1959 Errors that can not be entered into a workbook or workbench in I.E

---

discovery-server/src/main/java/app/metatron/discovery/common/Mailer.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
discovery-server/src/main/java/app/metatron/discovery/util/PolarisUtils.java
discovery-server/src/main/resources/messages/messages.properties
discovery-server/src/main/resources/messages/messages_en.properties
discovery-server/src/main/resources/messages/messages_ko.properties
discovery-server/src/main/resources/templates/api/email/user_reset_password.html
discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
discovery-server/src/main/resources/templates/api/email/user_signup_request.html

Internationalize mailing template
- Approved user registration
- Rejected user registration
- Change password
#1933 
1. Create a new account in the login page with a valid e-mail
2. Check your mailbox and confirm the messages are translated properly

Internationalize mailing template

---

discovery-frontend/src/app/common/component/input/input.component.ts
discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.html
discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
discovery-frontend/src/app/page/page.component.ts

스크립트 오류가 발생하면서 예측선이 그려지지 않습니다.
**Related Issue** : #1882 
1. timestamp 를 차원값으로 하여 라인차트를 생성합니다.
2. 예측선 표시를 On 으로 변경합니다.
3. 정상적으로 예측선이 표시되는지 확인합니다.

#1882 About Liner Predictive

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/create-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-complete/db-complete.component.ts
discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbench/workbench.component.ts

I found unnecessary pop-ups when creating datasource via workbench.
**Related Issue** : #1954 
1. Go to any workspace with published data connection
2. Click on '+Workbench'
3. Select any connection and create workbench
4. Run any sql
5. Click on "Save As.." > "Save as Datasource" in sql result view
6. Pass datasource creation stage

#1954 Unnecessary pop-ups when creating datasource via workbench

---

discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-select/create-workbench-select.component.html
discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-select/create-workbench-select.component.ts

워크벤치 생성시 DB type에 extension type이 나오지 않는 부분을 수정합니다. 
1. 워크스페이스에서 워크벤치 생성버튼을 클릭합니다.
2. DB 타입 select box를 선택하여, extension type의 내용이 표시 되는지 확인합니다. 
DB타입을 변경했을경우 정상적으로 목록이 뜨는지 확인합니다.

Fn fix extension dbtype workbench

---

discovery-frontend/src/app/model-management/notebook-server/notebook-server.component.html
discovery-frontend/src/app/model-management/notebook-server/notebook-server.component.ts

노트북 서버 목록 화면에서 체크박스 전체 선택 후 타입변경시 체크박스가 풀리는 내용을 수정합니다. 
1. notebook server 목록 화면으로 이동합니다. 
2. 전체 체크박스 선택을 클릭합니다. 
3. 타입을 변경 시, 선택된 체크박스가 유지되는지 확인합니다. 
체크박스 선택 해제 이벤트가 문제가없는지 확인합니다.

fn fix checkbox in notebook list

---

discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
discovery-frontend/src/app/common/component/chart/type/line-chart/line-chart.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
discovery-frontend/src/app/domain/meta-data-management/metadata-column.ts
discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.html
discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
discovery-frontend/src/app/page/page.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java

1. 예측선 에서 forecast / confidence 가 show/hide 기능이 동작하지 않습니다
2.  맵뷰에서 포인트 컬럼이 선반에 올라가 있는 경우 다른 차트로 변경하면 에러 메시지가 출력됩니다. 
선반에서 에러 없이 내려가게 해야 할것 같습니다.
3. timestamp type 의 필드의 logical name 과 description 이 수정이되지 않습니다.
1. 라인차트의 예측선에서  forecast / confidence 가 On/Off 되는지 확인합니다.
둘 중 하나가 off 가 되었을 때 나머지 하나를 off 시킬 수 없도록 되었는지 확인합니다.
2. 맵차트에서 다른 차트로 변경할 때 선반에서 Geo 타입의 필드가 자동적으로 제거되는지 확인합니다.
3. 데이터소스 > 컬럼상세 > 스키마 변경에서 타임스탬프 필드에 대한 설명/논리명이 수정되는지 확인합니다.

Fixed errors on charts and datasources.

---

discovery-frontend/src/app/domain/workspace/workspace.ts

Can not access workbook in a workspace which is allowed anyone to access
**Related Issue** : #2012 
1. userA allow anyone to access workspaceA
2. userB enter workspaceA
3. check userB can access workbook in workspaceA
Check that permissions are applied in a normal shared workspace, not in a published workspace.

#2012 Can not access workbook in a workspace which is allowed anyone to access

---

discovery-frontend/src/app/common/component/grid/grid.component.ts

Fixed number sorting. (grid)
https://github.com/metatron-app/metatron-discovery/issues/1966
1. Go to the menu where grid exists.
2. Verify number sorting in grid.
Grid test is required as a whole.

#1966 Fixed number sorting.

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.ts

파일업로드 중인 상태에서 파일이 업로드 가능했던 현상을 수정
#1816 
1. 데이터소스 생성 > 파일로 생성 선택
2. 파일 업로드
3. 파일업로드가 disable된 상태에서 drag drop으로 파일을 drop
4. 파일 drop이 되지 않는 것 확인
5. 파일이 업로드 중이 아닌 상태에서 drag drop이 원활하게 작동하는지 확인

#1816 Disable file upload in file uploading status

---

discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

Some unnatural translations in LNB
**Related Issue** : #1996 
1. Sign in.
2. Check LNB
AS-IS
Korean
English
TO-BE
Korean
English
Browser's language check

#1996 Some unnatural translations

---

discovery-frontend/src/app/workbench/workbench.component.ts

Script error when I go back after entering workbench
**Related Issue** : #1889 
2. Move to previous page before workbench is complete
3. See console debugger

#1889 Script error when moving to previous page of workbench

---

discovery-server/src/main/java/app/metatron/discovery/common/exception/GlobalExceptionHandler.java
discovery-server/src/main/java/app/metatron/discovery/common/exception/RestExceptionHandler.java
discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityWebSocketController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/NotebookController.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/RBuilder.java
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/TemporaryCleanJob.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/CachedUserService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/WorkbookController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookController.java

logging format not match

---

discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

대시보드 시간 필터에서 from ~ to 시간을 지정 후 [OK]버튼을 눌러야 반영되도록 변경하였습니다.
#2036 
* 내장 sales 데이터 소스로 대시 보드를 생성 후 시간 필터(2개 기간)를 만들고 [OK]버튼을 눌러야 차트에 반영되는지 확인 하였습니다.

#2036 Need a submit button to time filter in dashboard

---

discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-ds-select.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
discovery-frontend/src/app/workbook/workbook.component.html
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/app/workspace/component/management/workspace-list.component.html
discovery-frontend/src/app/workspace/component/management/workspace-list.component.ts

1. 워크스페이스 전체 개수를 페이징(20개) 내의 카운트가 아닌 실제 카운트를 해야할 것 같습니다
2. 2개의 데이터소스로 대쉬보드 생성후 사용자정의 필드명이 동일할 경우 에러가 납니다
3. 워크북의 more 버튼 클릭 후 차트 생성 버튼 클릭하면 레이어 사라지지 않음.
4. 대시보드 생성 시 생성 실패한 데이터소스 목록이 표시됩니다.
1. 워크스페이스 목록에서 현재 목록이 아닌 전체 목록의 개수가 표시되는지 확인합니다.
2. 두 개의 데이터소스를 사용해서 대시보드를 생성 시 동일한 이름의 사용자 정의 필드를 각각의 데이터소스에 생성할 수 있는지 확인합니다.
3. 워크북의 more 버튼 클릭 후 차트 생성 화면을 띄웠을 때 이상없이 표시되는지 확인합니다.
4. 대시보드 생성 시, 정상적인 데이터소스 목록만 표시되는지 확인합니다.

Fixed an error in creating a user field of a name

---

discovery-server/src/main/java/app/metatron/discovery/query/druid/datasource/UnionDataSource.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

We did not reflect the query to check for similarities in the engine and applied it!
**Related Issue** : #2060 
2. In the creation step, select one data source.
3. Select the selected data source and click the "Manage Schema" tab.
4. Click "Add datasource to join".
5. On the Join view, select the data source within the "Datasource to join" panel
6. If there is a column similarity, enter the column with the highest similarity score in the Join keys.

Fixed missing unionAll query spec

---

discovery-frontend/src/app/datasource/service/datasource.service.ts

최초에 차트를 생성할 때 차트가 그려지지 않는 오류를 수정합니다.
1. 대시보드를 생성하고 바로 차트 생성화면으로 이동합니다.
2. 차트가 정상적으로 그려지고 저장되는지 확인합니다.

Fixed an error when creating a chart for the first time

---

discovery-frontend/src/app/page/page-data/page-data-context.component.html
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-navigation/detail-workbench-navigation.html
discovery-frontend/src/assets/css/metatron/component/component.button.css
discovery-frontend/src/assets/css/polaris.v2.page.css

Fix number of css issues in workbook, workbench, chart
No issue 
1 . Workspace list view hover error
[before]
[After]
2 . Workbench query result tab , workbench navigation count
[Before]
[After]
3 .계산식 필드 등록 후 해당 필드의 컨텍스트 메뉴
[Before]
[After]

Css issues in workbench and workbook

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.html
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.ts
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.html
discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-frontend/src/app/workbench/workbench.component.ts

1. 조인 팝업에서 조인 컬럼 목록을 dimension 만 표시해야 합니다.
2. LNB를 닫을 때 워크스페이스 내 목록 화면이 닫히지 않는 문제가 있습니다.
3. 워크벤치 결과탭 불러오는 기능이 없어졌습니다.
1. 대시보드 생성 시 조인 팝업에서 조인 컬럼 목록이 dimension만 표시되는지 확인합니다.
2. LNB 의 워크스페이스 내 목록 화면을 펼치고 LNB를 닫을 때 목록 화면도 같이 닫히는지 확인합니다.
3. 워크벤치 쿼리 실행 후, 나갔다 들어오면 기존에 실행한 결과가 저장되어서 표시되는지 확인합니다.

Adding Constraints to Join Fields & Modify the Save Workbench Results feature

---

discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
discovery-frontend/src/app/shared/datasource-metadata/component/datetime-valid-popup.component.html
discovery-frontend/src/app/shared/datasource-metadata/component/datetime-valid-popup.component.ts
discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataColumnProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataEventHandler.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/mdm/MetadataRestIntegrationTest.java
discovery-server/src/test/resources/sql/test_mdm.sql

HIVE와 staigng 타입의 메타데이터 상세 schema화면에서 TIMESTAMP 컬럼이 존재하는경우 에러가 발생하던 현상 수정
통합테스트
1. HIVE 또는 staging 형태의 메타데이터 상세화면 진입
2. 컬럼중 TIMESTAMP가 있다면 에러가 발생하는지 확인
3. HIVE 또는 staging 의 경우 TIMESTAMP의 format 정보를 변경시 validation이 작동하지 않는지 확인

Fix format error in metadata schema

---

discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts

예측선이 그려지지 않는 오류를 수정합니다.
1. 멀티데이터소스 대시보드에서 예측선이 정상적으로 그려지는지 확인합니다.

Fix prediction line errors

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts

Fix script error when creating datasource with file
**Related Issue** : #2163 
1. Go to datasource.
2. Click new button and select My file.
3. Upload csv file and click Next button twice. (Schema view)
4. Click Previous button. (File preview)
5. Click Next button.

#2163 fix script error when creating datasource with file

---

discovery-frontend/src/app/admin/user-management/component/members/change-workspace-owner-modal/change-workspace-owner-modal.component.html
discovery-frontend/src/app/admin/user-management/component/members/change-workspace-owner-modal/change-workspace-owner-modal.component.ts
discovery-frontend/src/app/admin/user-management/component/members/change-workspace-owner-modal/workspace-members-select-box.component.html
discovery-frontend/src/app/admin/user-management/component/members/change-workspace-owner-modal/workspace-members-select-box.component.ts
discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.html
discovery-frontend/src/app/admin/user-management/component/members/user-management-members.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/information/detail-workspace-information.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/information/detail-workspace-information.component.ts
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/detail-workspace.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/detail-workspace.component.ts
discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.html
discovery-frontend/src/app/common/component/abstract.component.ts
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserProfile.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupProfile.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

user delete policy
**Related Issue** : #2115 
1. When a user is deleted, change owner of the shared workspace.
- If the shared workspace has a member, pick the owner.
- If the shared workspace has no member, the shared workspace will be deleted.
2. If a resource is created by a user who is deleted, the creator is displayed Unknown user.
3. Private workspaces of deleted users is not displayed.
4. Delete the Delete button in the Members list.
5. Delete this user button is only displayed when Inactive is selected at the user detail page.

#2115 user delete policy

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetDatabaseService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java

Query type dataset code has been adding "LIMIT n" always.
For Oracle (or some else) DB, this makes a bug.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2177
Ran locally.
Yes, if you are in environment that using not MySQL nor H2.

#2177 apply common jdbc module to remove bug when using oracle

---

discovery-frontend/src/app/workbench/workbench.component.html

When initializing the page, it printed without {{fullName}
1. Go to workbench.
2. Check the modified information in the top right corner.

#fn fix display workbench update user when initializing the page

---

discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.html
discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

1. 데이터를 리스트 형으로 선택 시에도 데이터가 100건이 넘으면 검색창이 보여지게 했습니다.
2. 포인트 컬러를 변경 했습니다.
#2045

#2045 Add a search to the Filter widget list type and change the color of the search results.

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/detail-data-source.component.ts
discovery-frontend/src/app/domain/datasource/datasource.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/granularity/UniformGranularitySpec.java

fix reingestion append file.
**Related Issue** : #2192 
1. Create datasource with file.
2. Re-Ingestion the datasource with the same schema file.
3. Check the result.

#fn fix reingestion append

---

discovery-server/src/main/java/app/metatron/discovery/util/CommonsCsvProcessor.java

fix csv total row counts
1. Create datasource with csv file
2. Check the total count in the preview page

#fn fix csv total row counts

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfJoin.java

There was a bug that made the sub-thread to stop.
Generating a snapshot resulted an empty set.
I almost rewrote the code.
The code has been much cleaner, I think :)
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2216
Followed https://github.com/metatron-app/metatron-discovery/issues/2216 on local machine.
Yes, thanks.

#2216 refactoring join code to avoid bugs and slow-down factors

---

discovery-server/pom.xml
discovery-server/src/main/java/app/metatron/discovery/domain/admin/SearchIndexService.java
pom.xml

Fixed error for java 11/12 compatibility.
- update Hibernate ORM(5.2.12.Final -> 5.4.3.Final) & Hibernate Search (5.5.5.Final -> 5.11.1.Final) version 
- upgrade commons-lang3 version (3.5 -> 3.8.1) 
**Related Issue** : #1704 
All of the default functions were tested search as Ingestion, Dashboard
All of the data crud processing must be checked.

Fix error for java 11/12 compatibility

---

discovery-server/src/main/java/app/metatron/discovery/common/MatrixResponse.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/SearchQueryRequest.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/ChartResultFormat.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/Pivot.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

Fix error for displaying percentage on bar chart series
**Related Issue** : #2184 
Within the bar chart, check the percent notation in the stacked case. (Like the below image case)
Testing of various shelf cases is required. (include converting stack/multi-series option)

Fix error for displaying percentage on bar chart series

---

discovery-frontend/src/app/workbench/workbench.component.ts

Automatically retry query execution if query execution fails in workbench.
**Related Issue** : #2272 
1. Add the following code to the loop statement in the QueryEditorService.java (199) line:
```
queryHistoryRepository.save(queryHistory);
LOGGER.debug("QueryHistory Updated : " + queryHistory.getId());
queryResult.setQueryHistoryId(queryHistory.getId());
//add this line
throw new WorkbenchException(WorkbenchErrorCodes.QUERY_STATUS_ERROR_CODE, "Test Error");
}
```
2. run metatron
3. Go to Workbench
4. execute query

#2272 remove execute checker when query exception

---

discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field-detail.component.html
discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field-detail.component.ts
discovery-server/src/main/java/app/metatron/discovery/util/CommonsCsvProcessor.java

the measure data can be replaced with a negative value in the data source ingestion process.
**Related Issue** : #2120 
1. Go to datasource.
2. Create new datasource.
3. In the schema configuration step, enter a negative value in the replace value.

#2120 measure data can be replaced with a negative value

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookProjections.java

fix hibernate error in book sub-folder
1. create sub-folder in workspace
2. click folder
3. see folder without error

fix hibernate error in book sub-folder

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-join-popup/rule-join-popup.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java

during join rule editing, 
APPEND command has a stageIdx is same to ruleIdx
UPDATE command has a stageIdx that is one less than ruleIdx 
1. add a join rule
2. press 'show result'
3. and edit the join rule
4. press 'show result' again
Both 2 and 4 should show correct results

to adjust ruldIdx for PREVIEW command

---

discovery-frontend/src/app/dashboard/update-dashboard.component.ts

필터 패널에 있는 필터를 대시보드로 올리면 격자가 어긋남
1. 대시보드를 생성합니다.
2. 대시보드 편집화면에서 빈 대시보드 영역에 위젯을 배치하기 위해 드래그 합니다.
3. 어긋남 없이 정상적으로 표시되는지 확인합니다.

The filter on the filter panel is shifted to the dashboard, causing the grid to skew

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.model.ts

Change search logic in dataprep grid. Numbers are searched as string
No issue
Go to dataflow detail -> main grid -> search

Fix search logic in dataprep

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbook/WorkBook.java

fix the count of workbook dashboard in workspace
1. Create a datasource.
2. Create a dashboard with the datasource.
3. Check the count of dashboard in workspace
4. Delete the datasource.
5. Verify that the number checked in step 3 has decreased by one.

fix the count of workbook dashboard in workspace

---

discovery-server/src/main/java/app/metatron/discovery/domain/mdm/preview/MetadataDataPreview.java

If the metadata column type is null, add exception handling
just null check added.

If the metadata column type is null, add exception handling

---

discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts

fix adding a map view chart to the dashboard
**Related Issue** : #2331
1. Create a dashboard with one or multi datasources including geo data(ex: sales)
2. Add a map view chart
3. Confirms that there are no errors

#2331 fix adding a map view chart to the dashboard

---

discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java

support external logout
If there is a logout request from the external system, the discovery is also logged out.

support external logout

---

discovery-frontend/src/app/page/page-pivot/popup-value-alias.component.html
discovery-frontend/src/app/page/page-pivot/popup-value-alias.component.ts
discovery-frontend/src/app/workspace/workspace.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

1. Initialization function when changing value alias(#2086)
2. Bugs that do not reflect values when changing the last value of several fields(#2085)
**Related Issue** : #2086, #2085 
1. Create a chart and set alias for value.
2. Click Reset All (#2086)
3. Change several field value and click Save button without Enter key (#2085)

#2086 reset value alias changes

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/Workspace.java

workspace_member 테이블에 데이터가 존재하는 워크스페이스에서 전역 변수 추가/변경 시 오류 나지 않도록 수정
#2360 
'metatron' 사용자로 로그인 후 공유 워크스페이스에서 워크벤치를 생성하고 전역 변수를 등록하거나 수정해 봄.

#2360 Error adding or changing global variables in workbench

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts

Fix dataflow next page error.
**Related Issue**
https://github.com/metatron-app/metatron-discovery/issues/2359
1. Go to Data Preparation menu.
2. Create more than 21 dataflows
3. paging function check.
No

Fix dataflow next page error.

---

README.md

Fix README.md > **user manual on our web site** link.
**Related Issue** : #2368 
Click on the **user manual on our website** link and check that the document is visible.

#2368 Fix `user manual on our website` link

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java

When you request the shared workspace list, there are unnecessary query calls.
**Related Issue** : #2366 
Move to the shared workspace list.
Check if it is processed normally.
Ensure that the count of sql calls is decreasing.

#2366 improve the shared workspace list

---

discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts

fix format chart value(Infinity, -Infinity, NaN)
In KPI chart, create a user-define value (ex. value / 0) and aggregate min, max

Fn fix chart value format

---

discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditPredicate.java

Change elapsed time condition from over to more than at the list of job log (초과에서 이상으로 변경)
1. Click over 10ms, 30ms, 60ms at the list of job log
2. Input 20 on the textbox

fix joblog more than elapsedtime condition

---

discovery-server/src/main/asciidoc/api-datasource-query-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/MeasureField.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/widget/shelf/LayerView.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/RelayAggregation.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/engine/DruidEngineRepositoryTest.java

Add aggregation types(FIRST/LAST) using function engine provided.
**Related Issue** : #2418
1. Create data source using the below data (you need to create csv file first).
- datasource name : test_first_last_datasource
- schema
> time : timestamp role
> dim : dimension role
> m : measure role
```
time,dim,m
2019-08-01,a,4
2019-08-01,b,2
2019-08-01,b,1
2019-08-02,a,5
2019-08-02,a,1
2019-08-02,b,3
```
2.  After creating datasource, query using search api and confirm!
※ refer to api guide : https://github.com/metatron-app/metatron-discovery/blob/master/.github/USE_REST_API.md
- FIRST/LAST Query Samples
(Query)
```
{
"name": "test_first_last_datasource"
},
"projections": [
{
"type": "dimension",
"name": "dim"
},
{
"type": "measure",
"name": "m",
"alias": …
```

#2418 add aggregation type for search api - 'FIRST','LAST'

---

README.md

Comming -> Coming

---

discovery-frontend/src/app/page/chart-style/split-chart-style.component.html
discovery-frontend/src/app/sample-component/sample-component.component.html

Fix depth error of div 
None
once, 
because of It's result of LINT analyze
nope
- [] I have read the **CONTRIBUTING** document.
- [x ] My code follows the code style of this project.

Fix depth error of div

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java

fix dataconnection list error when the list is empty
**Related Issue** : #2415 
When the dataconnection list is empty, check that there are no errors in the UI.

#2415 fix dataconnection list error

---

discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

Change lnb workspace list button UI.
**Related Issue** : #2354 
Check the Workspace List Button UI on the LNB.

#2354 change lnb workspace list button

---

discovery-frontend/package.json
discovery-prep-parser/pom.xml
discovery-server/pom.xml
pom.xml

We need to update vulnerable dependencies.
- **spring-security-oauth** to 2.0.17.RELEASE
- **lodash** to 4.17.13
- **jackson-databind** to 2.9.9
- **c3p0** to 0.9.5.3
- **commons-fileupload** to 1.3.3
No related issue, but several CVEs are detected.
Migrated seamlessly, but need to check at related functions.

Bump libraries

---

discovery-server/src/main/java/app/metatron/discovery/domain/notebook/NotebookConnector.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/NotebookConnectorController.java
discovery-server/src/test/java/app/metatron/discovery/domain/notebook/NotebookConnectorRestIntegrationTest.java

delete unused code to fix security vulnerabilities (SSRF)
**Related Issue** : #2446 
call /api/connectors/validation/{id} with any Rest client : 404 Not found
call /api/connectors/status/{hostname}/{port} with any Rest client : 404 Not found
== Response body ==
{
"code": "GB0002",
"message": "Resource(/api/connectors/status/localhost/9999) not Found",
"details": "ResourceNotFoundException: Resource not found!"
}

#2446 remove unused code to fix security vulnerabilities 

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/Workspace.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceRepositoryExtends.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceRepositoryImpl.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

improve performance for counting book, member in the workspace
**Related Issue** : #2455 
1. Go to workspace
2. Click "Workspace List" button
3. Check the counting of workbooks, workbenches, notebooks, groups, users

#2455 improve performance for counting book, member in the workspace

---

discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.html
discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.ts

removed unwanted components
[#2471 ](https://github.com/metatron-app/metatron-discovery/issues/2471)
if the unused components is not shown.
that is ok.

#2471 hide unused components

---

discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.page.css

reapply style sheet
polaris.v2.component.css
polaris.v2.page.css

fix reapply style sheet

---

README.md

- Add link for user forum at first paragraph
- Add installation video guide link

minor update for Readme.md

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.html
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
discovery-frontend/src/app/workbench/workbench.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

1. The ellipsis does not appear and the minimum panel width matches the length of the name and cannot be reduced.
2. Workbench > Schema Browser > Schema List layer popup > Missing clear button in search box
METATRON-2869
METATRON-2882
Workbench
1. The width of the pattern should be reduced.
2. If the width is reduced, it should appear as a shortened mark.
Workbench > Schema Browser > Schema List layer popup
1. The clear button should be displayed in the search box.
2. When the button is clicked, the search word entered in the search word input box is deleted.
3. The entire search result is displayed in the bottom list.

Added reset search button and edit slider

---

discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.html
discovery-frontend/src/app/explore-data/explore-data/explore-data-list.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.html
discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data.component.ts
discovery-frontend/src/app/explore-data/explore-data/popup/metadata-container.component.html
discovery-frontend/src/app/explore-data/explore-data/popup/metadata-overview.component.html
discovery-frontend/src/app/explore-data/explore-data/popup/recent-queries.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css

2957
remove user name's underline next to data name
2960
In overview tab of metadata exploration detail modal, catalogs information display is wrong
show unclassified if there is no catalog
2962
Show favorite icon in top user, remove favorite icon in recently updated
2963 
remove underline of user
2964
remove user's underline
remove workbench's underline
remove favorite icon next to user name
2966
every value of type column of recently queries table is 'type'
-> show proper value 
hide type column if source type is database
METATRON 2957
METATRON 2960
METATRON 2962
METATRON 2963
METATRON 2964
METATRON 2966
2957 
1. Explore Data -> click metadata card which doesn't have catalog
2. check user name's underline next to data is removed
2960
1. Explore Data -> click …

fn-fix_explore_data_detail_error

---

discovery-frontend/src/app/monitoring/audit/log-statistics/log-statistics.component.html
discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditController.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditPredicate.java

2859 
2868
Hide Total memory usage, total cpu usage, total resource usage if there are no datas
MEATATRON 2859
METATRON 2868
2859, 2868 same
1. Management -> data monitoring -> log statistics
2. change filter date that doesn't have memory usage or cpu usage or resource usage 
3. check each table is hidden

fn-fix_monitoring_log_statistics_cpu_memory

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts
discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
discovery-frontend/src/app/data-storage/service/field-config.service.ts
discovery-server/pom.xml
discovery-server/src/main/java/app/metatron/discovery/domain/code/ExpressionService.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/IngestionDataResultResponse.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/LocalFileIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/ExcelFileFormat.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/FileIngestionJob.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
discovery-server/src/main/java/app/metatron/discovery/util/CommonsCsvProcessor.java

fix detecting charset
METATRON-2836
METATRON-2837
METATRON-2838
METATRON-2836
1. Create a datasource with the attached file with charset EUC-KR
2. Check the file data preview (Korean data) without error
METATRON-2837
1. Create a datasource with the file with charset EUC-KR
2. Check the file data preview (Korean data) without error
3. Uncheck 'Use the first row as the head column. (If not checked, a new row is created and is used as the head column)'
4. Check the file data preview (Korean data) without error
METATRON-2838
1. Create a datasource with the file
2. Check Column delimiter and Line separator for an empty value.
3. See the error message

fix detecting charset

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/PostgresqlDataAccessor.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/ColumnDictionary.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataPredicate.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataService.java
discovery-server/src/main/java/app/metatron/discovery/domain/tag/TagRepositoryImpl.java

METATRON-2947 : Error when adding Column Dictionary.
METATRON-2961 : Error when adding code table.
METATRON-2980 : Tag not deleted.
METATRON-2987 : After entering a search keyword without a search result, the entire data is found when searching.
METATRON-2872 : Schema List Issue
METATRON-2947
1. Explorer Data > Explore Data
2. search creator with keyword "aaaaaaaaaa"
3. see "no result"
METATRON-2961
1. Management > Explore Data > Metadata > information tab
2. Delete tag without error
METATRON-2980
1. Management > Explore Data > Column Dictionary > Detail view
2. Add Code table without error
METATRON-2987
1. Management > Explore Data > Metadata > Column tab
2. Add Column Dictionary without error
METATRON-2872
1. Create Workbench for postgresql
2. if there are more than 30 schema lists
3. …

Fn fix mdm api error

---

discovery-frontend/src/app/workspace/workspace.component.ts

The problem is that only the workbench appears in the list of workspaces.
The problem is that only the workbench appears in the list of workspaces.

Temporarily modify the list of workspaces

---

discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts

fix search custom field function
METATRON-3012
METATRON-3012
1. Go to workbook and create or edit Chart.
2. Move to create custom-filed view.
3. Search the function and check that only the categories of the function containing the search term are displayed.

fix search custom field function

---

discovery-frontend/src/app/explore-data/explore-data/explore-data-search.component.ts

Remove creator option in select box
METATRON-2947
1. explore data -> check selectbox if contain creator

fn-fix_explore_search_error

---

discovery-server/src/main/java/app/metatron/discovery/common/scheduling/AutowiringQuartzBeanJobFactory.java
discovery-server/src/main/java/app/metatron/discovery/config/SchedulingConfig.java

During open source validation, I received a report that there was a problem with the class.
I don't understand but I changed the class name and modified the code that uses this class.
1. Run Application
2. Make sure that datasource check job is working properly through log message 
3. Check thread name - "scheduler_Worker-#N"

Changed class name related quartz bean factory

---

discovery-frontend/src/app/data-storage/component/criterion/criterion-extension-box.component.html
discovery-frontend/src/app/data-storage/component/criterion/criterion.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java

fix dataconnection list error
METATRON-3018
1. Go to dataconnection list.
2. Go to data source list.
3. Check that there are no errors, if applying filters from both lists.

fix dataconnection list error

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java

Fix to read euc-kr files properly.
METATRON-2851
METATRON-2853
METATRON-2855
METATRON-2857
METATRON-2875
METATRON-2892
1. Management - Data Preparation - Dataset - New
2. Select "My file"
3. Drag & drop [encoding.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3568161/encoding.csv.txt)
4. Next
5. See the Korean properly -> then all the issues above will be cleared.
Yes, please.

fix dataprep charset issue

---

discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.html
discovery-frontend/src/app/domain/common/abstract-history-entity.ts
discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamService.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserService.java

Add last access time in member management detail
METATRON-2912
1. Login as admin
2. Administartion -> User -> members 
3. click random user 
4. check lastAccessTime is exist
// if user is guest or doesn't have lastaccesstime ? hide message

Fn add last access time for user

---

discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.html

Remove favorite icon next to user name in top user
METATRON-2964
1. explore data -> choose random data
2. check favorite icon is removed next to username in top user

fn-explore_favorite_error

---

discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-information.component.html
discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-information.component.ts
discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-top.component.html
discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-top.component.ts
discovery-frontend/src/app/meta-data-management/metadata/service/metadata.model.service.ts
discovery-frontend/src/app/meta-data-management/metadata/service/metadata.service.ts
discovery-frontend/src/assets/i18n/ko.json

fix edit name and description not working if type is stagedb or database
METATRON-3022
1.Management-> Explore data -> Metadata
2. click list item
3. check edit name and description is working whatever metadata data type is

fn-fix_mdm_metadata_edit_error

---

discovery-frontend/src/app/workspace/component/management/create-workspace.component.ts
discovery-frontend/src/app/workspace/component/management/update-workspace.component.ts

fix name duplication check
METATRON-2856
1. click workspace list 
2. click create workspace
3. check name duplciation checking works well

fn-fix_workspace_name_duplication_error

---

discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

fix favorite workspace list
METATRON-2852
METATRON-3024
METATRON-2852
1. Become a member of a workspace where someone else is the owner.
2. Set that workspace as your favorite workspace.
3. Make sure the workspace is visible in the Favorites filter of the shared workspace.
4. Remove from members of that workspace.
5. Make sure that the workspace is not visible in the Favorites filter of the shared workspace.
METATRON-3024
1. Go to the datasource list.
2. Check that the filter displays Updated time.

fix favorite workspace list

---

discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.html
discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.ts

fix sort notebook server
METATRON-2940
1. Go to a workspace.
2. Set notebook server.
3. Check if sorting by name is possible.
4. URL sorting is removed.

fix sort notebook server

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-database/detail-workbench-database.html
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-database/detail-workbench-database.ts
discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbench/workbench.component.ts

1. There is a problem with the view behavior of the layer list when there are many schemas.
2. Error Toast pop-up is displayed when accessing user account directly.
METATRON-2931 
METATRON-2872
1. Verify that the initial 20 are displayed when you expand the schema layer, and 20 are added when you click More.
2. Check that the login window appears normally without any error warning when connecting to the user login type workbench.

fix workbench schema login

---

discovery-frontend/proxy.conf.js
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html

Change button design
METATRON-3005
1.Management -> Data prep -> Data flow -> click root
2. check button is changed

fn-fix_dataprep_dataflow_button

---

discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-frontend/src/app/meta-data-management/meta-data-management.component.html
discovery-frontend/src/app/meta-data-management/meta-data-management.component.ts
discovery-frontend/src/app/meta-data-management/metadata/metadata-detail.component.html
discovery-frontend/src/app/meta-data-management/metadata/metadata-detail.component.ts
discovery-frontend/src/app/meta-data-management/metadata/service/metadata.service.ts
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionController.java
discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionProperties.java

1. add LNB EXPLORE DATA beta tag
2. show Lineage tab with application.yaml
1. Check LNB 'EXPLORE DATA' menu
2. Check Lineage tab. (Hide)
3. Add polaris.extensions.lnb.name=Lineage
4. Check Lineage tab. (Show)

fix check metadata lineage

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java

Added BOM in front of a file snapshot.
METATRON-3025
Run locally.
Yes, please.
This should be done against HDFS snapshot soon.

fix snapshot encoding issue for Excel

---

discovery-frontend/src/app/admin/user-management/component/approval/user-management-approval.component.html
discovery-frontend/src/app/admin/user-management/component/approval/user-management-approval.component.ts
discovery-frontend/src/app/workspace/workspace.component.ts

add activitystream workspace
fix clear search text in member approval list
METATRON-3028
1. Check member last access time.
2. Click clear search text button in member approval list.

fix add activitystream workspace

---

discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts

fix dashboard data preview
METATRON-2934
1. Go to dashboard with single, multi, join datasource.
2. Click datasource.
3. See data without error

fix dashboard data preview

---

discovery-frontend/src/app/workspace/component/management/create-workspace.component.ts
discovery-frontend/src/app/workspace/component/management/update-workspace.component.ts
discovery-frontend/src/app/workspace/component/management/workspace-list.component.ts

fix check workspace name duplicate when creating workspace
METATRON-2856
1. Go to workspace
2. Go to workspace list
3. go to a shared workspace page
4. Input existing workspace name.
5. See error message

fix check workspace name duplicate

---

discovery-frontend/src/app/workspace/component/management/create-workspace.component.ts
discovery-frontend/src/app/workspace/component/management/update-workspace.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java

fix validate workspace name when creating or updating workspace
**Related Issue** : #2538 
METATRON-2856
1. Go to workspace
2. Go to workspace list
3. Go to a shared workspace page
4. Input existing workspace name.
5. See error message

fix validate workspace name when creating or updating workspace

---

discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/linked-resources/detail-workspace-linked-resources.component.html
discovery-frontend/src/app/explore-data/explore-data/popup/metadata-container.component.html
discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-top.component.html
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/app/workbench/workbench.component.html
discovery-frontend/src/app/workbook/workbook.component.html
discovery-frontend/src/app/workspace/workspace.component.html
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/css/polaris.v2.page.css

3023 
fix explore data detail description overflow
3030
fix workbench, workbook title and description overlap
3031
fix exploredata recommend data ui overlap
3033 
fix metadata detail - title description overflow 
3034
fix data flow description overflow
3036 
fix data description overflow
METATRON3023
METATRON3030
METATRON3031
METATRON3033
METATRON3034
METATRON3036
3023 
1. explore data -> click data card which has long description
2. check description shows properly
3030
1. workspace -> workbench & workbook which has long description and title
2.  check description and title show properly
3031
1. exploredata 
2. check recommend banner ui shows properly
3033
1.Management -> explore data -> metadata
2. click metadata which has long title
3. check title and description …

fn-fix_ie_ui_error

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts

[Management> Data Storage] Data files are not checked for validity when created.
**Related Issue** :  METATRON-3032
1. Manage> Data Storage> New
2. Upload attached csv file> select next button
3. Uncheck and reselect
4. Select Next button
5. Check that the validity is checked and does not advance to the next screen.

Fixed validation error when creating data source from file

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
discovery-frontend/src/app/explore-data/explore-data/component/explore-banner.component.html
discovery-frontend/src/app/explore-data/explore-data/component/explore-banner.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.html
discovery-frontend/src/assets/css/polaris.v2.page.css

3023, 3031
fix ui overlap
METATRON3023
METATRON3031
1. Explore Data
2. check ui is overlap

fn-fix_explore_data_ui_error

---

discovery-frontend/src/assets/css/polaris.v2.page.css

Long detail panel description overlaps button
**Related Issue** : METATRON-3034
1. Check the dataset details in the Management> Dataflow screen.
2. If the description is long, check if it is displayed normally.
3. Check if the screen is displayed correctly when the screen is resized.

Long detail panel description overlaps button

---

discovery-server/src/main/java/app/metatron/discovery/query/druid/postaggregations/MathPostAggregator.java
discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java

Fixed an error that occurred when using the `ifcountd` function in a user-defined field.
1. Create a dashboard utilizing the Sales data source.
2. Create a user-defined column of measure type.
3. Create a expression using the `ifcountd` function, enter an arbitrary column name, and create a column. ex. `IFCOUNTD( [Region]  != 'East',  [Region] )` 
4. Create a chart using this column.
5. Confirm that the chart is displayed without errors.
- Check that no other aggregate functions are working.

Fixed an error that occurred when using the `ifcountd` function in a user-defined field

---

discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.html
discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/detail-workspace.component.html
discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
discovery-frontend/src/assets/css/metatron/component/component.selectbox.css
discovery-frontend/src/assets/css/theme_dark/component/component.selectbox.css

1. Workspace > Workbook > Dashboard > Detail Filter view 
When I click advanced filter function icon. -> Buttons are attached
When I click sort icon -> Layers do not display correctly
2. LNB > Administration > Member > List > Detail View
missed align (combo-box, button)
3. LNB > Administration > Workspace > List > Detail View
missed align (combo-box, button)
**Related Issue** : #2633 
1. Workspace > Workbook > Dashboard > Detail Filter view 
When I click advanced filter function icon. -> Check for space between buttons.
When I click sort icon -> Make sure the layer looks normal.
2. LNB > Administration > Member > List > Detail View
Check if the combo box and the button are aligned properly.
3. LNB > Administration > Workspace > List > Detail View
Check if the combo box and the button are …

#2633 Some trivial css issues

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
discovery-frontend/src/app/data-storage/data-storage.module.ts
discovery-frontend/src/app/data-storage/service/scheduling.service.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

Pause and resume batch ingestion
**Related Issue** : #2463 
1. Go to a batch datasource.
2. Check Pause and Resume ingestion
3. If the batch works normally, the Pause button is shown.
4. If the batch job has been suspended, the Resume button is shown.

#2463 pause and resume batch ingestion

---

discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvIntegrationTest.java

Test failed after modifying the CSV-reading code.
Run test cases of data preparation (src/test/java/app/metatron/discovery/domain/dataprep)
Yes, thx

fix dataprep test case error

---

discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.html
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.ts
discovery-frontend/src/app/engine-monitoring/overview/component/graph.component.ts
discovery-frontend/src/app/engine-monitoring/overview/component/status.component.html
discovery-frontend/src/app/engine-monitoring/overview/component/status.component.ts
discovery-frontend/src/app/engine-monitoring/overview/overview.component.html
discovery-frontend/src/app/engine-monitoring/overview/overview.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringController.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java

fix engine monitoring duration
1. Overview duration
2. Ingestion(Supervisor) duration

fix engine monitoring duration

---

discovery-frontend/src/app/data-storage/data-source-list/create-data-source/snapshot-source/snapshot-preview.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.ts
discovery-frontend/src/app/engine-monitoring/overview/component/graph.component.ts
discovery-frontend/src/app/engine-monitoring/overview/overview.component.html
discovery-frontend/src/app/engine-monitoring/overview/overview.component.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts

1. fix engine monitoring chart resize event
2. fix engine monitoring duration
3. fix lnb script error (after login)
4. fix role to be set automatically when creating new data source with snapshot path
1. Engine monitoring - Overview -> window resize -> check chart resize
2. Engine monitoring - Overview -> change duration -> browser refresh -> check duration
3. Check for script errors immediately after logging in to metatron Discovery
4. Create new datasource -> select Snapshot -> Check for role to be set automatically

fix improve engine monitoring resize

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java

Add view in postgresql's table list
**Related Issue** : #2672 
1. create datasource via postgresql database
2. select "public"."active_customer_view" already created.
3. datasource created normally.

#2672 add view in postgresql's table list

---

discovery-frontend/src/app/explore-data/explore-data/component/catalog-folder.component.html
discovery-frontend/src/app/explore-data/explore-data/component/catalog-folder.component.ts
discovery-frontend/src/app/explore-data/explore-data/component/updated-time-radio-filter.component.ts
discovery-frontend/src/app/explore-data/explore-data/component/updated-time-radio-filter.html
discovery-frontend/src/app/explore-data/explore-data/explore-data-list.component.html
discovery-frontend/src/app/explore-data/explore-data/explore-data-list.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data-lnb.component.html
discovery-frontend/src/app/explore-data/explore-data/explore-data-lnb.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data-search.component.ts
discovery-frontend/src/app/explore-data/explore-data/explore-data.component.ts

fix filter error 
show only one filter layer at once
fix filter is set to todayy when click between option
1. Exploration data -> list ivew 
2. check filter works properly

fix exploration data filter error

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepRuleChecker.java

contains function had a wrong explanation
[#2530](https://github.com/metatron-app/metatron-discovery/issues/2530)
test the issue of #2530 
this is mistype issue.

#2530 contains function explanation was corrected

---

discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts

fix change theme
**Related Issue** : #2696 
1. Change to dark theme.
2. Change to general theme.
3. Refresh the screen and check that it looks a general theme.

#2696 fix change theme

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.html
discovery-frontend/src/app/data-preparation/dataset/dataset.component.html

the style sheet is for datasource.
as a result, other modules may be affected when the design changes.
[2723](https://github.com/metatron-app/metatron-discovery/issues/2723)
1. go to the list page of datasets
2. click to 'generate new dataset' 
make sure the button is clicked

#2723 create dataset button is not clicked

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java

unified null representations in datapreparation
[1750](https://github.com/metatron-app/metatron-discovery/issues/1750)
test the 1750 issue.
Test file : [Long-Term-Unemployment-Statistics 복사본.xlsx](https://github.com/metatron-app/metatron-discovery/files/3011447/Long-Term-Unemployment-Statistics.xlsx)
1. upload the file
2. column count is 5
3. check for null representation on all screens

#1750 unify null representations in datapreparation

---

discovery-frontend/src/app/domain/engine-monitoring/task.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.html
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task-detail.component.html
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task-detail.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task.component.ts
discovery-frontend/src/app/engine-monitoring/service/engine.service.ts
discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/css/theme_dark/metatron/page.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringController.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java
discovery-server/src/main/resources/application.yaml

Improve engine monitoring ingestion detail
**Related Issue** : #2732 
1. Go to engine monitoring Ingestion tab
2. Go to task detail. (Processed rows chart added)
3. Go to supervisor detail. (The Processed Rows chart has been removed, the Active tasks table has been added, and you can move to the task of your choice through a layer popup.)

#2732 improve engine monitoring ingestion

---

discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.page.css

fix custom field ui error (Window7, Chrome70)
1. Go to workbook and create or edit Chart.
2. Move to create custom-filed view.
3. Check UX for function selection area on user-defined field view.
Only stable version patch (3.3.x)

#fn fix custom field ui error

---

discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html

Fix popularity bar css in metadata detail column tab
Management -> Metadata -> Detail -> column-> check popularity bar css is proper

fix popularity css in metadata detail's column tab

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java

Applying #2646 into 3.3.x branch.
Related Issue : #2375

#2375 use type from snapshot2

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts

Applying #2664  into 3.3.x branch.
Related Issue : None

#0 fix snapshot list loads infinitely

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepRuleChecker.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java

Applying #2666  into 3.3.x branch.
Related Issue : None

fix can add an aggregate rule without group

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.html
discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.ts
discovery-frontend/src/assets/css/polaris.v2.page.css

Applying #2674  into 3.3.x branch.
Related Issue : #2063

#2063 adding union rule shows field type as icon correctly (#2674)

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts

Applying #2704 into 3.3.x branch.
Related Issue : #2610

#2610 preview reload problem (#2704)

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-join-popup/rule-join-popup.component.html

Applying #2707  into 3.3.x branch.
Related Issue : #2293

#2293 cannot close preview result (#2707)

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

Applying #2716  into 3.3.x branch.
Related Issue : #2705

#2705 when generate a new dataset, add sequence for distinction

---

discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.ts
discovery-frontend/src/app/meta-data-management/lineage/service/lineage.service.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepCsvUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepFileUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/lineage/LineageEdgeController.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvInputTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvOutputTest.java

Applying #2715   into 3.3.x branch.
Related Issue : #2640

#2640 unify charset detecting code (#2715)

---

discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
discovery-frontend/src/app/data-preparation/util/preparation-common.util.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java

Applying #2738 into 3.3.x branch.
Related Issue : #1750

#1750 unify null representations in datapreparation (#2738)

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/connector/PostgresqlJdbcConnector.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyDatabaseService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyStagingDbService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java

Applying #2748  into 3.3.x branch.
Related Issue : None

#2748 Use fetch size and set auto_commit=false for PostgreSQL

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts

Applying #2754   into 3.3.x branch.
Related Issue : #2753

#2753 checking the status of snapshot is repeated

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyOrcWriter.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfDerive.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSet.java

Applying #2761  into 3.3.x branch.
Related Issue : #2752

#2752 Fix null value representation in ORC files

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSource.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/granularity/UniformGranularitySpec.java

Fix ingestion append parameter
1. Create a datasource with file.
2. Re-ingest the data to be appended.
3. Check the data in the datasource.
4. Create a datasource from the database to load periodically (with ALL and INCREMENTAL).
5. Make sure you don't see any duplicate data.

Fix ingestion append parameter

---

discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts

맵뷰 차트 레이아웃 설정 값 중 color by 값이 유지되도록 수정 했습니다.
#2746

#2746 'Color by' values are not kept when setting layer in map view chart

---

discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/TimestampField.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQuery.java
discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
discovery-server/src/main/resources/logback-console.xml
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java

I changed select query type (select -> select.stream) for searching original data.
**Related Issue** : #1605 
You have to check searching original data through below UI views.
- Management > Data Storage > DataSource > Datasource detail > data tab
- Workbook > Dashboard > Datasource view 
- Workbook > Create Dashboard View > Selected Datasource preview
- Workbook > Dashboard > Chart Widget > Original view in Table chart 
(plus, check changing order function)
- I want to check more options in the original data view like filter, limitation etc.

change select query type (select -> select.stream) for searching original data

---

discovery-frontend/src/app/common/component/data-download/data.download.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts

다운로드 미리보기 건수와 실제 보이는 건수의 수를 일치 시켰습니다.
#2804 
아래 처럼 필터 조건을 설정 하고 미리보기 건수와 실제 보이는 건수가 일치함을 확인 했습니다.

#2804 Preview row count error when downloading original data in chart

---

discovery-frontend/src/app/common/domain/extension.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-server/src/main/asciidoc/application-config-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionProperties.java

Add permissions to Lnb extension configuration
**Related Issue** : #2764 
1. Add the first and second depth menus, referring to the bottom of the guide in the link below.
[https://github.com/metatron-app/metatron-discovery/blob/f%232764-add_permissions_to_lnb/discovery-server/src/main/asciidoc/application-config-guide.adoc#app-properties](https://github.com/metatron-app/metatron-discovery/blob/f%232764-add_permissions_to_lnb/discovery-server/src/main/asciidoc/application-config-guide.adoc#app-properties)
2. If you do not add a value for permissions, all users with permissions in the upper depth menu can access.
3. If you add a value for permissions, the extension menu will be displayed for the user corresponding to the permission you added.

#2764 Add permissions to Lnb extension configuration

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
discovery-frontend/src/app/domain/data-preparation/pr-dataset.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataset.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDatasetProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyFileService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepCsvUtil.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/lineage/LineageEdgeController.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvInputTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvOutputTest.java

reading csv file to create a dataset with quote character
[2835](https://github.com/metatron-app/metatron-discovery/issues/2835)
1. create a dataset with a CSV file
2. in the preview grid page, expand the more option.
3. you can change the quote character
make sure that the file is read well
you can use that test files
quote character empty file : [nmas_sensor_2019-09-02.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3823717/nmas_sensor_2019-09-02.csv.txt)
quote character " file : [big.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3823720/big.csv.txt)

#2835 create csv dataset with quote character

---

discovery-frontend/src/app/common/component/chart/option/define/common.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/common/component/color-picker/color-template.component.html
discovery-frontend/src/app/common/component/color-picker/color-template.component.ts
discovery-frontend/src/app/page/chart-style/color-option.component.html
discovery-frontend/src/app/page/chart-style/color-option.component.ts
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

Add color inversion to color template
**Related Issue** : #1442 
1. Go to chart.
2. Modify the color of Measure type by using Color Template.
3. Change the color using Color inversion.
4. See also Map View chart.

#1442 add color inversion to color template

---

discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/css/theme_dark/metatron/page.css
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/HttpRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/JupyterConnector.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/ZeppelinConnector.java

Fix create/set a notebook server if you do not have an existing notebook server.
**Related Issue** : #2824 
1. Add a notebook server when there is no registered notebook server in default and dark theme.
(The error occurred in the default theme.)
2. Set up a Jupyter notebook in a new workspace that has never been set up.

#2824 fix add new notebook server

---

discovery-server/pom.xml
discovery-server/src/main/resources/application.yaml
discovery-server/src/main/resources/db/changelog/db.changelog-master.xml
discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
discovery-server/src/main/resources/db/changelog/discovery.changelog-initial.xml
discovery-server/src/main/resources/liquibase-diff-hibernate.yaml
discovery-server/src/main/resources/liquibase-diff.yaml
discovery-server/src/main/resources/liquibase-generate.yaml
pom.xml

Apply Liquibase to make Schema versioning explicit.
**Related Issue** : #2756 
1. Run metatron-discovery application with existing h2-database as datasource.
2. Run metatron-discovery application with new h2-database as datasource.
3. Run metatron-discovery application with existing mysql-database as datasource.
4. Run metatron-discovery application with new mysql-database as datasource.

#756 apply liquibase for schema management

---

discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml

add missing column (quote_char) to pr_dataset
**Related Issue** : #2756 
start metatron-discovery application without error

#2756 add column(quote_char) to pr_dataset

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task-detail.component.ts
discovery-frontend/src/app/engine-monitoring/overview/component/graph.component.ts
discovery-frontend/src/app/engine-monitoring/overview/component/node-information.component.html
discovery-frontend/src/app/engine-monitoring/overview/component/node-information.component.ts
discovery-frontend/src/app/engine-monitoring/util/engine-monitoring.util.ts

fix engine monitoring error (convert local time)
fix datasource detail (by Metatron Engine)
1. Go to Engine monitoring -> Mouse over GC count and Avg Query time Chart -> Check local time.
2. Go to datasource detail from Metatron Engine -> Check script error.

#fix engine monitoring error and datasource detail

---

discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataService.java
discovery-server/src/main/java/app/metatron/discovery/domain/mdm/preview/MetadataJdbcDataPreview.java

Backward compatibility of connection information in Linked DataSource
1. goto Management > Metadata > Detail
2. See Data Tab of past created Metadata
Test Data in TestBed Link
http://52.231.153.96:8188/app/v2/management/metadata/metadata/2adb5547-5c4a-4050-896b-7f62bc6bef3e

Backward compatibility of connection information in Linked DataSource

---

README.md
discovery-distribution/bin/metatron.sh
discovery-frontend/src/app/explore-data/explore-data/explore-data.component.ts
discovery-frontend/src/app/explore-data/explore-data/popup/metadata-sample-data.component.ts
discovery-frontend/src/app/meta-data-management/detail/component/metadata-grid.component.html
discovery-frontend/src/app/meta-data-management/metadata/component/metadata-detail-information.component.html
discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/css/theme_dark/metatron/page.css
discovery-server/src/main/resources/application.yaml

1. metadata detail tag align
2. fix datasource title ellipsis in chart screen
3. fix explore data main title css
4. In the data preview on the dashboard, the total value of the time filter does not display properly.
5. fix explore data main scroll error
1. management -> explore -> metadata -> click metadata -> check tags alignment is proper
2. go to workbook -> click datasource list dropdown button -> check title ellipsis works well
3. Exploration -> data -> check title shows properly
4. Preview data in the dashboard-> click the entire date range button-> check if the date is displayed normally
5. Exploration -> data -> check scroll works properly

Fn fix exploration chart metadata css error

---

discovery-distribution/bin/common.sh
discovery-distribution/bin/metatron.sh
discovery-distribution/conf/metatron-env.sh.templete

Fix missing command in metatron.sh
Restart the metatron discovery application.

Fix missing command

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java

Currently, we could change the upstream I.DS or a W.DS to another I.DS in the same dataflow.
Now, we can bring any datasets in the system.
The original upstream stays in the dataflow.
**Related Issue** : #2907 
Ran locally.
Ran all test cases in dataprep.
Yes, please.

#2907 dataset swapping behavior change

---

discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts

Fix map view filtering error
METATRON-3053
1. Go to Dash board
2. Make Map chart and other charts
3. Select filter and zoom in or out map chart
4. Check map chart is showing filtered result.

fix map chart filtering error

---

discovery-frontend/src/app/explore-data/explore-data/explore-data.component.ts
discovery-frontend/src/app/explore-data/favorite/data-creator.component.ts
discovery-frontend/src/assets/css/theme_dark/metatron/page.css

Fix unnecessary scroll in favroite data
Fix toggle favorite error in data creators
fix ui error in data creator detail
1. Exploration -> My Favorite Data -> check scroll
2. Exploration -> Data Creator -> Check toggle favorite
3. Exploration -> Data Creator -> Data Creator detail -> check ui (Dark Theme)

fix explore data favorite screens

---

discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/HttpRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/JupyterConnector.java
discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/ZeppelinConnector.java

fix new notebook setup error in a new workspace that has never been set up
Set up a Jupyter notebook in a new workspace that has never been set up.

fix new notebook error

---

discovery-frontend/src/app/admin/user-management/component/approval/user-management-approval.component.ts
discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/detail-permission-schema.component.ts
discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.html
discovery-frontend/src/assets/css/metatron/component/component.table.css
discovery-frontend/src/lib/pivot-grid/pivot.grid.js

1. The operation row display function does not work in the table view.
2. You need to adjust the width of the data source list column.
3. Administrator> Workspace> Details> Data Source Popup> Top part of the icon is cut off.
4. Administrator> Workspace Permission> Workspace Permission Details> Workspace Details-Previous icon should be moved to Workspace list.
5. Toast error exclusions are required when retrieving period dates in Users> Membership Approval.
1. In the table view, check that the operation row is displayed normally.
2. Verify that the data source list column width is adjusted.
3. Verify that Administrator> Workspace> Details> Data Sources Popup> Top of the icon is displayed correctly.
4. If Administrator> Workspace Permission> Workspace Permission …

fix 3.3.x ui error

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-join.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-datasource-combo.component.html
discovery-frontend/src/app/dashboard/component/dashboard-datasource-combo.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.html
discovery-frontend/src/app/dashboard/component/update-dashboard/update-datasource.component.html
discovery-frontend/src/app/dashboard/component/update-dashboard/update-datasource.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/domain/dashboard/dashboard.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json

#2244 
* 내장된 sales 데이터소스를 사용하여 대시보드를 만들고 추가로 데이터 소스를 생성하여 기존 대시보드에 연관 관계 설정 및 JOIN을 하여 대시보드 구성하는 것을 테스트하였습니다.

#2244 Added function to edit data source relationship settings in the dashboard

---

discovery-frontend/src/app/data-storage/component/criterion/criterion-checkbox-list.component.ts

Fix keeping checkbox selections after refresh
**Related Issue** : #2981 
1. Go to datasource list
2. Select some checkbox filter
3. Refresh the page.
4. Check the checkbox filter
Dataconnection, Engine Monitoring list

#2981 fix keeping checkbox selections after refresh

---

discovery-frontend/src/app/common/component/abstract.component.ts
discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.html
discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field-detail.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-complete/file-complete.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.ts
discovery-frontend/src/app/data-storage/service/data-source-create.service.ts
discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
discovery-frontend/src/app/domain/datasource/datasource.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/app/shared/datasource-metadata/service/constant.service.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java

Support an array type column.
**Related Issue** : #2967 
1. Create a data source that contains an array type using a file.
[sample_ingestion_array.json.txt](https://github.com/metatron-app/metatron-discovery/files/3981764/sample_ingestion_array.json.txt)
2. You can select an array for both dimensions and measures.
3. When the data source is created, add a custom field.
- dimension : [sd][0] + '-test-' + [sd][1]
- measure : [array_measure][0] + [array_measure][1]
4. Check using the chart on the dashboard.
5. Check if the filter cannot be used for measure.

#2967 support an array type column

---

discovery-server/src/main/resources/db/changelog/db.changelog-master.xml
discovery-server/src/main/resources/db/changelog/dbchangelog-3.1.xsd
discovery-server/src/main/resources/db/changelog/dbchangelog-3.8.xsd
discovery-server/src/main/resources/db/changelog/dbchangelog-ext.xsd
discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
discovery-server/src/main/resources/db/changelog/discovery.changelog-initial.xml

Now, Liqubase schema files are located in the `resources/db/changelog` directory.
It makes runnable in the offline environment.
#3006 
I've tested in my local environment and the offline servers.
I don't think so. Once runnable, it would be ok.
N/A

#3006 Change Liquibase schema location to local

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.html
discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-upload.component.ts
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.html
discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/uploader.component.ts
discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-confirm-grid.component.ts
discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java

Replaced the code using plupload because of liscense issue
[3002](https://github.com/metatron-app/metatron-discovery/issues/3002)
Upload files on dataprep and datasource.
Test in various ways.
But not all behaviors will match exactly with the existing UX.
Because further work is needed.

#3002 exclude plupload module

---

discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/domain/dashboard/widget/page-widget.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json

When applying sync to an entire dashboard, not all widgets need to be applied.
Requires data processing of chart widget for real time environment.
**Related Issue** : #2954 
1. Create a dashboard using a real-time data source.
2. Set the data synchronization time on the dashboard edit screen.
3. Check if the sync button is activated and working for each widget.

#2954 Improvements for real-time dashboard

---

discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
discovery-frontend/src/app/common/component/abstract.component.ts
discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.html
discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.ts
discovery-frontend/src/app/explore-data/favorite/data-creator.component.html
discovery-frontend/src/app/explore-data/favorite/data-creator.component.ts
discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
discovery-frontend/src/app/meta-data-management/metadata/metadata.component.html
discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/css/theme_dark/metatron/page.css

1.Exploration> Data Creator User thumbnail not shown
2. The Exploration> Data Creator> Detail data list's sorting default is Created Time (descending), which is indicated by the Sort Name in the grid header.
3. Delete icon is overlaid when hovering over Management> Metadata Database, StagingDB
1.Explore Exploration> Data Creator User Image Thumbnail
2. Verify that the sort defaults in the Exploration> Data Creator> Detail data list are displayed in descending order at Created Time.
3. Check if the delete icon is displayed normally when hovering over Management> Metadata Database, StagingDB.

Fix user image display error and icon display error

---

discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.html
discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.ts
discovery-frontend/src/app/explore-data/favorite/data-creator-detail.component.html
discovery-frontend/src/assets/css/metatron/page.css
discovery-frontend/src/assets/css/theme_dark/metatron/page.css

1. Exploration-Data-Data overview There is a screen where the user profile image is not displayed.
2. Sort time by Create time in the Exploration-Data Creator-detail list is often incorrect.
1. Exploration-Data-Data overview Verify that the user profile image is available
2. Make sure that the Sort time of Create time in the Exploration-Data Creator-detail list is displayed correctly.

Fix user image display error, fix time display error

---

discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java

403 cors error when request /oauth/token api.
so add cors config for oauth.
**Related Issue** : #3022 
1. open google chrome DevTools.
2. execute script below in DevTool console
```
var data = new FormData();
data.append("grant_type", "password");
data.append("scope", "read");
data.append("username", "metatron");
data.append("password", "metatron");
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;
xhr.open("POST", "http://{TestBedHost}/oauth/token");
xhr.setRequestHeader("Authorization", "Basic cG9sYXJpc19jbGllbnQ6cG9sYXJpcw==");
xhr.send(data);
```

#3022 add cors config for oauth

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/resources/application.yaml

Admin can configure some consumer properties on the application settings.
default set is as below,
```
polaris:
datasource:
realtime:
consumerConfig:
groupId: KafkaSampleConsumer
keyDeserializer: org.apache.kafka.common.serialization.LongDeserializer
valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
autoOffsetReset: latest
requestTimeout: 10000
sessionTimeOut: 8000
fetchMaxWait: 8000
heartbeatInterval: 5000
```
#3035

#3035 Configurable Consumer

---

discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/accessor/AbstractJdbcDataAccessor.java
discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/connector/AbstractJdbcConnector.java
discovery-extensions/athena-connection/README.md
discovery-extensions/athena-connection/pom.xml
discovery-extensions/athena-connection/src/main/assembly/assembly.xml
discovery-extensions/athena-connection/src/main/java/app/metatron/discovery/AthenaConnectionExtension.java
discovery-extensions/pom.xml
discovery-frontend/src/app/data-storage/component/connection/connection.component.ts

Connection Extension for AWS Athena with JDBC.
The Athena JDBC Driver version used is 2.0.2.
For more information, refer to the JDBC Driver Documentation section of the page below.
https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html
How to Connect to Athena from Discovery with the Athena Connection Extension.
There are various ways to configure connection URL.
See the following page for a detailed configure guide.
https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC_2.0.2/docs/Simba+Athena+JDBC+Driver+Install+and+Configuration+Guide.pdf
Sample using endpoint URL can be configured as below.
```
jdbc:awsathena://athena.[Region].amazonaws.com:443;User=
[AccessKey];Password=[SecretKey];S3OutputLocation=[Output];
[Property1]=[Value1];[Property2]=[Value2];... …
```

#3015 Support for AWS Athena Connection via JDBC

---

pom.xml

change metatron nexus url to nexus.metatron.app
Refer to the guide below to successfully create an extension project using an extension archetype.
https://github.com/metatron-app/metatron-discovery/tree/master/discovery-extensions
```
$ mvn archetype:generate -DarchetypeGroupId=app.metatron.discovery -DarchetypeArtifactId=discovery-extension-connection-archetype -DarchetypeVersion=1.0.0
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for app.metatron.discovery:mssql-connection:jar:7.3.0
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ app.metatron.discovery:metatron-discovery:3.4.0-rc4, …
```

change metatron nexus url to nexus.metatron.app

---

discovery-frontend/src/app/common/service/abstract.service.ts
discovery-frontend/src/app/user/service/user.service.ts

Fixed a small typo error
If your token has expired, you can check to see if there are any problems

fixed typo

---

discovery-frontend/src/app/dashboard/service/dashboard.service.ts
discovery-frontend/src/app/dashboard/service/widget.service.ts
discovery-frontend/src/app/dashboard/util/dashboard.util.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/domain/dashboard/dashboard.ts

Set enginename in dashboard
**Related Issue** : #3057 
1. Create a datasource.
2. Create a dashboard with the datasource created in the first step and create a chart.
3. Change the name of the datasource created in the first step.
4. Make sure the dashboard looks without errors.
Check a dashboard with multi datasources

#3057 set enginename in dashboard

---

discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts

Improve configure schema and metadata column details performance
**Related Issue** : #3157 
1. Go to datasource details and column details.
2. Click 'Please configure the schema'.
3. Click anywhere and check if it operates normally without error.
4. Go to management - exploration - metadata
5. Go to a detail page and click Column details tab.
6. Click anywhere and check if it operates normally without error.

F#3157 improve configure schema performance

---

discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts

change line chart sampling option
1. Create a dashboard and add a line chart
2. Check if it operates normally without error.

change line chart sampling option

---

discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/resources/templates/api/oauth/login.html

change background and logo image in the external login page
1. generate clientId and clientSecret
URL : /api/oauth/generate
Param : 
_ clientName(clientName)
_ redirectUri(Uri you want to redirect)
_ backgroundFilePath(the background image path in the external page)
_ logoFilePath(the logo image path in the external page)
Header : Authorization (Bearer {})
Response(ex) : {
"clientId": "naU8OH",
"clientName": "test",
"basicHeader": "bmFVOE9IOlBuNWFwWERZaTc=",
"clientSecret": "Pn5apXDYi7"
}
2. test login page
{domain}/oauth/authorize?response_type=code&client_id=naU8OH&redirect_uri=https://www.google.com/&scope=read
the logo path is "/assets/images/oauth/{clientName}.svg"
the external app name is {clientName}
ex: Go to {clientName}
update and delete oauth client

change background and logo image in the external login page

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrSnapshotProjections.java

Improved snapshot list projection
1. Go to MANAGEMENT - Data Preparation - Data Snapshot list
2. Check if there are only necessary attributes in the list screen using Browser DevTools.

Fix snapshot list projection

---

discovery-frontend/src/app/engine-monitoring/datasource/datasource.component.html
discovery-frontend/src/app/engine-monitoring/datasource/datasource.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/EngineMonitoringSetter.java

Fix engine server list initialization
1. After installing the Druid cluster, check the list of Druid clusters on the Engine Monitoring Overview screen.
2. Check the engine server list by setting the URL of Druid's broker, overlord, and coordinator to different clusters.
3. Check the engine server list by setting the URL of Druid's historical, middleManager to different clusters.

fix engine server list initialization

---

discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/pie-chart.component.ts

fix script error when pie chart and table chart contain alias
**Related Issue** : #3181 
1. Go to a dashboard with 'Sales' datasource.
2. Create a text table chart.
3. Place Category and Sub-category on the second shelf and set the alias
and In the Common Setting, set the Text Style Aggregation Column to On (Horizonal).
4. Alias ​​is applied.
5. Create a pie chart
6. Place Category and Profit on the shelf and set the alias.
7. See without error

#3181 fix script error when pie chart and table chart contain alias

---

discovery-server/src/main/asciidoc/application-config-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/OauthClientInformation.java
discovery-server/src/main/resources/templates/api/oauth/login.html

Customized external login page
**Related Issue** : #3191 
1. generate clientId and clientSecret
URL : /api/oauth/generate
RequestBody : example
{ "clientName":  "test",
"redirectUri": "https://metatron.app/"
"faviconPath": "/static/favicon.ico",
"logoFilePath": "/static/logo.svg",
"backgroundFilePath": "/static/background.jpg",
"smallLogoFilePath": "/static/smalllogo.png",
"smallLogoDesc": "This is Test Client",
"copyrightHtml": "This is Test Client<br/>Copyright © metatron.app All rights reserved."
}
Header : Authorization (Bearer {})
Response(ex) : {
"clientId": "naU8OH",
"clientName": "test",
"basicHeader": "bmFVOE9IOlBuNWFwWERZaTc=",
"clientSecret": "Pn5apXDYi7"
}
2. test login page
{domain}/oauth/authorize?response_type=code&client_id=naU8OH&redirect_uri=https://metatron.app/&scope=re …

#3191 customized external login page

---

discovery-frontend/src/app/user/profile/change-password/change-password.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/asciidoc/application-config-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/config/OAuthInterceptor.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditErrorCodes.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditException.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/DomainAudit.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/DomainAuditController.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/DomainAuditService.java
discovery-server/src/main/java/app/metatron/discovery/domain/audit/DomainAuditType.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/User.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserPasswordProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserService.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/group/Group.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupMember.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/role/RoleDirectory.java
discovery-server/src/main/resources/application.yaml
discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml

Password maximum usage period, minimum usage period applied.
1. Users cannot log in after the maximum password usage period and must change the password through the password change dialog.
2. Users cannot change it again within the minimum period of use after changing the password. (but Administrator can change the password.)
1. add password period config to application.yaml
For testing, the minimum password usage period is 5 minutes, and the required change period is 10 minutes.
```
polaris:
user:
password:
requiredChangePeriod: PT10M           # The password must be changed within that period. (ISO 8601 Duration Format)
minimumUsePeriod: PT5M               # The password cannot be changed again within that period. (ISO 8601 Duration Format)
```
2. register userA
3. …

Password maximum usage period, minimum usage period applied.

---

discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
discovery-frontend/src/app/user/service/user.service.ts
discovery-server/src/main/java/app/metatron/discovery/common/StatLogger.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/BasicTokenExtractor.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/CookieManager.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/CustomWebResponseExceptionTranslator.java
discovery-server/src/main/java/app/metatron/discovery/common/revision/CustomEnversPostInsertEventListener.java
discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuthInterceptor.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/java/app/metatron/discovery/domain/revision/MetatronRevisionDto.java

Security log improvements
- login, logout 
- add, modify, and delete users, groups, and permissions
1. Login and logout
2. Create user, group and permission
3. Modify user, group, permission
4. Add users to groups
5. Add users and groups to permissions
6. Delete users and groups to permissions
7. Delete user, group and permission

Security log improvements

---

discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml

fix column type of user_fail_cnt
1. Use h2 database.
2. Check if the application starts without error.
3. Use mysql database.
4. Check if the application starts without error.

fix column type of user_fail_cnt

---

discovery-frontend/src/app/app.module.ts
discovery-frontend/src/app/common/common.module.ts
discovery-frontend/src/app/common/interceptor/loader-interceptor.ts
discovery-frontend/src/app/common/service/abstract.service.ts
discovery-frontend/src/app/common/util/alert.util.ts
discovery-frontend/src/app/user/login/login.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-server/src/main/asciidoc/application-config-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/common/oauth/CustomWebResponseExceptionTranslator.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/OauthProperties.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/JwtTokenUtil.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/cache/AccessTokenCacheRepository.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/cache/RefreshTokenCacheRepository.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/cache/WhitelistTokenCacheRepository.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/filter/RefreshTokenRetentionFilter.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/filter/WhitelistAuthenticationFilter.java
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/store/RefreshRetentionJwtTokenStore.java
discovery-server/src/main/java/app/metatron/discovery/config/InfinispanCacheConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuthInterceptor.java
discovery-server/src/main/java/app/metatron/discovery/config/SchedulingConfig.java
discovery-server/src/main/java/app/metatron/discovery/domain/admin/CacheAdminController.java
discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/common/OAuthCacheOutJob.java
discovery-server/src/main/java/app/metatron/discovery/domain/user/User.java
discovery-server/src/main/java/app/metatron/discovery/util/HttpUtils.java

1. The user's authentication information must time out after a certain period of time.
When creating an access token and refresh token, it is stored in the Infinispan cache.
When the API is called, the Expiration Date of the Refresh Token is updated.
When accessing to the refresh token, the token stored in the cache is used instead of the JWTToken.
2. When logging in from another IP, the existing authentication information should not be valid.
When creating an access token, username, ClientId, and ClientIp are stored in the cache.
When calling the API, compare whether the user IP is the same as the IP stored in the cache.
If they do not match, an Unauthorized Error (401) is generated.
1. Add timeout property in application.yaml
```
polaris:
oauth2:
timeout: 60                # 60 Seconds …
```

oAuth timeout and client whitelist using infinispan cache

---

discovery-frontend/src/app/page/page.component.ts

fix error for missing user defined field
1. Create a user defined field.
2. Create a chart using the field created in the first step.
3. Save the chart and dashboard.
4. Go to the chart editing screen created in the second step.
5. Check that the user defined field created in the first step is visible in the left field list.

fix error for missing user defined field

---

discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
discovery-server/src/main/java/app/metatron/discovery/config/OAuthInterceptor.java

Addo cors filter for oauth
[https://metatron.app/2019/05/20/lets-embed-a-dashboard-or-chart-in-another-application/](https://metatron.app/2019/05/20/lets-embed-a-dashboard-or-chart-in-another-application/)
**Related Issue** : #3022 
1. open google chrome DevTools
2. execute script below in DevTool console
```
var data = new FormData();
data.append("grant_type", "password");
data.append("scope", "read");
data.append("username", "metatron");
data.append("password", "metatron");
var xhttp;
xhttp=new XMLHttpRequest();
xhttp.withCredentials = true;
xhttp.onreadystatechange = function() {
if (this.readyState == 4 && this.status == 200) {
console.log(this.responseText);
}
};
xhttp.open("POST", "http://{testbed}/oauth/token");
xhttp.setRequestHeader("Authorization", "Basic …
```

#3022 add cors filter for oauth

---

discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.html
discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts

1. Data Filter Layer CSS error
2. Does not work after selecting Data Filter
3. Date filter check button CSS error
**Related Issue** : #3266 
2. Add charts and filters.
3. Check if the option is displayed properly when the filter is selected on the browse screen.
4. Check if the filter is applied to the chart when the option is changed.

#3266 Fix filter not working error

---

discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.html
discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts

Cherry pick to reflect on 3.3.x branch
**Related Issue** : #3266 
**Related PR** : https://github.com/metatron-app/metatron-discovery/pull/3277
Test with reference to previous PR (https://github.com/metatron-app/metatron-discovery/pull/3277)

#3266 Fix error of filter function

---

discovery-frontend/src/app/page/page.component.ts

Fix error for editing chart using join datasources
1. Create a dashboard using join datasources
2. Create a chart (ex: bar, grid chart).
3. Check the edit page, and check if editing is normal.

fix error for editing chart using join datasources

---

discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
discovery-server/src/main/resources/templates/api/oauth/login.html

fix external login in Internet Explorer 11
1. Login to an external client in Internet Explorer 11.
Other browsers including mobile devices.

fix external login in ie11

---

discovery-frontend/src/app/dashboard/util/dashboard.util.ts

fix linked datasource check
**Related Issue** : #3327 
1. Create a dashboard with 'Linked Datasource'
2. Click on 'Add Chart'
3. Check if it is added normally and is displayed.
Check both single and multi datasources.

#3327 fix linked datasource check

---

discovery-frontend/src/app/datasource/service/datasource.service.ts

fix map chart with multi datasources
**Related Issue** : #3346
1. Create a map view chart after selecting multi datasources.
2. Go to the dashboard and make sure it looks normal.
3. Go to the map view chart edit screen and make sure it looks normal.

#3346 fix map chart with multi datasources

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/AbstractEngineRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/DruidEngineRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineProperties.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
discovery-server/src/main/resources/application.yaml

support sql query results in Geojson format
**Related Issue** : #3357 
1. Check **nyc_boundaries** datasource.
(If it is deleted, create the datasource with [taxi_zones.csv.zip](https://github.com/metatron-app/metatron-discovery/files/5166414/taxi_zones.csv.zip) )
2. Call the added API.
url : /api/datasources/query/sql/geojson
method : POST
body : 
`{"query": "SELECT LocationID, borough, zone, geom_transform(geom_fromWKT(the_geom), 4326, 4326) as geom FROM \"druid\".\"nyc_boundaries\""}` 
Expected result : Geojson format [nyc_result_geojson.txt](https://github.com/metatron-app/metatron-discovery/files/5166405/nyc_result_geojson.txt)

#3357 support sql query results in Geojson format

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-info.component.ts
discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
discovery-frontend/src/app/domain/dashboard/dashboard.ts

If you use Association & Join edit screen with linked datasource, the screen displays javascript error.
https://github.com/metatron-app/metatron-discovery/issues/3365
1. Create dashboard with linked datasource.
2. edit dashboard.
3. Click "Association & Join" in Dashboard tab of right pane.
4. Check Association & Join edit view.

#3365 association edit view

---

discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts

There is an embedded chart page that is not displayed due to a script error.
Check if the embedded chart page is displayed normally.

fix script error in embedded view

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/DataSourceCheckJob.java

Check the status of the datasource that failed to ingest
**Related Issue** : #3372 
1. Create a datasource and make sure it is ingested normally.
2. Ingest with abnormal data to fail additional ingestion.
3. Make sure it is failed.
4. Call the added API.
url : /api/datasources/{id}/setSizeAndStatus
method : GET
Needs testing with metatron Integrator.

#3372 Check the status of the datasource that failed to ingest

---

discovery-frontend/src/app/engine-monitoring/query/query.component.html
discovery-frontend/src/app/engine-monitoring/query/query.component.ts
discovery-frontend/src/app/engine-monitoring/service/engine.service.ts
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringController.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java
discovery-server/src/main/resources/application.yaml

query information in engine monitoring
**Related Issue** : #3379 
1. Go to enigine monitoring and Query Tab.
2. Select a query detail.
3. Check the json or SQL of the query request.

#3379 query information in engine monitoring

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html

deprecate dataset, dataflow in data preparation
1. Check Lnb in datapreparation.
2. Go to data snaphot and check the tab menu at the top.

deprecate dataset, dataflow in data preparation

---

discovery-frontend/src/app/dashboard/widgets/abstract-widget.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java

treat measure double NaN
**Related Issue** : #3342 
1. Create a dashboard with sales datasource
2. Create a user-defined field field created with NaN values. (ex: Divide by zero)
3. Create a line chart with the user-defined field
4. Check if it is displayed normally without infinite loading.

treat measure double NaN

---

discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/DistinctSketchAggregation.java
discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java

#2996 # Description
https://github.com/metatron-app/metatron-discovery/issues/3401
See the issue.
https://github.com/metatron-app/metatron-discovery/issues/3401
We need to fix the test case. I just fix some test cases for my test.

#3401 Bug fix for wrong generated Druid query for countd expression in user defined field.

---

discovery-frontend/src/app/engine-monitoring/query/query.component.html
discovery-frontend/src/app/engine-monitoring/query/query.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/engine/monitoring/EngineMonitoringService.java

add exception, querytime to query information
**Related Issue** : #3408 
1. Go to Engine Monitoring and Query tab.
2. Click a fail query in the list.
3. Check the exception message.
4. Click another query in the list.
5. Check the Query Time. 
(Duration is the time taken by the service, and Query Time is the total time for query execution.)

#3408 add exception, querytime to query information

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts

See the issue
https://github.com/metatron-app/metatron-discovery/issues/3423
https://github.com/metatron-app/metatron-discovery/issues/3324
https://github.com/metatron-app/metatron-discovery/issues/3423
https://github.com/metatron-app/metatron-discovery/issues/3324
https://github.com/metatron-app/metatron-discovery/issues/3324

#3423 Remove unnecessary pagewidget configuration changing(Filter's datasource name)

---

discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java

enhance oauth client logout
**Related Issue** : #3432 
1. Register oauth clients with a different domain from metatron Discovery.
2. Check if you are logged in to the oauth client normally.
3. Call /api/oauth/client/logout?client_id={clientId}&redirect_uri={redirect_uri} to log out.
4. If a parameter that is not included in the redirect uri of the oauth client is transmitted, logout and redirect with the redirect_uri parameter value.

#3432 enhance oauth client logout

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceService.java

Users can use the workbench button only if there is a valid connection in their personal workspace.
**Related Issue** : #3420 
1. Log in as a user with an available connection
2. see workbench button.
3. Log in as a user without an available connection
4. see workbench button hided.

#3420 Users have workbench permissions if there are connections available

---

discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java

Remove POST handler overriding on data snapshots to add snapshot entities directly (from Prepbot)
**Related Issue** : #3417 
N/A
No.

#3417 remove POST handler overriding on data snapshots

---

discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/lib/at/jquery.atwho.js

See the issue
https://github.com/metatron-app/metatron-discovery/issues/3443
https://github.com/metatron-app/metatron-discovery/issues/3443
See the issue
https://github.com/metatron-app/metatron-discovery/issues/3443
In addition, it supports auto-completion for other user-defined fields. When auto-completion of user-defined fields, the user_defined prefix is ​​added in front of the field name.

F#3443 improvements of autocompletion in the fomula pane

---

discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
discovery-frontend/src/app/page/page-view.component.ts
discovery-frontend/src/app/page/page.component.ts

fix alias for values with multi datasources
**Related Issue** : #3455 
See the issue #3455

#3455 fix alias for values with multi datasources

---

discovery-frontend/src/app/dashboard/util/dashboard.util.ts
discovery-frontend/src/app/page/page.component.ts

fix existing user defined field when using multi datasource
**Related Issue** : #3463 
See the issue #3463

#3463 fix existing user defined field when using multi datasource

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/DataSourceCheckJob.java

check datasource status including failed datasource
**Related Issue** : #3466 
1. Create a data source with invalid raw data and check if the status is failed.
2. Check whether the failed datasource is included in the log of datasourceCheckJob, which is executed every 30 minutes.

#3466 check datasource status including failed datasource

---

discovery-frontend/src/app/dashboard/util/dashboard.util.ts

fix for user field list when changing datasource
**Related Issue** : #3463 
1. Create a dashboard with multi datasources
2. Create a chart
3. Change another datasource
4. Check that no script error occurs

fix for user field list when changing datasource

---

discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html

enable dataset, dataflow in data preparation
1. Check Lnb in datapreparation.
2. Go to dataset, dataflow, data snaphot and check the tab menu at the top.

enable dataset, dataflow in data preparation

---

discovery-frontend/src/app/embedded/page/embedded-page.component.ts

fix embedded view with multi datasources
**Related Issue** : #3491 
See the issue #3491

#3491 fix embedded view with multi datasources

---

discovery-frontend/src/app/common/component/chart/type/label-chart.component.ts

fix time compare with multi datasources
**Related Issue** : N/A
1. Create a dashboard with multi datasources.
2. Create a KPI chart widget.
3. Select a measure with the second datasource.
4. Use secondary indicators as a PERIOD type.

fix time compare with multi datasources

---

discovery-frontend/src/app/workspace/workspace.component.ts

fix private workspace name
**Related Issue** : #3456 
1. Log in with your polaris account. (except admin)
2. Change the user's full name to "Test user".
3. Check the user's own workspace has been changed to "Test user's workspace".
4. Sign up for a new account through the login page.
5. After admin approves, log in with the new account and check the personal workspace name.

fix private workspace name

---

discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/cache/TokenCacheRepository.java

fix check token validity seconds
See the pull request #3301

fix check token validity seconds

---

discovery-extensions/bigquery-connection/README.md
discovery-extensions/pom.xml
discovery-frontend/src/app/workspace/workspace.component.ts
discovery-frontend/src/assets/css/theme_dark/metatron/page.css
discovery-server/src/main/java/app/metatron/discovery/common/oauth/token/cache/TokenCacheRepository.java
discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/query/NativeCriteria.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java

Fix BigQuery Plugin's dependency conflict
There is a conflict problem with the slf4j library, so when copying the files, you need to exclude the slf4j-api-*.jar files.
And when previewing, 'LIMIT' clause was added.

Fix BigQuery Plugin's dependency conflict

---

discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspacePredicate.java

You need an API that can query workspaces by list of workspace ids.
```
URL: /api/worksapces
Method: GET
param: 
- workspaceIds : Workspace ID list using separator (,)
(ex: ws-00,ws-03)
```
Sample Response
URL: /api/workspaces?workspaceIds=ws-00,ws-03
```
{
"_embedded": {
"workspaces": [
{
"name": "Admin Workspace",
"id": "ws-00",
"active": true,
"description": "",
"owner": {
"type": "user",
"organizations": [],
"username": "admin",
"fullName": "Administrator",
"email": "admin@metatron.com"
},
"published": false,
"createdTime": "2020-07-17T00:00:00.000Z",
"modifiedTime": "2020-07-17T00:00:00.000Z",
"lastAccessedTime": "2021-01-25T04:24:44.656Z",
"publicType": "PRIVATE",
"_links": {
"self": {
"href": "http://localhost:8180/api/workspaces/ws-00"
},
"workspace": { …
```

search workspaces by id

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.ts
discovery-frontend/src/app/workbook/workbook.component.html
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/assets/i18n/en.json
discovery-frontend/src/assets/i18n/ko.json
discovery-frontend/src/assets/i18n/zh.json
discovery-frontend/src/lib/nicEdit/nicEdit.js

Display url when entering the Dashboard screen
**Related Issue** : #3643  
1. Check if the dashboard URL is copied when clicking the dashboard icon.
2. When entering the copied URL, check whether it moves without initial loading.
3. Check if the dashboard is displayed as the address changes when clicking on the dashboard list.
- [] New feature (non-breaking change which adds functionality)

Dashboard router fragment function was added.

---

discovery-server/src/main/java/app/metatron/discovery/util/ExcelUtils.java

fix compile error after poi bump

fix compile error after poi bump

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSource.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/IngestionUpdateRequest.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/HdfsIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/HiveIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/IngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/LocalFileIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/RealtimeIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/BatchIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/LinkIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SingleIngestionInfo.java
discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineIngestionService.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/KafkaRealTimeIndex.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/KafkaRealTimeIndexBuilder.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java

Stream type of data sources are configured using Druid's Supervisor. Since the supervisor is constantly loaded within Druid, we sometimes need to change the Supervisor specification when the data source changes. Therefore, it is possible to update the loading options and field changes using the API below.
```
(PATCH) /api/datasources/{id}/ingestion
{
"ingestionInfo": {
"type": "realtime",
"taskOptions": {...},            // see "https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html#kafkasupervisortuningconfig"
"tuningOptions": {              // see "https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html#kafkasupervisortuningconfig"
"resetOffsetAutomatically": "true",
"httpTimeout": "PT5S",
...
}
},
"patchFields": [
{
"op": …
```

Add API to change stream datasource information(ingestion spec.and field)

---

discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
discovery-frontend/src/app/domain/workbook/configurations/field/field.ts
discovery-frontend/src/app/page/chart-style/format/abstract-format-item.component.ts
discovery-frontend/src/app/page/chart-style/format/format-item.component.html
discovery-frontend/src/app/page/page-pivot/page-pivot-format.component.html
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
discovery-frontend/src/assets/i18n/ko.json

It is necessary to add the Combine Chart sub-axis function.
**Related Issue** : #3639 
1. Create a combined chart on the chart creation screen.
2. Check that the secondary axis setting menu is displayed on the measured value shelf.
3. When selecting the secondary axis setting, check whether the corresponding measured value is displayed as the secondary axis.

F#3639 combine chart sub axis

---

discovery-frontend/proxy.conf.js
discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
discovery-frontend/src/app/common/component/chart/option/util/option-generator.ts
discovery-frontend/src/app/common/component/chart/type/bar-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
discovery-frontend/src/app/page/page.component.html

Multiple values must be displayed at the same time in the tooltips of line charts and bar charts.
**Related Issue** : #3671 
1. Create a bar chart or line chart using more than one measure.
2. Make sure that the tooltip is displayed at once relative to the axis.

#3671 line and bar chart tooltip improvement

---

discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts
discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.ts

The embedded dashboard screen is not visible
Check if the embedded dashboard screen is displayed normally

fix error embedded dashboard

---

discovery-frontend/src/app/common/component/grid/grid.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.html
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.widget.header.component.ts
discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts

Fn fix script error

---

discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page.component.html
discovery-frontend/src/app/page/page.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts

There is an error that duplicate value aliases are generated.

Fixed an error with creating value aliases.

---

discovery-frontend/src/app/data-storage/data-connection/create-connection.component.ts
discovery-frontend/src/app/data-storage/data-connection/update-connection.component.ts

fix on data connection creation and editing pages
1. Go to the data connection creation page.
2. Check if the data connection is normally created.
3. Go to the data connection edit page.
4. Check if the data connection is modified normally.

fix on data connection creation and editing pages

---

discovery-frontend/src/app/domain/engine-monitoring/task.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor-detail.component.html
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task-detail.component.html
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task-detail.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task.component.ts
discovery-frontend/src/app/engine-monitoring/ingestion/ingestion.component.ts
discovery-frontend/src/app/engine-monitoring/query/query.component.ts
discovery-frontend/tslint.json

fix searching task list
1. Go to Engine monitoring.
2. Go to the task tab of the ingestion menu.
3. Check whether the search is normal and the page navigation works.

fix searching task list in engine monitoring

---

discovery-frontend/src/app/common/util/common.util.ts
discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.ts

There is a problem with infinite calls when unfiltering.

fixed infinite call issue when clearing filter

---

discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts

Fix script errors that occur when creating datasets.

fix script error when create dataset

---

discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts

Line Chart tooltip missing cross-shelf content
**Related Issue** : #3718 
1. Create a line chart using measured values and dimension values.
2. Check that the tooltip on the chart shows the measure by dimension value.

#3718 change multi series tooltip

---

discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts

Change the button position adjustment timing

Change the button position adjustment timing

---

discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-pop-ds-select.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java

Change to enable replacement of linked datasources
**Related Issue** : #3687 
1. Create a dashboard including linked datasources.
2. Replace with a datasource that can be changed.
3. Create a dashboard
4. Replace it with a linked datasource that can be changed.

Change to enable replacement of linked datasources

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java

get a logicalType by dataType when logicalType is null
#3759 
run an API that handle fields 
http://localhost:8180/api/datasources/{datasource id}/ingestion
No

Field can be updated when logicalType is null

---

discovery-frontend/src/app/common/util/loading.util.ts
discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.ts

fix script error in presentation view
**Related Issue** : #3761 
See the issue #3761

#3761 fix script error in presentation view

---

discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
discovery-frontend/src/app/workbook/workbook.component.html

fix table sql in workbench
1. Create a workbench of druid database.
2. Select a table in the lnb list.
3. Check if table sql is entered normally in the editor. ("database"."table")

fix table sql in workbench

---

discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts
discovery-frontend/src/app/embedded/embedded-view.module.ts

hide loading in embedded
**Related Issue** : #3763 
1. Open the dashboard with the following URL form.
~/app/v2/embedded/dashboard/frag#[dashboardId]
2. Check if loading is displayed when another dashboard is launched in the same form.

#3763 hide loading in embedded

---

discovery-frontend/src/assets/i18n/en.json

fix english typo
1. Go to login page
2. Check if a script error occurs.
3. Change the language and check.

fix english typo

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/BoardConfiguration.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java

fix changing datasource in dashboard
**Related Issue** : #3687 
1. Create a dashboard with time filters and widgets including user-defined fields and fields to which aliases are applied.
2. Replace the datasource of the dashboard with a new datasource.
3. Check if it is changed normally.

fix datasource replacement in dashboard

---

discovery-frontend/src/app/dashboard/dashboard.component.html
discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts

Check for errors in scrolling and filter function of embed dashboard
1. Check if it is displayed normally when the browser size is reduced to 1200px or less in the embed dashboard.
2. Check if the filter parameter in the fragment url works normally.

fix error embed dashboard

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/filters/component/time-date.component.html
discovery-frontend/src/app/dashboard/filters/component/time-date.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-date-filter.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/time-date-filter.component.ts
discovery-frontend/src/app/dashboard/util/filter.util.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/domain/workbook/configurations/filter/time-date-filter.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/page/page-view.component.ts
discovery-frontend/src/app/page/page.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRangeFilter.java

If you set granularity , you need a filter that can select a single date.
**Related Issue** : #3739
1. Open the filter creation popup.
2. Select the time field, select granularity, and make sure that there is a single time type in Filter Type.
3. After selecting a single time type, check if it is displayed normally on the panel.
4. Register the filter widget and check if it is displayed normally in the widget.

Fn fix single date filter

---

discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/meta-data-management/metadata/component/embedded-metadata-detail.component.ts

remove disable back key event in embed page

remove disable back key event in embed page

---

discovery-frontend/angular.json
discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/dashboard/dashboard.component.html
discovery-frontend/src/app/dashboard/dashboard.component.ts
discovery-frontend/src/app/embedded/dashboard/embedded-dashboard.component.ts
discovery-frontend/src/static/iframe.html
discovery-frontend/src/styles.css

Change the minimum size of embed dashboard and fix the prev filter function error
1. Resize the embed dashboard to check it.
2. Check if the pre-filter works without any errors when applying the pre-filter in the frag state.

Change the minimum size of embed dashboard and fix the prev filter function error

---

discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
discovery-frontend/src/app/page/chart-style/yaxis-option.component.ts
discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts

Fix secondary axis setting error
**Related Issue** : #3833 
1. Create a chart using the secondary axis.
2. Set the chart title to be hidden on the secondary axis.
3. Check if it is applied normally.

#3833 Fix secondary axis setting error

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/AbstractTuningConfig.java
discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/BatchTuningConfig.java
discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java

fix UnrecognizedPropertyException in tuningConfig
UnrecognizedPropertyException occurs when there is a property that does not exist in tuningConfig
**Related Issue** : #3828 
1. Added unit test
2. Patch an existing datasource and check the nested spec is preserving

fix UPE in tuningConfig

---

discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
discovery-frontend/src/app/common/component/chart/option/define/common.ts
discovery-frontend/src/app/page/chart-style/format/abstract-format-item.component.ts

Add Russian rouble into currency list.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/3859
Open currency list in chart settings, and choose 'RUB'
But there is no active release branch,  all pull request goes to master, so i did it too.

#3859 Added Russian rouble

---

discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/page/page-view.component.ts
discovery-frontend/src/app/page/page.component.ts

Fixed graph display error in chart editing screen

Fixed graph display error in chart editing screen

---

discovery-frontend/src/app/common/component/input/input.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
discovery-frontend/src/app/dashboard/filters/configure-filters.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/configure-filters-time.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.html
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-frontend/src/app/dashboard/util/filter.util.ts
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/domain/dashboard/dashboard.ts
discovery-frontend/src/app/domain/workbook/configurations/filter/time-relative-filter.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/page/page-view.component.ts
discovery-frontend/src/app/page/page.component.ts

Change how the time filter specifies the last date
1. Add a time filter.
2. Select Last Time to verify that the time is displayed as Last Data Time.

Change how the time filter specifies the last date

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts

set latestTime when new relative filter is created

set latestTime when new relative filter is created

---

discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts

In the dashboard, the relative filter should appear as a range filter.
**Related Issue** : #3895 
In the dashboard, make sure that the relative filter is displayed as a range filter.

#3895 Change Relative Filter to Range Filter in Dashboard when edit mode

---

discovery-frontend/src/app/user/login/component/join/join.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java

Fixed an error where the user registration button did not work.
**Related Issue** : #3894 
1. On the user registration screen, check whether the user registration application is successful.

#3894 Fixed an error that could not be registered as a member.

---

discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/app/workspace/workspace.component.ts

Description
Modify to move from workbook to parent workspace
Related Issue : #3921
How Has This Been Tested?
1. Go to workbook
2. Open another tab in your browser and go to another workbook.
3. In the browser tab of the first step, click the back button in the upper left corner.
4. Confirm that the workbook is moved to the workspace it belongs to.

#3921 Fixed an error in moving the workspace when clicking the home button

---

discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.html
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/page/page.component.ts

After registering the global filter, it does not appear on the list
1. Create a filter in the dashboard edit screen.
2. Exit without saving the dashboard.
3. When re-entering the edit screen, check if the filter list is displayed normally.

After registering the global filter, it does not appear on the list

---

discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/page/page.component.ts

When the global filter is modified, a console error occurs and infinite loading occurs.
**Related Issue** : #3937 
1. Clone the dashboard with global filter set.
2. Modify the filter in the cloned dashboard.
3. Check if the filter is modified normally.
- [x] Bug fix (non-breaking change which fixes an issue)

#3937 When the global filter is modified, a console error occurs and infinite loading occurs.

---

discovery-prep-parser/pom.xml
pom.xml

bump up logback to 1.2.9
**Related Issue** : #3956

#3956 bump up logback to 1.2.9

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts

1. When modifying the relative filter widget, the correction popup is displayed as a range filter
2. An error that the latest time does not apply to the relative filter widget's reference value
**Related Issue** : #3973 
1. When modifying the relative filter widget, check if the edit popup is displayed as relative filter widget
2. Check whether the latest time reference value of the relative filter widget is applied

#3973 Fixed relative time filter error

---

discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-frontend/src/app/dashboard/util/filter.util.ts

fix error relative filter

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
discovery-frontend/src/app/dashboard/util/filter.util.ts
discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
discovery-frontend/src/app/domain/workbook/configurations/filter/time-relative-filter.ts
discovery-frontend/src/app/embedded/page/embedded-page.component.ts
discovery-frontend/src/app/page/page-view.component.ts
discovery-frontend/src/app/page/page.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilter.java
discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/BoardConfigurationTest.java
discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilterTest.java

Fix not to save latestTime in time relative filter

---

discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts

Fixed an error when a relative time filter was added to the chart widget
1. Create a chart widget.
2. Add a filter to the chart widget.
3. Check that the dashboard is displayed normally.
- [X] Bug fix (non-breaking change which fixes an issue)

Fixed an error when a relative time filter was added to the chart widget

---

discovery-frontend/angular.json
discovery-frontend/package.json
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/common/interceptor/loader-interceptor.ts
discovery-frontend/src/app/common/service/common.service.ts
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/domain/dashboard/dashboard.ts
discovery-frontend/src/styles.css
discovery-server/src/main/asciidoc/application-config-guide.adoc
discovery-server/src/main/java/app/metatron/discovery/domain/properties/PropertyController.java

Displaying a preview of location data using mapbox in the data source column detail menu
**Related Issue** : #3907

#3907 datasource mapbox preview

---

discovery-frontend/src/app/dashboard/util/dashboard.util.ts

Fix global filter in dashboard of multi datasources with association
**Related Issue** : #4004 
See the issue #4004

Fix global filter in dashboard of multi datasources with association

---

discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java

Fix dashboard datasource replacement including widgets with chart filters
2. Create a widget with chart filters
3. Change the datasource
4. Check if the data source information of the filter has been changed.

Fix dashboard datasource replacement including widgets with chart filters

---

pom.xml

* Change pom.xml:810 & pom.xml:816 (http -> https)
**Related Issue** : #4021 
1. mvn clean install -DskipTest
No

Fix #4021 Maven build failure

---

README.md
discovery-distribution/bin/common.sh
discovery-distribution/bin/metatron.sh
discovery-distribution/docker/.dockerignore
discovery-distribution/docker/Dockerfile
discovery-distribution/docker/entrypoint.sh
discovery-server/pom.xml

Artifacts for dockerizing, including dockerfile for this project, need to be co-managed.
N/A
You can make an image by following these steps :
1. cd discovery-distribution
2. docker build -t discovery-test -f docker/Dockerfile
No, but you can run this image using your preferred arguments for docker.
ex) docker run -d -p 8180:8180 --name test discovery-test
Added some contexts in the main readme file.

Add a set for the dockerizing 

---

discovery-server/src/main/java/app/metatron/discovery/common/exception/GlobalExceptionHandler.java
discovery-server/src/main/java/app/metatron/discovery/common/exception/RestExceptionHandler.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardController.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/DashBoardService.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java

Add some more logs for changing datasources
2. Replace with a datasource that can be changed.
3. Check logs

Add some more logs for changing datasources

---

discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts

add undefined check for user custom field
**Related Issue** : #4035
1. create new chart widget (without user custom field)
2. create new user custom field.
3. If there is paging, you have to turn to the last page.

#4035 undefined check for customFields

---

discovery-server/pom.xml

This request is related to issue #4040.
#4040
Just compile and see the result.
- [ x] I have read the **CONTRIBUTING** document.
- [ x] My code follows the code style of this project.
- [ x] My change requires a change to the documentation.
- [ x] I have added tests to cover my changes.

Upgrade version of asciidoctor-maven-plugin from 1.5.3 to 1.5.8

---

discovery-frontend/src/app/workbook/workbook.component.ts

There is an error that the dashboard list is not updated.
As we continue to add dashboards, make sure the dashboard list is updated.

fix refresh dashboard list when it's not first load

---

discovery-frontend/src/app/common/component/select/select.component.ts
discovery-frontend/src/app/page/chart-style/color-option.component.html
discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.html
discovery-frontend/src/app/page/page.component.ts

1. Create a map chart using measure .
2. In the color settings, set the criteria to measure and change it to a custom color.
3. See if you can change the color range value.
- [x] Bug fix (non-breaking change which fixes an issue)

Fixed the error that the color setting range value could not be entered

---

README.md

Repair some broken links while migrating to new environments.

Move some links

---

discovery-frontend/src/app/common/component/chart/base-chart.ts
discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
discovery-frontend/src/app/common/component/chart/option/ui-option/ui-tooltip.ts
discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/gauge-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
discovery-frontend/src/app/common/component/chart/type/pie-chart.component.ts
discovery-frontend/src/app/common/constant/common.constant.ts
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.html
discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
discovery-frontend/src/app/dashboard/update-dashboard.component.ts
discovery-frontend/src/app/datasource/service/datasource.service.ts
discovery-frontend/src/app/page/chart-style/base-option.component.ts
discovery-frontend/src/app/page/chart-style/tooltip-option.component.html
discovery-frontend/src/app/page/chart-style/tooltip-option.component.ts
discovery-frontend/src/app/page/page.component.ts
discovery-frontend/src/app/workbook/workbook.component.ts
discovery-frontend/src/assets/css/metatron.css

1. Pie chart tooltip and chart label decimal point designation function
2. Insert a function or column name at the last cursor position of a user column
3. Chart color cannot be changed
1. When creating a pie chart, open the tooltip option and check if decimal point designation is possible.
2. When creating a user column, add and check the column name by which the cursor position has been moved in the formula input.
3. When creating a chart, change the order of the measures to see if the color of the chart changes.

Fix chart errors

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceProjections.java
discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetService.java

Fix NPE for changing datasource in dashboard
1. Create a dashboard with database datasource
2. Create a widget
3. Change the datasource to another database datasource

Fix NPE for changing datasource in dashboard

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java

Fix baseTime logic for KPI Chart
**Related Issue** : #4227

#4227 Fix baseTime logic for KPI Chart

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java

#4227 timerange filter error on kpi chart

---

discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java

add check logic for timeRangeFilter instance

#4227 instance check for timeRangeFilter

---

discovery-frontend/src/app/user/profile/change-password/change-password.component.ts
discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java

check previous password when password change
**Related Issue** : #4347

#4347 check password when change
