- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Snapshot 생성 중 취소를 위한 API(preparationsnapshots/{sanpshot_id}/cancel) 호출시,
running 중인 thread 들을 cancel 하고, snapshot의 상태를 canceled로 설정하도록 기능을 추가하였습니다.
> f#29-add_snapshot_cancelation_feature

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
FILE type dataset의 원본을 HDFS에 우선 저장하는 기능을 구현한 후,
snapshot 생성이 되지 않았던 문제.
Local file snapshot의 경우도 hadoop 설정을 해주도록 수정.
https://github.com/metatron-app/metatron-discovery/issues/73
I made a FILE snapshot after creating a FILE dataset on HDFS.
> #73 FILE snapshots also need hadoop configuration.

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/common/component/chart/type/bar-chart/bar-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/combine-chart/combine-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/line-chart/line-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/scatter-chart/scatter-chart.component.ts
마지막 저장시점의 데이터줌만 기억하여 차트 편집시 minmap on/off를 할 경우 위치가 리셋되어지는 오류를 수정합니다.
**Related Issue** : #64
- 축이 있는 차트를 그린 후 데이터줌의 크기 및 위치를 이동 합니다.
- 미니맵을 on/off하여 위치가 유지되는지 확인합니다.
> #64 chart zoom changing minimap on/off

- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.html
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board.component.html
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
* 대시보드 생성 시, association 설정 화면에서 가이드 화면을 추가합니다.
**Related Issue** : #3 
1. 대시보드 생성 화면을 띄웁니다.
2. 데이터소스 선택 팝업에서 복수의 데이터소스를 선택합니다.
3. (최초실행시) 가이드 화면에 표시되는지 확인합니다.
4. got it! 버튼을 클릭 시, 가이드 화면에 없어지는지 확인합니다.
5. 상단의 guide 버튼을 클릭했을 때, 다시 가이드 화면이 표시되는지 확인합니다.
> F#3 add guide connect multi ds

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
- discovery-frontend/src/app/common/data.preview.module.ts
* 워크스페이스 화면에서 데이터소스의 데이터 미리보기가 표시되지 않는 문제를 수정합니다.
**Related Issue** : #91  
1.  사용자 워크스페이스 화면에 접속합니다.
2. 상단 메뉴의 데이터소스 목록을 누르고, 표시되는 데이터소스 목록에서 하나의 데이터 소스를 선택합니다.
3. 우측에 표시되는 데이터소스 상세 정보에서 상단의 'Details' 버튼을 클릭합니다.
4. 데이터소스의 상세 정보가 표시되는 팝업이 정상적으로 표시되는지 확인합니다.
> #91 Datasource detail view of workspace doesn't work

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Util.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Snapshot 생성 실패 해결 및 전수 처리시 설정값 전달 코드 개선
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/99
File dataset -> File snapshot done.
StagingDB dataest -> File snapshot done.
File dataset -> Hive snapshot done.
StagingDB dataset -> Hive snapshot done.
개별 설정값들을 얻을 때 error를 내던 방식에서,
dataset, snapshot의 각 case들을 먼저 체크를 하고, (에러낼 것은 내고)
한번에 묶어서 전달하는 방식으로 바꿈.
> F#99 snapshot fail

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/resources/application.yaml
스냅샷 생성/취소 작업이 멀티 스레드로 실행될 때 생기는 문제점들을 개선.
https://github.com/metatron-app/metatron-discovery/issues/85
스냅샷 생성, 취소, 복수의 스냅샷 동시 생성 및 취소 작업에 대한 테스트 진행.
> F#85 make snapshot generating method thread safe

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-condition-input.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/extend-input-formula.component.ts
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/PrepRuleVisitorParser.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyOrcWriter.java
Hive-ORC 를 선택해 snapshot을 생성할 때 null 값이나 type mismatched인 row를 제거하도록 개선.
https://github.com/metatron-app/metatron-discovery/issues/110
Missing(null), Mismatched 값을 가진 dataset을 hive-ORC 규격으로 snapshot 생성.
1. 스냅샷 생성 성공.
2. null과 mismatched value가 있는 row가 결과에서 제거되어있음.
3. lineageInfo에 excludedLine 값이 기록됨.
> F#110 exclude mismatched rows in hive snapshot

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
편집 창에 들어가지 않고 스냅샷을 생성할 때, 서버 부팅 후 한번도 편집하지 않은 경우 에러 발생
스냅샷 생성 전에 RevisionSet 생성하도록 수정
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/66
서버 재부팅 후 편집 창에 들어가지 않고 스냅샷 생성 -> 성공함
> #66 build RevisionSet before snapshot generation

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Checking column names of Hive snapshots
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/121
I made Hive snapshots with Korean letter column names.
File snapshot succeeded, Hive snapshot failed. -> This is the right behavior.
The naming check comes before making a snapshot entity.
Some rules like pivot can produce columns which were not existed, so that we need to check again.
This comes just before sending CREATE TABLE.
> F#121 check hive naming rule

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
기존 수정본에 추가하여 Druid 내에서 쿼리 결과에 대한 처리 오류로 파생된  차트 표현 오류(Category 처리)를 수정하였습니다.
**Related Issue** : #102 
- 기존 Heatmap 오류 확인 외 Bar 차트내 행/열 차원값을 각각 1개씩 , 측정값 1개를 선반에 올려두어 차트가 잘 나오는지 확인합니다.
- 이후 데이터레이블/툴팁레이블에 Category Name/Value/Percentage 가 잘 표시되는지 확인합니다.
> #102 escape unexpected value in query result from druid

- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/BuiltinFunctions.java
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/Expr.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
1. substring함수의 사용 방법을 번경합니다.
: 현행 substring(text, start_index, end_index) >> substring(text, start_index, lenght)
: substring(text, start_index)사용을 허용합니다. 이때 start_index 부터 text의 끝까지 반환.
2. Snapshot Cancel 기능에서 상태 업데이트를 위해 JPA를 사용하도록 변경합니다.
3. Window rule의 rolling_sum()함수의 로직 변경.
https://github.com/metatron-app/metatron-discovery/issues/140
1. substring 함수
substring('hello world', 2) > 'llo world'
substring('hello world', 5, 2) > 'wo'
substring('hello world' -3) > 'rld'
2. snapshot cancel
preparing 상태로 비정상적으로 종료된 snapshot이 있는 상태에서 서버를 재시작한뒤 정상적으로 삭제되는지 확인.
3. window > rolling_sum
window value: [row_count(), rolling_sum(col1, 2, 3)] partition: col2 order: col3
테스트 결과 rolling_sum이 정상적으로 출력되는지 확인.
> F#140 data preparation function minor changes

- discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/embedded/dashboard/presentation-dashboard.component.ts
연관 차트가 설정되어 있는 대시보드의 경우 로딩바가 없어지지 않는 현상이 있습니다.
**Related Issue** : #144 
1. 대시보드를 생성한 후, 차트를 3개 생성합니다.
2. 대시보드 편집 화면의 차트 탭 하단에 있는 hierarchy 설정 버튼을 이용하여 차트 연관관계를 설정합니다.
3. 대시보드 편집을 저장하고 열람모드로 이동합니다.
4. 로딩바가 정상적으로 없어지는지 확인합니다.
> #144 bug fix - Dashboard loading bar is not hidden

- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.html
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-set-data-connection/db-set-data-connection.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/hive-set-connection.component.html
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
DB type, Server가 DB connection이라는 명칭으로 통합됨
커넥션 프리셋 선택시, 해당 프리셋의 데이터베이스의 타입이 잘 보이지 않는 상태 개선
커넥션 프리셋 선택시, URL only 가 비활성화 상태인것을 사용자가 인지할 수 없는 점을 개선  
https://github.com/metatron-app/metatron-discovery/issues/143
데이터 커넥션 > 커넥션 생성 > url타입과 host/password 타입의 커넥션 생성
```
// mysql
host: localhost
port: 3306
URL: jdbc:mysql://localhost:3306
// hive
host:localhost
port:10000
URL:jdbc:hive2://localhost:10000
```
데이터 커넥션 > 커넥션 수정 > 해당 커넥션 db 타입 비활성화 상태 확인
데이터 소스 > 데이터베이스로 생성 > 커넥션 설정 > 해당 커넥션 프리셋 선택 > URL 설정 비활성화 상태 확인
메타데이터 > HIVE로 생성 > 커넥션 설정 > 해당 커넥션 프리셋 선택 > URL 설정 비활성화 상태 확인
> #143 change css in connection

- discovery-frontend/src/assets/css/polaris.v2.page.css
Percentile menu 가 이상하게 보이는 부분을 수정합니다.
**Related Issue** : #148 
차트 편집화면에서 Measure > Aggregate > Percentile 메뉴의 화살표 방향이 올바른지 확인합니다.
> #148 Fix percentile menu bug

- discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
- discovery-frontend/src/app/domain/workbook/configurations/filter/inclusion-filter.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilter.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilterTest.java
* 필터 편집화면에서 지정된 정렬 정보가 필터 패널에 전달 되지 않고 초기화 됩니다.
* 대시보드내 Dimension 필터 항목에 대한 정렬정보가 저장이 되지 않고 초기화 됩니다.
**Related Issue** : #153 
1. 대시보드 편집화면으로 이동합니다.
2. 신규 필터 추가 팝업을 오픈합니다.
3. Dimension 필드에 대해서 필터 추가를 선택하고, 필터 설정 화면에서 정렬 방식을 변경합니다.
4. 변경된 정렬 방식에 따라 필터 패널과 필터 위젯의 목록이 표시되는지 확인합니다.
5. 저장한 이후에 변경된 정렬 방식이 유지되는지 확인합니다.
> #153 The sorting method of the filter is initialized without saving

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.ts
Fixed parameter when row condition (Use only under the following conditions) is blank.
Originally `row:undefined` to not sending `row:` at all
#190 
'SET'룰을 적용할 때 컨디션(다음 조건에서만 수행) 이 입력되지 않았을 때 `row: undefined`를 보내고 있지 않은지 확인,
편집 후 적용 시 undefined error 가 나는지 확인
> #190 fix parameter when row condition is blank

- discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.html
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
메타데이터 상세화면의 컬럼 스키마 탭에서 글자가 길어질 경우 다른 컬럼을 침범하는 것을 수정함
글자가 길 경우 말 줄임으로 변경하고 툴팁을 추가함
#162 
메타데이터 생성 > 데이터소스로 생성 > 메타데이터 상세화면 > 컬럼 스키마 탭 > 윈도우 가로넓이 줄여서 컬럼 확인
> #162 fix table header

- discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
* 대시보드 생성시 데이터소스를 선택하는 리스트에서 상세 정보에 뜨는 메타데이터 내용이 잘못 표시 됩니다.
**Related Issue** : #166 
1. 워크북으로 이동합니다.
2. 좌측 하단의 대시보드 생성 버튼을 클릭합니다.
3. 대시보드 생성 화면에서 데이터소스 추가 버튼을 클릭합니다.
4. 데이터소스 목록 중 하나를 클릭했을 때, 우측에 표시되는 데이터소스 상세 정보에서 메타데이터 정보가 정확히 표시되는지 확인합니다.
> #166 metadata information is incorrect on data source when creating dashboard

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/converter/common-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/define/common.ts
- discovery-frontend/src/app/common/component/chart/option/util/option-generator.ts
- discovery-frontend/src/app/common/component/chart/type/gauge-chart/gauge-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/heatmap-chart/heatmap-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/treemap-chart/treemap-chart.component.ts
- discovery-frontend/src/app/page/chart-style/color-option.component.html
- discovery-frontend/src/app/page/chart-style/color-option.component.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
- gradient를 배분을 제대로 못하는현상 발생 => 숫자포맷에서 설정된 소수점을 적용하여 색상배분이 제대로 되게 수정
- 색상 저장 후 로드시 저장된 색상이 반영되지 않은 에러 수정
- 색상 input 항목을 우측정렬, 숫자포맷의 천단위 구분자에 따라 설정
**Related Issue** : #58 
- 숫자포맷에서 설정한 decimal place가 제대로 설정되는지 확인
- decimal place가 적용된 상태로 색상 설정을 추가 / 수정시 잘 동작하는지 확인
- 색상 저장 후 저장된 색상 반영되는지 확인
- 숫자포맷의 천단위 구분자의 on / off에 따라서 색상 input에 반영되는지 확인
> F#58 incorrect color gradation

- discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
- discovery-frontend/src/app/dashboard/service/widget.service.ts
- discovery-frontend/src/app/page/page.component.ts
* 차트 위젯 복사후 복사된 위젯에 선반의 컬럼을 변경하면 로딩이미지가 사라지지 않습니다.
**Related Issue** : #151 
1. 대시보드 편집 화면으로 이동합니다.
2. 신규 차트 생성 버튼을 클릭합니다.
3. 신규 차트를 생성합니다. (ex. 바차트 - Sub Category - Sales )
4. 대시보드 편집 화면에서 차트를 복제합니다.
5. 복제된 차트를 수정합니다. ( ex. LineChart, OrderDate )
6. 차트를 저장합니다.
7. 정상적으로 대시보드 편집 화면에 표시되는지 확인하고, 대시보드가 정상적으로 저장되는지 확인합니다.
> #151 Loading image error when saving after changing column of shelf in copied widget 

- discovery-frontend/src/app/workspace/workspace.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/catalog/CatalogTreeService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookTreeService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workspace/BookRestIntegrationTest.java
* 워크스페이스에서 폴더 내 워크북을 삭제했을 때, 실제 워크북의 개수와 좌측 상단에 표시되는 개수가 다른 경우가 있습니다.
* 상단 로고를 클릭했을 떄 요약 정보 영역이 표시되지 않는 경우가 있습니다.
**Related Issue** : #48 #186 
1. 워크스페이스 내 폴더로 이동합니다. 
2. 폴더 내에 있는 워크북을 하나 삭제 합니다. 
3. 좌측 상단에 워크북 개수가 삭제된 것 만큼 변경되었는지 확인합니다.
4. 상단 로고를 클릭합니다.
5. 워크스페이스 화면이 정상적으로 표시되었는지 확인합니다.
> #48 Errors of disappearing summary areas and deletion errors in the workspace

- discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
- 색상모드를 measure로 설정 후 crossing point를 설정하면 전체색상이 지정된 값 범위게 맞게 동작하지않음
**Related Issue** : #65 
- color by measure로 설정시 crossing point에 값을 설정 후 범위에 맞게 색상이 설정되었는지 확인
- 저장 후 재조회시 설정된값에 맞게 색상이 설정되었는지 확인
> F#65 When I change crossing point value of area-line chart, measure based color distribution doesn't work

- discovery-frontend/src/app/page/page.component.ts
멀티데이터소스 대시보드의 차트 편집 화면에서 차트의 대상 데이터소스를 변경할 경우 차트 이름이 초기화 되는 현상을 수정합니다.
**Related Issue** : #227 
1. 멀티데이터소스로 생성된 대시보드의 편집화면으로 이동합니다.
2. 신규 차트 생성 화면으로 이동합니다.
3. 상단의 차트 이름을 수정합니다.
4. 좌측 데이터소스 목록에서 다른 데이터소스로 선택합니다.
5. 작성했던 차트 이름이 초기화 되는지 확인합니다. (초기화가 안되어야 정상)
> #227 Fix error chart name initialize

- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.html
- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
- discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.html
- discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.ts
* 다중, 모든 값을 다 선택한 필터 값을 위젯으로 올렸을때, Select box에 'object object...'라는 레이블이 찍히는 현상
**Related Issue** : #215 
1. 대시보드 편집화면에서 우측의 필터 패널 열어 필터 추가 버튼을 클릭합니다.
2. 문자 타입의 차원값 필드를 선택하고, 여러건 선택 타입으로 필터를 추가합니다.
3. 기본값을 All 로 선택합니다. 
4. 해당 필터를 대시보드에 배치하여 표시되는 라벨이 정상적인지 확인합니다. 
5. 대시보드를 저장하고, 열람화면에서 필터 위젯을 값을 변경하면서 필터 위젯의 라벨이 정상적으로 표시되는지 확인합니다.
> #215 An error that caused the label to be incorrect when the filter value is uploaded to the widget

- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
검색 질의 처리시 유효한 컬럼인지 확인하는 과정에서 패턴 매칭을 수행합니다. 
이때 Regexp 에서 사용하는 문자 (ex . + * ? ( ) [ ] { } ^ $)  가 포함된 경우 정삭적으로 escape가 되지 않아 
컬럼유효성 체크에서 오류를 발생시킵니다.
**Related Issue** : #218 
1.  Workbook > Dashboard 를 생성합니다. 
2. Dashboard 생성 후 차트 위젯을 생성합니다. 
3. 데이터 소스 패널에서 사용자 정의 필드를 생성하는 (+) 버튼을 클릭합니다. 
4. 사용자 정의 필드 명에 위에서 언급한 문자를 포함한 필드명을 구성합니다. 
4-1. expression 은 간단히 기존 있는 필드 명을 기입합니다. (ex. Sales)
5. 사용자 정의 필드 를 사용하여 차트가 정상적으로 생성되는지 확인합니다.
ex. BarChart , 행 : Category, 교차  : 사용자 정의 필드
> #218 escape column name with regular expression character

- discovery-frontend/src/app/dashboard/filters/component/time-range.component.html
- discovery-frontend/src/app/dashboard/filters/component/time-range.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.html
- discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.html
- discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
* 대시보드에 타임 필터에 대한 필터 위젯의 표현 방식이 개선되어야 함
** 타임 필터의 버튼 방식일 경우 너비에 따라 라벨이 달라져야 함
** 시간 범위 선택 방식일 경우 상/하 배치가 아닌 좌/우 배치도 필요함
* 필터 위젯의 스크롤 영역이 필터에 따라 상이하게 표현됨
**Related Issue** : #196 
1. 대시보드 편집 화면에서 타임스탬프 타입의 필드에 대한 필터를 추가합니다.
2. 해당 필터를 대시보드에 배치합니다.
3. 우측 필터 패널에서 relative 타입으로 변경한 후, 위젯의 너비를 변경하였을 때 너비에 따라 라벨이 변경되는지 확인합니다.
4. 우측 필터 패널에서 specific 타입으로 변경한 후, 위젯의 너비를 변경하였을 때 너비에 따라 입력바의 배치가 변경되는지 확인합니다.
> #196 Improve usability of the dashboard's time filter widget

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
유니온 팝업내 css 수정 
- 마스터 데이터 셋과 추가될 데이터 셋 영역에 두 개의 스크롤이 생기는 문제
- 마스터 데이터 셋과 추가될 데이터 셋을 높이가 다른 문제
#232 
한 페이지에 스크롤은 하나만 나올 수 있도록 마크업 수정,
마스터 데이터 셋과 추가될 데이터 셋 높이 수정
> #232 union css error

- discovery-frontend/src/app/common/component/chart/option/converter/color-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/define/common.ts
- discovery-frontend/src/app/common/component/chart/type/grid-chart/grid-chart.component.ts
- discovery-frontend/src/app/page/chart-style/color-option.component.ts
- discovery-frontend/src/app/page/page.component.ts
- 그리드차트에서 색범위가 반대로 편성됨
- 그리드차트의 최소값설정이 0으로 설정됨
**Related Issue** : #149 
- 그리드차트의 색상 그라데이션 표현시 색표현이 설정한 범위대로 적용되는지 확인
- 그라데이션에서 그리드차트의 최소값이 제대로 적용되는지 확인
> #149 fix incorrect gradient color in grid

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadAsyncConfig.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetSparkHiveService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepHdfsService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepPreviewLineService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
데이터셋 파일 업로드시 비동기 API 제공함.
스프링의 잔여파일 남기지 않음. (HDFS 복사 후 잔여파일 제거는 #264 이슈에 맞추기 위해 다음 이슈로 넘겨짐)
디렉토리 없는 경우 생성하는 것 확인. (부모 디렉토리에 권한이 없는 경우는 예외)
[#252](https://github.com/metatron-app/metatron-discovery/issues/252)
POST /api/preparationdatasets/upload_async {MULTIPART}
POST /api/preparationdatasets/upload_async_poll {filekey}
에 Json {filepath,filekey,filename} 응답하면 성공.
UI에서 테스트 호출 발생시키고 응답확인후 테스트 API 제거함.
- 임시 디렉토리에 생성되는 upload*.tmp 파일은 사용후 삭제되는 것 확인함.
- 설정경로/uploads 디렉토리 없을때 생성되는 것 확인 함.
> #252 async api to upload file dataset

- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.ts
데이터 커넥션 목록의 커넥션 타입이 커넥션 타입 필터링 목록과 문구가 상이하게 나오는것 수정
#143 
1. 데이터 커넥션 생성 > 생성
2. 데이터 커넥션 > 목록에서 1에서 생성한 커넥션 타입이 올바르게 출력되는지 확인
> #143 fix db type in connection

- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- 차트 편집화면에서 좌측의 데이터소스 변경시 기존 차트의 선반 animation이 남아있음
**Related Issue** : #227 
- dashboard 생성시 여러개의 datasource를 선택하여 생성하고,
선반에 dimension / measure를 기존 길이보다 길어지게 생성후, 
datasource를 변경시 animation이 해제되는지 테스트합니다.
> #227 fix animation bug when datasource is changed

- discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
- discovery-frontend/src/app/page/page-data/page-data-context.component.html
- discovery-frontend/src/app/page/page-data/page-data-context.component.ts
* 위도/경도 타입에 대한 메타데이터 정보가 약어로 표시되고 있습니다.
**Related Issue** : #221 
1. 메타데이터 화면으로 이동합니다.
2. 데이터소스에 대한 메타데이터를 생성하고, 상세 화면으로 이동합니다.
3. 특정 필드에 대한 논리형식을 위도/경도로 설정합니다.
4. 대시보드 편집 화면으로 이동합니다.
5. 신규 차트 생성 버튼을 클릭하고 좌측의 필드 목록을 확인합니다.
6. 필드 중 메타데이터의 논리형식을 위도/경도로 지정한 필드의 툴팁을 확인하여 위도/경도가 정상적으로 표시되는지 확인합니다.
> #221 Fix metadata tooltip error

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- 바차트에서 color by series로 선택 후 custom color setting 색설정 후 저장 후 조회시 반영이 되지않는 오류발생
**Related Issue** : #307 
- 바차트를 선택 후 선반에 dimension / measure를 한개씩 올리고 color by series에서 custom color setting에서
색상을 설정 후 차트를 저장 후 재조회시 설정된 색상으로 반영되었는지 확인하였습니다.
> #307 fix custom color setting error in bar

- discovery-frontend/src/app/page/chart-style/calrow-option.component.html
- discovery-frontend/src/app/page/chart-style/calrow-option.component.ts
* 연산행 설정 패널에서 '연산자 선택' 부분이 저장 후 다시 편집하려고 하면 초기화(합계) 되어 있는 현상
**Related Issue** : #262 
1. 그리드 차트를 생성합니다.
2. 오른쪽에 연산 행 설정 탭을 펼칩니다.
2. '연산자 선택'을 '평균'으로 변경합니다.
3. 차트와 대시보드를 저장 후 다시 차트를 편집합니다.
4. 연산행 설정 탭에서 '연산자 선택'이 이전에 설정한 값으로 표시되는지 확인합니다.
> #262 fix error setting of initial value of operating panel

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
계산식 필드 팝업에 '추천 컬럼' 영역에 모든 데이터소스 안 컬럼이 보이지 않고, 특정 컬럼은 빠져 있는 현상
**Related Issue** : #314 
1. 차트 생성 화면을 띄웁니다.
2. 필드 목록 상단의 계산식 필드 팝업 버튼을 눌러 팝업을 띄웁니다.
3. 팝업 내 필드 목록에서 필드 누락이 없는지 확인합니다.
> #314 fix error where field list paging

- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page.component.ts
- 차트 타입 UI가 안보이는 현상 발생
**Related Issue** : #315 
1. 차트페이지에서 차원값 1개 측정값 여러개를 설정합니다.
2. 측정값의 aggregation을 변경합니다.
3. 차트를 저장 후 재조회시 차트타입 UI가 깨지지 않는지 확인합니다.
> #315 chart type ui is not visible

- discovery-frontend/src/app/common/service/abstract.service.ts
- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/page/page.component.html
- discovery-frontend/src/app/page/page.component.ts
차트를 그릴 수 없는 상황일 때
차트와 대시보드 편집 화면의 차트 영역에 아무것도 나타나지 않아서 사용자가 어떤 상황인지 알수 없습니다.
**Related Issue** : #346 
1. 대시보드를 생성합니다. ( 테스트는 sales datasource를 이용하여 진행함 )
2. 라인 차트를 생성하고 예측선 기능을 추가합니다.
( 테스트 예 > dimension : OrderDate ( Granularity : year ) / measure : sales / 예측선 추가 => 오류가 나는 상황을 만들기 위한 설정 )
3. 차트 화면에 '데이터를 표시할 수 없음'이 표시되어야 합니다.
4. 차트를 저장합니다.
5. 대시보드 편집화면에서 차트 위젯에 '데이터를 표시할 수 없음' 이 표시되어야 합니다.
> #346 No error message when the chart can not be loaded

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
한글자판으로 룰 명령어를 타이핑 하였을 때 영문 룰이 검색되도록 변경
#365 
MANAGEMENT>Data Preparation>Dataflow 
데이터플로우 상세 룰편집 화면에서 명령어입력-명령어 부분 한글자판으로 영문 명령어를 타이핑하여 검색리스트를 확인
> F#365 display rule command in case of hangul typing

- discovery-frontend/src/app/common/component/chart/type/label-chart/label-chart.component.ts
- discovery-frontend/src/app/page/chart-style/common-option.component.ts
- discovery-frontend/src/app/page/chart-style/secondary-indicator.component.ts
KPI차트에서 Aggregation type이 다른 동일한 Pivot의 설명 및 아이콘을 개별 컨트롤할때 같이 변경되는 증상을 해결합니다.
**Related Issue** : #355
1. 차트 생성화면으로 이동합니다.
2. 동일 Measure를 Aggregation type이 다르게 두개 선택합니다.
3. 공통옵션 패널에서 Icon 사용 체크 후 하나의 Measure를 개별 선택합니다.
4. 아이콘 변경시 두개의 pivot이 각각 적용이 되는지 확인합니다.
> #355 KPI chart same pivot error

- discovery-frontend/src/app/workbench/workbench.component.ts
쿼리 입력 후 엔터키를 이용해 line을 추가할 경우 indent 위치가 정상적이지 않은 현상
**Related Issue** : #407 
1. 워크벤치 화면으로 이동합니다.
2. 여러줄 쿼리를 입력합니다. ( 아래의 쿼리는 입력 예시 )
select part_hour, count(distinct(user_key))
–- select *
FROM tmap.log_channel
where (part_hour >= '2018080100')
and terminal_code = '010121'
group by part_hour;
3. 엔터키를 입력합니다.
4. 자동으로 들여쓰기가 적용되지 않고 커서가 다음줄 앞으로 이동하는지 확인합니다.
> #407 workbench editor indent error

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
- discovery-frontend/src/app/common/component/chart/type/bar-chart/bar-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/combine-chart/combine-chart.component.ts
- discovery-frontend/src/app/common/component/chart/type/line-chart/line-chart.component.ts
- discovery-frontend/src/app/page/chart-style/datalabel-option.component.ts
- discovery-frontend/src/app/page/chart-style/labelbase-option.component.ts
- combine차트에서 measure가 복수개로 올라갈때 바 / 라인차트와 동일하게
데이터레이블과 툴팁에서 Category Value / Percent를 disable 처리합니다.
**Related Issue** : #391 
1. 차트상세화면에서 combine차트를 선택합니다.
2. dimension 1개와 measure2개를 설정시 데이터레이블과 툴팁에서 Category Value / Percent가 disable 처리가 되는지 확인합니다.
> #391 Displaying combo chart data is different from engine data

- discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.ts
모든 컬럼 인기도가 0인경우 정렬시 정렬이 작동하는 것 수정
#422 
메타데이터 > 모든 인기도가 0인 메타데이터 상세화면 > 컬럼 스키마
인기도 정렬 시도 > 컬럼이 바뀌지 않는것 확인
> #422 fix sorting popularity

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
Window 룰에 lag와 lead 함수를 추가합니다.
Add lag and lead function on window rule.
https://github.com/metatron-app/metatron-discovery/issues/374
Test below command on data preparation.
window value: [row_number(), max(column4), lag(column4, 2), lead(column4, 2)] partition: column2, column3 order: column1
> #374 Add lag and lead functions

- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/BuiltinFunctions.java
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/Expr.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
Preparation에 contains() 함수를 추가합니다.
Add contains() function to preparation.
ex) contains('hello world', 'world') > true.
All arguments should be string or string column.
https://github.com/metatron-app/metatron-discovery/issues/469
Test below rules in data preparation.
1. set col: column1 value: contains(column1, 'text')
>result will be true or false
2. set col: column2 value: 'it contains' row: contains(column1, 'text')
> #469 Add contain() function in data prep

- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/Window.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
Resolve these inconveniences in window rule.
Change label of "Grouping column" value from partition to group.
Drop dummy column that generated automatically when there's no grouping column.
https://github.com/metatron-app/metatron-discovery/issues/481
Try test codes below
1. window value: [row_number(), rolling_sum(col1, 2, 2)] group: col2 order: col3
2. window value: [avg(col1), lead(col1, 3)] group: order: col3
> F#481 improve window rule in data preparation

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/HiveTableInformation.java
StagingDB로 데이터소스를 생성할때 delimiter가 탭인 테이블일 경우 에러 발생함.
An error occurs when delimiter is a tabbed table when creating a data source with StagingDB.
**Related Issue** : #518 
1. http://52.231.189.217:8080/app/v2/index.html
2. create datasource from StagingDB
3. choose schema 'omniture', table 'omnitureslogs'
4. create datasource complete.
5. Check the state of the created datasource is an enable.
> #518 tab delimiter string convert to character

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/OracleConnection.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/PrestoConnection.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/TiberoConnection.java
removed @NotNull annotation for URL only option (Presto, Oracle, Tibero)
#449
1. MANAGEMENT > Data storage > Data Connection
2. Click 'Create new Data Connection'
3. choose PRESTO
4. choose 'URL only'
5. input url : 'jdbc:presto://localhost:8080/hive'
6. input user : hive, password : hive
7. Click 'Save'
8. successfully saved.
> F#449 catalog not required when presto

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.model.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
apply current rule index at scroll down in the main grid of Dataprep
modify by proper column size
#476 
#486 
#515 
1. select wrangle data [Annual Revenue Data 2013-2016.xlsx](https://github.com/metatron-app/metatron-discovery/files/2509337/Annual.Revenue.Data.2013-2016.xlsx)
2. Click "Edit rules"
3. add delete command
4. Scroll down
5. Verify that delete command has been applied, 
Verify  that the same result is repeated
Check that the proper column size is displayed
> F#476 fetching grid over over

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
When creating a Hive table with ORC format, all column names become lowercase.
If column names become duplicated in this process (when only the letter cases were different), you'll get an exception.
_ORC format으로 이루어진 Hive table을 만들 때에는 column 이름들을 모두 소문자화하도록 했습니다.
이 과정에서 중복되는 이름이 생기는 경우(원래 대소문자만 달랐던 경우)에는 exception을 발생시키도록 했습니다._
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/530
I've made a Hive table in ORC format and I could see all the contents.
> #530 lower column names for Hive tables in ORC format

- discovery-frontend/src/app/common/service/abstract.service.ts
- discovery-frontend/src/app/workbench/service/workbench.service.ts
- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
로그 출력 시 스크롤이 아래로 이동하지 않는 현상과 쿼리 실행 종료시간이 출력되지 않는 문제가 있습니다.
sql beautifier 버튼의 아이콘이 잘려서 표시되는 현상이 있습니다.
**Related Issue** : #563 
1. Hive Connection으로 생성된 워크벤치 메뉴로 이동합니다.
2. 쿼리를 실행합니다.
3. 로그가 출력되면서 스크롤이 내려가는지 확인합니다.
4. 쿼리 실행 종료 후 종료 시간이 정상적으로 표시되는지 확인합니다.
5. sql beautifier 버튼에 마우스를 올렸을 때 정상적으로 표시되는지 확인합니다.
> F#563 scrolling issue show end time

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfMove.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfReplace.java
Theres two kinds of bug in move and replace rule.
1. When move rule is applied nameIdxs[] in Row object is mixed, so you can't get right value from row with column name.
2. In DfReplace source code, variables that named "rows" and "this.rows" are used confusingly. So it might be cause snapshot creating failure.
So, corrected these 2 errors.
https://github.com/metatron-app/metatron-discovery/issues/595
1. Apply move rule to a column.
2. Apply other rule to the column.
3. It might be success.
4. Apply replace rule.
5. Create snapshot.
6. It might be success.
> Fix errors on replace and move rules in preparation

- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/app/workbench/workbench.module.ts
편집중에 브라우저 뒤로가기 버튼을 눌렀을 경우 바로 화면에서 벗어나기 전에 확인을 거치는 과정이 필요합니다.
**Related Issue** : #609 
1. 워크벤치 화면의 띄웁니다.
2. 브라우저 뒤로가기 버튼이나 새로고침 버튼을 누릅니다.
3. 화면을 바로 벗어나지 않고 확인창이 뜨는지 확인하고 확인을 누른 후에 벗어나는지 확인합니다.
> #609 Show notifications when browsing back

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/app/workbench/workbench.component.ts
에디터탭 추가 시 자동 이름 설정에서 숫자 지정에 대한 정책을 개선합니다.
**Related Issue** : #608 
1. 워크벤치 화면을 띄웁니다.
2. 에디터 탭 추가 버튼을 클릭합니다.
3. 에디터 탭의 이름뒤에 붙는 숫자가 현재 에디터 탭의 갯수 혹은 기존에 생성된 탭의 번호 중 큰 수의 다음 수로 생성되는지 확인합니다.
> #608 Improved editor name automatic naming policy

- discovery-frontend/src/app/page/chart-style/common-option.component.html
- discovery-frontend/src/app/page/chart-style/secondary-indicator.component.html
KPI 차트의 공통 설정에서 아이콘/설명 기능에 대해서 On 으로 변경해도 클릭할 수 없어 기능을 사용할 수 없습니다.
**Related Issue** : #634 
1. 대시보드를 생성합니다.
2. 차트 생성 화면으로 이동합니다.
3. KPI 차트를 선택하고 measure 를 하나 선반에 올립니다.
4. 우측의 공통 설정 탭을 열고 그래픽 아이콘 사용을 On 으로 변경합니다.
5. 버튼들이 클릭되는지 확인합니다.
> #634 Can not click common settings of KPI charts

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Util.java
When importing CSV file, if last column contains only single quote character and nothing else. Then a parsing error occurs.
This commit will makes CSV parsing function can handle single quote.
And additionally, improve CSV file preview quality. Now Preview check first 100 rows column type, not only first row.
https://github.com/metatron-app/metatron-discovery/issues/625
[고양이.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2537509/csv.txt)
(Remove ".txt" from filename)
1. Create dataset with attached CSV file and check if it success.
2. Create dataset with various CSV files that contains various column types.
> F#625 unpaired single quote in csv file causes error when importing

- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/ExprEval.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
If you enter function expression on condition field of keep/delete rule, it makes error.
Keep and delete rules are converted as filter(), and filter() uses Long.longValue function.
longValue() function is used for convert result of condition expression as long value.
But when condition expression returns boolean, longValue() function cannot cast it as long.
So change longValue () to the asLong () function, which can handle boolean input.
https://github.com/metatron-app/metatron-discovery/issues/638
Try this on preparation.
1. Keep/Delete rule condition with true
2. Keep/Delete rule condition with false
3. Keep/Delete rule condition with contains(column_name, 'txt')
> Make longValue function can cast boolean as 0 or 1

- discovery-server/src/main/resources/schema-mysql.sql
Our ddl schema has an error in mySQL > 5.7
It caused by mysql strict mode and we have to set default value of timestamp columns.
#567 
1. Initialize discovery app with mysql-default-db option.
2. All tables created without MySQLSyntaxErrorException.
> DDL error when init with mySQL

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
Now, if the column value is an empty string, it's not classified as a missing value, but as a matched value in the histogram.
_이제 column value가 empty string인 경우, histogram에서 더이상 missing이 아닌 matched로 분류됩니다._
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/621
Tested with the case in the related issue.
> #621 empty strings are not treated as missing values

- discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.service.ts
- discovery-frontend/src/app/data-preparation/dataset/detail-dataset/dataset-detail.component.ts
- discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDataset.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetProjections.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepHdfsService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepPreviewLineService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
1. Create and use GET datasets controller without using jpa repository
2. If the preview does not exist, it creates a new preview and returns it.
[#569](https://github.com/metatron-app/metatron-discovery/issues/569)
1. create a dataset
2. get the dataset with the option that the projection is detail
3. if the dataset has a preview grid, that is ok
> F#569 dataset preview on demand

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRule.java
the rule string field length is 4000.
sometimes this is not enough.
so we changed the type of rule string from 4000 chars to text.
[#585](https://github.com/metatron-app/metatron-discovery/issues/585)
1. create new dataset
2. make a dataflow with the dataset
3. create a wrangled dataset
4. edit the rules of that
5. add a rule longer than 4000. 
ex) set column with value 'xxx(over 4000)...'    
if the rule was successfully created. that is Ok
> #585 increase the size of the rule string field

- discovery-frontend/package.json
- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/common/service/image.service.ts
대시보드 목록에서 맵뷰영역은 표시되지 않는 현상이 있습니다. 
**Related Issue** : #617 
1. 대시보드를 생성하고, 맵뷰를 하나 생성합니다.
2. 대시보드를 저장하여 대시보드 목록에서 해당 대시보드의 이미지가 정상적으로 표시되는지 확인합니다.
> #617 Map chart does not appear on dashboard preview

- discovery-frontend/src/app/workbench/workbench.component.html
에러 메시지가 길 때 스크롤이 표시되지 않습니다.
**Related Issue** : #676 
1. Hive 워크벤치를 실행합니다.
2. 하단 결과 영역을 디바이드 바를 이용해 최대한 줄입니다.
3. 긴 에러가 표시될 수 있는 쿼리를 실행합니다.
```
SELECT * FROM default.testtesttetesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttestt …
```
> #676 If the error message is long on the workbench, no scroll bar generated

- discovery-frontend/src/app/data-storage/component/schema-detail/schema-detail.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.ts
데이터소스 생성 단계중 컬럼을 선택후 TIMESTAMP 형식으로 변경하면 스크립트 에러나는것 수정
- 컬럼의 데이터가 있는경우
- 컬럼의 데이터가 없는경우
#644 
1. 데이터소스 생성
2. 데이터소스 config 단계에서 컬럼을 체크후 체크된 컬럼 TIEMSTAMP로 타입변경 
3. 변경된 타입 확인
> #644 fix type change error datasource

- discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
멀티 데이터소스에서 타임스탬프 필터 중복해서 등록되는 현상이 있습니다.
**Related Issue** : #672 
1. 대시보드를 생성합니다.
2. 대시보드 편집화면에서 필터 패널을 엽니다.
3. 중복된 필터없이 정상적으로 필터가 표시되는지 확인합니다.
> #672 Error where multiple timestamp filters are registered in a multi data source

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
Originally grid information was requested every time user clicks on the sheet button.
Now grid information is returned with an array so the user doesn't need to wait for the server response 
every time user clicks on the sheet button.
#543 
Go to create dataset by file (excel)
Make sure excel file has at least two sheets
Click on the sheets, check if grid is shown without delay
> F#543 response grids of excel at once

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepPreviewLineService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Fixed an issue where loading and cloning could not be done with broken rules.
In the following cases, loading and cloning of broken rules will occur.
* Uploaded file change / destruction
* Dataset swapping to unmatched schema
* Server rebooting
* Binary patch which changed the behavior (This case was the problem recently. We used to put "_" instead of the space character. Now I have changed to use the space as it is.)
_Broken rule이 있는 경우 loading, cloning이 안되던 문제를 해결했습니다.
다음의 경우에 broken rule에 대한 loading, cloning이 벌어집니다._
* _Uploaded file 변경/훼손_
* _Schema가 다른 dataset으로 swapping_
* _서버 재기동_
* _동작이 바뀐 binary patch (이번에 문제가 된 경우. 공백대신 _를 넣던 것을 그냥 공백을 컬럼명으로 사용하게 했음)_
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/690
Honestly, the following is the best way:
1. …
> F#690 suppress exceptions from broken rules

- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- 워크벤치 쿼리 에디터에서 "Delete" 클릭 시 경고 문구 없이 쿼리 내용 전체가 삭제되며, 삭제 후 복구할 방법이 없음
- "Edit name" 버튼을 누르려다가 실수로 "Delete" 버튼을 누르는 사례들이 발생됨
- Notification 을 통해 확인을 거진 후 삭제하는 것이 필요함
**Related Issue** : #654 
1. 워크벤치로 이동합니다.
2. 에디터 탭을 1개 이상 생성합니다.
3. 생성한 에디터 탭 중 하나를 선택하여 삭제 버튼을 클릭합니다.
4. 바로 삭제되지 않고 확인창이 나타나는지 확인합니다.
> #654 Show notification when you click 'Delete' in workbench editor

- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table-info-schema/detail-workbench-table-info-schema.html
테이블 컬럼 정보 에서 컬럼사이즈가 있을경우만 보여지도록 수정합니다. 
**Related Issue** : #708  
1. Presto 워크벤치 화면으로 이동합니다. 
2. 테이블 컬럼 정보 화면, 스키마 브라우저의 컬럼 탭으로 이동합니다. 
3. 컬럼명만 표시되는지 확인합니다. 
4. Hive 워크벤치로 이동합니다.
5. 테이블 컬럼 정보 화면, 스키마 브라우저의 컬럼 탭으로 이동합니다. 
6. 컬럼명과 컬럼사이즈가 같이 표시되는지 확인합니다.
> #708 table column size exception handling

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
we did not support to download HDFS type snapshots.
now it can.
[#709](https://github.com/metatron-app/metatron-discovery/issues/709)
1. create a dataset
2. create a dataflow
3. edit the rules of the dataset
4. make a snapshot of 'HDFS type'
5. see the details of snapshot
6. click download CSV
if a CSV file is downloading, it is ok
> F#709 enable download hdfs snapshot

- discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.html
멀티레이어 구조에서 사용성에 대한 기획 정비가 필요하고, 
안정성이 보장되지 않고 있어 이에 대한 개선이 될때까지 레이어 추가 버튼을 제거합니다. 
**Related Issue** : #720 
차트 위젯에서 맵뷰 선택후 레이어 우측 "+" 버튼이 보이지 않습니다.
> #720 Remove layer add button

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/app/workbench/workbench.component.ts
워크벤치 에디터 창에서 스크롤 두개가 발생합니다. 
**Related Issue** : #730  
2. 에디터 화면에 스크롤이 생성되게 입력을 한 후, 다른 화면으로 이동합니다. 
3. 다시 워크벤치 화면으로 진입하여 추가 텍스트를 입력 후 스크롤이 하나만 생성되어 작동하는지 확인합니다.
> F#730 fixed editor screen scroll error

- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/Expr.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
When csv file has null contains columns, dataset preview is not displayed.
Dataset preview should be always displayed.
https://github.com/metatron-app/metatron-discovery/issues/701
Create dataset with attached csv file.
Dataset preview will be displayed.
[cat.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2575421/cat.csv.txt)
> #701 Fix null point exception when some rows has null contained columns

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
Broken rule colour should be red 
#749 
Go to dataflow detail -> click wrangled data -> see dataflow panel -> check if broken rule is coloured red
> #749 colour rule in red when rule is broken (dataflow panel)

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetSparkHiveService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Sometimes, canceling snapshot creation fails because snapshot has already been created.
When this commit is applied, it deletes the snapshots that were not created as desired.
https://github.com/metatron-app/metatron-discovery/issues/770
1. creat snapshot.
2. click cancel button before it end.
3. Do not click "Yes" button on the pop up window. Wait for the snapshot to be generated.
4. Then Click "Yes"
5. Snapshot should be canceled and file or table will be deleted.
You can also test with REST API
http://localhost:8180/api/preparationsnapshots/{ssId}/cancel
Local test is recommended. You can check if file is really gone.
> #770 Delete created snapshot files or hive tables when snapshot cancelation requested

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileUploadService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Previously, the server did not support txt file but the client did.
Now, The txt extension is considered csv file
[#570](https://github.com/metatron-app/metatron-discovery/issues/570)
1. create a dataset using txt file
2. make sure that preview is shown
3. create wrangled dataset
4. edit rules
5. make a snapshot
if you can download a snapshot file. it is ok.
> #570 supports_txt_file_upload_to_dataset

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepException.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
Lag and lead function can not process non-numeric values now.
This commit will allow non-numeric values for lag and lead functions, because there's no numeric calculation in lag and lead functions
https://github.com/metatron-app/metatron-discovery/issues/788
Tested window rule with lead and lag function like below.
window value: lag(`Call Date`, 2) group: City
window value: lead(Name, 2) group: City
> #770 Allow non-numeric values for lag and lead functions

- discovery-frontend/src/app/common/component/chart/type/label-chart/label-chart.component.ts
- discovery-frontend/src/app/page/chart-style/secondary-indicator.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
TImeFiled의 type을 서버 변경에 맞게 `time_format` 으로 수정
#516 
KPI Chart에서 Secondary Index 설정 시 스크립트 에러 발생하지 않고, 데이터가 나타남
> #495 Secondary indicators receive empty result

- discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
라인차트에서 교차선반에 추가된 dimension으로 시리즈가 생성될때 툴팁에 잘못된 값이 노출되고 있음
**Related Issue** : #629 
1. 차트화면에서 라인차트를 선택합니다.
2. 열선반에 dimension, 교차선반에 measure와 dimension을 추가합니다.
3. 툴팁을 확인시 툴팁표현이 중복되게 나오지 않는지 확인합니다.
> #629 In the case of series by dimension, the tooltip representation is incorrect

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
A null pointer error occurs when there is more than one expression in the window rule.
This error caused by shortenRuleString function which do not capable parsing Window rule.
This commit will fix this problem.
https://github.com/metatron-app/metatron-discovery/issues/845
1. go to preparation
2. add a window rule like this :
3. Also test single function window rule
> #845 Fix shorten rule string function for window rule

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
handle duplicate column name for mysql
#395 
1. goto mysql workbench
2. execute query with duplicate column
select * from polaris.book a join polaris.book b on a.id = b.id
3. see grid
> #395 handle duplicate column name for mysql

- discovery-server/src/main/java/app/metatron/discovery/domain/engine/model/SegmentMetaDataResponse.java
Colomn statistics in datasource error when has anomally ingeted column.
#710 
(Druid)
1. 데이터 소스 적재
2. segmentmeta 쿼리 결과에 error를 포함하도록 append
> 처음 적재한 스펙과 다르게 (dimension <-> metric)을 변경하여 새로운 세그멘트 생성 
(Discovery)
3. 데이터소스 > 새로운 데이터소스 생성 > 메타트론 엔진
4. 위에서 만든 error를 포함한 데이터 소스 import
정상적으로 데이터소스가 생성되고, 
데이터소스 상세 > 컬럼상세조회를 하면 에러가 발생한 컬럼은 조회되지 않아야 함
> Error in querying a specific column statistics in data source

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/DataConnectionProjections.java
There was an error in the projection process when adding the properteis of dataconnection.
Modified to handle projection for properteis only in case of JDBCDataConnection.
#738  
1. goto workbench
2. global variable create, update, delete without error.
> #738 properties projection use only JdbcDataConnection

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
워크벤치화면에서 에디터 전체화면 시 LNB open 영역이 나타납니다. 
**Related Issue** : #865  
1. 워크벤치화면으로 이동합니다. 
2. 에디터 전체 화면 버튼을 클릭합니다. 
3. 왼쪽의 LNB 영역이 숨겨졌는지 확인합니다.
> #865 edit LNB area in full screen of editor

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourcePredicate.java
워크북. 대시보드 생성 시에, PREPARING이나 FAIL 상태인 데이터소스도 리스트에 나타나며 선택 가능합니다.
1. 워크북 > 대시보드 생성
2. 사용할 수 없는 데이터 소스 목록이 조회되지 않아야 함
> Show only enabled datasources

- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/SearchQueryRequest.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/MeasureField.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
사용자 정의 필드가 포함된 위젯에서 다운로드 팝업이 정상적으로 표시 되지 않음
**Related Issue** : #240 #846 
1. 사용자 정의 필드가 포함된 위젯을 생성한다.
2. 대시보드 열람화면에서 데이터 다운로드를 실행하여 정상적으로 미리보기가 표시되고 다운로드가 이루어지는지 확인한다.
> #846 fix error download  included user-defined field widget

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
If the dataflow already have the dataset, skip to add it.
_Dataflow에 이미 해당되는 dataset이 있는 경우, 추가하지 않음_
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/885
Run locally.
> #885 skip to add a dataset if it's duplicated

- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-history/detail-workbench-history.html
워크벤치 쿼리 히스토리 팝업에서 목록이 없을경우 의미가 중복된 메세지를 삭제합니다. 
**Related Issue** : #890  
2. 쿼리 히스토리 에서 검색결과가 없을경우,  리스트가 없는경우 'No list' 부분이 제거 되었는지 확인합니다.
> F#890 query history message duplication

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-extract.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-extract.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-replace.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-split.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-split.component.ts
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/Extract.java
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/Split.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfExtract.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSplit.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Currently, split and extract rules can be applied to only one column at a time.
Allow multiple column as a target column parameter for split/extract rules.
Delete original columns after split rule applied.
https://github.com/metatron-app/metatron-discovery/issues/790
Do multi column split and extract.
Edit applied split and extract rule.
Check result.
> F#790 multi column split and extract on dataprep

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
Allow Keep and delete from context menu by clicking the histogram when column type is timestamp
#761 
Dataflow main grid -> click timestamp type histogram bar -> keep/ delete -> check if keep and delete works.
See screenshot
> F#761 timestamp histogram error

- discovery-frontend/src/assets/css/polaris.v2.page.css
대시보드 내 텍스트 위젯 목록에서 텍스트 위젯의 내용이 그대로 표시되어 목록이 정상적으로 표시되지 않습니다.
**Related Issue** : #904 
1. 대시보드를 생성하고 편집화면으로 이동합니다.
2. 텍스트 위젯 생성 버튼을 클릭하여 생성 팝업을 띄웁니다.
3. 아주 긴 내용을 입력한 후 저장합니다.
4. 우측 목록에서 위젯의 내용이 최대 두 줄만 표시되는지 확인합니다.
> #904 Need to fix displaying list of Text widget

- discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
- discovery-frontend/src/app/data-preparation/dataset/service/dataset.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetRepository.java
Sorting by `created` doesn't work after sorting by `used in`
#918 
Dataset tab > click created sorting button > check if list is sorted by created time > click used in sorting button > check if list is sorted by used in > click created sorting again > check if list is sorted by created time
> #918 fix sorting error in dataset list

- discovery-frontend/src/app/meta-data-management/catalog/catalog.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataErrorCodes.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/catalog/CatalogEventHandler.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/catalog/CatalogException.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/catalog/CatalogRepository.java
메타데이터 카탈로그 생성시 동일 레벨에서 이름을 중복해서 입력하면 등록이 되고 있습니다. 반면에 중복된 이름으로 수정하려고 하면 입력오류를 발생시킵니다.
**Related Issue** : #901 
1. 메타데이터 관리 > 카탈로그 메뉴로 이동합니다.
2. 카탈로그를 생성합니다. 
4. 동일한 이름의 카탈로그로 생성 시도 합니다. -> 생성되지 않고 경고창이 나타나는지 확인합니다.
5. 다른 이름으로 생성된 카탈로그 중 하나의 이름을 다른 카탈로그와 같은 이름으로 수정 시도 합니다. -> 수정되지 않고 경고창에 나타나는지 확인합니다.
> #901 Missing checking catalog name duplication when creating the catalog

- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board.component.ts
- discovery-frontend/src/app/meta-data-management/code-table/detail-code-table/detail-code-table.component.ts
필터를 복합적으로 적용하였을 때 센키차트가 그려지지 않는 경우가 있습니다.
**Related Issue** : #603 
1. 센키차트를 생성하고 대시보드에 배치합니다.
2. 측정값 필터 위젯을 두가지 생성하여 대시보드에 배치합니다.
3. 대시보드를 저장하고 열람화면에서 여러개의 필터값을 수정합니다.
4. 차트가 정상적으로 표시되는지 확인합니다.
대시보드 초기 버튼 문제와 코드테이블 alert 문제도 같이 처리 하였습니다.
> #603 Sometimes filter disappear when combining filters

- discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/create-permission-schema.component.ts
- discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/permission-schemas.component.ts
- discovery-frontend/src/app/common/component/abstract-popup.component.ts
- discovery-frontend/src/app/common/component/abstract.component.ts
- discovery-frontend/src/app/user/login/component/join/join.component.html
- discovery-frontend/src/app/user/login/component/join/join.component.ts
- discovery-frontend/src/app/user/profile/profile.component.html
- discovery-frontend/src/app/user/profile/profile.component.ts
회원 가입 화면 및 사용자 프로필 화면에서의 입력 체크 오류를 수정합니다.
퍼미션 스키마 화면에서의 스크롤 문제를 수정합니다. 
**Related Issue** : MT-12, MT-13, MT-22, MT-23, MT-48 
1. 사용자 등록화면에서 정상적으로 입력하였을 때 validation check 아이콘이 표시되는지 확인합니다.
2.사용자 등록화면에서 비밀번호 체크를 비밀번호와 다르게 입력하였을 때 정상적으로 체크하는지 확인합니다.
3. GNB > 사용자 프로필 관리 화면에서 Email, Full Name 관련하여 Validation check 가 표시되는지 확인합니다.
4. GNB > 사용자 프로필 관리 화면에서 내용이 수정되었을 때만 저장 버튼이 활성화 되는지 확인합니다.
5. administration > 퍼미션 스키마 화면에서 목록이 많을 경우 상하 스크롤이 정상적으로 동작하는지 확인합니다.
> Fixed input check error on user profile popup and join popup

- discovery-frontend/src/app/admin/user-management/component/approval/user-management-approval.component.html
- discovery-frontend/src/app/admin/user-management/component/approval/user-management-approval.component.ts
- discovery-frontend/src/app/admin/user-management/component/group/update-group/update-user-management-groups.component.ts
- discovery-frontend/src/app/admin/user-management/component/members/create-member/create-user-management-members.component.html
- discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.html
- discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
- discovery-frontend/src/app/admin/user-management/component/members/update-member/update-user-management-members.component.ts
- discovery-frontend/src/app/admin/user-management/component/members/user-management-members.component.ts
- discovery-frontend/src/app/admin/user-management/component/permission/detail-user-management-permission.component.html
- discovery-frontend/src/app/admin/user-management/component/permission/detail-user-management-permission.component.ts
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/detail-workspace.component.html
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/detail-workspace.component.ts
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.html
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.ts
- discovery-frontend/src/app/common/constant/common.constant.ts
Fixed some defected bugs
**Related Issue** : MT-44, MT-72, MT-73, MT-75, MT-80
1. administration > 멤버 > 사용자 생성 > 입력값 체크가 정상적으로 표시되는지 확인합니다.
2. administration > 멤버쉽승인 > 거절 기능 확인 > 거절 사유 입력 팝업이 표시될 때 이전값이 초기화되는지 확인합니다.
3. administration > 멤버 > 임의의 사용자 선택 > 상태 확인 > 선택된 항목에 선택 표시가 나타나고, 클릭 이벤트가 없는지 확인합니다.
4. administration > 워크스페이스 > 상태 확인 > 선택된 항목에 선택 표시가 나타나고, 클릭 이벤트가 없는지 확인합니다.
5. administration > 워크스페이스 > 임의 데이터 선택 > 상태 확인 > 선택된 항목에 선택 표시가 나타나고, 클릭 이벤트가 없는지 확인합니다.
6. administration > 멤버 > 임의의 사용자 선택 > 그룹 > 목록을 한 페이지당 30개씩 불러오는지 확인합니다.
7. administration > 그룹 > 임의의 그룹 선택 > 멤버 > 목록을 한 페이지당 30개씩 불러오는지 확인합니다.
8. administration > 권한 > 임의의 권한 선택  > 설명이 표시되는지 확인합니다.
> Bugfix in administration

- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.html
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-server/pom.xml
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Currently, we support dataset creation with excel, csv and txt files.
Let's also support json files.
https://github.com/metatron-app/metatron-discovery/issues/841
1. Go datapreparation
2. Go Dataset and Create new dataset
3. Import JSON file
4. Check preview and result dataset
5. Try import generated dataset into dataflow
> F#841 create dataset with json file

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/BoardConfiguration.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/BookService.java
There are some issues when copying dashboard (or workbook)
1. Widget title's visibility is not copied
2. Global time filter is not copied
#778 
#966 
1. Set global time filter to "Relative" and set some time range.
2. Set widget title's visibility to true.
3. Copy dashboard or workbook
4. Check time filter and widget's title copied well
Fixed sequences set properly while copying workbook.
(As it has been set dashboard's count)
> Fix some errors during copy dashboard

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
DB 데이터 소스 적재 단계에서 옵션중  "Get first option" 이 제대로 동작하지 않아 이를 수정합니다.
**Related Issue** : #832 
(사전에 데이터 베이스의 연결정보가 저장되어 있고, 특정 테이블이 준비되어있다고 가정합니다.)
1. 데이터소스 관리자 권한이 있는 사용자로 로그인합니다.
2. LNB 영역에 관리 > 데이터 스토리지 > 데이터 소스 로 이동하여 "새로운 데이터 소스 생성" 버튼을 클릭하여 데이터 소스 생성 단계로 진입합니다.
3. 소스 타입을 데이터 베이스로 선택합니다.
4. 임의의 데이터 커넥션, 테이블을 선택합니다. 
5. 수집 설정에서 "get only the first" 옵션에서 적재하려는 테이블의 총건수 보다 낮은 ROW 로 입력합니다.
(Roll up 설정을 설정안함으로 지정합니다.)
6. 데이터 소스 수정을 마친 후 상세 페이지에서 건수정보를 확인합니다.
> Fix missing "get only the first" option on db ingestion stage

- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/app/workspace/workspace.component.ts
노트북 서버를 연결하지 않은 워크스페이스의 경우 노트북 관련 기능을 사용할수 없는데도, 노트북 등록버튼이나, 노트북 개수 등, 사용자에게 혼란을 가져다 줄수 있습니다.
**Related Issue** : #958 
1. 워크스페이스 생성 시 노트북 관련 버튼/아이콘이 숨겨져 있는지 확인합니다.
2. 워크스페이스에 노트북 서버를 연결한 후 노트북관련 버튼/아이콘이 표시되는지 확인합니다.
> #958 Hiding notebook-specific features in workspace that no assigned notebook server

- discovery-frontend/src/app/workbook/workbook.component.html
- discovery-frontend/src/app/workbook/workbook.component.ts
사용자의 혼란을 방지하기 위해, 개인 워크스페이스의 경우 무의미한 show/hide 버튼을 제거하고, "Shown Only" 필터링 조건도 제거합니다.
**Related Issue** : #955 
1. 개인 워크스페이스 내에 있는 워크북으로 이동합니다.
2. 워크북내에서 숨김/표시 관련 기능이 숨겨져 있는지 확인합니다.
3. 공유 워크스페이스 내에 있는 워크북으로 이동합니다.
4. 워크북내에서 숨김/표시 관련 기능이 표시되어 있는지 확인합니다.
> 955 Under the personal workspace, the "Hide / Show" function for dashboards is meaningless

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
Close context menu when scrolling
(Added grid scroll event.)
#986 
1. menu MANAGEMENT > DataPreparation
2. Dataflow > click dataflow
3. click Edit rules > Click on any column Context menu button
4. scroll
> #986 Close context menu when scrolling

- discovery-frontend/src/app/workbench/workbench.component.ts
쿼리 실행 취소 후, 재실행을 할 경우 완료 이후에도 실행 시간이 계속 증가합니다. 
**Related Issue** : #762 
1. 워크벤치로 이동합니다. 
2. 쿼리 실행 후 취소를 시도합니다. 
3. 취소 성공 후 재실행을 할경우, 정상적으로 조회가 완료된 이후에도 실행 시간이 계속 증가 되지 않는지 확인합니다.
> #762 stop execute time when using retry button

- discovery-frontend/src/app/domain/meta-data-management/column-dictionary.ts
- discovery-frontend/src/app/meta-data-management/column-dictionary/create-column-dictionary/create-column-dictionary.component.ts
- discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.html
- discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.ts
Add/ edit Short Column Name in column dictionary
MT-58
Metadata -> column dictionary -> create new column dictionary 
Add column dictionary with short colum name -> 
Go to column dictionary detail -> check if you can see the short column name -> Try editing short column name
> Fail to add / edit short name in column dictionary

- discovery-frontend/src/app/common/component/chart/base-chart.ts
차원값이 2개인 경우 차원값에 따른 색상 설정을 할 경우 원복이 되는 문제 있습니다.
**Related Issue** : #970 
1. 대시보드에서 2개의 dimension을 이용하여 차트를 생성합니다. 
2. Color Setting 에서 dimension 으로 변경하고 선반의 dimension 을 선택합니다.
3. 차트를 저장하고 대시보드 편집화면으로 이동하였을 때 dimension 에 따른 색상 설정이 유지되는지 확인합니다.
> #970 Legend selection (selection through dimension of color setting) is not possible when there are two dimension values.

- discovery-server/src/main/java/app/metatron/discovery/config/SchedulingConfig.java
- discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/workbench/TimeoutConnectionCloseJob.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/WorkbenchController.java
- discovery-server/src/main/resources/application.yaml
- discovery-server/src/main/resources/logback-console.xml
If canceling the query, close the resultset first if it exists before canceling the statement.
This is a similar implementation of the cancel () method of an unimplemented PrestoStatement.
#953 
1. goto Presto workbench.
3. click cancel button
4. See if the cancellation is done.
> F#953 close resultset first before cancel statement

- discovery-frontend/src/app/workbench/service/workbench.service.ts
- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/common/TemporaryCSVFileCleanJob.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorProjections.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorResult.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryRunRequest.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/WorkbenchProperties.java
* 워크벤치 쿼리 에디터에서 쿼리를 실행 할 때 실행한 질의 결과를 데이터베이스에 테이블에 저장합니다.
* CSV 파일 경로, 쿼리 등
* 워크벤치 화면에 최초 진입할 때 저장한 쿼리 에디터의 질의 결과를 바탕으로 이전 쿼리 결과를 복원합니다.
* 결과 복원 시 기존에 만들어진 API(`/api/queryeditors/{id}/query/result`)를 사용하여 이전 쿼리 결과를 조회합니다.
* 이전 쿼리 결과 복원시 CSV 데이터 양이 많을 수도 있기 때문에 기본적으로 100 row로  제약 두었습니다.
* 저장된 CSV 파일이 삭제된 경우 쿼리 결과를 복원하지 못합니다. CSV 파일을 삭제하는 TemporaryCSVFileCleanJob에서 하드 코딩으로 되어있던 1일의 만료일을 WorkbenchProperties를 사용하여 사용자가 설정할 수 있도록 변경하였습니다.
> #814 The results of the query executed in workbench should be visible when you exit the browser and run it back into the workbench

- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/Aggregation.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/DistinctSketchAggregation.java
- discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
- discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java
Changed query method to datasketch mode to improve result of COUNT function.
#967 
1. Add custom measure using COUNTD function at chart editing page.
2. Create chart with this custom measure.
3. Result's accuracy might be enhanced.
http://druid.io/docs/latest/development/extensions-core/datasketches-aggregators.html
> Use datasketch query to COUNTD function

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-countpattern.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-drop.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-extract.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-flatten.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-merge.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-move.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-nest.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-pivot.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-replace.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-set.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-setformat.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-settype.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-sort.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-split.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-unnest.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-unpivot.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-window.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multicolumn-rename.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-join-popup/rule-join-popup.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.html
- discovery-frontend/src/app/data-preparation/dataset/dataset.component.html
- discovery-frontend/src/app/monitoring/audit/job-log/job-log.component.html
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
When sending ruleString to server, colum name must be wrapped with ` .
MT-184
Dataflow maingrid-> rename  one column -> check if column name is wrapped with back tick in request
> Use backticks with column in dataprep

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/PrestoConnection.java
Presto 내부적으로 사용하는 파티션 테이블을 사용자에게 노출하지 않도록 숨김처리
MT-130
1. 프레스토 워크벤치 접속
2. LNB에서 'information_scheam' Database 선택
3. 테이블 목록에 `__internal_partitions__` 테이블이 안나오는지 확인
> hide presto internal partition table

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetEventHandler.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Internally there is a process of converting JSON to CSV
This process has been added to the creation of imported datasets and creation of stage0.
[#841](https://github.com/metatron-app/metatron-discovery/issues/841)
1. create a dataset for JSON file
2. create a dataflow with the dataset
3. make a wrangled dataset
4. edit come rules of the dataset
5. if there is no error, everything is ok.
> #841 convert json to csv

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
데이터 미리보기 화면에서 데이터 요약 정보가 초기화 되지 않는 문제를 수정합니다.
1. 멀티데이터소스로 대시보드를 생성합니다.
2. 데이터 미리보기를 띄운 후 데이터소스의 요약 정보를 확인합니다.
3. 데이터소스를 변경한 후, 데이터소스 요약정보가 누적되지 않고 정상적으로 표시되는지 확인합니다.
> Fixed a problem where data summary information was not initialized in the data preview screen

- discovery-frontend/src/app/meta-data-management/catalog/catalog.component.html
- discovery-frontend/src/app/meta-data-management/catalog/catalog.component.ts
Fixed problem of jumping to root when clicking Back button while creating catalog.
#1042
Make catalog that has 2 depths
`Root > 1st depth  > 2nd depth`
Click one catalog from root -> Now you are in the 1st depth. click create new catalog -> click back button -> check if you are back in 1st depth catalog (not root)
> #1042 fix catalog back btn error

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepMonitorService.java
I have enhanced the processing for cases where there is no tables to migrate.
In other words, if the old entity group can not be found, it has to be passed without any critical log generation.
In fact, the absence of entity groups will increasingly become a major case very soon.
_아예 migration 할 것이 없는 경우에 대한 처리를 보완하였습니다.
즉, old entity group을 찾을 수 없는 경우, 아무 critical log 생성 없이 그냥 지나가도록 하였습니다.
사실, entity group이 없는 것이 점점 더 major case가 될 것입니다._
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1046
Locally. With H2 and MySQL.
> H#1046 dataprep migration

- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
데이터소스 중, `연결형`이고 데이터베이스가 `QUERY` 형태인 데이터소스의 상세화면에서 **edit filter** 버튼을 hide시킨것을 다시 보이도록 수정
#1079
1. 데이터소스 > 데이터소스 생성(DB)
2. 연결형 선택, database table 선택 단계에서 QUERY로 테이블을 선택 후 데이터소스 생성
3. 2에서 생성한 상세화면의 Column detail tab에서 **edit filter** 버튼이 제대로 보이는지 확인
> #1079 rollback edit filter validation in column detail datasource

- discovery-frontend/src/app/common/component/period/period.component.html
datepicker의 input이 입력되어 지정된 포맷과 다르게 보이는 현상 수정
input이 입력되지 않도록 readonly로 변경
적용 화면 : 데이터소스, 데이터모니터링, 어드민관리
MT-24
1. 데이터소스 > 데이터소스 상세화면 > 모니터링 > 하단의 쿼리 탭의 datepicker에 값이 입력이 안되는것 확인
2. 데이터 모니터링 > 로그 통계, 잡 로그 탭의 datepicker에 값이 입력이 안되는것 확인
3. 어드민 > 사용자관리 > 멤버쉽 승인, 멤버, 그룹 탭의 datepicker에 값이 입력이 안되는것 확인
> Datepicker input change to readonly

- discovery-frontend/src/app/common/component/abstract.component.ts
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-ds-network.component.ts
- discovery-frontend/src/app/dashboard/dashboard.component.ts
- discovery-frontend/src/app/dashboard/filters/abstract-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.html
- discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
- discovery-frontend/src/app/dashboard/service/dashboard.service.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRestIntegrationTest.java
링크 형태의 데이터 소스를 대시보드 연결시 필수 필터 편집 화면에 필수 필터 내 항목을 가져오는데서 오류가 발생합니다.
**Related Issue** : #1056 
(기존에 DB > Linked datasource 가 생성되었다고 가정합니다.)
1. 대시보드 생성시 링크 데이터 소스 연결 > 링크 데이터 소스 적재 작업 수행 완료
2. 연결된 데이터 소스를 클릭하면 하단에 데이터 소스 정보가 나타나는데 "필수 필터" 탭 선택
3. 탭 화면내 "수정" 버튼클릭
4. 정상적으로 목록을 가져와야 합니다.
> #1056 Problem with settings the mandatory filter in the link-type datasource

- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
When I entered an expression which started with number error toast pops out.
Then I clicked, the "click to see detail", and I get this message.
For input string: "22222222222222222222222222"
This error message is rather not intuitive.
Change error message more user friendly.
https://github.com/metatron-app/metatron-discovery/issues/985
Try set rule with value 22222222222222222222222222 and check the error message.
> #985 Catch numberFormatException and throw it as prepException

- discovery-frontend/src/app/common/component/abstract.component.ts
- discovery-frontend/src/app/common/gaurd/can.deactivate.guard.ts
- discovery-frontend/src/app/dashboard/service/dashboard.service.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/workbook/workbook.component.ts
차트 위젯의 다운로드에서 동작하지 않는 정렬 기능을 제거합니다. ( MT-162 )
대시보드에서 벗어날 시 수정되었을 때만 경고창을 표시하도록 수정합니다. ( MT-163 )
**Related Issue** : MT-162, MT-163 
1. 페이지 위젯의 데이터 다운로드에서 미리보기의 그리드에서 정렬 기능이 제거되었는지 확인합니다.
2. 대시보드 편집화면에서 내용을 수정하지 않고 바로 취소 버튼을 눌렀을 때, 경고창 없이 열람화면으로 이동하는지 확인합니다.
3. 대시보드 편집화면에서 내용을 수정하고 취소 버튼을 눌렀을 때, 경고창이 표시되는지 확인합니다.
> Bugfix in dashboard

- discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-configure-schema/db-configure-schema.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-ingestion-permission/db-ingestion-permission.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-configure-schema/file-configure-schema.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-ingestion/file-ingestion.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-configure-schema/staging-db-configure-schema.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-ingestion/staging-db-ingestion.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-select-data/staging-db-select-data.component.ts
config 단계에서 지정한 TIMESTAMP 정보에 따라 granularity를 세팅
#1058 
1. 데이터소스 > 데이터소스 생성 > 데이터베이스 선택단계 (FILE생성의 경우는 2번으로 건너뜀)
2. config단계에서 TIMESTAMP 를 설정 
3. ingestion 단계에서 아래의 조건에따라 granularity가 변경되는지 확인
> 1. config단계에서 TIMESTAMP를 `CURRENT_TIME`으로 선택한 경우, `segment granularity`가 HOUR로, `query granularity`가 SECOND로 설정
> 2. config단계에서 `TIMESTAMP`를 FIELD로 선택한 경우, 'format'의 마지막 날짜에 따라 `segment granularity`와 `query granularity`가 아래의 표를 기준으로 설정
> 3. config단계에서 `TIMESTAMP`를 FIELD로 선택하고 'UNIX'를 선택한 경우, `segment granularity`가 HOUR로, `query granularity`가 SECOND로 설정
> 4. ingestion단계에서 이전버튼을 눌르고, config단계에서 `TIMESTAMP`의 변경이 발생한경우 2번과 같이 값이 새로 설정되는지 확인
> 5. database selet 단계에서 변경이 발생한경우 (FILE의 경우 파일교체), 2번과 같이 값이 새로 설정되는지 확인
> #1058 granularity automation in ingestion

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceRepositoryTest.java
- discovery-server/src/test/resources/sql/test_datasource_filter.sql
exclude temp datasource creator in filter list
**Related Issue** : #1112 
1. login with never create datasource or create new member.
2. goto workbench.
3. execute simple select query
4. click preview chart button in result area.
5. goto datasource list.
6. click Creator Filter dropdown.
7. see creator list excluded login userid.
> #1112 exclude temp datasource creator in filter list

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
Generating JSON file from hive type snapshot has some issue.
Thus, Sometimes I can not create a new dataset with downloaded json file from hive type snapshot.
This commit will fix that problem.
https://github.com/metatron-app/metatron-discovery/issues/1119
1. Open any dataflow and dataset
2. Set some column's value as '01' or '02'
3. Create a Staging DB(Hive) type snapshot
4. Download it as a json file.
5. Create a dataset with the json file.
> #1086-fix Use original column type of hive table when generating json file

- discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
#1092 이슈에서 문제가 발생될 수 있는 SECOND와 MINUTE를 segment granularity에서 제거
current_date를 TIMESTAMP로 지정시 month가 기본값이 되도록 수정
#1058  #1092 
1. 데이터소스 생성 > config 단계에서 current를 timestamp로 지정
2. ingestion step의 granularity가 MONTH로 나오는지 확인
> Fix automation granularity

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepMetaDBMigrationService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
불필요한 룰 적용(룰 삭제, 삽입 등이 반복되었을 경우)을 by-pass하기 위해 룰 compaction 기능이 있는데, 이것이 잘못 적용이 되어서 문제를 일으켰었습니다. 차후 W.DS에 대해 exclusive lock을 구현할 때까진 compaction을 하지 않기로 했습니다.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1118
Run locally.
> F#1118 bugfix dataprep undo

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
If there are duplicate column names in the result of the query, add a random number to avoid duplicate column names.
Add a separator(`_`) before the random number.
ex) a4501_ -> a`_`4501_
#1081 
1. goto mysql workbench
2. execute query with duplicated column
ex) select 'a' as id, 'b' as id;
3. see changed column name;
> #1081 add '_' for duplicated column

- discovery-frontend/src/app/common/component/chart/option/converter/axis-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/define/common.ts
- discovery-frontend/src/app/common/component/chart/type/combine-chart/combine-chart.component.ts
- discovery-frontend/src/app/page/chart-style/axis-value-option.component.html
컴바인차트 보조축 Set Axis Range의 min/max 예시값이 보조축 데이터와 다른 부분을 수정합니다.
#175 
1. 컴바인 차트를 그린 후 보조축 옵션의 Set axis range를 on으로 설정합니다.
2. Max / Min value의 placeholder값이 보조축 데이터와 맞는지 확인합니다.
> #175 Combine chart => fix secondary axis range error

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.html
맵차트 편집화면에서 범례 축소 기능을 제거합니다.
**Related Issue** : #1047 
맵차트 편집화면에서 차트를 그렸을때 범례 축소 아이콘이 등장하지 않는것을 확인합니다.
> #1047 Map chart => Remove legend size change from Chart modify view

- discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.ts
연결형 데이터소스로 대시보드 생성 시 적재 과정에서 실패할 경우 오류 메시지 없이 dimmed 상태가 남아 있는 현상이 있습니다.
**Related Issue** : #1056 
1. linked로 데이터소스 생성 후 필수필터 지정
2. 대시보드에서 해당 소스 불러와 필수필터 설정
3. Done버튼 클릭시 ingestion되다가 에러 발생
4. 에러 발생하면 재적재 시도 메시지가 나타나는지 확인합니다.
> #1056 Fixed error message display failure when data ingestion failed

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetJdbcService.java
Use JdbcConnectionService instead of dataprep own implementation in while getting preview lines from JDBC connection
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1143
Run locally.
> #1143 use JdbcConnectionService instead of dataprep own implementation

- discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
연결형 데이터소스 상세화면에서 expiration 이 생성시처럼 시간과 분 표시가 나타나지 않아 사용자가 어떤 값인지 인지하기 어려운 현상을 수정함
3.1.1 release test
1. 데이터소스 생성 > DB 생성 > 연결형으로 데이터소스 생성
2. 데이터소스 상세화면 > information tab > 1에서 생성할때 선택한 expiration time이 생성할때와 마찬가지로 읽기 쉬운 형태로 표기되는지 확인
> Fix expiration time in datasource detail information

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
Error applying delete/ keep with context menu when column type is timestamp and column name has a whitespace
#1019 
Dataflow main grid -> change timestamp type column name to `Rename Column` -> try delete/keep with context menu by clicking histogram
> #1019 Fix delete error in context menu when column name has white space

- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/create-data-connection/create-connection.component.ts
- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/handler-data-connection/update-data-connection/update-connection.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.html
- discovery-frontend/src/app/data-storage/data-source-list/component/advanced-setting.component.ts
remove value validation in dataconnection custom prop.
**Related Issue** : #1168 
1. create data connection
2. input special character in custom properties
(Advanced Settings > Custom Properties)
3. save data connection without invalid error.
> #1168 remove value validation in dataconnection custom prop.

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetJdbcService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
preparation API uses custom controller for PrDataset and PrDataflow.
GET and POST are already served.
now PATCH controller was added.
**Related Issue** : [#1141](https://github.com/metatron-app/metatron-discovery/issues/1141)
1. create a dataset for JDBC
2. see the details of the dataset
3. totalBytes is a positive number not -1.
totalBytes is set by PATCH API
> #1141 added_preparation_custom_patch_controller

- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.html
- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/staging-db-component/staging-db-complete/staging-db-complete.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/information-dats-source/information-data-source.component.ts
파티션키가 있는 데이터소스인 경우 데이터소스 상세화면에서 설정된 파티션이 제대로 보이지 않던 현상수정
#725 
1. 데이터소스 > stagingDB로 데이터소스 생성 > 파티션 키가 있는 데이터로 생성
2. 1에서 생성한 소스의 상세화면으로 이동
3. information tab의 타임스탬프 설정에서 파티션키가 제대로 표시되는지 확인
> #725 fix partition keys in source detail

- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-dataconnection-info/detail-workbench-dataconnection-info.html
- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.html
커넥션 목록에서 connection type이 URL인 경우 파란색 텍스트로 보이던것을 수정
#740 
1. 데이터 저장소 > 커넥션 > 커넥션 생성 > URL타입으로 커넥션 생성
2. 데이터 커넥션 목록에서 1에서 생성한 커넥션의 url이 검정 텍스트로 보이는지 확인
> #740 remove url link in connection list

- discovery-frontend/src/app/notebook/component/create-notebook/create-notebook-name/create-notebook-name.component.ts
- discovery-frontend/src/app/notebook/component/create-notebook/create-notebook.component.ts
- discovery-frontend/src/app/workbench/component/create-workbench/create-workbench-complete/create-workbench-complete.component.ts
- discovery-frontend/src/app/workspace/component/etc/set-notebook-server.component.html
- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/app/workspace/workspace.component.ts
After creating the workbench, the user expects to go directly to the detail screen and work on it. Users are inconvenienced to stay in the workspace's content list after creating the workbench.
**Related Issue** : #803 
1. 워크스페이스에서 워크벤치를 생성합니다.
2. 생성한 워크벤치로 바로 이동하는지 확인합니다.
> #803 need to go to the detail page right after creating the workbench

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
- discovery-frontend/src/app/data-preparation/data-snapshot/service/data-snapshot.service.ts
- discovery-frontend/src/app/domain/data-preparation/pr-snapshot.ts
- discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
Allow modification of snapshot name in snapshot detail popup
#1186
Snapshot tab -> Change snapshot name
> F#1186 edit snapshot name

- discovery-frontend/src/app/workbench/workbench.component.ts
sql beautifier 기능을 수행하고 다른 작성 탭으로 이동 후, 다시 원래 작성하던 탭으로 이동 시 쿼리의 내용이 저장되도록 수정 
**Related Issue** : #743  
2. 쿼리를 입력하고, sql beautifier 버튼을 클릭하여 쿼리에 적용합니다. 
3. 다른 입력 탭으로 이동 후, 이전 작성하던 탭으로 이동 후 쿼리 내용이 정상적으로 남아있는지 확인합니다.
> #743 add sql beautifier and save

- discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
- discovery-server/src/main/resources/application.yaml
- Resource has been cached
- Excluded files and directory ( index.html, favicon.ico, assets )
#897 PR을 이어서 진행합니다.
기존에 `/resource/**` 해당 경로로 캐싱을 할 경우에 다국어 파일까지 캐싱되는 문제가 있었습니다.
인지하지 못하고 있었는데 `index.html`파일도 캐싱되고 있었습니다. 
해당 파일(index.html)이 캐싱되면 패키징되면서 해시가 바뀌어도 바뀐 파일을 불러오지 못합니다.
우선 패키징하면 아래와 같이 파일이 번들링됩니다.
```text
assets
0.315e1847c1f0b9743a14.chunk.js
1.80ae6146d0efc98b6a9f.chunk.js
2.8ca93f1afa72e48b88f4.chunk.js
3.599fcbba128f6e76be8c.chunk.js
4.da8900252b14296298d9.chunk.js
5.5eb561ad679634cf45ae.chunk.js
6.b639745031306faa43df.chunk.js
7.a9144137563f69cd23b7.chunk.js
8.c4b52a5e4bcca8f04a0a.chunk.js
9.de798d934d28ec1b000f.chunk.js
10.33cd71e402bfec6b0439.chunk.js
11.deeadfe544a46247eb13.chunk.js
12.e7b1d6460dca54445481.chunk.js
13.3d987814706bbcd7bde3.chunk.js …
```
> Apply static resource caching

- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorResult.java
* 워크 벤치에서 컬럼 갯수가 매우 많은 테이블(예. 500개 이상)을 select 시에 오류나는 것을 수정했습니다.
#1159 
* 메타트론 데이터베이스를 MySQL로 사용하고 MySQL 다른 데이터베이스 1000개 컬럼을 가진 테스트 테이블을 만들었습니다.
* 메타트론 워크벤치에서 오류나지 않고 SELECT 되는 것을 확인했습니다.
> #1159 Support for querying data in a table with a very large number of columns

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
Histogram never fails no matter how wide the timestamp range is like centuries.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1260
Run locally.
> #1260 histogram never fails no matter how wide the timestamp range is

- discovery-frontend/src/app/workbench/workbench.component.ts
Changed the rollup parameter to false when creating Chart Preview DataSource
**Related Issue** : #1215 
1. goto workbench
2. input simple query and execute query.
```
select 'aa' as col1
union all 
select 'aa' as col1;
```
3. click 'chart preview' button
4. click 'datasource info' button
5. grid must have two rows.
> #1215 roll up false for chart preview

- discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.html
- discovery-frontend/src/app/datasource/component/datasource-summary/datasource-summary.component.ts
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/ds-select-datasource.component.html
- discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-columnschema.component.ts
Fix minor errors in create metadata popup and column schema list
No issue. Bug from release test
1 . Go to metadata list  -> click create new metadata ->  select datasource -> click one datasource -> check in right panel if `Metadata name` is hidden
2. Go to metadata list -> Go to metadata detail page -> click column schema tab -> row with 
physicalName : current_datetime should not be shown on the list
> F#0 fix metadata error

- discovery-frontend/src/app/workbench/workbench.component.ts
워크벤치에서 쿼리 실행 취소 후, 쿼리 종료 시간이 초기화 되지 않습니다. 
쿼리 종료 시간 초기화 추가 
**Related Issue** : #1284  
1. 워크벤치 화면으로 이동 합니다. 
2. 쿼리 실행 후, 취소를 선택합니다.
3. 쿼리 재 실행할 경우 종료 시간이 초기화 되는지 확인합니다.
> F#1284 initialize time after retry

- discovery-frontend/src/app/data-storage/service/granularity.service.ts
- discovery-frontend/src/assets/css/metatron/component/component.form.css
string type의 데이터인 인 date/time 컬럼이 unix로 지정되고 타임스탬프로 설정했을경우, ingestion setting화면에서 오작동하는것 수정
#1092 
1. 데이터소스 생성 > string type의 unix형태의 컬럼을 타임스탬프로 지정
2. ingestion setting 화면에서 interval 설정이 올바르게 작동하는지 확인
> #1092 if string unix type, convert to number type

- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataPopularityService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/mdm/MetadataRestIntegrationTest.java
- discovery-server/src/test/resources/sql/test_mdm_popularity.sql
Fix metadata list when popularity is null.
#1311 
1. Go to 'Management' -> 'Metadata' Menu.
2. Metadata list is shown normally.
> f#1311 Fix Metadata list when popularity is null

- discovery-frontend/src/app/common/component/chart/option/converter/format-option-converter.ts
- discovery-frontend/src/app/common/component/chart/option/define/common.ts
- discovery-frontend/src/app/page/chart-style/format/format-item.component.ts
Add Chinese currency on chart's number format option.
#1291 
1. Create any chart and go to the edit mode.
2. Click 'Number format' option.
3. Set format option to 'Currency'
4. There is a new currency option named '¥ (CNY)'
5. Select '¥ (CNY)' then check the number format is adapted.
> Support Chinese currency on the chart.

- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
위젯 다운로드 화면에서 대상 파일의 사이즈 및 row 수를 계산하기 위한 selectMeta 쿼리 수행시 
불필요한 필드를 포함하여 druid에 보내는 케이스가 있습니다.
이로 인해 druid parser 에러가 발생하게 되기 때문에 
user defiend field를 실제 사용하는 경우에만 쿼리에 포함되도록 수정하였습니다.
#1276 
1. 측정값에 사용자 컬럼을 추가합니다.
- 수식 : COUNTD( [City] ) 등
2. 1항에서 생성한 사용자 컬럼을 **포함하지 않고** grid 차트를 만듭니다.
3. grid차트 설정 창에서 '공통 설정' > '차트 유형' 을 "원본 데이터"로 설정 합니다.
4. 차트와 대시보드를 저장한 뒤, 위에서 생성한 위젯 우측 상단의 다운로드 기능이 정상적으로 동작하는지 확인합니다.
5. 확인 가능하다면, 드루이드 쿼리 스펙에 아래와 같이 vitual column에 사용하지 않는 필드가 빠져있음을 확인합니다.
``` json
"virtualColumns": [
**{
"type": "expr",
"outputName": "user_defined.countd",
"expression": "COUNTD(\"City\")"
},**
{
"type": "expr",
"outputName": "user_defined.count",
"expression": "count"
}
],
```
> #1276 Remove unusing fields into SelectMeta Query.

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.html
Change zindex of aggregation tool tip
#1300 
1 . Go to dataflow main grid 
2 . select `aggregate` command 
3 . click expression input (drop down list will come down)
4 . hover yellow icon next to group by (when expression drop down is opened) 
5 . check if tool tip is not hiding under drop down
> #1300 Fix tooltip z-index

- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.html
- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
글로벌차트 위젯으로 구성한 대시보드의 경우 체크박스 선택이 의도와 달리 작동함
예를 들어 체크리스트 중 2를 선택했으나 1,2가 동시 선택되거나 전체를 선택했으나 2가 빠짐
**Related Issue** : #1274 
1. 필터 위젯이 포함된 대시보드를 생성합니다.
2. 필터 값의 체크 및 체크 해제가 정상적으로 동작하는지 확인합니다.
> #1274 Checkbox global filter widget does not work properly

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Hadoop을 통해 druid에 적재하는 경우, csv.stream이 아닌 string row parser를 이용합니다.
#1341 
1. Management > Datasource 메뉴에서 Staging DB로 데이터소스를 생성합니다.
2. default.nbis_tmp 테이블로 적재를 합니다.
3. 적재 스펙이 csv.stream이 아닌 string으로 변경되었는지 확인합니다.
As-Is)
```json
"parser" : {
"type" : "csv.stream",
"timestampSpec" : {
"type" : "hadoop",
"column" : "current_datetime",
"missingValue" : "2019-01-30T11:11:58.528Z",
"invalidValue" : "2019-01-30T11:11:58.528Z",
"replaceWrongColumn" : true
},
"dimensionsSpec" : {
"dimensions" : [ "~~~~" ],
"dimensionExclusions" : [ ],
"spatialDimensions" : [ ]
},
"columns" : [ "~~~~~" ],
"delimiter" : "\t"
},
"metricsSpec" : [ {
"type" : "count",
"name" : "count"
} ],
"enforceType" : true,
"granularitySpec" : {
"type" : "uniform",
"segmentGranularity" : "MONTH", …
```
> Change row parser to string on hadoop ingestion

- discovery-frontend/src/app/common/component/input/input.component.ts
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.html
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
- discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.html
- discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
- discovery-frontend/src/app/meta-data-management/catalog/catalog.component.html
- discovery-frontend/src/app/meta-data-management/code-table/code-table.component.html
- discovery-frontend/src/app/meta-data-management/column-dictionary/column-dictionary.component.html
- discovery-frontend/src/app/meta-data-management/metadata/metadata.component.html
1. 대시보드 생성 시, 이름 입력과 동시에 Done 버튼이 활성화되지 않습니다.
2. 데이터소스/데이터커넥션의 필터 메뉴가 마우스를 두번 클릭했을 때 동작합니다.
**Related Issue** : #199 
1. 대시보드 생성 시, 이름  입력과 동시에 Done 버튼이 활성화 되어야 합니다.
2. 데이터소스/데이터커넥션 필터 메뉴를 클릭했을 때 바로 동작해야 합니다.
> #199 fix error input component

- discovery-frontend/src/app/page/component/analysis/slider/range-slider.component.ts
Unable to see range slider
1. workspace > workbook > create a chart > choose mapView > geo dimension on the layer > click layer configuration
2. able to see range slider
AS-IS>
TO-BE>
> f#0-fix_range_slider fixed range slider

- discovery-frontend/src/app/workbench/workbench.component.ts
The icon in the results pane disappears when you query the workbench.
This happens when the query is canceled and then re-executed.
**Related Issue** : #1367 
3. cancel query
4. retry the query
> #1367 The icon in the results pane disappears when you query the workbench.

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/data-grid-data-source/data-grid-data-source.component.ts
- discovery-frontend/src/app/data-storage/service/timezone.service.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
- discovery-server/src/main/java/app/metatron/discovery/domain/geo/query/model/GeoQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeListFilter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRangeFilter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/ContinuousTimeFormat.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/limits/PivotColumn.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/model/HoltWintersPostProcessor.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
- discovery-server/src/main/resources/scripts/default.sql
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
데이터소스 생성화면에서 시간, 분, 초 의 datetime format 인 경우에만 timezone 셀렉트박스가 나오도록 수정
일 이상의 포맷은 데이터소스 상세화면과 데이터소스 생성화면에서 timezone 표시가 되지 않도록 수정
- 생성화면에서 타임존이 선택이 가능한 포맷 형태
- 생성화면에서 타임존이 선택 불가능한 포맷인 경우와, format validation 을 통과하지 못한경우
- 타임존 선택이 불가능한 포맷으로 데이터소스 생성시, 상세화면에서 표시되는 형태
- 타임존 선택이 불가능한 포맷과, 가능한 포맷으로 데이터소스 생성시, 상세화면에서 표시되는 형태
#1397 
1. 데이터소스 > 데이터소스 생성 > datetime으로 필드를 변경 
2. 해당 컬럼이 yyyy-MM-dd 이상의 포맷인 경우 타임존 선택박스가 나오지 않는것 확인
3. 2와 같은 포맷으로 데이터소스를 생성 후 상세화면에서 timezone 에 대한 정보가 나오지 않는것 확인
> #1397 remove day timezone

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
We consider all input data to be input initially as a string
However, JSON can have JSON object as a child
So we will assume that the input data is all strings
The data in the imported dataset will be represented as a String even if it is JSON
[#1376](https://github.com/metatron-app/metatron-discovery/issues/1376)
Attached two test files.
Import them for test.
> #1376 updated json parsing rules

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/assets/css/metatron/page/metatron.page.99Preperation_dataflow_rule.css
Fix main grid css
#1406 
In dataprep main grid, check histogram box has a border, and histogram description has a padding
> #1406 Fix dataprep main grid css

- discovery-frontend/src/app/data-storage/component/set-workspace-published/set-workspace-published.component.html
- discovery-frontend/src/assets/css/metatron/component/component.table.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
소유자를 표시할때 username이 같이 표기되도록 수정
#667 
1. 데이터소스 또는 커넥션 상세화면에서 워크스페이스를 지정하는 팝업 오픈
2. Owner(소유자) 에서 username이 같이 표기되는지 확인
> #667 fix workspace comp in datasource

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-rename.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/rule-suggest-input.component.ts
When selecting korean column name in the suggestion layer , Down Arrow goes to the first column.
한글 컬럼 이름 suggetion을 선택할때, 아래 화살표를 입력하면 첫번째 컬럼으로 간도록 수정
#1401 
1. menu > MANAGEMENT > DataPreparation.
2. click Dataflow > click Wrangled Data > Edit rules.
3. select rule  aggregate, pivot and window.
4. add function and then add korean column name.
5. select column name in suggestion layer.
> #1401 Down arrow event in korean input mode.

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-field-combo.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/grid/slick.grid.override.css
Apply timestamp format to rename popup
#1393 
Go to dataprep main grid -> change one column type to timestamp
-> open multi column rename popup (rename command) -> see if timestamp format is applied in grid data
> #1393 Add timestamp format to rename popup data

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
대시보드 상에서 글로벌필터 적용 시, 라인차트에는 반영 안됨
**Related Issue** : #1438 
* 표차트, 막대차트, 라인차트 생성합니다.
* 특정 차원값으로 글로벌 필터 생성 후, 필터 위젯으로 추가합니다.
* 대시보드 저장 후 열람화면에서 필터 위젯의 값을 선택합니다.
* 라인차트에 정상적으로 필터가 적용되는지 확인합니다.
> #1438 Filters do not apply to line charts.

- discovery-server/src/main/java/app/metatron/discovery/config/ApiResourceConfig.java
프론트엔드 라이브러리 버전업 이후에 정적 리소스가 캐싱되지 않고 있습니다
**Related Issue** : #1487 
1.  페이지 로딩 합니다
2. 브라우저의 디버그 모드 HTTP 응답에서 캐싱 항목을 확인합니다
> #1487 Apply caching static resource

- discovery-frontend/src/app/admin/user-management/user-management.component.html
- discovery-frontend/src/app/admin/user-management/user-management.component.ts
관리자 > 사용자 > 멤버(탭) 화면에서 사용자 목록이 길어져도 스크롤이 활성화 되지 않습니다
**Related Issue** : #592 
- 스크롤이 생길정도의 사용자를 등록하고 스크롤이 생기는지 확인합니다
> #592 Fix error scrolling user list page

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/DruidConnection.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
An error occurs if the druid table starts with a number in the Data tab view of the schema browser
Modify source to wrap table names in double quote
**Related Issue** : #1464 #1099 
1. goto druid workbench
2. popup schema browser
3. select table starts with a number
4. click data tab
> #1464 add double quote to druid table name for workbench data preview

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/json/PrepJsonUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
JSON property can have a null value.
When creating a snapshot in json this caused a null exception when creating a snapshot in json
[#1455](https://github.com/metatron-app/metatron-discovery/issues/1455)
1. edit rule on dataflow
2. using set rule makes any column to have a null value
3. make a snapshot
and
1. create a dataset with JSON file
2. create a dataflow with the dataset
3. create a snapshot with them
Both must be successful.
> transform snapshot uses JSON parser

- discovery-frontend/src/app/admin/user-management/component/group/detail-group/detail-user-management-groups.component.ts
- discovery-frontend/src/app/admin/user-management/service/groups.service.ts
사용자 그룹에 20명을 넘는 멤버를 할당하는 경우 20명 까지만 노출됨
**Related Issue** : #1425 
* 그룹 관리 화면에서 멤버를 20명 이상 할당합니다.
* 할당 후 멤버가 20명 이상 표시되는지 확인합니다.
* 다시 할당 팝업에서 들어갔을 때 지정된 수 만큼 표시되는지 확인합니다.
> #1425 If you assign more than 20 users to a user group, only 20 or fewer are exposed

- discovery-frontend/src/app/dashboard/component/update-dashboard/dashboard.layout.config.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-list-filter.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-range-filter.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-relative-filter.component.ts
대시보드 편집 화면에서 필터 edit 을 클릭하면 팝업이 떴다가 사라짐
**Related Issue** : #1447 
* Edit dashboard
* 필터위젯의 수정 버튼 클릭
* 필터 위젯의 수정 팝업이 정상적으로 표시되는지 확인
> #1447 Filter edit popup error 

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
Currently, when the file has a BOM of UTF-8, it cannot be read.
This is because, typically, for UTF-8, there is no BOM.
Anyway, it has been fixed.
Please refer to the issue below. It contains a sample file attached and a detailed bug scenario.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1492
Ran locally.
> #1492 bug-fix on BOM of UTF-8

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/dashboard/component/dashboard-layout/dashboard.layout.component.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/app/page/page.component.ts
I didn't set an advanced filter but I found unnecessary advanced filter specification when saving configuration spec.
**Related Issue** : #1472 
* Go to 'Dashbard' and Chart widget.
* add the filter edit view on widget using "+" on filter panel
* select any filter and crate any chart.
* turn on developer tools and move the network tab
* Save widget and you can see "/api/widgets" response
> #1472 remove adding unnecessary advanced filter specification even if doing nothing

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
- discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
Dataset/ snapshot name markup changed from textarea to input.
#1532 
1 . - Go to dataflow detail -> click one dataset ->
You can't use shift and enter together.
- With description, you can only apply changes when you click on tick button.
This is because you can use new line with description.
2 . Go to snapshot detail -> change snapshot name -> You can't use shift and enter together.
> F#1532 fix dataprep name input

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfWindow.java
Changed new column order of windows rules so that the new columns are located in the order of expressions user entered.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1380
Run locally.
> #1380 changed new column order of window rules

- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
다중 필터 선택 변경 시, All 항목 선택 오류 발생함
**Related Issue** : #1444 
1. 다중선택 필터에서 전체 값보다 1건이 적게 미리 값을 설정하고 대시보드를 저장합니다. (2개인 경우 1개를 미리 선택해둠)
2. 해당 대시보드 접근 후 위젯에서 필터를 선택하여 전체값이 선택되고 난 뒤
3. 원래 선택되어 있던 값을 체크해제 할 시 정상적으로 동작하는지 확인합니다.
> #1444 Multiple filter selection error

- discovery-frontend/src/app/common/component/grid/grid.component.ts
- discovery-frontend/src/assets/grid/slick.grid.override.css
- 워크벤치의 데이터 그리드에 공백이 포함되어 있으면 정렬 오류가 발생한다
헤더를 클릭할 때 정렬 결과가 부정확하다 그리고 헤더를 클릭할 때 화살표 아이콘의 위치가 잘못된다.
**Related Issue** : #1489 
- 워크벤치 화면에서 아래 쿼리 실행 후 [수정 결과](https://github.com/metatron-app/metatron-discovery/issues/1489#issuecomment-469116107)와 같이 나오는지 확인한다
```sql
select "1", "a"
union select "2", "b"
union select "3", "";
```
> F#1489 A sort error occurs if the data grid contains blanks

- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
We do not know the date format for the timestamp type.
So, when creating a temporary data source, convert it to STRING type and process it.
#1494 
1. goto workbench
2. execute query contains timestamp field.
3. click chart preview button
4. see chart preview without error
> #1494 convert TIMESTAMP field's datatype to STRING

- discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/JupyterBuilder.java
Jupyter Notebook is not created.
**Related Issue** : #1570 
1. 워크북에서 주피터 노트북 설정
2. 노트북 버튼 생성
3. 주피터 노트북 생성이 정상적으로 되는지 확인
> #1570 JupyterBuilder.java Invalid SPARK_HOME setting

- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
워크벤치 생성 시 브라우저에서 데이터 커넥션 목록을 표시하지 못하는 오류 수정. 상세한 내용은 아래 이슈 코멘트 참조
https://github.com/metatron-app/metatron-discovery/issues/1564#issuecomment-469913524
#1564 
* API 변경에 따라 영향 받는 화면이 아래 두 개인 것을 확인 했고, 정상적으로 동작하는 것을 확인 하였습니다.
* 워크스페이스에서 워크벤치 생성 화면
* 관리 > 워크스페이스 > 연결된 리소스
* SK Telecom 환경이 아닌 로컬에서 해당 오류를 재현하려고 했지만 재현하지 못했습니다.
> #1564 It is not possible to create a new workbench by returning too many connection lists.

- discovery-frontend/src/app/meta-data-management/metadata/metadata-detail-information.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
- 메타데이터 인포메이션 화면에서 설명이 작성되지 않았을 경우 기본문구로 “No description”을 노출되고 있는데 
실제 사용자가 입력한 내용은 아니라서 시각적으로 구분 되도록 폰트 톤다운 처리합니다
- 메타데이터 인포메이션 화면에서 설명이 없는 경우 폰트 톤다운 처리가 되었는지 확인한다
> F#0 Modifying the font color when the metadata has no explanation

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
In the case of mysql, a blank column name is returned if there is no column name.
So if it is an empty column name, convert it to an 'anonymous' column name.
**Related Issue** : #1489 
1. goto mysql workbench
```
select "1", "a", ""
union select "2", "b", ""
union select "3", "", "blank"
union select "4", " ", "space";
```
3. see result
> #1489 add prefix 'anonymous' if column label is empty.

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
1. A JSON snapshot now keeps the column order of the W.DS.
2. CSV snapshots do not lose their headers.
Run locally.
> #fn use ordered map for JSON snapshot. bug-fix on CSV snapshot.

- discovery-server/src/main/java/app/metatron/discovery/common/CommonLocalVariable.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/widget/shelf/GeoShelf.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GeoBoundaryFilterQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
- discovery-server/src/test/resources/sql/test_gis_datasource.sql
- 맵 차트내 multiple layer 스펙을 변경하면서 기존스펙과 충돌이 발생하여 위젯 복사 및 기존 차트 스펙 저장시 오류를 발생시킵니다.
- 맵 차트내 multiple layer를 호출시 2개의 쿼리를 호출하는데, 이때 동일한 queryId 를 호출하여 간헐적으로 쿼리 수행 오류가 발생합니다. 
- 기존(3.2-rc2) 맵이 추가된 대시보드 내에서 대시보드 편집 후 저장 하여 정상동작합니다. 
- 멀티 레이어를 설정한 맵뷰내에서 차트를 줌인/아웃 또는 이동을 여러번(5회 이상) 진행후 오류없이 정상 동작합니다.
> #fn add spec backward for geoshelf and fix duplicated query id

- discovery-frontend/src/app/app.module.ts
- discovery-frontend/src/app/common/gaurd/stagedb-enabled.guard.ts
- discovery-frontend/src/app/data-storage/service/storage.service.ts
- discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
- discovery-frontend/src/app/layout/layout/layout.module.ts
- 메타데이터에서 데이터 타입 필터링이 상이하게 동작합니다.
최초 조회시 `ALL, Datasource, Hive`
두번째 조회시 `ALL, Datasource, StagingDB, Hive`
- 메타데이터에서 데이터 타입 필터링에 `스테이지 DB`가 나오는지 확인합니다
> #0 Change when to invoke the Stage DB Activation Check API

- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-select/file-select.component.ts
파일 데이터소스 생성화면에서 기존 파일에서 새로운파일로 업로드시 기존에 적용된 row 가 바뀌지 않던 현상 수정
아래와 같은 초기화 반영
```
파일 변경시 100 row 로 조회 => 결과가 100미만이면  row 를 다시 최대 max값(100) 으로 수정
head column 체크시 100 row 로 조회  => 결과가 100미만이면 row 를 다시 최대 max값(100) 으로 수정
```
release test
1. 파일 데이터소스 생성
2. 생성할 파일 업로드 (업로드 성공후 row 확인)
3. 파일 변경 또는 하단의 use column head 체크
4. row가 이전 값으로 고정되지 않는것 확인
> Fix row number error in file datasource create

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/HiveTableInformation.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/CsvFileFormat.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
fix typo in CsvFileFormat.java
delimeter -> delimiter
**Related Issue** : #1613 
1. create datasource with tab delimiter csv file
[geo_seoul_roads.csv.zip](https://github.com/metatron-app/metatron-discovery/files/2944497/geo_seoul_roads.csv.zip)
2. change delimter to '\t'
3. uncheck "use the first row as head"
4. create datasource
5. after creation, see data tab
> F#1613 attribute typo in csv file format delimiter

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfMerge.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Revision.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
1. Fixed wrong stageIdx after UPDATE (also after REDO)
2. Remove the original columns after merge transformation
3. Prevent auto-header when there's duplication or numbers or nulls on the 1st line.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1599
1. Check https://github.com/metatron-app/metatron-discovery/issues/1599 please.
2. Open the dataset of https://github.com/metatron-app/metatron-discovery/issues/1599 -> merge **itemNo**, **speed** -> the new column should be located before **weight** and **itemNo**, **speed** are removed.
3. Import & wrangle [header_test.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2952136/header_test.csv.txt) -> header transformation should be applied.
> F#1599 wrong stage idx after redo

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrUploadFile.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/repository/PrUploadFileRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
Uploaded files are stored locally on the server until now.
but now, those will be copied to final destination when uploading the files
[#1651](https://github.com/metatron-app/metatron-discovery/issues/1651)
1. When uploading files, 
The upload location should be selectable as LOCAL or HDFS if you set the settings 
'localBasedIr', 'stagingBaseDir'
2. Atfer the dataset was created
The file should be saved in the location you choose. LOCAL or HDFS
You can check the file location in the dataset details
> #1651 upload files to finaldestination

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/ColumnDescription.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyOrcWriter.java
We used to store the arrays as struct type in Hive snapshots.
Now we use Hive array type when the sub-types are all the same, like string, string, string or long, long, long, ...
When the sub-type are mixed, we ㅗave no choice but to store as struct type.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1541
1. Import and wrangle [sales_well_renamed.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2966020/sales_well_renamed.csv.txt)
2. Select division and market columns by clicking with shift.
3. Nest via context menu or entering transform rules on the bottom of the main transform page.
4. Make sure that the type should be array.
5. Click "Snapshot button"
6. Select Hive snapshot. (by default, we use ORC type)
7. Click the new snapshot to see …
> #1541 In Hive snapshots, dataprep array type is store as Hive arrays

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/ContinuousTimeFormat.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
fix error display time due to processing time zone (backward compatibility for changing time format)
**Related Issue** : #1660 
1. ingestion from spec([sample_datehour_ingestion_spec.json.txt](https://github.com/metatron-app/metatron-discovery/files/2968987/sample_datehour_ingestion_spec.json.txt)) and orignal file([sample_ingestion_datehour.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2968984/sample_ingestion_datehour.csv.txt))
2. Check whether creating datasource on coodinator console (named by test_datehour_datasource)
3. Create datasource from "metatron Engine"  (find "test_datehour_datasource")
4. Create workbook, dashboard linked  "test_datehour_datasource", create chart
5. Make sure it appears the same as the original time value
> error display time due to processing time zone (backward compatibility for changing time format)

- discovery-frontend/src/app/common/component/chart/type/label-chart/label-chart.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/domain/datasource/data/time-compare-request.ts
- discovery-frontend/src/app/domain/workbook/configurations/filter/time-relative-filter.ts
relative filter 처리시 time zone 속성 명이 잘못 전달 되어 time zone 연산시 문제를 일으킵니다. 
**Related Issue** : #1660 
#1661 진행 후, 대시보드내 relative time filter 내 호출중 timeZone 값이 정상적으로 전달되는지 확인
> Fix setting parameter name (timezone -> timeZone)

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
Save scroll position when grid changes
#1638 
1 . Use dataset with more than 20 columns
2. Go to dataflow main grid
3. Open multi column rename popup
4. 
5 . Check if scroll position is saved even after grid is reloaded.
> #1638 save scroll position in rename

- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
Even when `/stagedb` returns Hive is configured,
`/connections/query/hive/databases` returns error.
When  `/connections/query/hive/databases` returns error do not show alerts, instead remove hive option from snapshot create popup
#1665 
Check if hive option is removed from create snapshot popup when 
`/connections/query/hive/databases` returs error
> #1665 Remove alert when fetching staging db returns error

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/Histogram.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepHistogramService.java
If long values are too big, histogram labels get overflowed when it is increasing beyond the long type limit.
Besides, there was an inexplicable long type processing code when loading CSV type files.
This code was the origin of the bug. Actually, the overflow case was not the main reason, but it was lucky.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1667
Run locally. Please refet to https://github.com/metatron-app/metatron-discovery/issues/1667 to get the test scenario.
> #1667 bug-fix in histogram when long label values overflow

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.html
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-select.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
Parameter for fetching database information was wrong.
Presto should have catalog
Postgre should have database
#1588 
First make Make postgre, and presto data connections  from LNB -> Management -> Data storage -> Data connection.
Go to dataset list -> click create new database type -> 
1 . select postgre connection -> validate -> check if you can make dataset 
2 . select presto connection -> validate -> check if you can make dataset
> #1588 Fix parameter when database is presto and postgre

- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/db-create-component/db-select-data/db-select-data.component.ts
Data preview fails when creating data source.
**Related Issue** : #1664 
1. create datasource
2. select database
3. select hive connection
4. select table or execute select query
5. show preview
> #1664 Data preview fails when creating data source

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDataflowService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Currently, a cloned dataset is named after the upstream I.DS.
Now, it will be named after the W.DS that is being cloned.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1681
1. Click a W.DS in the dataflow detail (chart) page.
2. Click the context menu on the right panel.
3. Clone
4. The new W.DS will be named as <W.DS> (1)
5. If the name exists, <W.DS> (2) will be.
6. If exists, then +1 (again & again)
7. TMI, 100,000 is the limit. Cloning will fail with assertion.
> #1681 name after W.DS not I.DS

- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/snapshot-source/snapshot-preview.component.html
데이터소스 생성 화면에서 스냅샷 미리보기의 row 수가 제대로 표시되지 않던현상 수정
통합테스트
1. 데이터소스 생성 > 스냅샷으로 생성
2. row가 10000건이 넘어가는 스냅샷 선택
3. 우측에 열리는 preview에서 row수가 올바르게 표시되는지 확인
> Fix field length in datasource create snapshot preview 

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
When rename popup is opened via snapshot create popup and is in edit mode
transform API is failed due to wrong ruleIdx.
룰을 수정하는 중에 스냅샷 생성 팝업에서 Rename을 하려고 하면 ruleIdx가 틀려서 룰이 적용되지 않음
#1717 
Check #1717 for details.
1 . Go to dataflow main grid
2 . Add at least 3 ~ 5 rules. (any)
3 . Change one column to '컬럼1'
4 . 
5 . Rename rule should be applied at the end of the rule.
> #1717 Fix ruleIdx when sending rename transform api

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
if localBaseDir or stagingBaseDir is not exist
Invalid directory created because File url has not URI schema
So this has been replaced by a scheme-sensitive way
[#1735](https://github.com/metatron-app/metatron-discovery/issues/1735)
1. Set the nonexistent path to localBaseDir or stagingBaseDir
2. Start the server 
3. upload a file to the destination
'file:' or 'hdfs:' should not be created and file upload should succeed
> #1735 create new directory without schema problem

- discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.html
- discovery-frontend/src/app/data-preparation/dataset/add-dataset-dataflow.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.html
- discovery-frontend/src/assets/css/metatron/popup/metatron.popup.99Preperation_dataset.css
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/i18n/ko.json
Some words are not translated in korean.
No issue
1 . Go to dataset list
2 . Click one dataset
3 . Click add `Add to existing dataflow`
4. Check if name and dataset is translated properly
------ 
1 . Change browser setting to korean
2. Go to dataset list -> click new dataset -> check if 파일 is changed to  My file
> Fix some translations in dataprep

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
Did not move to last step when using query type to make dataset
No issue
Go to dataset list -> click create new dataset -> click staging db -> 
use QUERY tab -> click next -> should move to next step. Entering dataset name
새로운 데이터셋 생성 버튼 클릭 -> Staging db 선택 => query tab 이용 -> 다음 선택 -> 데이터셋 이름 정하는 화면으로 이동하면 OK
> Fix dataset creation error

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/DataSourceServiceTest.java
Can not set a NONE granularity when importing a datasource from druid (not through metatron discovery).
#1760 
1. I've added a unit test for null granularity
2. For manual testing,
2-1. Create a datasource with NONE granularity into druid (not through metatron discovery)
```
"granularitySpec": {
"type": "uniform",
"segmentGranularity": "HOUR",
"queryGranularity": "NONE",
"intervals": [
"2018-09-24/2019-03-25"
]
}
```
2-2. Import the above datasource into metatron discovery.
2-3. Imported successfully.
> Fix datasource setter when engine's granulraity is set NONE or null

- discovery-server/src/main/java/app/metatron/discovery/util/CsvProcessor.java
- discovery-server/src/main/java/app/metatron/discovery/util/csv/CsvTemplate.java
Extend the number of csv file's columns. 
It is increased from 512 to 2048.
#1748 
1. Create a csv file with over 1000 columns
2. Go to 'Management' > 'Data storage' > 'Datasource' Menu and create a datasource with above csv file.
3. Datasource is created successfully.
This is a first aid measure that discussed with mates.
**It is necessary to manage within the configuration** so will be cleared soon.
> Extend the maximum number of csv file's columns

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
The data connection filter condition is missing a shared workspace that I am the owner
1. goto data connection
2. click publish filter dropdown.
3. see workspace that my shared workspace
> add my shared workspace to data connection filter

- discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
맵차트에서 레이어 유형을 변경하는 경우, 데이터가 사라지는 케이스가 있습니다. 
**Related Issue** : #1785  
1. 맵차트에서 선반에 값을 추가합니다. 
2. 레이어 유형을 변경하여 데이터가 잘 나오는지 확인합니다.
> #1785 fix multi data disappers map chart

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/common/constant/common.constant.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.ts
- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page.component.ts
1. 연산행 레이어가 추가되었을 때 맵차트가 대시보드에서 그려지지 않는 문제가 있습니다.
2. Geo 데이터를 선택하면 Geo 데이터는 맵차트를 이용해야 한다고 경고창이 나옵니다.
**Related Issue** : #1463 
1. 차트 생성 페이지로 이동합니다.
2. Geo 데이터를 선반에 옮겼을 때, 그릴 수 있는 차트 표시로 지도 차트가 표시되는지 확인합니다.
3. 연산행 레이어를 생성하고 저장 한 후, 대시보드에서 맵 차트가 표시되는지 확인합니다.
> fix map chart error

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/CsvFileFormat.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/CsvStreamParser.java
CSV ingestion spec's delimiter is inserted two of backslash when using characters that contain a backslash.
For example, when using \n for the delimiter, it will be generated \\n
We don't like to this situation and just want to pass by the same as the input.
1. Create datasource with a CSV file.
2. Check ingestion spec and delimiter is set properly (not with double backslash)
```json
"delimiter": "\t",
"recordSeparator": "\n",
````
> Set delimiter properly on CSV file parser

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
We only need to set delimiter and line separator on the not default CSV file.
Otherwise, in cases not through UI like JDBC or hadoop, it can defect.
#1807
> Should not be set delimiter on default csv

- discovery-frontend/src/app/dashboard/filters/configure-filters-update.component.ts
- discovery-frontend/src/app/dashboard/filters/configure-filters.component.html
- discovery-frontend/src/app/dashboard/filters/configure-filters.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
1. 대시보드 화면에서 맵차트에 글로벌 필터가 적용되지 않는 문제가 있습니다.
2. 필터 추가 화면에서 필드를 선택한 후 다시 되돌아가면 이전에 선택했던 데이터소스가 아닌 다른 데이터소스가 선택되어 있는 경우가 있습니다.
1. 지도차트를 생성 한 후 대시보드에서 글로벌 필터가 적용되는지 확인합니다.
2. 필터 추가 화면에서 데이터소스를 변경하고 필드를 선택한 후에 다시 필드 선택 화면으로 되돌아 갔을 때, 이전에 보았던 데이터소스의 필드 목록이 나오는지 확인합니다.
> Fixed an issue where filters were not applied in map charts.

- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
사용자가 생성한 GEO타입 중 좌표계 선택박스가 disable 처리되던 현상 수정
- 사용자가 생성한 GEO 타입
- 변경된 GEO 타입 (valid)
- 변경된 GEO 타입 (invalid)
통합테스트
1. 데이터소스 생성 > config setting 
2. 우측 상단의 add column을 선택하여 geo point형 컬럼 선택
3. select 박스가 활성화 되는지 확인
> Fix geo coordinate disable selectbox error

- discovery-frontend/src/app/page/page-pivot/popup-value-alias.component.html
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
Fixed "value alias" function error.
Also, since the field name display in the value alias popup view is "undefined", this part has also been corrected.
**Related Issue** : #1821 
1. Create workbook and dashboard in the workspace  (with any datasource)
2. Create a chart widget
3. Click option for a column in the data panel
4. Click "Alias for Value"
5. Make sure that the value alias pop-up displays normally. 
6. Make sure  field name and name alias in the alias popup view is correct
> fix error for value alias

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
On occasion, an opening the detailed snapshot is failed as soon as its snapshot created. The pooling progress bar is not being updated as it moves toward the completion.
Related Issue : #1721  
Run locally according to #1721
> #1721 failure of continuous update in opening detailed snapshot

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
워크벤치 쿼리 결과에서 마지막 row 의 마지막 column 값이 확인 불가함
**Related Issue** : #1504 
1. 워크벤치에서 쿼리 실행합니다.
2. 쿼리 결과가 표시된 후 스크롤을 제일 아래로 내렸을 떄 아이콘 이미지가 숨겨지는지 ( 흐릿하게 ) 확인합니다.
> #1504 Icon overlaps the last column of query result

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/scroll-loading-grid.component.ts
Fix unselecting rows and columns logic from grid component
#1827 
1 . Go to dataflow main grid (use dataset with at least 500 rows)
2 . Click histogram -> context menu -> delete
3 . Scroll down again and again. No rows should be selected
> #1827 Fix unselect rows and column method in grid component

- discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/create-permission-schema.component.html
- discovery-frontend/src/app/dashboard/component/create-dashboard/create-board-complete.component.html
- discovery-frontend/src/assets/css/polaris.v2.layout.css
1. 실제 스크롤되는 영역과 스크롤의 위치가 다릅니다
2. 팝업의 헤더(제목과 스텝) 부분에 신규 디자인을 적용해야 합니다
**Related Issue** : #1197 #1199 
1. 대시보드 생성 화면과 퍼미션 스키마 생성 화면에서 제목과 버튼은 고정되고 내용부분만 스크롤 되어야 합니다.
> #1197 Improved scrolling UI when creating dashboard

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
If a postgresql's database has multiple schemas, table listing query doesn't execute properly.
So I changed the existing query's target column
`
obj_description(TABLE_NAME::regclass, 'pg_class') as comment
`
to
`
obj_description((TABLE_SCHEMA||'.'||TABLE_NAME)::regclass, 'pg_class')
`
because It should be structured like **'schema'.'table'**
#1823 
1. Create a datasource with Postgresql DB. (contains a database with multiple schema)
You can use 'Adventureworks' database.
2. In the 2nd step of creating datasource, you can preview the table.
> bug fix in the table listing query in postgres

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/dashboard/filters/component/timeUnit-select.component.ts
- discovery-frontend/src/app/page/chart-style/secondary-indicator.component.ts
- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
- discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
Currently, granularity units for the timestamp column are configured to minutes. Given the nature of the real-time data source, it should be expressed in seconds.
**Related Issue** : #1840 
1. 차트 생성 화면으로 이동합니다.
2. 선반 설정에서 granularity 설정에서 초 단위가 선택이 되는지 확인합니다.
> #1840 add "second" granularity for timestamp column

- discovery-frontend/src/app/data-storage/component/connection/connection.component.ts
데이터소스 생성 > 데이터베이스로 생성 에서 기존에 생성된 데이터커넥션을 이용할 때,
해당 커넥션이 catalog가 존재하는경우, 커넥션 불러오기가 제대로 표기되지 않던 현상 수정
#1868 
1. 데이터소스 생성 > 데이터베이스로 생성
2. 데이터 커넥션 선택화면에서 catalog를 사용하는 커넥션 프리셋 선택
3. 2에서 선택된 커넥션 정보가 화면에 제대로 표시되는지 확인
> #1868 Fix connection parameter in create datasource

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/widget/shelf/LayerView.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/funtions/ShapeCentroidYXFunc.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/funtions/StructFunc.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
When loading a WKT column of the Point type, changed to longitude latitude storage structure of struct type. As a result, the point-related query structure has been simplified.
**Related Issue** : #1871 
1. Using the below file, create datasource.
[newyork_subway_entrance.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3087529/newyork_subway_entrance.csv.txt)
2. In the ingestion step, specify the "the_geom" column as the column of the point type.
3. Make sure the ingestion is successful, and check that the actual map chart is well represented.
> #1871 change ingestion method for Point type WKT column

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/page/chart-style/color-option.component.ts
If you change the line chart to Custom Color and then add dimension, the color will return to the initial palette.
**Related Issue** : #1784 
1. create line chart
2. color setting > cusom color setting
3. change color
4. add dimension
> #1784 line chart custom color initialized

- discovery-frontend/src/app/meta-data-management/component/choose-column-dictionary/choose-column-dictionary.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
Code table detail page : No margin between two buttons
Column dictionary popup : Column name hiding behind rows.
No issue
1 . Go to metadata -> code table ->  detail page ->  
Check if there's marging between two buttons.
2 . [BROWSER LANGUAGE MUST BE ENGLISH!] Go to metadata detail -> column schema tab
Check if second column name is shown with no error
> Fix css in code table detail and column dictionary popup

- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
메타데이터 > 컬럼 스키마 화면의 `컬럼 딕셔너리`, `코드 테이블` 아이콘 클릭시 팝업이 열리지 않는 문제를 수정합니다
#1540 
1. 메타데이터 > 컬럼 스키마 화면으로 이동
2. 컬럼 딕셔너리 아이콘과 코드 테이블 아이콘을 클릭했을 때 팝업이 열리는지 확인합니다
> #1540 Modify column dictionary and code table icon click event

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
Data preparation has been designed to work on the local file system without Hadoop or Hive.
But, when I ran without hadoop configuration, an error popped out.
For more description, take a look at the related issue.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1894
Ran locally.
> #1894 fix to work when only local system is configured

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Removed unnecessary column name check while snapshot generation.
We do not need to check middle datasets. Only the final dataset matters.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/1912
Run locally.
> #1912 do not check upstream's column name for hive snapshot

- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/dialect/JdbcDialect.java
- discovery-extensions/mssql-connection/src/main/java/app/metatron/discovery/MssqlConnectionExtension.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionHelper.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/DruidDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/MySQLDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PrestoDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/query/expression/NativeProjection.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
We need to change default quote for druid JDBC according to calcite spec.
Because the default identifier quoting character is double-quote("), so back-quote(`) would be an error without additional configuration.
- As-Is: using ` for quote
- To-Be: changed \\" for quote
#1911 
1. Create a data connection with the druid.
2. Create datasource with the above connection. **(as linked type)**
3. Create a dashboard with the above datasource.
4. Databoard created successfully.
> #1911 Change default quote in druid jdbc

- discovery-server/src/main/java/app/metatron/discovery/common/web/OauthFilter.java
- discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
When clientId is diffrent and the access token is expired, the page is forwarded to login page.
**Related Issue** : #1922 
1. Sign in.
2. Wait 12 hours (access token need to be expired)
3. Try to sign in at the external apps.
> #1922 Fix access denied when clientId is different

- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-schema-browser/detail-workbench-schema-browser.component.ts
workbench schema browser에서 database 변경 후 
schema browser를 닫은 뒤 LNB에서 테이블명을 검색하면 목록 다르게 표시되는 부분을 수정
2. schema browser을 열고 database 변경 후 창을 닫습니다.
3. LNB 영역에서 테이블명으로 검색 시, 선택되어있는 테이블 목록에서 검색된 결과가 표시되는지 확인합니다. 
schema browser에서 데이터 소스 변경 시, 문제가 없는지 체크합니다.
> fn fix change datasource in schema browser

- discovery-frontend/src/app/common/component/input/input.component.ts
- discovery-frontend/src/app/common/service/image.service.ts
- discovery-frontend/src/app/dashboard/component/dashboard-datasource-combo.component.html
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/page/page.component.html
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/polyfills.ts
1. 대시보드 생성후 -> 편집화면 진입 -> 위젯 이 없는 상태에서 Done 버튼 클릭시 오류 발생
2. 대시보드 편집 화면 우측 패널 > 데이터 패널 내 dimension/measure 컬럼 정보가 나타나지 않음
3. 대시보드 데이터 소스 View 팝업내 데이터 그리드 /컬럼 상세 정보가 나타나지 않음
4. 대시보드 내 위젯 이미지 다운로드 안됨
1. 위젯 이 없는 상태 대시보드 저장이 되는지 확인합니다.
2. 대시보드 편집 화면 우측 패널에서 필드 목록이 표시되는지 확인합니다.
3. 데이터 소스 View 팝업 내 데이터 그리드가 표시되는지 확인합니다.
4. 대시보드 내 위젯 이미지 다운로드가 되는지 확인합니다.
> fix dashboard critical issues in ie

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/csv/PrepCsvUtil.java
If a CSV file has UTF-8 BOM, reader also reads BOM header as data
so StreamReader will remove the BOM 
[#1971](https://github.com/metatron-app/metatron-discovery/issues/1971)
1. create a dataset has with a CSV file has UTF-8 BOM and has header fields
2. create a dataflow and edit rules
3. add a derive rule with first column
If thers is the first column name in column list, It works
> #1971 to read csv without BOM

- discovery-frontend/src/app/dashboard/filters/configure-filters-select.component.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
동일한 필드명을 가지는 두개의 데이터 소스를 이용하여 대시보드를 생성할 경우, 각각의 데이터소스에서 동일한 필드명에 대한 필터를 생성할 수 없습니다. 
**Related Issue** : #1901  
1. 동일한 필드명(ex:category) 이 있는 두 개의 데이터소스(sales_A,sales_B)를 이용하여 대시보드를 생성합니다.
2. 대시보드 편집 화면에서 sales_A 데이터소스를 이용하여 category 필드에 대한 필터를 생성합니다.
3. 다시 필터 생성 화면을 띄워 sales_B 데이터소스를 이용하여 category 필드를 생성합니다.
4. 필터가 정상 동작 하는지 확인합니다.
> #1901 filter; if two table has same column names, it cannot apply to both table

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceRepositoryImpl.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workspace/WorkspaceRestIntegrationTest.java
- discovery-server/src/test/resources/sql/test_import_workspace_list.sql
When you move a workbook, you can see the workspaces that can be moved. 
However, the workspace that can not be moved was searched and It was fixed.
**Related Issue** : #1512 
1. Create workbooks and dashboards from datasource published only to your personal workspace.
2. Select the workbook you created and click the "move selection" button at the bottom.
3. Confirm that no workspaces other than your personal workspaces appear.
- If datasources in your workbook is an open data only, you should see a list of workspaces that I have edit permission.
- If the data source in the workbook is not open data and is published to the workspace you want to move, that workspace must also be listed.
> #1517 fix an error in retrieving the list of movable workspaces

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
IE에서 워크벤치 진입 후 왼쪽에서 테이블을 선택하면 오른쪽 화면이 깨지는 이슈를 수정합니다. 
1. IE에서 워크벤치 화면으로 이동합니다. 
2. 워크벤치 LNB에서 테이블을 선택 시, 오른쪽 에디터 화면에 깨지지 않는지 확인합니다. 
마크업이 깨진 부분이 없는지 확인합니다.
> fn ie issue when table select in workbench

- discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
- discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
- discovery-frontend/src/app/user/profile/profile.component.html
- discovery-frontend/src/app/user/profile/profile.component.ts
1. 사용자 프로필 이미지를 수정하였을 때 저장 버튼이 활성화되지 않는 오류가 있습니다.
2. 대시보드내 데이터소스 패널에서 10번째 필드가 표시되지 않는 오류가 있습니다.
1. 상단 메뉴에서 이미지를 불러오고 저장 버튼이 활성화 되는지 확인합니다.
2. 저장 후 프로필 이미지가 바로 변경되어 표시되는지 확인합니다.
3. 대시보드 편집화면에서 데이터소스 패널을 열어 필드 목록이 제대로 표시되는지 확인합니다.
> Save button activation error when editing profile image

- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/dialect/JdbcDialect.java
- discovery-extensions/mssql-connection/src/main/java/app/metatron/discovery/MssqlConnectionExtension.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/DruidDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/MySQLDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PrestoDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceErrorCodes.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceEventHandler.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunner.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/JdbcIngestionJob.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilderTest.java
Re-verify the query builder for incremental ingestion for each DB type.
Below is a sample of each Where Clause for each format of Timestamp Field.
```
//1. If the field of the timestamp role is unixtime
//Presto
//sec : secUnix >= to_unixtime(cast('2018-07-01 00:00:00' as timestamp))
//ms : msUnix >= to_unixtime(cast('2018-07-01 00:00:00' as timestamp)) * 1000
//Hive
//sec : secUnix >= unix_timestamp('2018-07-01 00:00:00', 'yyyy-MM-dd HH:mm:ss')
//ms : msUnix >= unix_timestamp('2018-07-01 00:00:00', 'yyyy-MM-dd HH:mm:ss') * 1000
//MySQL
//sec : secUnix >= UNIX_TIMESTAMP('2018-07-01 00:00:00');
//ms : msUnix >= UNIX_TIMESTAMP('2018-07-01 00:00:00') * 1000;
//MSSQL
//sec : secUnix >= CAST(DATEDIFF(s, '1970-01-01', CAST('2017-04-21 00:00:00' as DATETIME)) as BIGINT)
//ms : msUnix >= …
```
> #1948 date function for incremental ingestion

- discovery-server/src/main/resources/templates/api/email/user_reset_password.html
- discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
- discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
- discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
- discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
- discovery-server/src/main/resources/templates/api/email/user_signup_request.html
Remove useless terms on bottoms of accounts mail.
N/A, just for clearity.
1. Send account mail by actions as follow:
- Create an account by an admin user.
- Send request for register an account
- Approve request for registration
- Deny for registration
- Reset password
2. Check the bottom of E-mail that disappeared 'Privacy' and 'Terms of service'.
No.
It just removes the thymeleaf lines, so don't need to be added some test codes.
> Remove useless terms on bottoms of accounts mail

- discovery-frontend/package.json
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/linked-resources/detail-workspace-linked-resources.component.html
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/detail-workspace/component/viewer/resources-view.component.html
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.html
- discovery-frontend/src/app/dashboard/component/update-dashboard/datasource-panel.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-sort.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.html
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
- discovery-frontend/src/app/layout/layout/component/gnb/gnb.component.ts
- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/app/workbook/workbook.component.html
- discovery-frontend/src/app/workbook/workbook.component.ts
- discovery-frontend/src/assets/css/metatron/component/component.table.css
- discovery-frontend/src/assets/css/polaris.v2.layout.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
1. 사진 저장 후 사용자 이미지가 나타나지 않는 현상이 있습니다.
2. 데이터소스 스키마 설정 팝업에서 입력창이 정상적으로 표시되지 않습니다.
3. 데이터소스명과 "open data" 라벨 사이 마진이 넓습니다. 
administration > workspaces list > detail  ( linked resources >datasource > more popup )
4. 대시보드에서 데이터소스가 없을 때 빈 목록이 나옵니다.
5. 대시보드에서 툴팁이 잘립니다.
6. 대시보드에서 타임스탬프 필터를 삭제할 수 없습니다.
1. 프로필에서 사진 저장 후 사용자 이미지 정상적으로 변경되는지 확인합니다. 
2. 데이터소스 > 상세 > 컬럼 상세 > 컬럼 스키마 설정 팝업에서 입력창이 정상적으로 표시되는지 확인합니다.
3. administration > workspaces list > detail  ( linked resources >datasource > more popup )
"open data" 라벨이 정상적으로 표시되는지 확인합니다.
4. 대시보드에서 데이터소스가 있을 때만 데이터소스 목록이 표시되는지 확인합니다.
5. 대시보드에서 툴팁이 정상적으로 표시되는지 확인합니다.
6. 대시보드에서 타임스탬프 필터를 삭제할 수 있는지 확인합니다.
> Fixed a UI error

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
맵뷰에서 필터 적용시 커스텀 컬러가 초기화 되는 오류를 수정 했습니다.
#1969 
* 내장된 Sales 데이터소스를 사용하여 맵뷰를 만들고 #1969 에 재현 경로에 따라 테스트 하였고 커스텀 컬러가 유지 되는 것을 화인 했습니다.
> #1969 Custom color settings in map charts are initialized when changing other filter conditions

- discovery-server/src/main/java/app/metatron/discovery/KeepAsUnescapeSerializer.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/file/CsvFileFormat.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/CsvParseSpec.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/TsvParseSpec.java
- discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/parser/ParseSpecTest.java
Make it possible to specify a delimiter other than a comma or a tab when ingest by stagingDB.
#1979 
0. I add some unit testing code.
1. Create a table that delimited by a special character.
For example, using this configuration on your DDL : 
`FIELDS TERMINATED BY '\u0001'`
2. Create a datasource with the above table.
3. Create successfully.
The whole type of datasource ingestion needs to be testing.
I think it only defects on StagingDB but you can advise about more point can be affected.
> Support various type of delimiter on hive ingestion

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
When loading into a data source via an ORC table in StageDB, we created an orc schema internally and passed it in the typeString property. The orc schema is created through the jdbc table schema information. 
Because of this, sometimes the datasource ingestion does not work properly when it differs from the actual orc schema, and this is fixed.
According to the engine developer, the typeString value in the ingestion spec. is now meaningless. so, I removed it.
**Related Issue** : #1869 
- Assume that StageDB is set up.
- Assume that a table of type ORC is created in StageDB.
※ It can be created by utilizing Dataprep function. (Create Dataset -> Flow -> Create Snapshot).
1. Go to 'datasource management'
2. Click on 'create datasource' and then 'StageDB' type
3. Select table of orc type
4. …
> Remove 'typeString' property in ingestion spec.

- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceRepositoryImpl.java
The user which has watcher privileges must not be able to move the the workbook to a workspace with watcher privileges.
**Related Issue** : #1850 
1. userA have watcher privileges in workspaceA.
2. workspaceA is allowed on the datasources about workbookA 
2. userA try to move workbookA to workspaceA.
3. Check that it is not visible in the workbook list.
- about all privileges
> #1850 The user must not move the workbook to a workspace with watcher privileges

- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-action-bar.component.ts
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.html
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config-detail.component.ts
- discovery-frontend/src/app/data-storage/component/schema-config/schema-config.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/component/add-column.component.html
- discovery-frontend/src/app/data-storage/data-source-list/component/add-column.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.html
- discovery-frontend/src/app/data-storage/data-source-list/component/storage-filter-select-box.component.ts
데이터소스 생성 > schema 설정 화면 > 컬럼 상세화면의 셀렉트박스 목록이 낮은 해상도에서 잘리는 현상 수정
적용 셀렉트박스 : 타임존 셀렉트박스, 타입 셀렉트박스, 좌표계 셀렉트박스
(적용과 동시에 셀렉트박스가 열려있는경우 스크롤 이벤트가 발생했을때 닫히는 것 추가 - 선택한 컬럼의 설정부분)
#1925 
1. 데이터 소스 생성 > schema 설정 화면
2. 컬럼 선택후 우측 패널에서 타임존, 타입, 좌표계 셀렉트박스를 클릭
3. 셀렉트박스가 우측 패널 위에 floating된 상태로 보이는지 확인
4. 셀렉트박스가 열려있는 상태에서 우측 패널 스크롤 이벤트 발생시 셀렉트박스가 닫히는지 확인
> #1925 Fix combobox in create datasource schema step

- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/edit-filter-data-source.component.html
Hide geo type column from the filtering list
**Related Issue** : #1989 
1. Generate datasource with geo type.
2. Select the datasource
3. Click Column details
4. Click Edit filters.
5. Check that there is a check box in the recommendation filter.
> #1989 hide geo type column from the filtering list

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/PrestoDataAccessor.java
For a presto connection, the valid check succeeds even if it is an invalid catalog.
If the catalog is not valid, inform the user that it is invalid.
**Related Issue** : #1890 
1. Generate or modify Presto connection.
2. Type an invalid catalog
3. Validation check -> Notify invalid Connection.
4. Type a valid catalog
5. Validation check -> Success
> #1890 enhance presto connection valid check if it is an invalid catalog

- discovery-server/pom.xml
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriterTest.java
When querying presto on the workbench,
If the query column has an array type, the column value is not displayed and the package name is output.
**Related Issue** : #1309 
Query presto on the workbench which has an array type.
Check the column value is displayed, not the package name.
> #1309 fix displaying array type of column on presto connection

- discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/MetaStoreProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
- discovery-server/src/main/resources/application.yaml
The partition validation feature is enable only if the current stagedb jdbc information is provided.
**Related Issue** : #2023 
1. Create a new StagingDB datasource
2. Check the partition validation feature visibility if the current stagedb jdbc information is provided.
- stagedb metastore property
> #2023 change the partition validation feature visibility

- discovery-frontend/src/app/meta-data-management/code-table/detail-code-table/detail-code-table.component.ts
- discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.ts
Maintain filters in column dictionary and code table after delete in detail page
No issue. Release test bug
Ran locally.
Go to metadata -> code table / column dictionary ->  apply filters -> move to detail page -> delete -> check if filters are still applied (must not refresh)
> maintain filters in list after deleting

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionFilterService.java
Changed data-connection filter condition to remove stage connection from all registered jdbc implementors.
Because stage connection is a type of connection that user can not create.
**Related Issue** : integrated test
1. move to Data Storage > Data Connection
2. open DB Type layer.
3. You can see that the stage connection has been deleted.
NA
> Remove stage connection from filter criteria in data-connection list

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/column-detail-data-source.component.ts
데이터 소스 상세화면 > 컬럼 상세화면 , 대시보드 > 데이터소스 프리뷰 화면에서 DIMENSION인 컬럼을 조회시 .map alert error 가 발생하는 현상에 대한 방어코드 추가
통합테스트
1. 데이터소스 생성
2. 1에서 생성한 데이터소스로 대시보드 생성
3. 대시보드에서 데이터소스 미리보기 화면 클릭
4. .map error alert이 나타나는지 확인
> Fix alert error in data preview

- discovery-frontend/src/app/admin/user-management/component/group/detail-group/detail-user-management-groups.component.ts
- discovery-frontend/src/app/admin/user-management/component/group/update-group/update-user-management-groups.component.html
- discovery-frontend/src/app/admin/user-management/component/group/user-management-groups.component.ts
- discovery-frontend/src/app/admin/user-management/component/members/detail-member/detail-user-management-members.component.ts
- discovery-frontend/src/app/admin/user-management/component/members/user-management-members.component.ts
- discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/permission-schemas.component.ts
- discovery-frontend/src/app/admin/workspace-management/component/workspaces/shared-workspaces.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.ts
- discovery-frontend/src/app/meta-data-management/code-table/code-table.component.ts
- discovery-frontend/src/app/meta-data-management/column-dictionary/column-dictionary.component.ts
Show previous page when there is no item left in the list
No issue
- Users > member, group
- Prep > Dataset, dataflow
- Workspaces > permission schema, workspaces
- Data storage > Datasource, data connection
- Metadata > Code table, column dictionary
현재 리스트에 아이템이 하나만 있게 만들고(현재 페이지가 1번 페이지가 아닌상태) 상세 화면으로 들어가서 아이템을 삭제합니다.
리스트로 돌아갔을 때 보고 있던 페이지가 아닌 전 페이지로 랜딩 하면 OK
Make sure there is only one item in the list and it is not the first page !
Go into the detail screen and delete the item.
When you return to the list paging number should be : page you were looking at minus 1
> Error when deleting last item in the list 

- discovery-frontend/src/app/workspace/workspace.component.html
Do not show folders when workspace/workbench/notebook filter is applied in workspace list
No issue
[BEFORE] Folders are present event when filter is applied
[AFTER] Hide folders
> Hide folders when filter is applied

- discovery-frontend/src/app/common/component/pagination/pagination.component.html
- discovery-frontend/src/app/common/component/pagination/pagination.component.ts
- discovery-frontend/src/assets/css/metatron/component/component.page.css
Disable next or previous button when there is no next or previous pages
No  issue
Button is disabled when next, previous page does not exist
> Disable next and previous button in paging component

- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspacePredicate.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- fix list workspace for publish at data storage
- fix show csv file header when downloading chart data
1. When publishing workspaces at data storage management, check whether inactive workspaces are not visible.
2. Save table as csv file at chart and check the header.
> fix list workspace for publish at data storage

- discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
- discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
We need to change the link URL of the online manual.
"Online" button will link to
(English) https://metatron-app.github.io/metatron-doc-discovery/en/
(Korean) https://metatron-app.github.io/metatron-doc-discovery/
N/A
1. Open the LNB
2. Click on the 'Online' button at the bottom of the LNB
3. The online manual opens in a new tab.
No!
> Change manual link in the LNB

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
When polaris.dataprep.etl.explicitGC is true, GC occurs explicitly on every transform in snapshot generation.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2144
Run locally, with -verbose:gc JVM option
No.
> #2144 Explicit GC in snapshot when polaris.dataprep.etl.explicitGC=true

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/io/KafkaIoConfig.java
Make IoConfig can be set at real-time ingestion.
#2158 
1. Create a real time ingestion spec.
2. Add a nested object named "taskOptions" into "ingestion" key.
3. Post a datasource
4. Check your ingestion spec that ioConfig is set.
No
> #2158 Enable ioConfig in the real-time ingestion spec

- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspaceController.java
Cannot transfer workspace to user whose name contains dot
**Related Issue** : #2152 
1. Make a shared workspace.
2. Add an user whose name contains dot to a workspace member.
3. Change owner to the user.
User delete and transfer to the user
> #2152 fix transfer workspace to user whose name contains dot

- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.html
- discovery-frontend/src/app/dashboard/filters/component/filter-multi-select/filter-multi-select.component.ts
- discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.html
- discovery-frontend/src/app/dashboard/filters/component/filter-select/filter-select.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/domain/workbook/configurations/filter/inclusion-filter.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
* 대시보드 필터(단건, 다건)에 나타나지 않던 값을 추가로 사용자가 직접 검색하여 사용할 수 있도록 하였습니다.
* 대시보드 편집 > 필터 Search all 검색시 문구를 추가 하였습니다.
#2045 
1. 내장된 Sales 데이터소스를 사용하여 City 차원값을 사용하여 필터를 만들고 대시보드에 추가하였습니다.
2. 대시보드 필터 검색창에 사용자가 문자를 입력하는 경우 '전체 검색' 버튼이 노출되는 것을 확인했습니다.
2. 'York'을 입력하고 '전체 검색'을 누르면 일치하는 값이 필터에 추가되는 것을 확인했습니다.
1. 검색창에 사용자가 문자를 입력하는 경우 안내 문구가 노출되는 것을 확인했습니다.
2. 검색결과가 없는 경우 안내 문구가 노출되는 것을 확인했습니다.
> #2045 Users should be able to search for hidden value in filter widget

- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
When the list of dataset, dataflow is empty, an infinite loop occurs.
**Related Issue** : #2176 
1. Make the list of dataset, dataflow empty.
2. Go to the list.
3. An infinite loop does not occur.
> #2176 fix infinite loop when list is empty

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/DataConnectionController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/job/IngestionJobRunner.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataEventHandler.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
Make runnable without the staging db configuration.
Related properties key is
- polaris.storage
#2179 
1. Delete polaris.storage properties in your 'application.yaml'
2. Run Metatron Discovery
3. Run normally
Changed the condition of the classes that autowiring the StorageProperties.
(Especially in the data preparation and data connection)
Please check related logic @joohokim1 @ufoscw  😄 
**It is configured in the 'local' profile, so a user who not using the 'local' profile can run.**
> #2179 Conditional register the StorageProperties bean

- discovery-frontend/src/app/workbench/workbench.component.ts
서버 재 시작으로 워크벤치에서 웹 소켓 아이디로 연결된 데이터소스 커넥션이 존재하지 않는 경우 사용자가에게 알림으로 표시하고 페이지를 새로고침하여 새로운 웹 소켓 아이디에 데이터소스 커넥션을 생성하도록 수정하였습니다.
사용자에게 알림 메시지와 처리 방식은 AbstractComponent.checkAndConnectWebSocket 를 참고하여 구현 하였습니다.
#2168 
* 워크벤치에서 진입한 상태에서 대기 후 메타트론 서버를 재시작 후 쿼리를 다시 실행 하였을 때 알림 메시지와 페이지가 새로고침 되고 쿼리가 정상적으로 실행 되는 것을 테스트 하였습니다.
* 위와 동일한 상황에서 워크벤치 쿼리 "Retry"를 테스트 하였습니다.
> #2168 DataSource for webSocket is not existed

- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
메타데이터의 타입이 database, stagingDB인 경우 상세화면 > 컬럼 화면에 진입시 에러가 나는 현상 수정
추가로 호출하는 api를 호출하지 않도록 수정
**Related Issue** : #1539 
1. 메타데이터를 database, stagingDB로 생성
2. 1에서 생성한 상세화면 > 컬럼 화면 진입
3. 에러가 발생하지 않는것 확인
추후 database, stagingDB에서 timestamp에 대한 validation이 필요한 경우 해당기능을 수정해야됩니다.
> #1539 Fix database, stagingDB type error in metadata column

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
There is a missing field while creating a dataset of Oracle connection.
so dataset creation was failed
If you can create a dataset of Oracle connection with no error, it is OK
make sure that you are using an extension for oracle connection
> #fn fill all fields of DataConnection class while dataset creation

- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
대시보드 열람 화면에서 위젯 생성 버튼이 위젯에 숨겨지는 문제가 있습니다.
1. 셀렉트박스 형태의 필터 위젯이 우측 상단에 위치한 대시보드를 생성합니다.
2.대시보드 열람화면에서 필터의 셀렉트박스를 펼친 후 우측 상단의 위젯 생성 버튼으로 마우스를 위치합니다.
3. 필터 위젯의 셀렉트 박스가 닫히고 위젯 생성 버튼이 정상적으로 표시되는지 확인합니다.
> Fixed a problem where the create widget button was hidden

- discovery-extensions/oracle-connection/src/main/java/app/metatron/discovery/OracleConnectionExtension.java
When retrieving additional information from an Oracle table, the query was modified because of a permissions problem.
1. create oracle workbench
2. open scheam browser
3. see information tab without error
> #fn changed the query to retrieve table information

- discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field.component.ts
- discovery-frontend/src/app/domain/datasource/datasource.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
schema configure 단계에서 컬럼 편집을 누르고 수정없이 확인을 누르는 경우 invalid에러가 나는 현상 수정
선택된 컬럼이 삭제되었을때 selected 표시가 깨지는현상 수정
컬럼을 선택후 delete layer popup이 뜰때 undo 아이콘이 popup 위에 뜨는 현상 수정
#1920 
schema configure 에서
1. 컬럼편집을 누르고 수정없이 확인을 눌렀을 경우 invalid error가 발생하지 않은채 편집이 닫히는것 확인
2. 선택된 컬럼에서 우측 detail 에서 삭제버튼을 클릭할 경우, selected 표시가 깨지지 않는것 확인
3. undo 아이콘이 하나라도 있을때(삭제된 컬럼이 하나라도 존재하는경우), 다른 컬럼을 체크후 나타나는 하단의 layer에서 delete를 클릭해나오는 layer popup위에 undo 아이콘이 뜨지 않는것 확인
> #1920 Fix edit field name and css in datasource create step

- discovery-distribution/bin/metatron.sh
The upstart mode couldn't be used because there was no logic to extract the flag from the arguments passed to the script.
The upstart mode starts the application in foreground mode which is useful if you use a service manager which manages the lifecycle of the process. I renamed the upstart mode to foreground since it basically just starts the application in the foreground. This mode is also used by other service managers like systemd or Solaris / Illumos SMF.
I have also removed the piping of stdout to log file from the forgeround mode. When using systems like systemd, SMF, etc. these manage the output of the processes they manage. For example in case of systemd by displaying it via journalctl and SMF does this similar.
#2206
Metatron could be sucesfully started with …
> Fixed metatron.sh script upstart mode

- discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/audit/AuditRepositoryImpl.java
removing mysql dedicated string template in audit stats query.
An error occurred in h2 environment.
1. Data Monitoring > Log Statistics > Daily query success / failure rate
2. see chart without error
> #fn removing mysql dedicated string template in audit stats query.

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorService.java
In the process of creating the DataSource, the method used to process the ResultSet in the API used differs from the method used to process the ResultSet in the CsvWriter.
Modified CsvWriter's processing method to be same as other API
1. create datasource from oracle database
2. select schema : SCOTT
3. select table : EMP
4. choose segment granularity : MONTH
5. create datasource without error
> #fn apply result object converter to CsvWriter

- discovery-frontend/src/app/workbench/workbench.component.html
fix display update user on workbench
2. Check displaying update information
> #fn fix display workbench update user

- discovery-frontend/src/app/common/component/input/input.component.html
- discovery-frontend/src/app/common/component/input/input.component.ts
- discovery-frontend/src/app/data-storage/component/criterion/criterion.component.ts
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.html
- discovery-frontend/src/app/data-storage/data-connection/data-connection.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.html
- discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/column-detail-data-source/edit-config-schema.component.ts
- discovery-frontend/src/assets/css/metatron/component/component.filtering.list.css
- 데이터소스, 커넥션 목록에서 defaultFilters가 존재하는경우 변경된 필터가 제대로 유지되지 않던 현상 수정
- MSSQL인 경우 커넥션 목록에서 제대로 표기되지 않던 현상 수정
- 데이터소스, 커넥션 목록에서 목록이 없는경우 template 추가
- 데이터소스, 커넥션 목록에서 검색어를 입력하는경우 x 버튼이 뜨도록 수정
- 데이터소스 > 상세화면 > edit schema 화면에서 기존 타임스탬프 타입을 변경 하는 경우 format값을 null을 보내도록 수정
통합테스트
1. 데이터소스, 커넥션 목록에서 defaultFilters가 존재하는경우 변경된 필터가 제대로 유지되는지 확인
2. 커넥션 > MSSQL인 경우 목록에서 제대로 표기되는지 확인 
3. 데이터소스, 커넥션 목록에서 목록이 없는경우 결과가 없다는 안내가 dataset과 같게 표기되는지 확인
4. 데이터소스, 커넥션 목록에서 검색어 입력시 x 버튼이 뜨는지 확인
5. 데이터소스 > 상세화면 > edit schema 화면에서 기존 타임스탬프인 컬럼의 타입을 변경하는 경우 params에 format: null이 제대로 넘어가는지 확인
> Fix datasource and connection ui error

- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
1. 사용자 정의 필드에 대해 필터가 동작하지 않습니다. 
2. 초기 대시보드 생성 후, 대시보드 내 위젯이 없는 상태에서, 필터를 위젯으로 처음 추가 시 위젯으로 등록되지 않음
1. 처음 대시보드를 생성하고, 필터만 생성한 후에 위젯으로 배치되는지 확인합니다.
2. 차트 편집 화면에서 사용자 정의 필드를 만들고 필터로 추가되는지 확인합니다.
> Fix custom field filter and filter widget errors

- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/component/metadata-control-complete.component.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/component/schema-select-box.component.ts
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-db-complete.component.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-db-select.component.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-db-select.component.ts
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-staging-complete.component.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-staging-select.component.html
- discovery-frontend/src/app/meta-data-management/metadata/create-metadata/create-metadata-staging-select.component.ts
- discovery-frontend/src/app/meta-data-management/metadata/metadata.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
메타데이터 생성시 테이블 선택을 하지않은 경우 '다음' 버튼이 비활성화 되도록 수정
저해상도의 환경에서 메타데이터 목록을 볼때 name의 width가 사리지지 않도록 수정
#1539 
1. 메타데이터 생성 >  테이블 선택 단계에서 테이블을 선택하지 않을 경우 하단의 '다음' 버튼이 비활성화 되는지 확인
2. 저해상도 환경에서 메타데이터 목록 화면을 볼 때, name이 사라지지 않는지 확인 
(고해상도에서 브라우저 창의 가로폭을 줄여서 확인)
> #1539 Fix css in metadata create step

- discovery-frontend/src/app/domain/meta-data-management/metadata-column.ts
- 데이터소스 생성 후 만들어진 메타데이터 컬럼에서 TIMESTAMP 컬럼이 제대로 표기되지 않던 현상 수정
통합테스트
1. 데이터소스 생성 후 만들어진 메타데이터 컬럼에서 TIMESTAMP 컬럼이 제대로 표기되는지 확인
> Fix timestamp column flag in metadata column schema

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-settype.component.ts
While auto-typing is working,
The JsonRuleString of Set-Type rule can have column name is enclosed in "`"
1. create a dataset of number type fields -> auto-typing is working
2. create a dataflow and make a wrangled dataset 
3. click edit button of the set-type rule in rule tab. 
4. make sure the column names of the select box is checked
> #fn represent selected cols when the col-name is enclosed in quotation marks

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/ColumnType.java
When get a dataframe from an Oracle table, the BigDecimal object is used as the numeric type
However, when I draw the histogram, We missed it because we did not recognize the object type
1. create a dataset of database with an oracle data connection
2. edit rules of the W.dataset
3. check numeric fields
If the fields have a correct histogram, the problem was solved.
> #fn show histogram correctly for oracle number datatype

- discovery-frontend/src/app/domain/meta-data-management/metadata-column.ts
- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
- discovery-frontend/src/assets/css/polaris.v2.page.css
메타데이터 컬럼의 타입 변경시 TIMSTAMP 타입이 아닌 경우 format이 남아있던 현상 수정
메타데이터 컬럼의 role이 TIMESTAMP인 경우 format을 변경할 수 있는 아이콘이 나오는 현상 수정 (데이터소스와 동일)
disable 된 컬럼 위에 컬럼 타입 목록이 열려있는경우 해당 위치의 타입을 클릭할 수 없던 현상 수정
통합테스트
1. 메타데이터 > 컬럼 Dictionary를 type을 TIMESTAMP가 아닌 타입으로 생성 (format이 없는타입)
2. format 정보가 있는 메타데이터 상세화면
3. format 정보가 있는 컬럼에 1에서 생성한 컬럼 Dictionary를 import
4. 수정 완료후 조회시 에러가 발생하지 않는것 확인
5. role이 타임스탬프인 컬럼에서 format을 변경 할 수 있는 아이콘이 출력되지 않는지 확인
- 기존에 format이 있는 컬럼에 컬럼 Dictionary를 import 한 경우 에러가 발생할 때 아래와 같은 조치로 해결할 수 있습니다.
1. 해당 컬럼의 컬럼 Dictionary를 재설정(또는 해제후 재설정)
2. 해당 컬럼의 컬럼 Dictionary를 해제후 다른 타입으로 변경
- 추후 별도의 이슈를 통해 수정이 필요
메타데이터 > column dictionary를 생성시에 timestamp 타입으로 생성하는 경우 format이 있음
이렇게 생성한 column dictionary를 메타데이터에서 불러올경우 format validation없이 해당 포맷이 덮어 씌워지게 됨
(현재는 logical column …
> Fix metadata change column error

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSet.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/Histogram.java
Null values will be treated as missing on the Histogram bar.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2243
1. Import & wrangle [nulltest.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3296160/nulltest.csv.txt)
2. Add set rule ->
col: Num
expression: '' (empty string)
where: `Num`==1
3. See missing (black) in the histogram of Num column. It was missmatched (red) before.
Yes. Let's use one of testbeds.
For string type, I'd like to keep showing _(null)_ for null values. (One of the famous data preparation tools works the same way).
_(null)_ might be removed for *non-string types*, later. (It makes the page messy!)
But now, all null values are shown as _(null)_.
> F#2243 show null as missing

- discovery-common/src/main/java/app/metatron/discovery/extension/ExtensionInformation.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/ConnectionExtensionInformation.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/JdbcConnectInformation.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/accessor/AbstractJdbcDataAccessor.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/accessor/JdbcAccessor.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/accessor/JdbcRowMapper.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/connector/AbstractJdbcConnector.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/connector/JdbcConnector.java
- discovery-common/src/main/java/app/metatron/discovery/extension/dataconnection/jdbc/dialect/JdbcDialect.java
- discovery-extensions/README.md
- discovery-extensions/mssql-connection/pom.xml
- discovery-extensions/oracle-connection/README.md
- discovery-extensions/oracle-connection/pom.xml
There is no function modification.
fix typos in README.md
add comments for extensions
NullPointerException fixed.
> fix typos and add comment for extensions

- discovery-server/src/main/resources/application.yaml
- discovery-server/src/main/resources/logback-console.xml
Currently, the release_mode of the hibernate connection is on_close (default), which keeps the connection until the hibernate session is closed.
There is a risk of error if it does not match db timeout setting.
Also, resources are wasted due to connection.
So we need to change it to after_transaction to release it at the end of the transaction.
**Related Issue** : #2250 
NA
NA
> #2250 change hibernate connection properties

- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/WorkbenchProjections.java
HibernateProxy object unproxy in WorkbenchProjections.
Proxy object error due to hibernate version up.
To solve this problem, HibernateProxy Object unproxy.
1. create workbench
2. go into workbench withour error.
> HibernateProxy object unproxy in WorkbenchProjections

- discovery-frontend/src/app/admin/workspace-management/component/workspace-permission-schemas/detail-permission-schema.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/user/role/RoleSet.java
- discovery-server/src/main/java/app/metatron/discovery/domain/user/role/RoleSetEventHandler.java
If a permission schema deleted, linked workspaces to the schema is setted to the default permission schema.
**Related Issue** : #2214 
1. Create a shared workspace.
2. Create a new permission schema.
3. Set the permission schema to the workspace.
4. Delete the permission schema.
5. Check the workspace to see if it is set to the default permission schema.
> #2214 permission schema deleted and set default permission schema

- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
- discovery-frontend/src/app/shared/datasource-metadata/component/datetime-valid-popup.component.ts
- discovery-frontend/src/assets/css/metatron/component/component.table.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/source/MetaSourceService.java
테스트 목록 기획서 참고해주세요.
1. Can't modify column dictionary when column is geo type
2. When removing Dictionary, initialise logical name, type, code table, description
3. Description is always editable whether you add a column dictionary or not
4. If you add a timestamp type column dictionary, you can modify the format
5. If metadata type is datasource and column role is timestamp,
type and format should not be changed when adding a column dictionary. It stays as timestamp
#2242 
Ran locally
> #2242 metadata col dictionary timestamp validation

- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/source/MetaSourceService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/source/MetadataSourceProjections.java
An error occurs when casting a resource object through projection.
**Related Issue** : #2242
1. create linked datasource.
2. go to created datasource's metadata.
3. click column tab
4. see column without error
> #2242 fix proxy casting error with MetadataSource

- discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
- discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.html
- discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
An error occurs when you place a measure that declares a user-defined field on the shelf and activates the prediction line.
**Related Issue** : #2227 
1. Go to 'New Dashboard' linked with "Sales"
2. Click on 'New Chart'
3. Create a user-defined field with measure role named "test_field"
: Set the expression to "Sales + 1"
4. Put on the shelf: Orderdate (month) on column area, "test_field" on aggregation area.
5. Click on "Analysis" tab > Predict line and enable "Activation"
> #2227 add ref to user defined field

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-dataflow-rule-2.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.ts
For the convenience of editing, the operation of the history back is limited
However, we changed the history back to route to the details of dataflow because a path that can not escape from the edit screen occurred
[#2232](https://github.com/metatron-app/metatron-discovery/issues/2232)
1. go to a page of the rule editing
2. go to a page of the diagram of the dataflow
3. press back button or go back to previous page 
If you are on the page of the dataflow list. It works.
> F#2232 back button action on dataflow details

- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/ColumnDictionaryController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/ColumnDictionaryPredicate.java
fix column dictionary's name duplicate check
1. create column dictionary (name : abc, recommended name : qwe)
2. change name "abc" to "qwe"
3. click check button for duplicate check
4. Confirms that there are no errors
> fix column dictionary's name duplicate check

- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/app/workspace/workspace.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
fix default dataconnection icon of extensions
**Related Issue** : #2303 
1. create oracle connection and workbench.
2. remove oracle extension and restart discovery.
3. see default dataconnection icon.
> #2303 fix default dataconnection icon of extensions

- discovery-frontend/src/app/data-storage/data-connection/update-connection.component.ts
특정 타입의 database의 커넥션 상세화면에서 데이터를 수정 후 완료를 누를때 script error가 발생하는 현상 수정
통합테스트
1. 커넥션 생성 (druid)
2. 1에서 생성한 커넥션 상세화면으로 이동
3. 커넥션 데이터를 수정하거나 수정하지 않고 done(완료)를 눌렀을떄 script error가 발생하는지 확인
> Fix authentication script error in update connection component

- discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.html
- discovery-frontend/src/app/meta-data-management/column-dictionary/detail-column-dictionary/detail-column-dictionary.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
컬럼 딕셔너리가 TIMESTAMP 타입이고 format이 없거나 비어있는경우 아래와 같은 placeholder가 보이도록 수정
통합테스트
1. 메타데이터 > 컬럼 딕셔너리 > 컬럼 딕셔너리 생성
2. 타입을 TIMESTAMP로 지정하고 format을 입력하지 않고 생성
3. 2에서 생성한 컬럼 딕셔너리 상세화면으로 이동
4. format부분이 placeholder가 표기되는지 확인
> Add format placeholder in column dictionary detail

- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.ts
메타데이터 상세화면 > 컬럼 스키마에서
TIMESTAMP타입이고 format이 없는 컬럼 딕셔너리를 import하는 경우 error가 발생하는 현상 수정
통합테스트
1. 메타데이터 > 컬럼 딕셔너리 > 컬럼 딕셔너리 생성
2. TIMESTAMP로 타입 지정후 format을 입력하지 않고 생성
3. 또는 이미 생성된 컬럼 딕셔너리 상세화면 > 타입을 TIMESTAMP로 바꾸고 format을 입력하지 않음
4. 메타데이터 상세화면 > 컬럼 스키마 화면으로 이동
5. 2 또는 3에서 생성, 수정된 컬럼 딕셔너리를 import
6. 에러가 발생하지 않는 것 확인
> Fix dictionary import error in metadata column schema

- discovery-frontend/src/app/data-storage/data-connection/update-connection.component.ts
When you do not allow all workspaces to use a dataconnection, the checkbox does not change.
1. Create a dataconnection.
2. Uncheck the checkbox which is allowing all workspaces.
3. See the checkbox.
> fix dataconnection unpublishing checkbox

- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
fix the original name of reserved fields when loading a temporary datasource
1. Create a data connection with druid
2. Create a workbench with the datasource
3. Execute a query and chart preview
> fix the original name of reserved fields when loading a temporary datasource

- discovery-frontend/src/app/data-storage/data-source-list/create-data-source/file-create-component/file-preview/file-preview.component.html
fix advance setting folding in re-ingestion popup
Re-ingest a datasource with a file.
Fold advance setting in re-ingestion popup
> fix advance setting folding in reingestion popup

- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/Workbench.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/WorkbenchProjections.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/WorkBook.java
fix workspace view with status of data storage items
1. Hover workspace hierarchy and check underline.
2. Allow all workspaces to use a dataconnection, check a workbench with the dataconnection in a workspace.
3. Create a workbook without creating a dashboard, check the workbook in the workspace
> fix workspace view with status of data storage items

- discovery-frontend/proxy.conf.js
- discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.html
- discovery-frontend/src/app/data-storage/data-source-list/component/ingestion-setting.component.ts
Disable the rollup mode radio button in case of including geo type column
**Related Issue** : #2299 
1. Create a datasource with the geo type column at least one.
2. See the rollup mode radio button which is disabled in the ingestion setting page.
3. Create a datasource without the geo type column.
4. See the rollup mode radio button which is able to choose in the ingestion setting page.
> #2299 disable rollup mode in case of including geo type column

- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
1. 라인차트 예측선 활성화시 선택필터 동작하지 않음
2. 워크스페이스 내 폴더 생성을 hover하려고 하면 폴더경로 하이어라키가 활성화가 됨
1. 워크스페이스 폴더 생성 아이콘에 마우스를 위치했을 때 좌측 하이어라키 경로에 밑줄이 생성되지 않는지 확인합니다.
2. 대시보드에서 셀렉션 필터를 적용했을 때 예측선이 적용된 차트에 필터가 적용되는지 확인합니다.
>  fix error that not working selection filter when use prediction

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
the custom field name of a chart can not be a reserved word
1. Go to a workbook.
2. Create a chart with a custom field
3. Set the column name to count, __time, timestamp.
4. See the error message.
> fix the custom field name of a chart can not be a reserved word

- discovery-server/src/main/java/app/metatron/discovery/common/exception/RestExceptionHandler.java
Fix exceptionhandler to include HttpMessageNotWritableException
> fix exceptionhandler to include HttpMessageNotWritableException

- discovery-server/src/main/resources/templates/api/oauth/login.html
fix setting cookie domain in external login page
After logging in through the external login page, check to see if you can log out of Discovery.
> fix setting cookie domain in external login page

- discovery-frontend/src/app/dashboard/filters/configure-filters-update.component.html
- discovery-frontend/src/app/dashboard/filters/configure-filters-update.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
* 필터 설정에서 눈 아이콘을 제거 하였습니다.
* 데이터 소스명이 길어져서 줄임(...)이 발생하는 경우에만 브라우저 툴팁이 보여 지도록 하였습니다.
#2322
> #2322 Filter Popup Enhancements

- discovery-frontend/src/app/data-storage/component/schema-configure/schema-configure-field-detail.component.ts
- discovery-frontend/src/app/data-storage/service/granularity.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/format/DateTimeFormatChecker.java
Change timestamp column validation logic if the data contains null / empty values
**Related Issue** : #2294
Create a datasource with null / empty value in the timestamp column.
Check if the percentage of empty values ​​is more than or less than 50%
> #2294 check timestamp datasource column

- discovery-frontend/src/app/dataconnection/service/dataconnection.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/HiveDataAccessorUsingMetastore.java
There is a bug that can not be viewed more than 20 times when viewing StageDB table list.
Added a missing "size" parameter for bug fixes.
**Related Issue** : #2363 
1. create datasource from StageDB
2. select "default" database
3. Check that there are more than 20 table in dropdown.
> #2363 add size parameter for StageDB's table list

- discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
- discovery-frontend/src/assets/i18n/en.json
- 차트 필터에서 보더와 헤더사이의 여백 제거
- 차트 number format에서 CuNumber라고 되있는 문구를 Number로 수정 (영문일떄만 발생)
통합테스트
1. 대시보드 > 차트 > 차트 편집
2. 차트 생성을 클릭한 후
3. 우측 메뉴에서 filter를 추가하고 여백이 생기는지 확인
3-1. 우측 메뉴에서 Number format을 선택하고 Number Abbreviation 문구가 CuNumber Abbreviation로 표기되지 않는것 확인
> Fix chart filter css and message

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/assets/css/polaris.v2.page.css
- 워크스페이스 화면에서 이름이 긴 workbook, workbench 등 에 대해 말줄임 표시가 나타나지 않는 현상 수정
- lnb에서 데이터스냅샷 접근시 로딩이 사라지지 않는 현상 수정
통합테스트
1. 개인 워크스페이스 화면 진입
2. 이름이 긴 이름의 book에 말줄임 표시가 표시되는지 확인 (커서를 올렸을 경우 tooltip이 표시되는지 확인)
3. LNB에서 '데이터스냅샷'을 클릭시 데이터스냅샷 화면에서 로딩이 사라지는지 확인
> Fix snapshot loading and add name title

- discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupMember.java
- discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/user/group/GroupService.java
느림 현상 원인은 아래 Hibernate가 생성한 쿼리를 공유 워크스페이스 하나에 한번씩 실행(SKT 환경에서 2초 정도 소요)하면서 발생
```sql
-- app.metatron.discovery.domain.user.group.GroupService#getJoinedGroups
-- Iterable<Group> groups = groupRepository.findAll(GroupPredicate.searchGroupByMemberId(username));
select
group0_.id as id1_65_,
group0_.created_by as created_2_65_,
group0_.created_time as created_3_65_,
group0_.modified_by as modified4_65_,
group0_.modified_time as modified5_65_,
group0_.version as version6_65_,
group0_.group_contexts as group_co7_65_,
group0_.group_default as group_de8_65_,
group0_.group_desc as group_de9_65_,
group0_.group_member_count as group_m10_65_,
group0_.group_name as group_n11_65_,
group0_.group_predefined as group_p12_65_,
group0_.group_read_only as group_r13_65_ 
from
user_group group0_ 
where
exists …
```
> #2396 Performance issues when viewing a list of shared workspaces

- discovery-frontend/src/assets/css/polaris.v2.component.css
The drag and drop of the maximum value of the gradient color is malfunctioning.
#1902 
Chart > Color > Measure > Custom Color Setting > Gradient
1. 차트 생성 화면으로 진입합니다.
2. 임의의 차트를 그립니다.
3. 색상 설정 옵션을 열고 Measure를 선택한 후에 custom color setting을 활성화 합니다.
4. 색상 설정 방식을 gradient로 변경하고 gradient tool에서 슬라이더를 중간으로 옮겼다가 끝으로 옮깁니다.
5. 슬라이더가 정상적으로 끝에 위치하는지 확인합니다.
> #1902 Fix Gradient Settings Maximum

- discovery-server/src/main/java/app/metatron/discovery/domain/notebook/connector/RBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/notebook/NotebookServiceTest.java
Simple one.
Add a guidance comment for R functions into auto-generated Jupyter cells.
#2343 
metatron-app/discovery-jupyter-r-utils#2
Add a unit test and already using in the own notebooks.
If you want to use the functions described in the comment, you need to upgrade RMetis module to the latest version.
> Add guide for Discovery api into jupyter cells

- discovery-frontend/src/app/workbench/workbench.component.html
A very small modification has been made to show the tooltip on the "workbench" tab.
**Related Issue** : N/A
Make sure that the tooltip is visible when you hover your mouse over the tab in the workbench.
N/A
> Add Tooltips to the Workbench Tab

- discovery-extensions/oracle-connection/src/main/java/app/metatron/discovery/OracleConnectionExtension.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/ingestion/jdbc/SelectQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
fix todate function of query builder in oracle extension
append is false if batch ingestion type is ALL
**Related Issue** : #2442 
1. Create a datasource from oracle database
2. See the log file and check the select query TO_DATE value. (single quotes)
> F#2442 fix oracle extension todate

- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryEditorController.java
prevents path traversal through csv download api
**Related Issue** : #2445 
1. Call the api with any REST client
Method : POST
URL : /api/queryeditors/test/query/download/csv
Body : {"csvFilePath":"../etc/passwd"}
2. Return 500 error.
{
"code": "WB0003",
"message": "CSV Download Failed",
"details": "WorkbenchException: CSV Download Failed"
}
> #2445 prevents path traversal through csv download api

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbServiceTest.java
- Extract duplicated sql string generating logic into method in `PrepDatasetStagingDbService`
- Replace empty string check with `StringUtils.isEmpty`
**Related Issue** : This resolves #2459 
- Add testcases for `getSQLString`
> #2459 Extract duplicated sql string generating logic into method

- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-detail.component.html
- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-detail.component.ts
- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.ts
when loading, main node will be selected
if main node is selected, 'go to metadata' button will not be shown
[#2472 ](https://github.com/metatron-app/metatron-discovery/issues/2472)
1. go to lineage diagram page
2. check them
1) is main node selected? 
2) on the details of main node, is there a button labeled 'go to metadata'?
> #2472 hidden the button for main node

- discovery-frontend/src/assets/css/metatron/component/component.tag.css
- discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
- discovery-frontend/src/assets/css/polaris.v2.component.css
- discovery-frontend/src/assets/css/polaris.v2.layout.css
- discovery-frontend/src/assets/css/polaris.v2.page.css
crashed style sheets by issue #2266
so we restored the style sheet
restored 5 css files from commit **2e236028b** to commit **a8cb97f1b**
discovery-frontend/src/assets/css/polaris.v2.component.css
discovery-frontend/src/assets/css/polaris.v2.layout.css
discovery-frontend/src/assets/css/polaris.v2.page.css
discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
discovery-frontend/src/assets/css/metatron/component/component.tag.css
[#2266 ](https://github.com/metatron-app/metatron-discovery/issues/2266)
check the pages of discovery-frontend globally
issue #2008 is affected. 
we will be check it.
> recovery original style sheets

- discovery-frontend/src/app/meta-data-management/meta-data-management.component.html
- discovery-frontend/src/assets/css/metatron/polaris.metatron.page.css
metadata menu tab is changed according to recovered style sheet
[#2266 ](https://github.com/metatron-app/metatron-discovery/issues/2266)
Check that the metadata menu is well displayed overall
> #2266 metadata menu tab uses old design styles

- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.ts
- discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-confirm-grid.component.ts
- discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.html
- discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.ts
1. index of selected node will be clear when reloading linege view
2. test file has txt extension. now txt is supported
3. test file has not a tier field. it is not a right format. now this will make an error.
[#2491](https://github.com/metatron-app/metatron-discovery/issues/2491)
1. decrease the node count. 
2. click all nodes.
If all nodes are selected. that is ok
> #2491 index of selected node will be clear when reloading linege view

- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.html
- discovery-frontend/src/assets/css/metatron/page/metatron.page.05Management_metadata.css
the lineage view page has the tabs for navigation now
[#2470 ](https://github.com/metatron-app/metatron-discovery/issues/2470)
go to [Management]-[Explore data]-[metadata]-[lineage view]
there are the navigation tabs
if it works, then ok
> #2470 navigation tab on lineage view

- discovery-frontend/src/app/monitoring/audit/log-statistics/log-statistics.component.ts
Need to show default cursor on query success, failure rate bar chart
When mouse cursor is on the query success/failure rate bar chart cursor type is pointer
METATRON-2845
1. Using LNB -> Management -> Data Monitoring -> Log statistics
2. check if mouse is on query success/failure rate barchart, cursor type is default.
> fn-fix_monitoring error

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.html
- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
- discovery-frontend/src/app/domain/data-preparation/pr-snapshot.ts
original dataset information has not all fields.
[#2477 ](https://github.com/metatron-app/metatron-discovery/issues/2477)
See the details of a snapshot.
If no warning pops up, it is ok.
> #2477 not all fields on the origin need to be filled

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
- fix data source detail popup error
METATRON 2925
1. Move to https://dev-discovery.metatron.app/app/v2/workspace
2. login using metatron id 
3. choose ysv_workbook
4. click the datasource icon which is next to presentation view button
5. check detail modal shows without error
> fn-fix_workbook-datasource-detail-error

- discovery-frontend/src/app/data-storage/component/criterion/criterion-extension-box.component.html
- discovery-frontend/src/app/data-storage/component/criterion/criterion.component.ts
Set source type as a default filter
In datastorage default of extension filter was no filter was selected, so set source type as a default option
METATRON 2833
1. Management -> Datasource
2. Check if source type filter is selected as an default filter
> fn-fix_datastorage_default_filter error

- discovery-frontend/src/app/workspace/component/permission/permission-schema.component.html
- discovery-frontend/src/app/workspace/component/permission/permission-schema.component.ts
fix default role not to be deleted
METATRON-2888
METATRON-2888
1. Go to the Workspace > Permission schema.
2. Move to the permission schema detail screen
3. Select User Role Settings button
4. Checking Default Role Delete Button
> fix default role not to be deleted

- discovery-frontend/src/app/workspace/component/permission/permission-schema.component.ts
Show toast popups when validation errors occur when adding or removing roles in a permission schema.
METATRON-2864
METATRON-2864
1. Create Shared Workspace > Permission Schema > Select Custom Schema > Select Edit
2. If you add duplicate user role names, or if you do not select more than one permission, check to see if you have a toast popup.
> fix permission schema role validation

- discovery-frontend/src/app/meta-data-management/detail/component/lineage-view/lineage-view.component.ts
default node count is 7
METATRON-2983
1. Login as admin
2. management -> explore data -> metadata -> metadata detail -> lineage tab
3. check the node count. 7 is right
> Fn default node count is 7 on lineage view

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/dataset-info-popup/dataset-info-popup.component.ts
If imported dataset if from EXCEL, sheet name will be shown.
METATRON-3007
click an imported dataset of EXCEL on dataflow detail page.
there is a sheet name on info area.
> Fn show sheet name on dataset info

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-db-query.component.ts
When create a dataset of database.
If you pass the query validation once, you can submit the query after changing the query.
so it fixed.
METATRON-2886
create a dataset of database.
verify your query and change that.
> Fn query verification of jdbc dataset

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset.component.ts
on snapshot deletion popup in korean 
the button name was 'done'
it is changed to 'confirm'
METATRON-2898
choose language as korean
delete a snapshot
you can see the button 'confirm' not 'done'
> Fn confirm button to delete snapshot is corrected

- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
The file URL of snapshot is from snapshot name.
Snapshot name can contain special characters. But the file name is not.
So replace the special character with _
In addition, if the user manually changes the URL, 
the URL does not follow the snapshot name.
The rules: file name is a combination of alphanumeric, hangul, _ and .
[#2568 ](https://github.com/metatron-app/metatron-discovery/issues/2568)
1. go to the popup to create snapshot
2. you can change the snapshot name. type special characters
3. change file URL on advanced settings. and type special characters
4. change the snapshot name again. It does not work. This is the intended behavior.
> #2568 constrained file name

- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/exceptions/FunctionArgumentCountException.java
- discovery-prep-parser/src/main/java/app/metatron/discovery/prep/parser/preparation/rule/expr/Expr.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfKeep.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/exceptions/TeddyException.java
When there is an error on function expression, like there's a mismatch of argument count, the internal exception should be catched and rethrown as the external exception (for internationalization)
There was a hole that didn't catch the RuleException.
METATRON-2861
1. Import and wrangle [s5k_1.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3575135/s5k_1.csv.txt)
2. Select keep rule.
3. Put length() as the expression.
4. Click "add" -> The error should be the argument count problem. __NOT UNKNOWN ERROR__
Not necessary.
> fix exception handling in the expression in dataprep

- discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
Prediction is not activated when the time unit is less than day.
METATRON-3010
1. Go to the chart creation screen.
2. Select the line chart and create a chart with timestamp as dimension.
3. Verify that the prediction is activated in the analysis.
> change condition for prediction analysis

- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/QueryResult.java
- discovery-server/src/test/java/app/metatron/discovery/common/ObjectMapperTest.java
If the query result is a numeric type and the value is null, NaN or 0 is displayed.
**Related Issue** : #2589 
2. Query for the value that contains null data among numeric columns
3. Check if the blank value is displayed normally.
> #2589 Error displaying null when workbench query result is numeric type.

- discovery-frontend/src/app/common/component/data-download/data.download.component.ts
- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
- discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.html
- discovery-frontend/src/app/dashboard/filters/essential-filter/essential-filter.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
1. The download data button is displayed on the map chart.
2. It takes a long time for the download layer to appear in the data source information popup.
3. You cannot return to the original screen when loading failed and the window is closed.
METATRON-3037 
METATRON-3040
METATRON-3041
1. Verify that the Download Data button is missing from the map chart.
2. In the Data Source Information pop-up, verify that the download layer is displayed immediately.
3. Make sure that you return to the original screen when loading failed and the window was closed.
> fix dashboard err

- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.html
- discovery-frontend/src/app/data-preparation/component/create-snapshot-popup.component.ts
if dataprep.etl.spark option is disabled, 
the spark option should be unselectable on creating snapshot popup
[#2584 ](https://github.com/metatron-app/metatron-discovery/issues/2584)
1. Do not give spark option (refer below):
Just delete spark: option and its children.
2. Import & wrangle s5k_1.csv.txt
3. Click "Snapshot" button
4. Click "Advanced settings"
5. Spark should be disabled.
> #2584 disable spark engine when not properly configured

- discovery-frontend/src/app/common/component/abstract.component.ts
- discovery-frontend/src/app/common/constant/local-storage.constant.ts
- discovery-frontend/src/app/common/value/used-criteria.data.value.ts
- discovery-frontend/src/app/workspace/workspace.component.html
- discovery-frontend/src/app/workspace/workspace.component.ts
사용자가 워크스페이스에서 3가지 조건(정렬, 뷰타입,워크북 종류)을 선택하면 이를 저장하여 다른 화면으로 가거나 브라우저를 종료 하더라도 유지할 수 있도록 하였습니다.
#2617
> #2617 Keep sorting conditions used in the workspace

- discovery-frontend/src/app/workbench/component/detail-workbench/detail-workbench-table/detail-workbench-table.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/PostgresqlDataAccessor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
Workbench, datasource, and dataset errors when postgresql table name contains uppercase letters
**Related Issue** : #2629 
1. Create connection to postgresql
2. Create table with Upper case
ex) create table "Table1" (i int);
3. Create workbench, DataSource, DataSet.
4. Check if it runs normally.
> #2629 fix uppercase table name in postgresql

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
Now, when we create a datasource with a data snapshot, the types and roles will be set automatically with the information from the snapshot.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2375
1. Import and wrangle [s5k_1.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3651207/s5k_1.csv.txt)
2. Create a snapshot without any change.
3. See the snapshot detail page.
4. Click "Create datasource" button.
5. See the datasource creating pop-up with appropriate types, roles, timestamp setttings.
Yes, please.
> #2375 use type from snapshot2

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PrestoDialect.java
Error occurs when querying array column data of presto.
If the query result is an array, join it with comma delimiter and convert it to String.
1. goto workbench (presto)
2. create table with array column and insert rows.
```
create table if not exists default.arr_test (a varchar, b array<varchar>);
insert into default.arr_test 
values ('1', array['aa', 'bb']), ('2', array['cc', 'dd']), ('3', array['ee', 'ff']);
```
3. select query or create datasource.
> fix presto array column handling as string

- discovery-frontend/src/app/workbench/workbench.component.html
- discovery-frontend/src/app/workbench/workbench.component.ts
- discovery-frontend/src/assets/css/metatron/page.css
An error occurs if the workbench cancels a query too soon for a hive.
Prevent error by disabling cancel button for 10 seconds after executing query.
METATRON-3043
1. goto workbench (hive)
sample : 
```
select currentdatabase, owner, sourcetablename, targettablename, count(*), max(eventtime)
from default.lineage
group by currentdatabase, owner, sourcetablename, targettablename;
```
3. see cancel button disabled for 10 seconds
> Add timer to cancel button in workbench

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetDatabaseService.java
Dataset had a bug when postgresql table name contains uppercase letters
Fixed this bug.
[#2651](https://github.com/metatron-app/metatron-discovery/issues/2651)
1. Create connection to postgresql
2. Create table with Upper case
ex) create table "Table1" (i int);
3. Create DataSet.
4. No error should occur.
> #2651 Uppercase table name of postgresql to create dataset

- discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
In the grid chart, dimension values ​​are aliased.
Measures are not aliased.
**Related Issue** : #2533
1. Go to workbook.
2. Create a grid chart.
3. Change original type.
4. Apply aliases to the measurements.
5. Check that aliases are applied to the dimension values ​​and the measured values.
> fix grid chart measure alias

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot.component.ts
loading image does not disappear on snapshot list
because updating list repeats indefinitely
None
go to [management] - [data preparation] - [data snapshot]
the loading image should be disappear soon
> #0 fix snapshot list loads infinitely

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule/edit-rule-aggregate.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepRuleChecker.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
The aggregate rule of dataflow don't have to contain group
go to [data preparation]-[dataflow]-[dataflow detail]-[edit rules]
add an aggregate rule without group
there is no warning and your rule will be added
> fix can add an aggregate rule without group

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.html
- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
- discovery-frontend/src/app/domain/engine-monitoring/engine.ts
- discovery-frontend/src/app/engine-monitoring/component/druid-cluster-information/druid-cluster-information.component.html
- discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor.component.html
- discovery-frontend/src/app/engine-monitoring/ingestion/component/supervisor/supervisor.component.ts
- discovery-frontend/src/app/engine-monitoring/ingestion/component/task/task.component.ts
- discovery-frontend/src/app/engine-monitoring/ingestion/component/worker/worker.component.ts
- discovery-frontend/src/app/engine-monitoring/overview/component/graph.component.ts
- discovery-frontend/src/app/engine-monitoring/overview/component/node-information.component.ts
- discovery-frontend/src/app/engine-monitoring/overview/overview.component.html
- discovery-frontend/src/app/engine-monitoring/overview/overview.component.ts
- discovery-frontend/src/app/engine-monitoring/overview/pipe/table-filter.pipe.ts
- discovery-frontend/src/app/workspace/workspace.component.html
The overview area is visible only in the common tab of the Druid configuration.
Filter node type  for overview of engine monitoring
Modify workspace Notebook Connector tooltip
Maintain focus when you click a function in a custom field
1. Go to engine monitoring 
- Click druid configuration in the top right corner of the screen
- Check the Overview area is visible only on the common tab.
2. Go to engine monitoring
- Check if filtering is performed by node type in the center of the screen.
3. Go to workspace
- Check the Notebook Connector tooltip
4. Go to workbook and create or edit Chart.
- Move to create custom-filed view.
- Click a function and check the function you click is in focus and the help is displayed in the help area.
- When focusing out of the function …
> fix engine monitoring trivial error

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.ts
- discovery-frontend/src/assets/css/metatron/page.css
in the popup of adding union rule,
the type icon should be shown as their own type
[#2063 ](https://github.com/metatron-app/metatron-discovery/issues/2063)
1. add an union rule in the page of dataflow details
2. union some datasets have fields which are not string type.
3. make sure the correct type of icons are displayed
> #2063 adding union rule shows field type as icon correctly

- discovery-frontend/src/app/explore-data/explore-data/component/explore-data-user-card.component.ts
- discovery-frontend/src/app/explore-data/explore-data/popup/metadata-overview.component.ts
Open the dashboard/workbench with a tab(not popup) in Exploration.
1. goto Exploration > Detail View
2. Click Workbench or Dashboard link
3. Look at the new tab, not the popup.
> open the dashboard/workbench with a tab in Exploration

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectsheet.component.ts
reloading preview had a problem when uploading files for dataset
[#2610 ](https://github.com/metatron-app/metatron-discovery/issues/2610)
1. Import [finefood.sample.txt](https://github.com/metatron-app/metatron-discovery/files/3614956/finefood.sample.txt)
2. Change the delimiter into \n
3. Change it to anything else 
make sure that preview is changed
> #2610 preview reload problem

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-join-popup/rule-join-popup.component.html
the padding of the show result button screened the close result button
[2293](https://github.com/metatron-app/metatron-discovery/issues/2293)
test the issue of 2293
on join popup, click show and close repeatedly 
the close button should be clicked every time
> #2293 cannot close preview result

- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
When using the dark theme, a blank screen appears only when clicking 'save table as file' in the dashboard widget.
**Related Issue** : #2695 
2. Create a chart and place it on the dashboard.
3. After saving the dashboard, press the Save File button to see if the preview popup is displayed normally.
> #2695 Dashboard widget 'save table as file' screen error in dark theme

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
If dataset names are duplicates, separate them by numbers.
[#2705 ](https://github.com/metatron-app/metatron-discovery/issues/2705)
go to the details of dataflow
generate new wrangled dataset
make sure the generated dataset has sequence number
> #2705 when generate a new dataset, add sequence for distinction

- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Fix not working regex filtering mode in advance filter.
**Related Issue** : #2698
1. Create a dashboard that is linked to an existing sales data source.
2. Create chart widget within the dashboard.
3. Create a user-defined column named "test" with the following expression in the created chart edit screen. ex. `CONCAT( [State] , [City] )`
4. Add the "test" column filter you created in the left filter panel.
5. Click the Add option on the right of the added filter and click the "edit" button. and then You can see the filter details screen.
6. Select the advanced filter and select "Matcher"> "Regular expression" mode to specify an arbitrary regular expression. ex `A.*`
7. check that the filtering items are displayed accordingly.
- In addition to the regular expression mode in the advanced …
> fix error for regex filtering mode in advance filter 

- discovery-frontend/src/app/workbench/workbench.component.ts
postgresql sql syntax error.
The comment in postgresql is '--', not '#'.
And there is an error when executing sql statements with '#'.
Even if the response is returned, it does not proceed to the next sql run.
**Related Issue** : #2686 
1. Go to workbench(postgresql).
2. write some sql.
```
select 1;
```
3. input comment shortcut (Ctrl + /)
4. Check that it is created as follows:
```
-- select 1;
```
> #2686 postgresql sql syntax error

- discovery-frontend/src/app/meta-data-management/lineage/component/create-lineage-upload-file.component.ts
- discovery-frontend/src/app/meta-data-management/lineage/service/lineage.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepCsvUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepFileUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/lineage/LineageEdgeController.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvInputTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvIntegrationTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/csv/ApacheCommonsCsvOutputTest.java
There are many different charset-detecting-codes in dataprep. (also in metatron-discovery)
I unified that codes within dataprep.
Originally, I was going to unify all different codes in whole metatron-discovery.
But recently, we made a plan to integrate @dataprep & @datasource, that makes the unification to be meaningless.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2640
Import the files attached at https://github.com/metatron-app/metatron-discovery/issues/2640.
Yes, please.
> F#2640 unify charset detecting code

- discovery-frontend/angular.json
- discovery-frontend/src/app/data-storage/component/criterion/criterion-time-radiobox-list.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/data-source-list.component.ts
- discovery-frontend/src/app/data-storage/data-source-list/detail-data-source/detail-data-source.component.ts
When you return to the list from the detail screen, the filter information you selected may not be retained.
**Related Issue** : #2635 
1. Go to 'LNB > management > data storage > datasource
2. Click on any filtering condition and check list view.
3. Click on any content in searched list and check detail view
4. move to list using back button.
5. In the list screen, verify that filter conditions are maintained.
> #2635 Maintain search result list view in datasource mgmt. after moving to detailed view

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepRuleChecker.java
When I use union rule, "rule is known" error comes out.
I added the missing case statement for union.
1. Import and wrangle 
[sales_2011_01.txt](https://github.com/metatron-app/metatron-discovery/files/3749032/sales_2011_01.txt)
[sales_2011_02.txt](https://github.com/metatron-app/metatron-discovery/files/3749033/sales_2011_02.txt)
[sales_2011_03.txt](https://github.com/metatron-app/metatron-discovery/files/3749034/sales_2011_03.txt)
2. Create a dataflow that includes these datasets.
3. Select sales_2001_01.txt W.DS and click Edit.
4. Select union rule in the left-bottom pull-down, add other datasets.
5. Click "Union" --> No error, then passed.
Yes, please.
This is a critical and urgent bug-fix.
> fn fix union typo

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
사용자가 입력한 맵뷰 color range 값이 유지 되도록 변경 하였습니다.
#2734
> #2734 'Custom Color Range' values are not kept when setting layer in map view chart.

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
맵뷰에서 Layer Setting에 'Size by', 'Radius Range' 설정 후 값이 유지 되도록 수정 했습니다.
#2722
> #2722 'Size by', 'Radius Range' values are not kept when setting layer in map view chart

- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/Metadata.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataController.java
1. Hibernate error occurs when editing metadata description
So change Hibernate fetchType to LAZY -> EAGER for @OneToOne relation
2. No popularity displayed on Exploration Main banner
So add popularity and tags in popurality api.
**Related Issue** : #2659 
1. Management > Metadata > Detail > Change description without error.
2. Exploration > Data > See popularity bar.
> #2659 change Hibernate fetchType to LAZY -> EAGER for @OneToOne relation

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/connector/PostgresqlJdbcConnector.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyDatabaseService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyStagingDbService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
When I create a dataset based on PostgreSQL, I got an OOM.
I found out that it was because of JDBC fetch count.
And I knew that PostgreSQL JDBC ignores the fetch count when auto_commit is true.
I gave a property polaris.dataprep.sampling.maxFetchSize and polaris.dataprep.etl.maxFetchSize.
The default values are 1000 both.
And I set auto_commit as false for all JDBC connections in dataprep.
Generate a dataset against a table that has more than 1m rows.
No, it's troublesome.
I guess Workbench code also needs to care of this issue.
> Use maxFetchSize on JDBC. Set auto_commit=false for PostgreSQL

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
if you out of the snapshot screen
checking status should stop
[2753](https://github.com/metatron-app/metatron-discovery/issues/2753)
When the status of a snapshot is PREPARING, go to the snapshot detail page  
And out of the page
API call should stop
> #2753 checking the status of snapshot is repeated

- discovery-frontend/src/app/data-preparation/data-snapshot/data-snapshot-detail.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetStagingDbService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyOrcWriter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrSnapshotService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfDerive.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfSet.java
When I first implemented the ORC writer code, I decided to skip null or mismatched values in ORC files because they made some troubles.
Now, we need appropriate representations of them.
1. Null values are stored as nulls.
2. For string type columns, the non-null values are stored as their toString() values.
3. For non-string type columns, it's impossible to store mismatched values usually. Rows that have any of this kind of mismatched values are skipped. We can check this with skippedLines.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2752
1. Import & wrangle 
[s5k_1.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3766125/s5k_1.csv.txt)
2. Select set command.
3. Put null as expression, column9 < 2 as condition. Then click "Add"
4. Click …
> Fix null value representation in ORC files

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/page/chart-style/map/map-layer-option.component.ts
Custom Color range 가 초기화 되지 않는 문제를 해결 하였습니다.
추가로 맵뷰 옵션에서 각 Layer 타입별 Custom Color range 를 설정하고 Layer 타입을 변경하는 경우에도 유지되도록 수정했습니다.
#2745
> #2745 When you create a new map view widget, 'Custom Color range' does not reset

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
when a connection doesn't work, the error about fetch failure should be shown
[2476](https://github.com/metatron-app/metatron-discovery/issues/2476)
1. make a dataset using hive connection
2. turn off the hive
3. run a metatron and edit rule of the dataset
an error message should be shown
> #2476 show an error when fetch failed by connection

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepCsvUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepFileUtil.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
We used to read such a lot of bytes to decide the right charsets. Just 1000 is OK.
In addition, I reduced the preview size of file uploaded datasets.
It was too slow for me. If any problem afterward, then I'll fix it again.
**Related Issue** : #2795 
Ran locally.
No, thanks.
> #2795 Read less bytes to get charset. Reduce size of preview grid.

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-context-menu.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRuleService.java
Adding a set rule while the bar is pressed should complete the condition automatically
[2760](https://github.com/metatron-app/metatron-discovery/issues/2760)
1. go to the page of editing rules of dataset
2. select some values of histogram bar
3. click [edit]-[set] in context menu
4. add the rule with a value which you want to set
Make sure the rule is added correctly
> #2760 fill condition automatically using histogram bar selection

- discovery-frontend/src/app/data-preparation/component/dataset-summary.component.html
- discovery-frontend/src/app/data-preparation/component/dataset-summary.component.ts
Too many spaces in the preview area of the dataset for dataset.
**Related Issue** : #2230 
1. On the dataflow screen, select a dataset.
2. Press the dataset substitution button to display the substitution popup.
3. Click dataset to see a preview.
4. Confirm that the preview is displayed without spaces.
> #2230 Too much space in dataset swap pop-up

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/SparkExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyExecutor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/etl/TeddyFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
Even though there're timestamp format information when creating a snapshot, we ignored the format for now.
With this PR, timestamp columns will be formatted as expected.
**Related Issue** : #2066 
1. Import & wrangle [s5k_1.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3810115/s5k_1.csv.txt)
2. Set format of column1 with context menu into like "yyyy"
3. Click "Snapshot"
4. Click "Done"
5. Click the new snapshot on right panel.
6. See "2011", "2012", etc.
Yes, please.
> #2066 apply timestamp format to file type snapshots

- discovery-frontend/src/app/meta-data-management/code-table/code-table.component.html
- discovery-frontend/src/assets/css/metatron/component/component.form.css
- discovery-frontend/src/assets/css/metatron/page.css
- discovery-frontend/src/assets/css/theme_dark/component/component.form.css
- discovery-frontend/src/assets/css/theme_dark/metatron/page.css
fix column dictionary layer, chart color setting align, code table title ellipsis
1. Exploration -> data -> click metadata -> column tab
hover column dictionary has long description and title. -> Check scroll is not showing
2. Explore -> metadata -> code table tab -> Check title shows properly with ellipsis
3. Workspace -> workbook -> edit dashboard -> choose one chart -> color setting tab -> choose measure -> click color template icon -> check each color template's width aligned properly
> fix code table, column dictionary, chart color setting css error

- discovery-server/src/main/java/app/metatron/discovery/common/ConnectionConfigProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/accessor/HiveDataAccessor.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/hive/DataTableHiveRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/hive/HivePersonalDatasource.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/hive/WorkbenchHiveService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbench/util/WorkbenchDataSource.java
- discovery-server/src/main/java/app/metatron/discovery/util/ApplicationContextProvider.java
- discovery-server/src/test/java/app/metatron/discovery/TestLocalHdfs.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbench/WorkbenchRestIntegrationTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbench/hive/DataTableHiveRepositoryTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbench/hive/WorkbenchHiveServiceTest.java
- discovery-server/src/test/resources/sql/workbench.sql
#2821
1.. 메타트론 application.yaml에 propertyGroup 추가
```yaml
polaris:
connection:
property-group:
group1:
hdfs-conf-path: /test1/hdfs-conf
admin-name: admin
admin-password: 1111
personal-database-prefix: private
group2:
hdfs-conf-path: /test2/hdfs-conf
admin-name: admin
admin-password: qwer
personal-database-prefix: pv
```
2. Hive connection을 만들고 커스텀 프로퍼티 `metatron.property.group.name` 에 group1 을 입력하여 기존과 동일하게 동작하는 것을 확인하였습니다.
> #2821 Hive personal database improvement

- README.md
- discovery-distribution/bin/metatron.sh
- discovery-server/src/main/resources/application.yaml
Since initial-changelog xml is created for users who run the metatron-discovery application for the first time, delete the initial profile to initialize the development environment.
Also delete the contents of init profile in READEME.md.
Users must initialize the database manually for initialization.
**Related Issue** : #2756 
run below command without initialization and error.
```
$ bin/metatron.sh --init
```
> #2756 remove initial profile

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/dataflow-detail2.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.ts
- discovery-frontend/src/app/data-preparation/dataflow/service/dataflow.service.ts
when you come back to the dataflow list page from the dataflow detail page
always the first page is shown
1. go to the dataflow list
2. load the next page
3. go to any detail page
4. back to the list page
make sure it's the list you saw earlier
> #fix paging of the dataflow list on return from the dataflow detail page

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/multiple-rename-popup.component.ts
multiply rename column popup shows blank grid
[2844](https://github.com/metatron-app/metatron-discovery/issues/2844)
1. make a dataset has MAP type column
2. go to the edit rule page of the dataflow details
3. add a rule for rename
4. select the multiply rename
5. the grid of the popup should be shown well
> #2844 blank grid on multiple rename page

- discovery-frontend/src/app/data-preparation/dataflow/dataflow.component.html
there is no margin at the top of the dataflow list.
fixed it.
go to the dataflow list page and check it
> #fix there is no margin at the top of dataflow list

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
There are more actual tables / views in the workbench, but there are some things that are not displayed in Page Nation.
1. Create a workbench postgresql.
2. Verify that the table list is displayed correctly.
> Added 'VIEW' table count target of Postgresql.

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfExtract.java
Create null values instead of empty strings, when the pattern is not found.
**Related Issue** : https://github.com/metatron-app/metatron-discovery/issues/2873
Ran locally.
Refer to the issue.
No, thanks.
> #2873 extract as nulls when not found instead of empty strings

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/edit-rule-grid/edit-rule-grid.component.ts
a failure of any rule makes the editor freeze
the apply action is using Promise's then-catch-then chain.
the catch routine was already returned with error
so the then routine does not know what is the error
now the catch routine was changed to pass the error. 
[2878](https://github.com/metatron-app/metatron-discovery/issues/2878)
1. go to the edit rule page of any dataflow
2. apply a rule with wrong condition to be failed on server process. ex) apply 'replace' rule with a LONG type column. server will reply with error message.
3. make sure that an error occurs
4. apply any rule again.
if the add button works well. it is ok
> #2878 a failure of any rule makes the editor freeze

- discovery-frontend/src/assets/i18n/en.json
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/exceptions/PrepMessageKey.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/file/PrepJsonUtil.java
policies of parsing JSON was changed.
when an object is empty, the object should be passed.
and the list of key name depends on the first line.
if the first line is empty object, throws an exception
[2893](https://github.com/metatron-app/metatron-discovery/issues/2893)
1. upload a JSON file to create a dataset
2. check the preview of the file
make sure that column count is depend on first object
and empty object should be null
if the first object is empty, exception occurs
test files ( change the extension to json. txt means the file is for csv )
[test_col_empty.json.txt](https://github.com/metatron-app/metatron-discovery/files/3873116/test_col_empty.json.txt)
[test_col_1.json.txt](https://github.com/metatron-app/metatron-discovery/files/3873117/test_col_1.json.txt)
> #2893 policies of reading json is changed

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DataFrame.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfMerge.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/DfUnnest.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/teddy/TeddyUtil.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/DataFrameTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/NestUnnestTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/SplitMergeTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/dataprep/teddy/TeddyTest.java
I've added more check code into unnest test cases.
Some bugs are found and to solve this, I had to implement auto-typing by column value.
When unnesting the JSON string in Map (Object) or Array type, according to the type of value expressions, the result type chages no matter what types they had before.
For unnest, deciding the type is very simple and obvious, but for other rules, there're some considerations. I'll apply auto-typing by value with extra care, later.
**Related Issue** : #2896 
Ran all test cases in dataprep.
Tested with a file that contains a very complex json column: [nmas_sensor_short.csv.txt](https://github.com/metatron-app/metatron-discovery/files/3874082/nmas_sensor_short.csv.txt)
Yes, thank you.
> Bug-fix on unnest. Implement auto-typing by value

- discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
- discovery-server/src/main/resources/db/changelog/discovery.changelog-initial.xml
An error occurs because the hibernate sequence was not created correctly.
There are two fixes.
1. Added create sequence changeset for DBs with sequence support.
2. If there is no initial value of hibernate_sequence table, an error occurs and the initial value is inserted.
**This patch also needs to be applied to 3.4.0-rc3-hotfix.**
1. Delete existing H2 database if it exists.
2. create metadata (via creating datasorce or from database)
3. Check metadata creation complete without error.
> fix changeset for hibernate sequence

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceRepository.java
Fix duplication error when creating a data source for the metatron engine with a registered disabled datasource
1. Create a datasource from the metatron engine using the physical name of the datasource in the DISABLED state.
2. When creating a data source, make sure that it works correctly without duplication errors when you click the next button in the preview step.
> fix duplication error when creating a datasource with a registered disabled datasource

- discovery-frontend/src/app/layout/layout/layout.module.ts
Allows users other than SYSTEM MANAGER to access engine monitoring.
1. Register a user without SYSTEM MANAGER privilege to DATA MANAGER.
2. Confirm the connection to the engine monitoring menu with the user.
> fix permission error for engine monitoring

- discovery-frontend/angular.json
- discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
- discovery-frontend/src/app/page/chart-style/common-option.component.ts
- discovery-frontend/src/app/page/chart-style/format-option.component.html
- discovery-frontend/src/app/page/chart-style/format-option.component.ts
- discovery-frontend/src/app/page/chart-style/format/format-item.component.html
- discovery-frontend/src/app/page/chart-style/format/format-item.component.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
- discovery-frontend/src/lib/pivot-grid/pivot.grid.js
1. Boundaries broken when there is no data in the chart
2. In the grid original view, the number is displayed according to the original type of the field. 
**Related Issue** : METATRON-3057 
====== Metatron-3057 ====== 
1. Create a data source using sample data with empty data.
2. After creating the dashboard, create a grid chart using fields with empty data.
3. Check if the display is normal without cracking.
========================
1. Create a grid chart and change to the original view.
2. After changing the original view, under Number Format, verify that the original format exists and select the original format.
3. Check that the number is displayed according to the field type.
> Table chart broken issue and original format display issue in original view

- discovery-server/src/main/resources/db/changelog/discovery.changelog-initial.xml
We've changed a middle section in the liquibase's initial script.
But it occurred an error such as : 
`
liquibase.exception.validationfailedexception : 1 change sets check sum
`
We have to record a new changeSet sequentially at the end of the liquibase file.
N/A
But it occurred during integrated testing.
tested In my local mysql,
and deployed to integrated test environment (mysql too)
please check this strategy is correct @ufoscw @kyungtaak
> Change liquibase initial script

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/PostgresqlDialect.java
add type to result object converter on Postgresql
1. Go to workbench on Postgresql.
2. Go to schema information popup.
3. Preview the data in the table containing the PgSQLXML type.
(Test DB / Databasename : Adventureworks / Schema : Person / Table : Person)
> add type to result object converter on Postgresql

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/WidgetController.java
ㅌ날짜 필터 사용 하여 특정 날짜만 조회한 경우 차트에는 반영 되나 차트 데이터 보기에는 반영되지 않는 오류를 수정 했습니다.
#2921 
1. 차트 필터를 추가하여 차트를 만들었습니다.
2. 날짜 필터를 대시보드에 추가하고 특정 기간을 조회하였습니다.
3. 차트에 나타나는 데이터와 데이터 다운로드에 나타나는 데이터가 일치하는 것을 확인 했습니다.
> #2921 Timestamp filter not applied when downloading chart original data

- discovery-frontend/src/app/dashboard/service/dashboard.service.ts
- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/app/workbook/workbook.component.html
- discovery-frontend/src/app/workbook/workbook.component.ts
Whenever switching between view and edit screens in the dashboard, the data in the widget is loaded newly. The bigger the amount of data loaded in the widget, It's getting the more difficult to switch screens in the dashboard.
**Related Issue** : #2952 
1. Check one dashboard on the dashboard view.
2. When entering the dashboard edit screen, make sure that you move to the edit screen without loading data on the dashboard.
- [] New feature (non-breaking change which adds functionality)
> #2952 Remove unnecessary loading data when switching the view / edit screen on the dashboard

- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-name.component.ts
- discovery-frontend/src/app/data-preparation/dataset/create-dataset/create-dataset-selectfile.component.ts
- discovery-frontend/src/app/data-preparation/dataset/dataset-detail.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepDatasetFileService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepPreviewLineService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataset.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDatasetProjections.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/service/PrDatasetService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
the fileFormat field in PrDataset will be removed
that information is not needed because we can see the file format by uri
[2962](https://github.com/metatron-app/metatron-discovery/issues/2962)
create datasets from files of various formats
the fileFormat field must not be used
PrDataset is JPA entity.
the table should be changed.
make sure that ALTER TABLE is done well
> #2962 stop to use fileFormat

- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.html
- discovery-frontend/src/app/data-preparation/dataflow/dataflow-detail/component/edit-dataflow-rule/rule-union-popup/rule-union-popup.component.ts
the union rule works for same schema only.
[2983](https://github.com/metatron-app/metatron-discovery/issues/2983)
add a union rule with datasets have different schema
the union button must be disabled
> #2983 constraints of union rule

- discovery-server/src/main/java/app/metatron/discovery/config/SchedulingConfig.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/PrepProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/RevisionSet.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/TeddyImpl.java
- discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/dataprep/DatasetCacheOutJob.java
Old W.DS will be cache-out'ed according to the configuration.
polaris.dataprep.sampling.cacheSize -> How many W.DS should be keep.
polaris.dataprep.sampling.idleTime -> Although it's the oldest, if it had been used recently, it's excepted.
**Related Issue** : #2966 
Ran locally.
No, thanks.
> #2966 dataset cache out per every 3 hours

- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/entity/PrDataset.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/dataprep/transform/PrepTransformRequest.java
When re-import a W.DS from an exported file, not the original W.DS is recovered.
**Related Issue** : #2987
Ran locally.
No, thanks.
> #2987 import W.DS with original name

- discovery-frontend/src/app/meta-data-management/detail/component/column-schema/column-schema.component.html
Fix column type of metadata to be same as filter type
1. Management - Metadata - Column Details
2. Check that the column type of the metadata is the same as the type of the filter.
> fix column type of metadata to be same as filter type

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/dialect/HiveDialect.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
워크벤치 스키마 브라우저 같은 사용자가 쿼리를 제어할 수 없는 부분에 한하여 커넥션에 `hive.mapred.mode=nonstrict`를 추가로 실행하도록 수정 하였습니다.
#2997
Hive 서버에 아래와 같이 설정 후 파티션 컬럼이 포함된 테이블을 만들고 스키마 브라우저에서 'Data' 탭에 데이터가 정상적으로 보여지는지 확인 했습니다.
```xml
<property>
<name>hive.mapred.mode</name>
<description>The mode in which the hive operations are being performed. 
In strict mode, some risky queries are not allowed to run. They include:
Cartesian Product.
No partition being picked up for a query.
Comparing bigints and strings.
Comparing bigints and doubles.
Orderby without limit.</description>
<value>strict</value>
</property>
```
> #2997 Workbench schema information Data tab query error

- discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
changed to use plain text password for sending welcome mail
**Related Issue** : #3045 
1. turn on "bcrypt-encoder" in application.yaml
2. Go to Administration > User > Members
3. Click on 'Create member'
4. Create user with email address.
5. Check email inbox.
6. See the plain password in the welcome email.
> #3045 decrypt password in welcome email

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
Use enigneName parameter regardless of connection type.
**Related Issue** : #3040 
1. Create Chart with Data Source of Korean Name
2. Create user defined column
3. Click "Validation check"
4. Validation check success
> #3040 use engineName parameter for user-defined validation

- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
Real-time dashboard should use queried data, not cached data when chart drawing.
**Related Issue** : #3049 
1. Create real-time dashboard.
2. turn on "Data sync" in dashboard edit.
3. turn on "Data sync" in widget tool bar.
4. should re-draw the chart every interval.
> #3049 In case of real-time dashboard, cache should not used

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/ExpressionField.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
- discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java
The point that is considered unnecessary substitution is the dimension type of user-defined field.
Therefore, in the case of it, only the measure type of user-defined fields are managed by substitution.
_불필요한 치환이라고 판단되는 지점은 차원값 사용자 정의 필드입니다. 
따라서, 차원값 사용자 정의 필드의 경우 치환하지 않고 측정값 사용자 정의필드는 치환하여 관리합니다._ 
**Related Issue** : #3062 
First, I linked with the Sales data source that we manage internally in the dashboard.
From there, I created a chart widget and then created two types of user-defined fields as shown below. Next, I built a chart with the custom fields I created.
_대시보드에서 내부적으로 관리하고 있는 Sales 데이터 소스와 연결합니다. 
차트 위젯을 생성하고, 아래와 같이 두가지 타입의 사용자 정의 필드를 생성합니다. 
생성한 사용자 정의 필드를 가지고, 차트를 생성해 봅니다._ 
dimension type of user-defined field
- name : r_symbol
- expression : SUBSTRING( [Region] , 0, 1 ) …
> Remove unnecessary expression substitution

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/filter/TimeRelativeFilterTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormatTest.java
When the relative filter is processed in the system, the time filter is configured by setting the unit lower time value to 0.
**Related Issue** : #3099 
You can check with the built-in "Sales" data source.
1. Create a text table in the dashboard that you linked to the "Sales" data source.
2. Place "Category" in the column area, "OrderDate" with the "Month" granularity in the row area, and "Sales" in the Aggregation.
3. Confirm that the result value of the relative mode and the absolute mode is the same as below
> Adjust filtering start/end timestamp when specifying relative filter

- discovery-frontend/src/app/common/domain/extension.ts
- discovery-frontend/src/app/external/external-page.component.ts
- discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.html
- discovery-frontend/src/app/layout/layout/component/lnb/lnb.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/extension/ExtensionProperties.java
The open target of the lnb menu supports "new tab" and "frame" types.
**Related Issue** : #3155
1. modify application.yaml
```
extensions:
lnb:
- name: Extensions
parent: management
level: 2
subMenus:
- name: Open New Tab menu
parent: Extensions
route: https://metatron.app
openTarget: blank
- name: Open in iFrame menu
parent: Extensions
route: https://metatron.app
openTarget: frame
```
2. Click on the LNB menu to see if both openTarget types "iframe" and "new tab" work well.
> The open target of the lnb menu supports "new tab" and "frame" types

- discovery-server/src/main/java/app/metatron/discovery/domain/workspace/WorkspacePredicate.java
An error occurs in the following cases when moving the workbook.
- No authorized workspace.
- When the data source is not open data
So, modified the predicate logic to search the target workspace.
1. Log in with "metatron" account
2. Move the workbook created for testing
> When moving a workbook, always check the permission of the target workspace

- discovery-server/src/main/java/app/metatron/discovery/config/OAuth2ServerConfig.java
- discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
If you change the row of the initial client_id (polaris_trusted, polaris_client) in the oauth_client_details table and restart the server, the changed values ​​are initialized.
Therefore, liquibase manages the initial data.
1. Empty the data in the oauth_client_details table.
2. After the server is started, check if the initial data is inserted in the oauth_client_details table.
3. Modify the initial client_id (polaris_trusted, polaris_client) row in the oauth_client_details table.
4. After restarting the server, verify that there are no changes to the data in the oauth_client_details table.
> fix initial oauth client details

- discovery-server/src/main/asciidoc/api-datasource-query-guide.adoc
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/SqlQueryRequest.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/DruidEngineRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineProperties.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/QueryService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/MeasureField.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/TimestampField.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/format/TimeFieldFormat.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/Granularity.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/granularities/AbstractGranularity.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/granularities/DurationGranularity.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/granularities/PeriodGranularity.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/granularities/SimpleGranularity.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
There are cases where fixed granularity cannot be solved when using Search API. Therefore, API was constructed by using the period and duration type granularity options supported by Druid.
**Related Issue** : #3154 
Using the [Search API](https://github.com/metatron-app/metatron-discovery/blob/master/discovery-server/src/main/asciidoc/api-datasource-query-guide.adoc#search) documentation, run two types of queries as shown below to see if the results were viewed in the intended period.
Case1. ISO8601 Period format
```
{
"name": "sales_geo",
},
"filters": [
],
"projections": [
{
"type": "timestamp",
"name": "OrderDate",
"alias": "DAY(OrderDate)",
"ref": null,
"granularity": {
"type": "period",
"period": "P2M",
"timeZone": "UTC",
"origin": …
```
> add granularity options - peroid, duration (only Search API)

- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
*IT Security Vulnerability Notes.*
Stagedb access user information is exposed.
1. login metatron discovery
2. After logging in, check the list of APIs that are called with the dev tool.
3. check '/api/storage/stagedb' API response.
4. Confirm that the response does not contain user information.
> masking stagedb connection's user info

- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
In some cases, the following error occurs when creating a custom field using an expression.
```
QueryTimeExcetpion: [{"error":"Instantiation of [simple type, class io.druid.query.groupby.GroupByQuery] value failed: Missing fields [xxx] for postAggregator [SUM(yyy}]
```
In the case of a calculation expression that does not use an aggregation operation, it is common.
- Create a dashboard connected to the "Sales" data source.
- Create a user-defined field "aaa" by creating an expression ("Sales + 1"). At this time, you should not use a separate aggregate operation function. (avgof, sumof...)
- Place another dimension value (ex. Category) and user-defined "aaa" on the chart shelf and select the aggregation "AVG" on the shelf.
- Check if the chart is displayed normally.
> fix error for calculating user-defined field

- discovery-server/src/main/java/app/metatron/discovery/domain/dataconnection/query/NativeCriteria.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/mdm/MetadataService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionServiceTest.java
Apply limit clause for sampling druid table
1. Create a dataset in data preparation
2. Select druid type connection.
3. Select druid table and see how many rows are displayed.
We need to test metadata sample view.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] My code follows the code style of this project.
- [x ] I have added tests to cover my changes.
> #3305 Apply limit clause for sampling druid table

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
Fix creating new custom fields when re-entering the chart editing page
**Related Issue** : #3314 
1. Create a new dashboard.
2. Create a new chart with a new custom fields.
3. Go to the chart edit popup window created using the custom field.
4. Create a new custom field.
5. The custom field is visible in the data column list.
> fix creating new custom fields when re-entering the chart editing page

- discovery-frontend/src/app/dashboard/util/dashboard.util.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-frontend/src/app/shared/datasource-metadata/service/constant.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/datasource/MultiDataSource.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/datasource/MultiDataSourceTest.java
If a dashboard with multiple datasources includes an associated linked datasource, an error occurs when creating a chart.
And I mofied association bug with linked datasources.
https://github.com/metatron-app/metatron-discovery/issues/3361
Go to 'Creating dashboard'
Select two linked type datasource and associate each other.
Creating chart.
No screen displays(Javascript error)
> F#3361 associated linked datasource

- discovery-frontend/src/app/common/component/data-preview/data.preview.component.html
- discovery-frontend/src/app/common/component/data-preview/data.preview.component.ts
When using datasource detail view with linked datasource, we need to check temporary datasource first.
It will improve performance.
https://github.com/metatron-app/metatron-discovery/issues/3367
Go to dashboard.
Click datasource source detail view.
Check discovery reads from temporary datasource(You can also see column detail view with linked datasource).
> #3367 When temporary datasource exists, read from temporary datasource first

- discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.html
- discovery-frontend/src/app/explore-data/explore-data/explore-data-main.component.ts
- discovery-frontend/src/app/meta-data-management/metadata/service/metadata.service.ts
Bug fix for creator pane in data explorer
https://github.com/metatron-app/metatron-discovery/issues/3370
1. Go to 'Data Explorer'
2. Click on 'Make a favorite creator in Data creator menu'
3. Go back Data explorer home.
4. The favorite creator pane displays the creator. If you click the creator, you can go to creator detail view of data explorer.
- [] My change requires a change to the documentation.
> #3370 Bug fix for creator pane in data explorer

- discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
If I use the prediction function of line chart, it occurs error.
https://github.com/metatron-app/metatron-discovery/issues/3374
1. Go to 'Draw line chart'
2. Click on 'Prediction'
3. You can see the prediction line for every series of line chart.
> #3374 Prediction of line chart does not work.

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceTemporaryRepository.java
- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineQueryService.java
- discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/engine/TemporaryCleanJob.java
If Druid is shutdown anomaly after creating a temporary data source, Discovery does not know the data source has been disabled and tries to get data from it.
https://github.com/metatron-app/metatron-discovery/issues/3382
1. Create linked datasource.
2. Create dashboard from created linked datasource.
3. Restart Druid.
4. Check to reload message appears.
Discovery needs to know the temporary datasource is disabled and reload it.
Discovery reload process is unstable in my local environment. We need to check stability of re-ingestion process.
> #3382 bugfix non-existing temporary datasource cleansing and some code cleansing

- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/widget/Widget.java
- discovery-server/src/main/resources/db/changelog/db.changelog-master.xml
- discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
If the widget configuration length exceeds 64kb, an error occurs.
DataType of widget_conf column has been changed to mediumtext
1. Create Dashboard and widget.
2. Create enough user-defined fields to store data over 64kb.
> fix widget_conf column's dataType to MEDIUMTEXT

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormatTest.java
Addition of processing logic when null is included in Double type result.
Previously, JsonNullNode was treated as String, but changed to treat as null.
1. Create Dashboard and chart
2. The dimension value whose group by result is null is put on the cross shelf and the data containing null in the result is drawn on the chart.
> Addition of processing logic when null is included in Double type result

- discovery-frontend/src/app/page/page.component.ts
fix user defined field duplicated in multi datasources
**Related Issue** : #3397 
1. When creating a dashboard, select two or more datasources to create them.
2. Click Create Chart.
3. Create a user defined field from the default datasource in the chart creation popup.
4. After moving to another datasource, check if the user defined field created in step 3 is not visible.
> #3397 fix user defined field duplicated in multi datasources

- discovery-server/src/main/asciidoc/application-config-guide.adoc
- discovery-server/src/main/java/app/metatron/discovery/common/oauth/CustomDaoAuthenticationProvider.java
- discovery-server/src/main/java/app/metatron/discovery/domain/user/UserPasswordProperties.java
exclude from login lock when login fail of whitelist users including admin
1. Add password lock count config to application.yaml
For testing, the count is 3.
```
polaris:
user:
password:
lockCount: 3   # The Password must match within that number.
```
2. repeat 4 times in a row to try logging in with the wrong password of admin
3. Add password lock whitelist config to application.yaml
For testing, add 'polaris'
```
polaris:
user:
password:
excludeLockUsername: [polaris]      # Whitelist except login password lock.
```
4. repeat 4 times in a row to try logging in with the wrong password of polaris
> exclude from login lock when login fail of whitelist users

- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TimeseriesQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TopNQueryBuilder.java
Currently supported, but some errors exist. In the process of deleting unused user-defined columns for performance, there is a situation that cannot be processed. Druid removes unused columns during query optimization, so modify to include all user-defined columns in the query.
https://github.com/metatron-app/metatron-discovery/issues/3411
https://github.com/metatron-app/metatron-discovery/issues/3411
> #3411 Making a user-defined column reference another user-defined column

- discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
If the mail server is not linked, the user cannot reset the password.
When the administrator changes the user's status to Activate, it initializes the number of password failures.
1. add password lock count config to application.yaml
For testing, the count is 3.
```
polaris:
user:
password:
lockCount: 3   # The Password must match within that number.
```
2. Repeat 3 times in a row to try logging in with the wrong password.
3. Check the login fail message.
4. After logging in to the admin account, change the account whose login failed to Activate.
(Activate -> Inactive -> Activate)
5. Try logging in with the correct password.
> reset password failure count when user is activated

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/HiveTableInformation.java
- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageProperties.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
support parquet format for staging db.
1. create parquet format table in staging db.
```
CREATE TABLE parquet_test (
id int,
category string,
sales int)
PARTITIONED BY (part string)
STORED AS PARQUET;
desc parquet_test;
INSERT INTO TABLE parquet_test
VALUES 
(0, 'cat1', 100, 'part1'), 
(1, 'cat2', 1100, 'part1'),
(2, 'cat1', 1010, 'part2'), 
(3, 'cat2', 1001, 'part2');
```
2. create datasource with parquet hive table.
3. Check whether parser.type, parser.parseSpec.format, and parser.timestampSpec.replaceWrongColumn of the created ingestion spec are as follows.
```
{
"type" : "index_hadoop",
"spec" : {
"dataSchema" : {
...
"parser" : {
"type" : "parquet",
"parseSpec" : {
"format" : "timeAndDims",
...
},
"timestampSpec" : {
...
"replaceWrongColumn" : false,
...
}
}
}, …
```
>  support parquet format for staging db

- discovery-frontend/src/app/dashboard/component/custom-field/custom-field.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SearchQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectMetaQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SelectStreamQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TimeseriesQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/TopNQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
- discovery-server/src/test/java/app/metatron/discovery/query/druid/AbstractQueryBuilderTest.java
- discovery-server/src/test/java/app/metatron/discovery/query/polaris/ComputationalFieldTest.java
It also includes improvements in treating variable containing space and checking user-defined function containing aggregation functions. It also includes a patch for #3413 
https://github.com/metatron-app/metatron-discovery/issues/3427
https://github.com/metatron-app/metatron-discovery/issues/3413
Additionally, the logic for determining whether a field includes aggregation has been improved for this issue and treating variable containing space like 'total income'.
See the issue
https://github.com/metatron-app/metatron-discovery/issues/3427
Additionally, we can test following.
1. Create user-defined field 'total sales' : SUMOF([Sales])
2. Create user-defined field 'total profit' : SUMOF([Profit])
3. Create user-defined field 'profit ratio' : [user_defined.total profit] …
> #3427 Hot fix for #3411 Remove variable unUsedVirtualColumnName.

- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpec.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpecBuilder.java
Move spec temporary from parameter to json.
https://github.com/metatron-app/metatron-discovery/issues/3429
After creating temporary datasource, see it's type is not temporary.
Discovery always creates non-temporary datasource for HA issue when creating its own temporary datasource.
> #3429 Move spec temporary from parameter to json.

- discovery-frontend/src/app/page/component/analysis/prediction/analysis-prediction.component.ts
- discovery-frontend/src/app/page/component/analysis/service/analysis.prediction.service.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcCSVWriter.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/DataQueryController.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/CovarianceQueryBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/SegmentMetaDataQueryBuilder.java
See the issue
https://github.com/metatron-app/metatron-discovery/issues/3431
And I also commit the following
1. If Druid returns NaN or Infinity for Double type in Druid SQL, It returns an error.
For example
select Profit / Sales from sales_geo limit 8000;
Workbench returns ClassCastException.
2. Previous issue #3427, I omit fixes for SegmentMetaDataQueryBuilder and CovarianceQueryBuilder.
Discovery works well without this bug fix. But I commit for consistency.
https://github.com/metatron-app/metatron-discovery/issues/3431
See the issue
https://github.com/metatron-app/metatron-discovery/issues/3431
> F#3431 Bugfix for prediction of user-defined field

- discovery-frontend/src/app/dashboard/filters/bound-filter/bound-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/filters/bound-filter/configure-filters-bound.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
The initial maximum and minimum values ​​of the measure filter must not be 0. It should be Number.MIN_SAFE_INTEGER and Number.MAX_SAFE_INTEGER. Otherwise, the wrong filter is applied.
https://github.com/metatron-app/metatron-discovery/issues/3436
See the issue.
https://github.com/metatron-app/metatron-discovery/issues/3436
> #3436 Fix for invalid initializing measure-filter

- discovery-frontend/src/app/workspace/workspace.component.ts
Replace private workspace name with the user's full name, not the username.
https://github.com/metatron-app/metatron-discovery/issues/3456
1. Change the user's full name to "Test user".
2. Check the user's own workspace has been changed to "Test user's workspace".
- [] My change requires a change to the documentation.
> #3456 Replace private workspace name with user's fullname

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/PivotResultFormat.java
- discovery-server/src/test/java/app/metatron/discovery/core/oauth/OAuthRequest.java
- discovery-server/src/test/java/app/metatron/discovery/core/oauth/OAuthTestExecutionListener.java
- discovery-server/src/test/java/app/metatron/discovery/domain/datasource/data/DataQueryRestIntegrationTest.java
Fixed that NPE error occurred when there were two or more aggregation fields in the query when searching using period granularity.
**Related Issue** : N/A
In the current timestamp type of column specification, the period type of granularity property is not supported by the UI, so you need to check the result through the Search API.
As shown below, it can be confirmed that no error occurs when calling with the request body content.
Ref. 1 : https://github.com/metatron-app/metatron-discovery/blob/master/.github/USE_REST_API.md
Ref. 2 : https://discovery.metatron.app/docs/api-guide.html#resources-datasource-query
(POST) /api/datasources/query/search
[Request Body]
```
{
"name": "sales_geo"
},
"filters": [
],
"pivot": {
"columns": [
{
"type": "timestamp", …
```
> Fixed NPE error when searching using period granularity

- discovery-frontend/src/app/engine-monitoring/query/query.component.ts
change the initial value of time filter on the Engine Monitoring Query tab to the last hour
**Related Issue** : #3515 
1. Go to Engine Monitoring
2. Click on Query tab.
3. Check whether the initial value of the time filter is the last hour.
> #3515 change the initial value of time filter on the Engine Monitoring Query tab

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/DataSourceQueryHistory.java
- discovery-server/src/main/resources/db/changelog/discovery.changelog-3.4.0.xml
If the length of the message caused by data query failure is more than 5000 bytes, an error occurs.
DataType of query_message column has been changed to mediumtext
1. Create Dashboard and widget.
2. Executes a query whose message length is 5000 bytes or more due to a data query failure.
3. Additionally, check the data type of the **query_message** column of the **datasource_query** table.
> fix query_message column's dataType to MEDIUMTEXT

- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
If the measure field is a user field and an alias is applied to the dimension field, the query result value is different.
Selecting the same shelf, but setting Alias results in different results as shown below.
1. AS-IS Select Query
```
{
"queryType": "groupBy",
"type": "table",
"name": "event_log_sample"
},
"granularity": "all",
"intervals": [
"2020-10-26T00:00:00.000Z/2020-11-29T23:59:59.999Z"
],
"virtualColumns": [
{
"type": "expr",
"outputName": "user_defined.dt_day",
"expression": "TIME_FORMAT(__time,'yyyy-MM-dd')"
},
{
"type": "expr",
"outputName": "user_defined.MEASURE_1",
"expression": "\"cnt\""
}
],
"dimensions": [
{
"dimension": "month_week",
"outputName": "주차"
},
{
"dimension": "depth_1",
"outputName": …
```
> Fix query error with dimension alias

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/MapParser.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/parser/Parser.java
- discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
Currently, when loading data through StagingDB (Parquet type), a library conflict problem in Druid occurs.
So, should not use ParquetParser, but MapParser.
* AS-IS
```
dataSchema.parser.type : parquet
```
* TO-BE
```
dataSchema.parser.type : map
```
> Using MapParser instead of ParquetParser due to library conflict in druid

- discovery-server/src/main/java/app/metatron/discovery/domain/storage/StorageController.java
Fixed NPE error when checking staging db metastore
1. Create a datasource with stagingdb
2. In the third step, ingestion settings, if NPE does not occur and a partition exists, check that the textbox for entering the partition key is displayed.
> Fixed NPE error when checking staging db metastore

- discovery-frontend/src/assets/css/theme_dark/metatron/page.css
fix original grid chart css in black theme
1. Change black theme.
2. Create a grid chart of the original view type.
3. The text color of the dimension type line is displayed in black.
Pivot type, original theme
> fix original grid chart css in black theme

- discovery-extensions/bigquery-connection/src/main/java/app/metatron/discovery/BigQueryConnectionExtension.java
An error occurs when creating a data source because the quoted field name processing code is missing.
1. create datasource from database
2. select bigquery connection
> fix quoted field name for bigquery

- discovery-frontend/src/app/common/component/chart/base-chart.ts
Fix auto measure range calculation error in stacked chart
1. Create a stacked chart.
2. Uncheck Mini-map.
3. Check that the measure range is automatically calculated in the stacked chart and displayed properly on the screen.
> Fix auto measure range calculation error in stacked chart

- discovery-server/src/main/java/app/metatron/discovery/query/druid/aggregations/DistinctSketchAggregation.java
- discovery-server/src/main/java/app/metatron/discovery/query/polaris/ComputationalField.java
Change the aggregation type of IFCOUNTD user calculation formula to thetaSketch type
**Related Issue** : #3602 
1. create dashboard with sales datasource
2. create user custom measure
```
IFCOUNTD( [Region] == 'Central',  [OrderID] )
```
3. Check the debug log to see if ifcountd's aggregation type is changed to thetaSketch.
```
{
"type": "thetaSketch",
"name": "aggregationfunc_000",
"fieldName": "OrderID",
"predicate": "Region == 'Central'",
"size": 65536,
"shouldFinalize": true
},
```
> #3602 change aggregation type of ifcountd to thetaSketch

- discovery-frontend/src/app/common/component/chart/base-chart.ts
fix chart error where datazoom property does not exist
1. See the PR #3596 
2. Create a pie chart.
3. Check if the chart is displayed normally without any script error.
> fix chart error where datazoom property does not exist

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/result/ChartResultFormat.java
- discovery-server/src/main/java/app/metatron/discovery/query/druid/queries/GroupByQueryBuilder.java
add sorting columns for cumulative option
**Related Issue** : #3616 
1. create cumulative line chart with "sales" datasource.
2. select option below
3. please check that the accumulated data comes out correctly
> #3616 add sorting columns for cumulative option

- discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/scheduling/common/OAuthCacheOutJob.java
Fixed token not being deleted when logging out
Fix CCE that occurs when the cache entry saved as NULL Value is deleted by searching for expired tokens
```
Caused by: java.lang.ClassCastException: org.infinispan.spring.provider.NullValue cannot be cast to app.metatron.discovery.common.oauth.token.cache.CachedToken
at app.metatron.discovery.domain.scheduling.common.OAuthCacheOutJob.lambda$executeInternal$0(OAuthCacheOutJob.java:56)
```
1. Set to store tokens in cache. (See the PR #3571)
2. Login A account and check if the token is stored in the cache (/api/admin/caches/token-cache).
3. Logout A account and check whether the token stored in the cache has been deleted.
> fix CCE expired oauth token

- discovery-frontend/src/app/dashboard/update-dashboard.component.ts
Fixed that the widget filter is changed to a global filter after copying the widget.
**Related Issue** : #3651 
See the issue #3651
> #3651 Fixed that the widget filter is changed to a global filter after copying the widget

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/connection/jdbc/JdbcConnectionService.java
In the case of a field created by data source field sync, the sqlName attribute is omitted.
At this time, if the data source is reingested, an error occurs in the query generation step.
> fix generating query without sqlName property

- discovery-frontend/src/app/common/component/chart/type/combine-chart.component.ts
fix to find secondary axis in combine chart
1. Check whether the previously created combine chart is rendered normally.
2. Check whether the newly created combine chart is rendered normally.
> fix to find secondary axis in combine chart

- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/domain/workbook/configurations/field/measure-field.ts
- discovery-frontend/src/app/page/page-pivot/map/map-page-pivot.component.ts
- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
- discovery-frontend/src/app/page/page-pivot/pivot-context.component.html
- discovery-frontend/src/app/page/page-pivot/pivot-context.component.ts
- discovery-frontend/src/app/page/page.component.ts
- discovery-server/src/main/java/app/metatron/discovery/query/druid/AbstractQueryBuilder.java
For hashed_map type, countd must be applied unconditionally.
**Related Issue** : #3691 
1. Create a dashboard using a data source with a hashed_map type.
2. From the created dashboard, go to the chart creation screen and place a hashed_map type field on the shelf.
3. Check if the aggregation type is applied as countd.
> F#3691 set countd aggregation in widget

- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/embedded/page/embedded-page.component.ts
There is a problem that the filter is not applied when the time filter is not placed as a widget.
**Related Issue** : #3741 
1. Create a dashboard with time filters.
2. Compare the data difference when the time filter is inserted as a widget and when it is not.
> #3741 Fixed an issue where time filters were not applied

- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
The tooltip is hidden by the widget and is not visible.
**Related Issue** : #3745 
1. Add the Measure Filter widget to your dashboard.
2. Check that the icon tooltip at the top of the dashboard is displayed normally when it is displayed.
> #3745 Tooltips are not displayed properly.

- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.html
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/configure-filters-inclusion.component.ts
- discovery-frontend/src/app/dashboard/filters/inclusion-filter/inclusion-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.css
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/app/domain/workbook/configurations/filter/inclusion-filter.ts
- discovery-frontend/src/assets/i18n/en.json
- discovery-frontend/src/assets/i18n/ko.json
- discovery-frontend/src/assets/i18n/zh.json
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilter.java
- discovery-server/src/test/java/app/metatron/discovery/domain/workbook/configurations/filter/InclusionFilterTest.java
Added ability to change default size of filter list
**Related Issue** : #3717 
1. On the Create Dimension Value Filter screen, check if the number of list views can be changed.
2. Check that the changed size are also persisted in panels and widgets.
> #3717 Added ability to change default size of filter list

- discovery-server/src/main/java/app/metatron/discovery/common/datasource/DataType.java
- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/Field.java
Support thetaSketch type when adding engine datasource
**Related Issue** : #3644
1. Create a datasource using the engine data source including thetaSketch type column.
2. Check whether the thetaSketch type column is displayed as HashedMap.
3. When creating a chart using the created datasource, check that the aggregation type of the column is fixed to COUNTD.
> Support thetaSketch type when adding engine datasource

- discovery-server/src/main/java/app/metatron/discovery/domain/engine/EngineLoadService.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpec.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/BulkLoadSpecBuilder.java
The default value of the overwrite property of the druid ingestion spec has been changed to true.
Accordingly, the corresponding property was changed to be set to false.
1. create linked datasource or chart preview in workbench.
> Add overwrite property to ingestion spec builder

- discovery-frontend/src/app/common/component/chart/type/line-chart.component.ts
The selection filter of the multi series line chart is malfunctioning.
**Related Issue** : #3805 
1. Create a line chart with multiple series.
2. Check if the filter is applied normally when the chart is clicked.
> #3805 Fixed an error in the selection filter of multi-series line charts

- discovery-frontend/src/app/common/component/abstract.component.ts
- discovery-frontend/src/app/dashboard/filters/component/time-range.component.ts
- discovery-frontend/src/app/dashboard/util/filter.util.ts
- discovery-frontend/src/app/dashboard/widgets/filter-widget/filter-widget.component.ts
When the date of the range filter is changed, other dates are also changed.
**Related Issue** : #3811 
1. Create a dashboard by adding a time range filter.
2. When you change the time range, make sure the other date ranges change.
3. Check if the filter is applied normally.
> #3811 range filter changed error

- discovery-frontend/src/app/page/chart-style/color-option.component.ts
Fixed a script error that occurred when modifying the color of a measure value in a grid chart
1. Create a grid chart with gradient color settings.
2. When editing the chart, check whether the color setting is executed normally.
> Fixed a script error that occurred when modifying the color of a measure value in a grid chart

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/IngestionSpecBuilder.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/index/IndexSpec.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/AbstractTuningConfig.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/BatchTuningConfig.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/HadoopTuningConfig.java
- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/KafkaTuningConfig.java
- discovery-server/src/test/java/app/metatron/discovery/spec/druid/ingestion/IndexSpecTest.java
Apache Common's BeanUtils can not convert nested object directly.
So I changed the copying properties logic and enhance some code clairity.
#3828 
1. Added unit test
2. Patch an existing datasource and check the nested spec is preserving
> #3828 Nested object in tuningConfig should be overrided

- discovery-frontend/src/app/app.component.ts
- discovery-frontend/src/app/dashboard/component/selection-filter/selection-filter.component.ts
- discovery-frontend/src/app/workbook/workbook.component.ts
- discovery-frontend/src/assets/css/lib/dnd/style.css
Removed the API for querying filter candidate values from the dashboard query screen.
**Related Issue** : #3857 
1. Create a dashboard that uses filters but does not place widgets.
2. Check if the filter candidate values are inquired during the initial inquiry of the dashboard.
3. Check that the candidate values are normally displayed in the top filter summary information.
> #3857 Removed the API for querying filter candidate values from the dashboard query screen.

- discovery-frontend/src/app/common/component/abstract.component.ts
remove websocket retry message toast
1. If websocket reconnection is attempted more than 20 times, the existing toast pop-up is removed.
> remove websocket retry message toast

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/tuning/AbstractTuningConfig.java
When overriding the tuningConfig for the real-time datasource, 
an error occurs if the tugningConfig does not exist.
So skip the overriding method when the tuningConfig is null.
#3828 
already applied to the GV environment and prove it.
> Fix config overriding when tuningConfig is null

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/dashboard/filters/abstract-filter-panel.component.ts
- discovery-frontend/src/app/dashboard/filters/time-filter/time-filter-panel.component.html
- discovery-frontend/src/app/dashboard/util/filter.util.ts
Fix chart filter errors
1. When designating a chart filter, check if the parameters are configured normally.
2. After selecting Relative > Lastest Time > Previous 1 month, check if an error does not occur when saving the dashboard.
- [X] Bug fix (non-breaking change which fixes an issue)
> fix error chart filter

- discovery-frontend/src/app/domain/workbook/workbook.ts
- discovery-frontend/src/app/workbook/workbook.component.ts
- discovery-frontend/src/app/workspace/workspace.component.ts
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/WorkBookProjections.java
Modify to move from workbook to parent workspace
**Related Issue** : #3921 
1. Go to workbook
2. Open another tab in your browser and go to another workbook.
3. In the browser tab of the first step, click the back button in the upper left corner.
4. Confirm that the workbook is moved to the workspace it belongs to.
> #3921 workbook to parent workspace

- discovery-frontend/src/app/common/component/chart/option/converter/legend-option-converter.ts
Fixed an error where the chart's legend and color settings did not match
1. Create a chart and display a legend.
2. While changing the color settings, make sure they are applied properly to the legend.
> fix legend color by removing duplicated data

- discovery-frontend/src/app/common/component/chart/type/grid-chart.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.html
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/page/page.component.ts
Reset when changing global filter after adjusting grid chart width
**Related Issue** : #3925 
1. Create a dashboard with a grid chart and filter widget.
2. Check if the width of the grid chart is maintained when you change the filter on the browse screen.
> #3925 Reset when changing global filter after adjusting grid chart width

- discovery-frontend/src/app/common/component/chart/base-chart.ts
- discovery-frontend/src/app/common/component/chart/option/converter/legend-option-converter.ts
Chart and legend colors are displayed differently
**Related Issue** : #3936 
If you put one dimension value on the cross shelf and set the color setting to the dimension value, the legend color is displayed strangely.
- [X] Bug fix (non-breaking change which fixes an issue)
> Chart and legend colors are displayed differently

- discovery-frontend/src/app/page/page-pivot/page-pivot.component.ts
After changing the granularity of the timestamp field of the grid to MONTH and downloading the chart data, the granularity is being downloaded as DAY.
**Related Issue** : #3968 
After changing the granularity of the timestamp field of the grid to MONTH, check if the granularity is normally applied when the chart data is downloaded.
> #3968 set right granularity of download grid chart

- discovery-extensions/athena-connection/README.md
- discovery-extensions/athena-connection/pom.xml
- discovery-extensions/athena-connection/src/main/assembly/assembly.xml
- discovery-extensions/pom.xml
athena jdbc dependency removed from maven central.
Updated README.md so that users can directly download and compile the jdbc driver.
**Related Issue** : #3977
> #3977 remove athena jdbc dependency

- discovery-server/src/main/java/app/metatron/discovery/domain/datasource/data/SearchQueryRequest.java
- discovery-server/src/main/java/app/metatron/discovery/domain/workbook/configurations/field/TimestampField.java
fix download chart data  with timestamp field that is a dimension role
1. Create a grid chart using a data source that includes a timestamp field that is a dimension role, 
2. Save table as file.
3. Make sure the correct data is displayed.
> fix download chart data  with timestamp field that is a dimension role

- discovery-frontend/proxy.conf.js
- discovery-frontend/src/app/common/component/abstract.component.ts
add websocket disconnection when is onbeforeunload called
1. Check the websocket disconnection logging when is onbeforeunload called.
2. Check whether the workbench query is normally executed.
3. Check if the activity stream is added normally.
> add websocket disconnection when is onbeforeunload called

- discovery-server/src/main/resources/templates/api/oauth/login.html
로그인 페이지에서 로그인이 성공한 후 나타나는 Welcome 다이얼로그내 아래 이미지와 같이 "X" 가 노출되어있습니다. 이때 "X" 버튼을 클릭하면 로그인이 완료된 후에도 로그인 화면이 그대로 남겨져있는 문제가 있습니다.  이러한 상황을 방지하고자, X 버튼 제거를 제안 드립니다. 
'X' button is exposed as shown in the image below on the welcome(accesslog) dialog that appears after successful login on the login page. At this time, if you click the "X" button, there is a problem that the login screen remains even after login is completed. To prevent this situation, I suggest removing the 'X' button. 
**Related Issue** :  #3905
1. Access external login page ex. https://dev-login.metatron.app/oauth/authorize?response_type=code&client_id=polaris_trusted&redirect_uri=http%3A%2F%2F52.231.101.87%3A8380%2Fapi%2Foauth%2Flogin&scope=trust%20read%20write?client_id=polaris_trusted&redirect_uri=http%3A%2F%2F52.231.101.87%3 …
> Remove 'X' button when showing access log dialog on log-in page

- discovery-server/src/main/java/app/metatron/discovery/common/Mailer.java
- discovery-server/src/main/java/app/metatron/discovery/domain/auth/AuthenticationController.java
- discovery-server/src/main/java/app/metatron/discovery/domain/auth/OauthClientInformation.java
- discovery-server/src/main/java/app/metatron/discovery/domain/user/UserController.java
- discovery-server/src/main/resources/messages/messages.properties
- discovery-server/src/main/resources/messages/messages_en.properties
- discovery-server/src/main/resources/messages/messages_ko.properties
- discovery-server/src/main/resources/templates/api/email/user_reset_password.html
- discovery-server/src/main/resources/templates/api/email/user_reset_password_by_admin.html
- discovery-server/src/main/resources/templates/api/email/user_signup_approved.html
- discovery-server/src/main/resources/templates/api/email/user_signup_approved_by_admin.html
- discovery-server/src/main/resources/templates/api/email/user_signup_denied.html
- discovery-server/src/main/resources/templates/api/email/user_signup_request.html
- discovery-server/src/main/resources/templates/api/oauth/reset-password.html
- discovery-server/src/test/java/app/metatron/discovery/common/MailerTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/user/UserRestIntegrationTest.java
Discovery 기반 서비스 운영시 인증 기능에서 전달하는 패스워드 초기화 관련 메일 내용에 대해 개선이 필요하여 아래와 같이 수정해 보았습니다.
_When operating a Discovery-based service, I need to improve the password initialization related email delivered by the authentication function, so I modified it as follows._
→ 메일 내용 내 Copyright 문구 제거 (전체 메일 템플릿 대상)
- Copyright 를 이메일 전달시까지 표시하는것은 무의미하다고 판단되었습니다. 관련하여 각 서비스가 discovery의 인증기능을 활용하는 경우, 각 서비스별 메일 템플릿용 Copyright 문구를 관리해야하는 부담이 있고, 정보를 제공하는 이메일에 Copyright 정보가 필요할지도 의문이 들어 제거하는것으로 제안 드립니다. 
→ _Remove the Copyright phrase in the mail content (for all mail templates)_
- _I thought that it was meaningless to display the copyright in the email content. In relation to this, if each service utilizes the authentication function of discovery, there is a burden to manage the copyright statement for each …
> Improve email template for password reset

- discovery-server/src/main/java/app/metatron/discovery/spec/druid/ingestion/AbstractSpecBuilder.java
Fix discarding null values ​​in timestamp field
1. Prepare source data that contains null values ​​in the timestamp field.
2. Set it as Time-type column, and select Discard as the Missing setting.
3. Ingestion, and check whether data containing null values ​​are excluded.
> fix discarding null values ​​in timestamp field

- discovery-frontend/src/app/common/component/grid/grid.component.ts
fix grid chart data excel download with double quotes
1. Create a grid chart with double quote data.
2. Click Download csv.
3. Check that the csv looks fine in Excel.
> fix grid chart data csv download with double quotes

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.html
- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
Tooltips are sometimes hidden in map charts.
**Related Issue** : #4045 
Create a map chart and check if the tooltip is created inside the map when you float the tooltip on the edge of the map.
- [x] Bug fix (non-breaking change which fixes an issue)
> #4045 improved tooltip position in map charts

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
There is an error where the dashboard is not displayed when there are more than 2 map charts in the dashboard.
2. Create and place two map charts within the dashboard.
3. Check if it is displayed normally on the browsing screen.
- [x] Bug fix (non-breaking change which fixes an issue)
> Fixed an error that did not draw when there are two map charts in the dashboard

- discovery-server/src/main/asciidoc/application-config-guide.adoc
- discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStream.java
- discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamConfiguration.java
- discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamService.java
- discovery-server/src/main/resources/application.yaml
- discovery-server/src/test/java/app/metatron/discovery/AbstractIntegrationTest.java
- discovery-server/src/test/java/app/metatron/discovery/domain/activities/ActivityStreamServiceTest.java
At the time the Activity Stream is recorded, it is not saved by using the pre-given exception condition in configuration.
_Activity Stream 이 기록되는 시점에 미리 주어진 예외 설정을 활용하여 기록 되지 않도록 구성하였습니다._ 
**Related Issue** : #4069 
주어진 로컬 머신에서 테스트 한다고 가정합니다.
1. 주어진 로컬 설정 그대로 discovery server 를 가동합니다.  사전에 설정파일내 예외 조건이 걸려 있습니다.
```
polaris:
activity_stream:
excludes:
-
action: ARRIVE
remoteHost: 0:0:0:0:0:0:0:1
objectId : polaris_trusted
```
3. 아래와 같이 토큰 발급을 요청합니다. 
```
curl http://localhost:8180/oauth/token -d grant_type=password -d client_id=polaris_trusted -d client_secret=secret -d scope='read write' -d username=admin -d password=admin
```
4. 아래 예시 처럼 서버내 디버그 로그를 확인하여 실제 로컬 머신의 remoteHost 정보를 얻어 remoteHost 내 기입후 재시작 합니다.
```
2022-07-19 06:18:43.005 DEBUG [127.0.0.1-polaris_trusted] …
```
> #4069 Add exclusion condition to save activity stream

- discovery-frontend/src/app/common/component/chart/type/map-chart/map-chart.component.ts
- discovery-frontend/src/app/dashboard/widgets/page-widget/page-widget.component.ts
- discovery-frontend/src/app/datasource/service/datasource.service.ts
- discovery-frontend/src/app/page/page.component.ts
If you remove the filter after limiting to the number of data, it will be fixed at the initial filtering position
**Related Issue** : #4044 
1. Create a map chart.
2. Apply filters to the chart and check the display coverage of the map.
3. Turn off the filter and check whether the display range of the map fits the data.
- [X] Bug fix (non-breaking change which fixes an issue)
> #4044 fix map position when filters are changed

- discovery-server/src/main/java/app/metatron/discovery/common/web/OauthFilter.java
When logging out after oauth login, the token set in the cookie is removed to prevent re-login.
After logging in to the client through oauth login, when logging out, go back to the oauth login page and check if login is possible again.
> Remove token cookie from oauth login process

- discovery-server/src/main/java/app/metatron/discovery/domain/activities/ActivityStreamService.java
- discovery-server/src/test/java/app/metatron/discovery/domain/activities/ActivityStreamServiceTest.java
I changed the way the exclusion criteria for activity stream items are matched. (equal -> contain)
기존 액티비티 스트림 항목에 대한 제외조건을 매칭하는 방식을 변경하였습니다. 
In the case of the exact same matching method, as in the case of the "remoteHost" item, it is very difficult to handle the activity case of a request with a different port value, so it is necessary to change the condition to contain it.
완전히 동일한 매칭 방식일 경우, remoteHost 항목의 경우와 같이 port 값이 다른 요청의 액티비티 건을 처리하기 무척 어렵기 때문에 포함하는 조건으로 변경이 필요합니다.
**Related Issue** : #4070 
Same as #4070 pr
- [] My change requires a change to the documentation.
> Changed matching method of activity stream exclusions
